### ISSUE TITLE
Hot reload fails in 3.5.4

### ISSUE THREAD

**Issue by prashaantt** [mobxjs/mobx-react#101]
I'm unable to get `react-hot-loader@3.0.0-beta.2` to work with `mobx-react@3.5.4`. Rolling back to 3.5.3 works as before.

![image](https://cloud.githubusercontent.com/assets/390540/17462999/b2ff01c8-5cda-11e6-8928-840d6adadf5b.png)

**Comment by mweststrate** [comment]
@prashaantt would you mind testing whether `npm install mobx-react@3.5.4-fix101` solves the issue? If so I'll cut a new release with that patch

**Comment by prashaantt** [comment]
Yes it does 👍

**Comment by prashaantt** [comment]
I had a conflict with `mobx-react-devtools` with this patch, so you may want to update its dependency too.

**Comment by mweststrate** [comment]
Released as 3.5.5
