### ISSUE TITLE
Allow @observer decorator for stateless functional components as properties

### ISSUE THREAD

**Issue by Strate** [mobxjs/mobx-react#105]
We have a lot of react components, composed with custom render methods, instead of render components. For example:
```ts
class SomeComponent extends React.Component {
  renderHead() {
    // render head here
  }
  renderFoot() {
    // render foot here
  }
  render() {
    return (
      <div>
        {this.renderHead()}
        {this.renderFoot()}
      </div>
    );
  }
}
```
I found that mobx's `observer` could be used to improve performance of rendering that components, without huge refactorings: just decorate render methods by `observer`, change arguments list to single argument object and replace method calls to component instantiation:
```ts
@observer
class SomeComponent extends React.Component {
  @observer
  renderHead() {
    // render head here
  }
  @observer
  renderFoot() {
    // render foot here
  }
  render() {
    return (
      <div>
        <this.renderHead />
        <this.renderFoot />
      </div>
    );
  }
}
```
It was very naive, because this example isn't works at all. `this.renderHead` refers to undefined after decorating it to `observer`. The only working example i've found is to use `observer` as a function, not as decorator:
```ts
@observer
class SomeComponent extends React.Component {
  renderHead = observer(() => {
    // render head here
  })
  renderFoot = observer(() => {
    // render foot here
  })
  render() {
    return (
      <div>
        <this.renderHead />
        <this.renderFoot />
      </div>
    );
  }
}
```
So, mu question is: is it a bug or expected behaviour? Should `observer` used as decorator on class methods?

**Comment by andykog** [comment]
@Strate, basically, you are using your renderHead and renderFoot as a stateless components, so applying `observable()` may help, but not as a decorator, it is not intended to be used like this.
PS: To me it's seems more logical to declare those components outside the class.

**Comment by Strate** [comment]
@andykog that components are not completely stateless, because they has access to `this`, which helps to reduce boilerplate with bypassing props from parent to child.

**Comment by andykog** [comment]
@Strate, using `this` doesn't make them statefull. They don't have own `state`. And “stateless functional component” is the [official term](https://facebook.github.io/react/blog/2015/10/07/react-v0.14.html). I think the way you are using it not very obvious. I would at least pass `this` as a prop. But thats not the topic of current issue. You can use `observable(statelessFunctionalComponent)`, not decorator.

**Comment by Strate** [comment]
@andykog okay :)
I just want to suggest to allow use `observer` as a decorator on class method, because there is at least one use-case :)

**Comment by andykog** [comment]
Ok, then I changed the title :-)

**Comment by andykog** [comment]
To me using stateless components like this is still seems like a bad practice, so I'm not sure we should encourage that.

**Comment by Strate** [comment]
It is already allowed, but with `observer()` signature.

**Comment by andykog** [comment]
@Strate, Yes, `observer()` creates you observer component, and you can place it anywhere, even in class property, but I don't like this idea, so I wouldn't make `@observer` a class property decorator that will serve only for that single purpose. You are also allowed to use classes like this by the way:
```js
@observer
class SomeComponent extends Component {
   
  child = observer(class extends Component {
    render() { return null; }    
  });

  render() {
    const Child = this.child;
    return <Child />
  }    
}
```

**Comment by mweststrate** [comment]
I think doing like `child = observable(props => rendering)` is not like really bad, but it is a bit weird because of the following; each `SomeComponent` get's its own, bound versions of those components. That is ok-ish, but what is trickier is that these fields are initialized during the construction of the `SomeComponent` instance. That is quite expensive as not all instantiated components will be mounted (if I remember correctly the reconciler works on instances and not on elements). 

I agree with @andykog that stylewise not nesting components is nicer (I never saw that anywhere although I think that should work indeed from a technical perspective.

**Comment by andykog** [comment]
So I guess, this feature won't be implemented. @Strate, feel free to reopen if you have additional arguments/propositions
