### ISSUE TITLE
How to specify observableArray in propTypes?

### ISSUE THREAD

**Issue by nareshbhatia** [mobxjs/mobx-react#107]
As described in the README:

> MobX-react provides the following additional propTypes which can be used to validate against MobX structures

How do I use these proptypes in my declarations? I tried this:

    import {observableArray} from 'mobx-react';
    RepoList.propTypes = {
        repos: observableArray
    };

But I get the following error:

    Warning: Failed prop type: RepoList: prop type `repos` is invalid; it must be a function, usually from React.PropTypes.

**Comment by mweststrate** [comment]
you need to `import {PropTypes} from 'mobx-react'` and then use `PropTypes.observableArray`

**Comment by nareshbhatia** [comment]
Thanks, @mweststrate. That worked like a charm. Only change was that `propTypes` needed to be camelCase.
