### ISSUE TITLE
More examples

### ISSUE THREAD

**Issue by ifokeev** [mobxjs/mobx-react#108]
I developed a real-world tiny app that demonstrates use of `React` with `Mobx` and `Mobx-store`:
https://github.com/ifokeev/support-service

It has a single store, prefetch and server-side rendering. I tried to make it clean and correct. 
I think it may be useful for beginners. 
If you have the same view, please, add it to your readme. It's non-commerce project, of course, but it may be used as real-world example or lightweight support-service. 

Thank you in advance.

**Comment by andykog** [comment]
@ifokeev, thanks, added: https://github.com/mobxjs/mobx/commit/79e268d40add5a2f45029553477ad3a11a64bd8e
