### ISSUE TITLE
@observer got an syntax error 

### ISSUE THREAD

**Issue by Zcgong** [mobxjs/mobx-react#109]
I got this syntax error for use mobx-react in react-native. Anyone know what's happened
?
![2955d7b5-0ba7-46c7-8cdc-45511b10e8ee](https://cloud.githubusercontent.com/assets/13640428/17915980/9b7582c0-69e1-11e6-979f-d8ae80588df7.png)

This is my code 

[MobxDemoRN 2.zip](https://github.com/mobxjs/mobx-react/files/433898/MobxDemoRN.2.zip)

**Comment by mweststrate** [comment]
Not familiar with RN projects setup, but where is the babel configuration? `.babelrc` or something like that

**Comment by andykog** [comment]
@mweststrate, people are usually using `react native packager`, with exclusive (babel-preset-react-native)[https://github.com/facebook/react-native/blob/master/babel-preset/configs/main.js], I'l try to check @Zcgong's example

**Comment by andykog** [comment]
@Zcgong, I see you are using decorators without any configuration for that. I, personally, haven't managed to get it working with react native packager. And [they saying](https://github.com/facebook/react-native/blob/master/breaking-changes.md) that decorators won't work until [T2645](https://phabricator.babeljs.io/T2645) lands in Babel. So thats not a mobx issue.

After 2 chages you app is working for me:
```js
// before:
@observer
export default class App extends Component {
}

// after:
class App extends Component {
}
export default observer(App);

// before:
@list = []

// after:
  constructor() {
    extendObservable(this, {
      list: [],
    });
  }
```

**Comment by Zcgong** [comment]
@andykog Thanks ! I will try this.

**Comment by Zcgong** [comment]
@andykog Thanks a lot ! I fix this by two way:
1. add .babelrc file  add plugins "transform-decorators-legacy" 
2. your way 

but I feel confuse with the first way, did it must add at the project init ? I try to add it in my current project but it not works. Then I init a new project and add it then copy code to this new , it works. Why ?

**Comment by andykog** [comment]
@Zcgong, I guess, your last question is about `react-native packager`, not mobx-react. Try to google `react-native packager transform-decorators-legacy`

**Comment by aryejfa** [comment]
Thankyou all sir, is working..
