### ISSUE TITLE
How to write tests if you use Provider for passing props

### ISSUE THREAD

**Issue by optimatex** [mobxjs/mobx-react#112]
Hi. I start using `Provider` and encounter that writing test is tricky. I use enzyme mount function for my tests. My first intent was next:
```

const profile = new Profile_Store({ id: 1, name: 'Tod' });
wrap = mount(
         <Provider profile ={profile}>
            <Person age={'30'} />
         </Provider>               
      );

```

and component
```

@observer(['profile']) class Person extends Component {
   render() {
      return(
         <div className="person">
            { this.props.profile.name }
         </div>
      )
   }
}

export default Person;

```

but dealing that way produce 2 problems:
1) Enzyme .context() function doesn't work cuz it try to get state of Provider instead of Person 
2) `Error: MobX observer: Store 'profile' is not available! Make sure it is provided by some Provider`

**Comment by mweststrate** [comment]
@optimatex in your test you should be able to pass `profile` directly, `@observaber` will pick that up as well: `mount(<Person profile={profile} age={'30'} />)`

**Comment by mweststrate** [comment]
Closed for inactivity, answer has been provided in the docs

**Comment by optimatex** [comment]
oh, i did write answer in docs. Maybe it didn't show u my post
 optimatex added a line comment 14 days ago 

Thank for ur response. I did like u suggest and met another error:
TypeError: Attempted to wrap undefined property handleLike as function
in this sinon function:
handleLike_spy = sinon.spy(Person.prototype, 'handleLike');
this error appears only if i use @observer(['profile']) . If i remove (['profile']) - no more error.

i also did console.log(Person.prototype) :

// Prototype
Constructor{
    constructor: function (props, context, updater) { ... }, 
    __reactAutoBindMap: Object{getDOMNode: function () { ... }}, 
    getDOMNode: function () { ... }, render: function (){ ... }, 
    mixins: null, 
    statics: null, 
    propTypes: null, 
    contextTypes: null, 
    childContextTypes: null, 
    getDefaultProps: null, 
    etInitialState: null, 
    getChildContext: null, 
    componentWillMount: null, 
    componentDidMount: null, 
    componentWillReceiveProps: null, 
    shouldComponentUpdate: null, 
    componentWillUpdate: null, 
    componentDidUpdate: null, 
    componentWillUnmount: null, 
    updateComponent: null
}

and in case when i remove (['main_store']) the output is next:

Bar{
    componentWillMount: function (){ ... }, 
    componentWillUnmount: function (){ ... }, 
    componentDidMount: function (){ ... }, 
    componentDidUpdate: function (){ ... }, 
    shouldComponentUpdate: function (e,t){ ... }
}

do u have any idea what can cause this transformation which lead to unrealizable wrapping function with sinon?

**Comment by mweststrate** [comment]
@optimatex is `Person` the component? note that when using `inject` or `observer([stores])`, a component get's actually wrapped around your component, so this might lead to a mismatch if you try to access component functions / props from outside. The wrapped (your original) component should be available as `.wrappedInstance` / `.wrappedComponent`. E.g: `Person.wrappedComponent.prototype.handleLike`

**Comment by optimatex** [comment]
@mweststrate thank u for ur answer. I'll try

**Comment by github-account-because-they-want-it** [comment]
So what about the case when the component under test is using child components that also use `inject`?
In my test, I tried to pass child stores from the parent, assuming they are going to be inherited but that didn't work, throwing the error in the title of this issue.
For example
```
const wrapper = renderer.create(<Videos videos={videosStore} routing={{}} thread={mockThreadStore} classes={{}}/>)
expect(wrapper.toJSON()).toMatchSnapshot()
```
Here, `videos` store is used by the `Videos` component. `routing` and `thread` are being used by a child.

**Comment by mweststrate** [comment]
Does your Videos pass these stores on to its children? Note that Videos
itself does not become magically an provider by just passing it some stores
:) So if nested children need injection, just wrap your component under
test with a Provider

Op wo 28 mrt. 2018 om 08:01 schreef Mohammed Hamdy <notifications@github.com

**Comment by github-account-because-they-want-it** [comment]
thank you for the fast response @mweststrate ! I thought that won't work given the OP comment but it worked for me. Thank you!
