### ISSUE TITLE
Nested Providers?

### ISSUE THREAD

**Issue by mohsen1** [mobxjs/mobx-react#114]
I'm trying to refactor my [contacts-mvc project](https://github.com/contacts-mvc/mobx-react-typescript/pull/6) to use `Provider`. 

I came to this problem where I want to provide a store to some of the components and a big store to every component. The inner component (`'contact'`) provider is a computed property of bigger store (`@computed get selectedContact()`). 

First I had it this way:

```tsx
ReactDOM.render(
  <Provider appState={appState} >
    <Router history={browserHistory}>
      <Route path='/' component={App}>
        <IndexRoute component={Empty} />
        <Route path='search/:query' component={ContactDetails} />
        <Route path='new' component={EditContact} />
        <Provider contact={appState.selectedContact}>
          <Route path=':contactId' component={ContactDetails} />
          <Route path=':contactId/edit' component={EditContact} />
        </Provider>
      </Route>
    </Router>
  </Provider>,
  document.getElementById('root'));
```
But I was getting these errors: 

<details>
```
warning.js:36 Warning: There is an internal error in the React performance measurement code. Did not expect componentDidMount timer to start while render timer is still in progress for another instance.printWarning @ warning.js:36warning @ warning.js:60beginLifeCycleTimer @ ReactDebugTool.js:123onBeginLifeCycleTimer @ ReactDebugTool.js:234invokeComponentDidMountWithTimer @ ReactCompositeComponent.js:58notifyAll @ CallbackQueue.js:67close @ ReactReconcileTransaction.js:81closeAll @ Transaction.js:204perform @ Transaction.js:146batchedMountComponentIntoNode @ ReactMount.js:127perform @ Transaction.js:138batchedUpdates @ ReactDefaultBatchingStrategy.js:63batchedUpdates @ ReactUpdates.js:98_renderNewRootComponent @ ReactMount.js:321_renderSubtreeIntoContainer @ ReactMount.js:402render @ ReactMount.js:423(anonymous function) @ index.tsx:11(anonymous function) @ index.tsx:15(anonymous function) @ bundle.js:1042__webpack_require__ @ bundle.js:556fn @ bundle.js:87(anonymous function) @ multi_main:3(anonymous function) @ bundle.js:586__webpack_require__ @ bundle.js:556(anonymous function) @ bundle.js:579(anonymous function) @ bundle.js:582
index.js:1 Uncaught Error: MobX observer: Store 'contact' is not available! Make sure it is provided by some Provider
```
</details>

But if I remove the nested `Provider` and move `contact` store to the wrapper `Provider` it doesn't throw errors anymore:

```tsx
ReactDOM.render(
  <Provider appState={appState} contact={appState.selectedContact}>
    <Router history={browserHistory}>
      <Route path='/' component={App}>
        <IndexRoute component={Empty} />
        <Route path='search/:query' component={ContactDetails} />
        <Route path='new' component={EditContact} />
        <Route path=':contactId' component={ContactDetails} />
        <Route path=':contactId/edit' component={EditContact} />
      </Route>
    </Router>
  </Provider>,
  document.getElementById('root'));
```

Although that's not what I want and it's not really giving me the `contact` prop in those components anyway...

**Comment by mweststrate** [comment]
I see a few potential isues in your listing:

1. the search routing also uses the ContactDetails component, but in that case contact is not provided in the store, that might be an issue
2. you dereference the `selectedContact` already here in the router configuration, that means that if it changes, your app will not pick it up (as the computed value is not dereferenced in an observer component, changes to it cannot be tracked by mobx)
3. that first warning sounds scary :-P

**Comment by mohsen1** [comment]
I did another pass and made my state simpler. Now I only have `appState`. Please take a look. 

But the question of how to use multiple stores or nested stores remains unanswered. Do nested `Provider`s work if they are providing two separate stores?

**Comment by mweststrate** [comment]
yes no problem multiple providers are supported and may even override /
shadow stores

Op zo 4 sep. 2016 22:14 schreef Mohsen Azimi <notifications@github.com>:

**Comment by mohsen1** [comment]
Thanks, I just checked and nested Providers with two different stores work.
