### ISSUE TITLE
issue #21 regression test fails on last assert

### ISSUE THREAD

**Issue by amir-arad** [mobxjs/mobx-react#115]
After cloning and installing the project from scratch (OSX, node 4.4.4, npm 2.15.1) I get a test error on [the regression suite for issue](https://github.com/mobxjs/mobx-react/blob/master/test/issue21.js#L121) #21 
```
# verify issue 21
ok 1 should be equal
ok 2 should be equal
not ok 3 should be equal
  ---
    operator: equal
    expected: 3
    actual:   4
    at: Test.assert [as _assert] (http://localhost:55474/bundle.js:72538:17)
  ...
```

**Comment by amir-arad** [comment]
all tests seem to work fine when using mobx ```2.4.4``` instead of ```2.5.1```

I suggest not using semver ranges in package.json. That's what I do.

**Comment by mweststrate** [comment]
Confirmed, thanks for reporting. Shouldn't cause any bugs but I'll check whether the optimization can be restored.

**Comment by mtyaka** [comment]
Can we keep this issue opened until it's fixed or the test updated?
