### ISSUE TITLE
Which files need to be hosted?

### ISSUE THREAD

**Issue by kennynaoh** [mobxjs/mobx-react#118]
Hello @mweststrate ,
I am the member of [cdnjs](https://github.com/cdnjs/cdnjs).
We want to host this library.
But there is a question want to ask.
I am not sure which file need to be grab on [npm](https://www.npmjs.com/package/mobx-react).
There are three js file, `index.js`, `custom.js` and `native.js`.
And I think all of them are minified file.
But I couldn't find that which is needed from its name.
Please help me confirm that and maybe change to the obvious name to know, like `mobx-reast.js`.
Thanks for your help!

https://github.com/cdnjs/cdnjs/issues/8309

**Comment by mweststrate** [comment]
All those files are correct, `index` is the default implementation of `mobx-react`, `native` and `custom` are the bindings for react-native / a custom renderer. Basically the `files` section of the package.json is representative for what should be hosted, although `d.ts` files could be left out.

**Comment by kennynaoh** [comment]
Thanks @mweststrate ,
So could you change the name which is easy to understand?
Thanks!

**Comment by mweststrate** [comment]
Preferrably not until a next major, as that would break a lot of jsbins /
fiddles which are included from unpkg (npmcdn)

Op di 6 sep. 2016 om 13:57 schreef naoh <notifications@github.com>:

**Comment by kennynaoh** [comment]
@mweststrate 
Sorry for late reply.
So if change the file name from `index.js` to `mobx-react.js`(or any other obvious name), it will break your structure.
What you mean is this?
Thanks!

**Comment by mweststrate** [comment]
@kennynaoh hmm never mind, I was afraid that it would break unpkg.com links (like https://unpkg.com/mobx-react@3.5.6), but probably most people mention the `index.js` file directly. I have to say though that I am not sure whether something else would be nicer, e.g. `react.js` would be confusing, as `native.js` is also for react, which then should become `react-native.js`, but then you get really ugly common js imports (`mobx-react/react-native` instead of `mobx-react/native`) etc. In other words, is this really an issue?

**Comment by kennynaoh** [comment]
@mweststrate , hmm I just try to confirm which files need to be host. So I will add `custom.js`, `index.js` and `native.js`, right?
If yes, I will add this library ASAP.
Thanks!

**Comment by mweststrate** [comment]
@kennynaoh correct, thanks!

**Comment by kennynaoh** [comment]
My pleasure.
Another question want to ask.
We also need to maintain old version of library, but both `custom.js` and `native.js` are not exist in some of old versions on git repo.
I just want to confirm whether it's fine to add only `index.js` in some of old versions.
Thanks!

**Comment by mweststrate** [comment]
that is no problem

Op di 8 nov. 2016 03:25 schreef naoh <notifications@github.com>:

**Comment by kennynaoh** [comment]
Thanks!
