### ISSUE TITLE
@inject doesn't hoist statics props of component

### ISSUE THREAD

**Issue by johncho75** [mobxjs/mobx-react#120]
RE: #88, #92, #95 

I was previously on v3.5.1 and just upgraded to v3.5.5. Discovered an issue where a component decorated with @inject was failing to apply my defaultProps for the component causing an undefined error for a property:

```
@inject("mystore") @observer
class MyClass extends React.Component {
    // ...
}

MyClass.propTypes = { /* ... */ }
MyClass.defaultProps = { /* ... */ }
```

This was working fine in v3.5.1. But as of v3.5.5 (I assume as of v3.5.4) this code fails. Default props for this component never gets set. And I see the new warning about setting props on the HoC. Given in #92, static props were hoisted for @observer, I was wondering why the same wasn't done for @inject, and instead the new warnings were added?

The code I had before was much easier to read. I now have to do this:

```
MyClass.wrappedComponent.propTypes = { /* ... */ }
MyClass.wrappedComponent.defaultProps = { /* ... */ }
```

and at least in my opinion that doesn't look that clean. Shouldn't the use of @inject be transparent? Just curious. I have only been using react and mobx for a couple months now so I could be missing something.

**Comment by mweststrate** [comment]
Thanks for reporting! This should behave the same for both `inject` and `observer` indeed

**Comment by mweststrate** [comment]
Addressed this issue in mobx-react 4. Hoisting is not possible the other way around, as it leads to highly confusing / ambigious scenarios (initially tested that, see the discussion on this commit: https://github.com/mobxjs/mobx-react/commit/666577b41b7af8209839e7b243064a31c9951632

Instead, improved the docs to explain these scenarios better.

**Comment by mweststrate** [comment]
4.0.0 has been released, closing the issue
