### ISSUE TITLE
Can we autorun custom methods just like the `render` method?

### ISSUE THREAD

**Issue by paulsoh** [mobxjs/mobx-react#122]
I am trying to replace all my states to use mobx observables. 
So, `this.setState({ ... })` now became just as simple as `this.observableValue = ...`

One short coming I have encountered, is that now that I don't use `states`, I can't use the common React lifecycle methods such as `componentDidUpdate` or `componentWillUpdate`. Which I sometimes need to handle some internal logic. 

For example, lets say I am trying to make a List view that sends request to an endpoint according to the filter the user selected. 

When I used states, It's pretty straight forward, I could have simply done this:
```javascript
class ListView extends React.Component {
  constructor(props) {
    super(props)
    this.state = {
      filterType: 'all', // or 'completed' or 'cancelled'
    }
  }

  componentDidUpdate(prevProps, prevState) {
    if (this.state.filterType !== prevState.filterType) {
      this.handleFilterTypeChange(this.state.filterType);
    }
  }

  handleFilterTypeChange(filterType) {
    fetch('http://endpoint/according/to/filtertype')
      .then()
      .then()
  }
} 
```

But when using mobX, It is not as intuitive. 

```javascript
@observer class ListView extends React.Component {
  constructor(props) {
    super(props)
  }

  @observable filterType = 'all'

  handleFilterTypeChange(filterType) {
    fetch('http://endpoint/according/to/filtertype')
      .then()
      .then()
  }

   // I want the method that autoruns whenever the @observable filterType value changes!!!
  hookThatDetectsWhenObservableValueChanges() {
    ... 
  }
} 
```

Currently `mobx-react` provides an api that lets the `render` method `autorun` whenever an `@observable` changes inside an `@observer`, I was wondering if there is an elegant and nice way to to this for any other method inside an React component.

Thanks.

**Comment by paulsoh** [comment]
I think I found the answer to my question. Please correct me if I am wrong or I could to better.
I used `reaction`'s to do the work.

So in the case above, I did something like this:
```javascript
@observer class ListView extends React.Component {
  constructor(props) {
    super(props)
  }

  @observable filterType = 'all'

  handleFilterTypeChange(filterType) {
    fetch('http://endpoint/according/to/filtertype')
      .then()
      .then()
  }

   // I want the method that autoruns whenever the @observable filterType value changes!!!
  hookThatDetectsWhenObservableValueChanges = reaction(
    () => this.filterType,
    filterType => {
      this.handleFilterTypeChange(filterType);
    }
  )
} 
```

**Comment by mweststrate** [comment]
@paulsoh yep this is a fine approach. Don't forget to clean up the hook in componentWillUnmount. (And if you don't like reactions for this, you can always use your own methods that update the filterType and trigger the request)

**Comment by paulsoh** [comment]
@mweststrate Thanks. When you say `you can always use your own methods that update the filterType and trigger the request`, I realized that in some cases, the `observable` value changes somewhere else and affects the store. 

```
@observer(['filterStore])
class ListView extends React.Component {
  constructor(props) {
    super(props)
  }

  @observable filterType = 'all'

  handleFilterTypeChange(filterType) {
    fetch('http://endpoint/according/to/filtertype')
      .then()
      .then()
  }

  hookThatDetectsWhenObservableValueChanges = reaction(
    () => this.props.filterStore.filterType,
    filterType => {
      this.handleFilterTypeChange(filterType);
    }
  )
} 
```

If this were the case, how would you make an local method that is triggered from a remote observable value change?

**Comment by mweststrate** [comment]
ah, in that case I would definitely use reactions indeed. It's more that sometimes you just have two localized things that should happen together, and then a reaction might just be overkill compared to introducing a convenience method :)

**Comment by sandropoluan** [comment]
@mweststrate . How to clean up the hook ?

**Comment by mweststrate** [comment]
```
componentWillUnmount() {
  this.hookThatDetectsWhenObservableValueChanges()
}
```
