### ISSUE TITLE
observerAsync?

### ISSUE THREAD

**Issue by jamiewinder** [mobxjs/mobx-react#123]
More of a discussion than an issue. Is there anything to be said for adding `observerAsync(minimumDelay)`? Basically like `observer`, but wrapping render using `autorunAsync` rather than `autorun`. 

I can imagine it'd have some uses where you want to render data that changes rapidly.

The main drawback I can think of is that you'll end up wanting some data to update immediately, and some to update every now and then (for example, a stats table component - if the title changes, do it immediately. If the data changes, it can wait). You could get around this by making the title a separate component of course.

Thoughts? I might give it a go unless anyone can think of why I couldn't / shouldn't.

**Comment by mweststrate** [comment]
In general I think throttling is best done on the receiving side of things, e.g. on the incoming websockets before the changes are applied to the observable state. If that is not applicable to your case, then I would go for a viewmodel like constructions that uses for example `autorunAsync` to update the model on a timely bases from the source data
