### ISSUE TITLE
Guidance on (intelligently) overriding mobx's shouldComponentUpdate

### ISSUE THREAD

**Issue by arackaf** [mobxjs/mobx-react#125]
The crux of the problem I'm dealing with is that a component is being rendered inside a bootstrap tab pane.  Inside the component is a react-collapse `<Collapse>` component. 

When the relevant observable changes, and that tab no longer is "active" (ie it's not displayed because another tab is shown), the component's render is fired, `<Collapse>` calculates the height to be 0, and collapses it.  When I click back, `<Collapse>` sees that my component now visible again, has a height, and so the animation is re-triggered.  So as the user clicks back and forth, the animation is inappropriately re-triggered.  

I've confirmed that setting `shouldComponentUpdate = () => false` does prevent this from happening, though of course it would also cause my component to no longer update when needed.

Are there any hooks in mobX for me to customize sCU a tad?  Is there some way for me, somehow, somewhere in my component to do something like

```
autorun(() => {
    this.props.labels;
    this.props.loading;
    this.props.loaded;
    
    //trigger re-render somehow?  Ie set a state value that sCU looks at, for example
});
```

The problem of course with the above is that `this.props.labels` is already un-rolled.  You do some magic, I assume, in render() that I can't (as far as I can tell) do in componentDidMount.

 Any guidance would be much appreciated.

---

*EDIT*

I re-re-searched and found https://github.com/mobxjs/mobx-react/issues/50#issuecomment-231850824

I assume my best bet is to add an autorun to my store, and change some junk value whenever any of the relevant observables change, and then check that in sCU?

I got hopeful when I saw

> shouldComponentUpdate is respected, but only for setState or newly passed in props. It is not respected when observables used in render are changed.

I thought `sCU = () => false` *would* work for me, since the observables I *want* respected *are* referenced in render, but no, that causes the component to simply never update, as I assumed it would.

**Comment by andykog** [comment]
@arackaf, that works fine: https://jsfiddle.net/Sl1v3r/83k26bgw/

**Comment by arackaf** [comment]
Thanks @andykog - I knew something like that would work.  Was mainly wondering if @mweststrate had anything built into a MobX utility somewhere that would be a bit simpler.

**Comment by mweststrate** [comment]
@arackaf nope, sorry :) (btw I didn' t get your problem description entirely I think, why the re-rendering is inappropiate)

**Comment by arackaf** [comment]
@mweststrate - thanks anyway :)

The problem description boils down to:

There's a tab pane.  Tab 1 has a *collapsible* list of things.  It's expanded.  User clicks to tab 2, then back to tab 1.  Upon tab 1 re-rendering, the collapsible list re-expands even though it was always expanded.

Just wanted to suppress that re-rendering to prevent that from happening. 

Although, thinking about this weeks later, I think if I wrapped the *content* of that tab into a new component with @ observer I think that'd fix it......

^_^

**Comment by mweststrate** [comment]
@arackaf ok :) ok to close the issue? (trying to keep up haha)

**Comment by fxfactorial** [comment]
@arackaf Similar situation on ReactNative, and yes. The solution is to move out the components into their own separate observer component.

**Comment by guoyang007** [comment]
I totally understand your problem, because I just encountered this problem. But after condiferation, I think the point is that the collapse should not be animated when the panel is updating. As the active state has been changed, the panel state is indeed changed, so the update in the panel is appropriate, but to control the collapse has no animation is so tough... The collapse should only be animated when we click the panel but not whenever the component is rendering
