### ISSUE TITLE
Wrong typings for 'observer' and 'inject'

### ISSUE THREAD

**Issue by mkozhukharenko** [mobxjs/mobx-react#129]
#### Observed:

compiling next component 

```js
import * as React from 'react'
import { Component, PropTypes } from 'react'
import { observer, inject } from 'mobx-react'
import MyStore from './myStore'

@inject((allStores) => ({
    store: new MyStore(),
}))
@observer
class LoginContainer extends Component<any, void> {
    static contextTypes = {
        router: PropTypes.func.isRequired,
    }
    render() {
        return (<div>Hello!</div>)
    }
}
export default LoginContainer
```
gives an error:
```js
error TS2345: Argument of type 'typeof MyComponent' is not assignable to parameter of type 'string[]'.  Property 'push' is missing in type 'typeof MyComponent'.
```
So, it means that none of the provided 'observer' functions signatures match a component type. 

New signatures for functions `observer` and `inject` should be added. Not sure which exactly. 

For now I added a quick fix:
```js
export function observer<P>(clazz: any): any;
export function inject<P>(storesToProps: any): any
```

#### How to reproduce
This problem occurs when a static field `contextTypes` is added to the component class together with 'observer'

**Comment by mweststrate** [comment]
@mkozhukharenko I was able to reproduce this one, but actually TypeScript gave me a compile error on `contextTypes` itself first. It seems that the type of contextTypes is not inferred correctly by TypeScript, which can fixed by declaring context types as:

```
@inject((allStores) => ({
    store: {},
}))
@observer
class LoginContainer extends Component<any, void> {
    static contextTypes: React.ValidationMap<any> = {
        router: PropTypes.func.isRequired,
    }

    render() {
        return (<div>Hello!</div>)
    }
}
```

That being said, in your example `propTypes` should be used, as `@inject` will take stuff from the context and inject it as `props` to the component

**Comment by mkozhukharenko** [comment]
@mweststrate thanks for the response with detailed explanation.

**Comment by cloverich** [comment]
I landed here with similar errors; My component definition:

```ts
@observer
class Container extends React.Component<T, null> {
```

Seemed to be my **declaring state as null** (void has same result). [This stackoverflow question](https://stackoverflow.com/questions/45024559/jsx-element-type-app-is-not-a-constructor-function-for-jsx-elements-types-of) led me there. Simply omitting the type for state resolved the error:


```ts
@observer
class Container extends React.Component<T> {
```

(Hadn't realized I could omit the State type altogether, maybe that's a later addition to @types/react).

**Comment by mweststrate** [comment]
Use {}

**Comment by cloverich** [comment]
The [DefinitelyTyped react typings][1] provide a default `{}` for state:

```ts
// Base component for plain JS classes
// tslint:disable-next-line:no-empty-interface
interface Component<P = {}, S = {}> extends ComponentLifecycle<P, S> { }
class Component<P, S> {
  constructor(props?: P, context?: any);
```

Is there an impact when leaving it off / explicitly using `{}`? 

[1]: https://github.com/DefinitelyTyped/DefinitelyTyped/blob/master/types/react/v15/index.d.ts#L281
