### ISSUE TITLE
@observable Map is not converted to ObservableMap

### ISSUE THREAD

**Issue by valorize** [mobxjs/mobx-react#135]
Hi, I thought that everytime I add a \@obserable before my property name the underlying object / array / map is converted to an mobx datatype like ObservableMap is that the case?

```
export default class TickStore implements Stores.Ticks.ITicks {
	collection;
	@observable models: Map<string, Models.Tick.ITick> = new Map();
	@observable isLoading = true;
...
	createTick(value) {
		var tick = new TickModel(this, value);
		this.models.set(tick.id, tick);
```
I have to exchange new Map with new ObservableMap. Then this.models.set updates my view. In the documentation you also name asMap and map is it the same as calling new ObserableMap() ?

**Comment by mweststrate** [comment]
correct, `@observable models = asMap()` should be used here. `Map` is not supported on all ES5 environments and therefor not used atm.
