### ISSUE TITLE
Can @observer detect an @injected component and throw an error?

### ISSUE THREAD

**Issue by mohsen1** [mobxjs/mobx-react#139]
This happened to me in two cases, I had the `@observer` and `@inject` decorators order wrong. 

``` ts
@observer
@inject('store')
class MyComponent {}
```

Since `@inject` is wrapping the class, can it mark the class somehow that `@observer` can see and throw an error or warning that order of decorators are wrong?

**Comment by mweststrate** [comment]
Yep, good idea! 

Any volunteer? Shouldn't be too hard I think. cc @delaetthomas

**Comment by delaetthomas** [comment]
Yes, I will try to fix this one!

**Comment by delaetthomas** [comment]
@mohsen1 this issue is fixed now.
