### ISSUE TITLE
[react-native] Getting warning "object supplied, expected an array" when sending an array

### ISSUE THREAD

**Issue by dccarmo** [mobxjs/mobx-react#141]
Here's my AppState class:

```
export default class AppState {
    constructor() {
        this.navigationState = {
            index: 0,
            routes: [{ key: "InitialView" }]
        };
    }
(...)
}
__decorate([
    observable
], AppState.prototype, "navigationState", void 0);
```

(This code is generated by TypeScript)

Notice the `routes` property, it's an Array. But when passing it:

```
const { CardStack: NavigationCardStack } = NavigationExperimental;
let GlobalNavigation = class GlobalNavigation extends Component {
    render() {
        return (React.createElement(NavigationCardStack, {renderScene: this._renderScene.bind(this), navigationState: this.props.appState.navigationState}));
    }
(...)
};
```

I get the error:

![simulator screen shot oct 26 2016 18 27 31](https://cloud.githubusercontent.com/assets/638474/19743900/f0348bfe-9ba9-11e6-8477-1408b8abc255.png)

If I remove the `@observable` decorator, the warning goes away.

**Comment by urugator** [comment]
Array is converted into ObservableArray, which is an object not an array:

https://mobxjs.github.io/mobx/refguide/array.html

> Bear in mind however that Array.isArray(observable([])) will yield false, so whenever you need to pass an observable array to an external library, it is a good idea to create a shallow copy before passing it to other libraries or built-in functions (which is good practice anyway) by using array.slice(). In other words, Array.isArray(observable([]).slice()) will yield true

Possible solutions:
a) not making an array observable by using `asReference` modifier
b) changing NavigationCardStack to accept one of the mobx provided PropTypes (e.g. PropTypes.observableArray)
c) passing an unobservable copy by using `slice()`

**Comment by dccarmo** [comment]
Oh, that makes sense. Thank you for pointing that out.
