### ISSUE TITLE
Prop validation throws a warning still an issue. Related to closed ticket #70

### ISSUE THREAD

**Issue by mromanoff** [mobxjs/mobx-react#142]
Related to: Prop validation throws a warning when used on a decorated component expecting store #70

@mweststrate i followed your last post on this topic. and still getting warning. 
**Mobx Injector: you are trying to attach propTypes to HOC instead of Actions. Use `wrappedComponent` property.**

here is my component:

```
@inject('store') @observer
export default class Actions extends Component {
    render() {
        return <div>abc</div>;
    }
}

Actions.wrappedComponent.propTypes = {
  store: PropTypes.object.isRequired
};

```

am i missing something?
btw I'm using Babel

**Comment by SagiMedina** [comment]
@mromanoff did you find any solution to this warning?
@mweststrate Any thoughts?

**Comment by mromanoff** [comment]
@SagiMedina sorry but i did not find any solution. for now I ignore this message.

**Comment by mweststrate** [comment]
@mromanoff @SagiMedina just tried to reproduce this issue, but it worked for me without warnings. Could you setup a small reproduction? Are you using the latest `mobx-react` version?

**Comment by mromanoff** [comment]
@mweststrate thank you for quick response. Due complexity of this project I'm working on and running on local environment only. I can send you link to public repo if this helps.
API: https://github.com/mromanoff/therapy-match-api
FE: https://github.com/mromanoff/therapy-match
Let me know if you can quick spot the issue. If not then I need to deploy this project on Heroku or Digital Ocean.

Currently I have 4 warning messages: 

```
Mobx Injector: you are trying to attach propTypes to HOC instead of Actions. Use `wrappedComponent` property.
Mobx Injector: you are trying to attach propTypes to HOC instead of Search. Use `wrappedComponent` property.
Mobx Injector: you are trying to attach propTypes to HOC instead of Provider. Use `wrappedComponent` property
Mobx Injector: you are trying to attach propTypes to HOC instead of Success. Use `wrappedComponent` property.
```

**Comment by SagiMedina** [comment]
@mweststrate Please take a look here, https://github.com/SagiMedina/system_dashboard
I have 6 warning messages, one for every store injection.

**Comment by SagiMedina** [comment]
Never mind, adding the wrappedComponent to the props validation fixed it.

**Comment by mweststrate** [comment]
@mromanoff you still seem to attach the propTypes to Search, so the warning is correct? https://github.com/therapymatch/therapymatch-fe/blob/e1e90d6b48b1fd80fb9fd6d6e3d330d7057ea2d6/src/components/Search/Search.js#L60

**Comment by mweststrate** [comment]
That being said, `mobx-react@4` will probably redirect the property, instead of giving a warning, which is more convenient to work with:)

**Comment by mromanoff** [comment]
@mweststrate oh... my assumption was that I need to use .wrappedComponent only for "inject", "observer" store props but not for the other props. route props etc.

I had before: 
```
Search.propTypes = {
  params: PropTypes.object.isRequired
};
Search.wrappedComponent.propTypes = {
  providersStore: PropTypes.object.isRequired
};
```
I have now:
```
Search.wrappedComponent.propTypes = {
  params: PropTypes.object.isRequired,
  providersStore: PropTypes.object.isRequired
};
```
it fixes the warning. 
thank you for help.

**Comment by mweststrate** [comment]
I've made the distinction between HoC's and non-HoC's more clear in `mobx-react@4.0.0-rc.1` and removed the warnings. It is now allowed to define the propTypes on the HoC again. But note that you cannot check for the presence of your stores there, for that you will still need `.wrappedComponent`.

**Comment by mweststrate** [comment]
4.0.0 has been released :)
