### ISSUE TITLE
Is it possible to make Provider and @inject type safe?

### ISSUE THREAD

**Issue by mohsen1** [mobxjs/mobx-react#143]
Currently `Provider` and `@inject` are using strings for providing stores and injecting them in components. Is it possible to use TypeScript generics to make sure that those strings are type checked by TypeScript compiler? Since strings can be their own types in TypeScript it should be possible to take advantage of that feature.

**Comment by mohsen1** [comment]
If `Provider` was a generic [as described here](https://github.com/Microsoft/TypeScript/issues/3960#issuecomment-165335501) it would be possible to make a custom type of all injected props with `type` operator

```ts
export type stores = 'store1' | 'store2';

interface MyStoresProviderInterface { new (): Provider<stores> } ;
const MyStoresProvide = Provider as MyStoresProviderInterface;

const provided = <MyStoresProvide store1={store1} store1={store2} />
```

Then later when injecting

```ts
import stores from './app.ts' // 'store1' | 'store2

typedInject = (store: stores) => inject.bind(inject, store)

@typedInject('store1'); // this will make sure string 'store1' is type safe
```

I don't know TypeScript well enough to say this is a proper way of making Provider and `@inject` type safe, any ideas?

**Comment by mweststrate** [comment]
@mohsen1, I don't think your example will work (especially as strong typing Provider is actually not very interesting, it is on inject where you want to get the proper types). I think the closest way to get there is described here: https://github.com/mobxjs/mobx-react#strongly-typing-inject.

If you feel it can be better typed, feel free to submit a PR!

**Comment by mohsen1** [comment]
I liked the example in README but it's not as type safe as it should be. When you use `as` it's not really strictly typed! :) 

If `Provider` and `inject` where under the same class, we could make that class a generic of store types:


```ts
class MobXReact<StoreType[]> {
    public Provider(...stores: StoreType[]) {
        return Provider.bind(Provider, ...stores); 
    }

    public inject(...stores: StoreType[]) {
        return inject.bind(inject, ...stores)
    }
}
``` 

But those are two independent functions that can't really share generic types without a bridge.

**Comment by mweststrate** [comment]
Yep, and there might be many different configs of Provider and inject in the same app. Unless somebody has a genius idea, I do't think this is feasible
