### ISSUE TITLE
Possible to add something like shape to PropTypes?

### ISSUE THREAD

**Issue by simpixelated** [mobxjs/mobx-react#145]
Is it possible to add something like [React.PropTypes.shape](https://github.com/facebook/react/blob/14156e56b9cf18ac86963185c5af4abddf3ff811/src/isomorphic/classic/types/ReactPropTypes.js#L381) for mobx observable objects? I'm assuming if it was easy it would have already been done! 😄  The [current PropTypes](https://github.com/mobxjs/mobx-react#proptypes) are great! However, I'm having to replace very specific propTypes that used `shape` to verify nested properties with the more generic `observableObject`.

I'm happy to attempt a PR, but wanted to check viability first.

**Comment by mweststrate** [comment]
Just wondering, isn't it composable with react's shape system already? Or could you give some examples where not?

**Comment by simpixelated** [comment]
You're right! I was thinking I would gain some benefit from swapping `shape` for `observableObject`, but in practice I suppose I can continue to use shape to check the nested properties of an observable object.

I was trying to do:
```js
store: mobx.PropTypes.observableObject({
  someProperty: PropTypes.string
});
```

But there's no reason I can't continue to use:
```js
store: React.PropTypes.shape({
  someProperty: PropTypes.string
});
```

Closing this. Thanks for the response @mweststrate!

**Comment by alexhisen** [comment]
Currently we have to use:
Notification.propTypes = {
  observable: React.PropTypes.shape({
    active: React.PropTypes.bool.isRequired,
  }).isRequired,
};
A propTypes.observableShape is what we need, I think.
