### ISSUE TITLE
Warning: forceUpdate(...): Can only update a mounting component

### ISSUE THREAD

**Issue by louy** [mobxjs/mobx-react#149]
With server-side rendering, I'm getting this warning a lot:

```
Warning: forceUpdate(...): Can only update a mounting component. This usually means you called forceUpdate() outside componentWillMount() on the server. This is a no-op. Please check the code for the LoginPage component.
```

I think the issue is that `observer` starts listening for changes on `componentWillMount` and stops on `componentWillUnmount`. However, `react-dom/server` never calls `componentWillUnmount` as the component is never mounted in the first place.

I'm not sure how to solve this to be honest, but the way it works right now probably has a lot of memory leaks as well.

**Comment by mweststrate** [comment]
See #140, a feature will soon be added to stop subscribing to data changes on the server.
