### ISSUE TITLE
Brand new type of component store injection

### ISSUE THREAD

**Issue by Strate** [mobxjs/mobx-react#151]
Hey all. I want to suggest you new, good from typescript view store-to-component injection mechanism.
This is working example:

```tsx
class Store {
  @observable items: string[];
}
class RootComponent extends React.Component<void, void> {
  @inject
  private store: Store;

  render() {
    return <ul>{this.store.items.map(i => <li>{i}</li>}</ul>;
  }
}

ReactDOM.render(
  <StoresProvider><RootComponent /></StoresProvider>
)
```

*Implementation details*

Thanks to typescript `emitDecoratorMetadata` feature, information about type of `RootComponent.store` available at runtime. So, `@inject` decorator can define getter at that field, which gather `Store` instance from context. Context provided by `StoresProvider` component, which manage instances of requested stores too.

For javascript it is possible to pass store class to `inject` decorator: `@inject(Store)`

What do you think about it? Is it fittable to this package, ot mobx-react, or maybe separated package?

**Comment by mweststrate** [comment]
@Strate I think it looks cool! I would only consider the decorator version, for non-typed environments without decorators the old syntax is fine I think.

**Comment by jamiewinder** [comment]
I've been experimenting with something very similar to this:
```typescript
import React from 'react';

export const injectable = (target: Function) => {
    if (!('contextTypes' in target)) {
        target['contextTypes'] = {};
    }
    const contextTypes = target['contextTypes'];
    if (!('mobxStores' in contextTypes)) {
        contextTypes['mobxStores'] = React.PropTypes.object;
    }
};

export const inject = (name: string) => {
    return (target: Object, propertyKey: string | symbol) => {
        Object.defineProperty(target, propertyKey, {
            get: function(this: React.Component<any, any>) {
                return this.context['mobxStores'][name];
            },
            enumerable: false,
            configurable: false
        });
    };
};
```
Basically put `@injectable` on your component, then `@inject` on a field:

```typescript
@injectable
public class TestComponent extends React.Component<any, void> {
    @inject('color') private _color: string; // === "red"
}

// ...

<Provider color='red'>
    <TestComponent />
</Provider
```
I'm sure it could be streamlined (the `@injectable` decorator feels superfluous), but it works. I'm curious to know what the pros and cons are that I can't see? Injecting context into props has always felt weird with mobx-react - I know Redux does it, but MobX has it's own way of handling changing data that aren't reliant on React's idea of changing props.

**Comment by Strate** [comment]
@jamiewinder almost same technique used in my project, With exception of `@injectable` - operations from it performed on first `@inject`

**Comment by jamiewinder** [comment]
@Strate - I tried that and it didn't seem to work. I think I'll give that another go, thanks for the tip. I really like the sound of the benefits of your version (type matching). Any chance you can share the code?

**Comment by jamiewinder** [comment]
Here's an updated version:

```typescript
import React from 'react';

const MOBXSTORES = 'mobxStores';

function ensureContext(target: Function) {
    if (!('contextTypes' in target)) {
        target['contextTypes'] = {};
    }
    const contextTypes = target['contextTypes'];
    if (!(MOBXSTORES in contextTypes)) {
        contextTypes[MOBXSTORES] = React.PropTypes.object;
    }
}

export function provide(name: string) {
    return (target: Object, propertyKey: string | symbol) => {
        ensureContext(target.constructor);
        Object.defineProperty(target, propertyKey, {
            get: function(this: React.Component<any, any>) {
                return this.context[MOBXSTORES][name];
            },
            enumerable: false,
            configurable: false
        });
    };
}
```
Renamed `inject` to `provide` is it seems better suited (and doesn't clash with the existing class decorator). Also does the `contextTypes` changes automatically as @Strate suggested. 

I think it'd be great to have something like this in the library. The above follows the same patterns that `<Provider>` and `@inject` already do so shouldn't be a big deviation in that regard. PR?

**Comment by Strate** [comment]
I don't think that `provide` is good over `inject` - because this is exactly the same behaviour, but applied to property, not a class.
Yet another note: it would be great to allow inject by class:
```ts
class Component {
  @inject
  private store: Store
}
```
and thiw how it could be done in non-typescript:
```ts
class Component {
  @inject(Store)
  private store
}
```

**Comment by Strate** [comment]
Maybe this could be done in separate package? For example `mobx-inject` or `mobx-dic`, with extra ability to handle dependency injection stuff in stores and etc

**Comment by alejomendoza** [comment]
it would be great to have the stateless component support, one thing I'm still missing from this is to be able to inject a class and get that instantiated like the example above. ^^  ```class Component {
  @inject
  private store: Store
}``` this would be similar to what angular2 does.  For now I have to instantiate the class in the injector like this: ```export const FacebookAuth = inject(
  stores => ({
    sessionStore: new stores.SessionStore()
  })
)(({sessionStore}) => {
  return (<Image style={styles.bg} source={require('./facebook-auth-bg.png')}>
    <View style={styles.contentWrap}>``` thoughts?

**Comment by mweststrate** [comment]
@Strate / @jamiewinder sorry, somehow got out of sync with this thread, but I think the `@inject` looks great, especially with the `@injectable. Would any of you feel for creating a PR including tests? Thanks!

**Comment by Strate** [comment]
@mweststrate right now my buddy works on separate package to achieve same behaviour. Ping @mass3ff3ct

**Comment by mass3ff3ct** [comment]
Hi, here's my implementation https://github.com/mass3ff3ct/mobx-react-inject
Strictly do not judge, was created to meet specific needs ))

**Comment by jamiewinder** [comment]
I don't think I'm well placed to champion this anymore, as I've found myself 'converted' to the props-way of doing it (convenient for testing things in isolation). It might still be nice for certain situations though.

**Comment by mweststrate** [comment]
closing issue, I think a separate package is nice. I like the approach (will probably start using it myself), but I thik it is good that the standard package provides one way of doing it. Will make sure it is mentioned in the awesome list though.
