### ISSUE TITLE
Clean up unit tests, setup babel / jest

### ISSUE THREAD

**Issue by mweststrate** [mobxjs/mobx-react#155]
The test suite is currently a quite messy, primitive ES5 only environment. If somebody feels for cleaning and modernizing it, welcome :)

**Comment by A-gambit** [comment]
@mweststrate I can help to improve this case on weekends) Is it still actual?

**Comment by mweststrate** [comment]
Yep! Feel free to pick tools which seem suitable. But I think it is important that a part of the tests will still be run in a real browser environment, and that it is easy to debug in a browser environment, to make sure mobx-react properly works together with Reacts batched rendering / rendering queueing etc. (so far that seemed easier with tape-runner then jest)

I'll add you to the org so that you can easily branch etc. As base branch atm you can best pick `v4`, but I'll hope to release and merge that one back to master within a week.

**Comment by A-gambit** [comment]
@mweststrate thank you. I will create a branch from `v4` and will start test refactoring on the weekends.
