### ISSUE TITLE
Using unsubscribed data structure

### ISSUE THREAD

**Issue by henriklundgren** [mobxjs/mobx-react#159]
How to listen to changes in any unsubscribed structure, i.e.

```javascript
observer(function A() {
  function componentDidMount() {
    // my mobx prop eventually changed that is NOT used in this component
    // ...do update
  }
  function render() {
    return (
      <h1>Nothing here is subscribing to any mobx structure</h1>
    );
  }
}
```

**Comment by mweststrate** [comment]
@henriklundgren so far the question is quite unclear to me, can you make your example a bit more complete ;-) ? Do you have a real life example / scenario?

**Comment by henriklundgren** [comment]
Sorry about that.
The current solution works, though, I guess I am looking for input.

In the example below I am using the value from the observable,
but that is not the case for production code.

```javascript
const state = observable([
  Math.random()
]);

const head = (arr) => arr[0];

const Main = function Main(props) {
  return (
    <div>
      <Bar state={ props.state } />
      <Foo state={ props.state } />
    </div>
  );
};

const Foo = function Foo(props) {
  return observer({
    render() {
      return (
        <ul>
          <button type="button" onClick={ action(() => props.state.push(Math.random())) }>Press me</button>
          { this.props.state.map((value, key) => <li>{value}</li>) }
        </ul>
      );
    }
  });
}

const Bar = function Bar(props) {
  return observer({
    componentDidMount() {
      this.node.innerText = head(this.props.state);

      // current solution
      observe(this.props.state, function(change) {
        const { added } = change;
        this.node.innerText = head(added);
      }.bind(this));
    },
    render() {
      return <h1 ref={ function(node) {
        this.node = node;
      }.bind(this) }>Bar</h1>;
    }
  });
};
```

**Comment by mattruby** [comment]
That's pretty confusing with the props.state. Would you cut a fiddle
showing your issue and I'll try to fix it for you.

**Comment by mweststrate** [comment]
@henriklundgren the interesting question here is: why are you manipulating DOM nodes by hand? You break out of the React component abstraction here, and as a result out of mobx-react as well. If you want this, using `observe` or `autorun` is indeed the way to go (but make sure to clean up the subscriptions on `componentWillUnmount`!)

But foremost I would try to stay within the React system, using `dangerouslySetInnerHTML` if needed if you want to render raw HTML.

On a side node, why is `Foo` not defined as just `observer(props => <ul>..</ul>)` ? Instead you return a new component from what is seemingly already a component, which looks confusing to me?

**Comment by henriklundgren** [comment]
@mattruby Refering to Main? Well, I left out the render method (and also the dependencies :) ).

```javascript
render(<Main state={ state }, document.body);
```

@mweststrate Thanks, reassuring to hear one is one the right path.
For the sidenote,... no reason, I should have, I could have. :)

But to be fair its not really a component in a component, React accepts, either, a VNode/null, or, a object with at least a render method that returns a VNode/null. Both are valid.
