### ISSUE TITLE
Mobx observer: You are trying to use 'observer' on a component that already has 'inject'. 

### ISSUE THREAD

**Issue by vonovak** [mobxjs/mobx-react#161]
I'm developing with RN and getting this: Mobx observer: You are trying to use 'observer' on a component that already has 'inject'. Please apply 'observer' before applying 'inject'.

This is present on both 3.5.9 and 4.0.0.-rc.3

all Components that use both observable and inject in my project have it used in this order:
```
@inject("userStore")
@observer
export default class LoginComponent extends Component {
...
```

**Comment by mweststrate** [comment]
do you use inject with a function somewhere?

Op vr 18 nov. 2016 13:10 schreef Vojtech Novak <notifications@github.com>:

**Comment by vonovak** [comment]
not that I'm aware of, no. But I do use some other decorators too, maybe that could be the trouble. Will get back to it later

**Comment by mweststrate** [comment]
If others also run into this, please report!

**Comment by mweststrate** [comment]
Closing for now, please reopen if others run in this as well
