### ISSUE TITLE
RN: unable to resolve react-dom on 4.0.0-rc3

### ISSUE THREAD

**Issue by vonovak** [mobxjs/mobx-react#162]

**Comment by mweststrate** [comment]
are you requiring from mobx-react/native ?

Op vr 18 nov. 2016 13:26 schreef Vojtech Novak <notifications@github.com>:

**Comment by vonovak** [comment]
Yes, I am. I did npm i of mobx-react rc3 and got this error. I looked at the native.js file and saw "react-dom" directly in there, around line 140 if i remember correctly.

**Comment by mweststrate** [comment]
@vonovak ok thanks for reporting, I'll investigate it! It should be stubbed :(  https://github.com/mobxjs/mobx-react/blob/83e7e93fb202b90b813184e60ee567f1026b22a7/webpack.config.js#L26

**Comment by mweststrate** [comment]
Could you try `4.0.0-rc.4`?
