### ISSUE TITLE
Inject syntax (render error)

### ISSUE THREAD

**Issue by farwayer** [mobxjs/mobx-react#163]
Are you sure new `inject(fn, Component)` syntax is correct? I am getting error:
```js
Component(...): A valid React element (or null) must be returned. You may have returned undefined, an array or some other invalid object.
```

All ok with `inject(fn)(Component)`.

**Comment by mweststrate** [comment]
correct, where did you see this? would you mind creating a PR with a fix?
tnx!

Op di 22 nov. 2016 11:48 schreef farwayer <notifications@github.com>:

**Comment by farwayer** [comment]
Very simple example
```jsx
import React from 'react'
import ReactDOM from 'react-dom'
import {Provider, inject} from 'mobx-react'

function Test() {
  return (
    <div>Hello!</div>
  )
}

const TestInjectedOk = inject(stores => {})(Test);
const TestInjectedError = inject(stores => {}, Test);

function App() {
  return (
    <Provider>
      <TestInjectedError />
    </Provider>
  )
}

const container = document.getElementById('container');
ReactDOM.render(<App />, container);
```

`TestInjectedError` throws error.

**Comment by farwayer** [comment]
I didn't find any code for supporting such `inject` method signature. So look like it's documentation issue. Am I right? If so I can provider PR.
