### ISSUE TITLE
mobx-react@4.0.1: _mobx2.default.extras.setReactionScheduler is not a function

### ISSUE THREAD

**Issue by le0nik** [mobxjs/mobx-react#168]
`extras` is exported here https://github.com/mobxjs/mobx/blob/e32ed8283a493de3a385a2e3a5d69d9303cd49ee/src/mobx.ts#L71

and `setReactionScheduler` is used here https://github.com/mobxjs/mobx-react/blob/master/src/index.js#L17

`extras` should be imported like this instead: `import { extras } from 'mobx';`

This error is not present in mobx-react@3.5.9

I'm using webpack@2 and babel config without commonjs transform

**Comment by mweststrate** [comment]
@le0nik could you verify that `mobx-react@4.0.2-rc` solves the issue?

**Comment by le0nik** [comment]
It does.

**Comment by mweststrate** [comment]
Released as `4.0.2`. Thanks for reporting!

**Comment by omaksi** [comment]
Having the same issue with `4.0.3` but only when using `yarn` to install, when using `npm` it works fine.

**Comment by mweststrate** [comment]
@omaksi doublecheck, isn't your dep pinned? Maybe throw away your lockfile are use yarn update?
