### ISSUE TITLE
[idea] Introduce statefulFunctionComponent?

### ISSUE THREAD

**Issue by mweststrate** [mobxjs/mobx-react#170]
Is this an interesting pattern to introduce? Makes stateful components syntactically a lot more similar to stateless function components. But maybe another syntax is just confusing

demo: http://jsbin.com/camuzip/edit?html,js,output
also needs beter name

```javascript
const {observable} = mobx;

const Counter = statefulFunctionComponent(
  // initial state function (props, context) => state
  ({start}) => ({ counter: start }),
  // new props function (props, state, context) => render function
  ({color}, state) => {
    function inc() {
      state.counter++
    }
  
    function dec() {
      state.counter++
    }
  
    return () => (
      <div>
        <button onClick={dec}>-</button>
        <button onClick={inc}>+</button>
        <span style={{color}}>{state.counter}</span>
        <hr/>
      </div>
    )  
  }
)


const Parent = statefulFunctionComponent(
  () => ({ color: "red" }),
  (props, state) => {
    const toggle = () => state.color = (state.color === "blue" ? "red" : "blue")
  
    return () => (
      <div>
        <Counter start={10} color={state.color} />
        <Counter start={5} color={state.color} />
        <button onClick={toggle}>Color toggle {state.color}</button>
      </div>
    )
  }
)

React.render(
  <Parent />,
  document.body
)

function statefulFunctionComponent(initialStateFunc, renderFunc) {
  return React.createClass({
    componentWillMount: function() {
      this._state = observable(initialStateFunc(this.props))
      this._renderer = renderFunc(this.props, this._state, this.context)
    },
    componentWillReceiveProps: function(nextProps) {
      this._renderer = renderFunc(nextProps, this._state, this.context)
    },    
    render: function() {
      return <mobxReact.Observer>{this._renderer}</mobxReact.Observer>
    }
  })
}
```

**Comment by urugator** [comment]
The point of functional components is not the possibility to write a class as a function, but a realization, that stateless component is so simple that it needs only single method, so it's unneccessary to introduce a class.
In other words the component expressed as a function is a consequence, not the initial goal.
However, what you have presented is complex enought to be rather expressed by class. It actually is a class, you have just changed the class syntax into something much less readable. 
If there is some heavy lifting done by Mobx (aside from constructing a class), let me extend some Mobx.Component or provide Mobx.createClass analogy to React.createClass for ES5 users.

**Comment by mweststrate** [comment]
I agree with you largely, especially and extensible `ObserverComponent` or something like that would be convenient to have (although it composes badly, I don't like it when other libs require you to extend something other than Components, that leads to inheritance classes sooner or later).

But while using and playing with the above pattern, one thing I found much clearer than with normal react classes; the interaction between props and state. Somehow knowing that when receiving new props the second function is called again, but the first one isn't, made it much simpler to reason about then using `componentWillReceiveProps` etc. It might just work only for me, but knowing "everything stored in the second closure will be lost when receiving new props, so store stuff in state if needed" felt much more straight forward then thinking about "what properties should I merge, how does state need to be updated in cWRP"? Of course, it is just sugar, in the end the problem is exactly the same, but for me it was surprising that this pattern made it easier to reason about.
