### ISSUE TITLE
After upgrade to 4.0.0: Can't get instance of React component using enzyme

### ISSUE THREAD

**Issue by chauthai** [mobxjs/mobx-react#171]
I've just updated from 3.5.9 to 4.0.0 and a test that worked fine stopped working with 4.0.0.
I can't get a instance of the observing React component to manipulate an observable.

The enzyme [instance()](https://github.com/airbnb/enzyme/blob/master/docs/api/ReactWrapper/instance.md) function of the [mount wrapper](https://github.com/airbnb/enzyme/blob/master/docs/api/mount.md#mount--reactwrapper) gets a different instance than the one that is actually rendered by the `mount` function.

I will post sample code tomorrow, when I've finished an example.

**Comment by mweststrate** [comment]
@chauthai are you using `inject` (or still using `observer("store name", component)? Note that mounting a HoC wrapped component returns the HoC, not the original component (which can be accessed through the  `wrappedInstance` property). Otherwise, please provide a reproduction :)

**Comment by chauthai** [comment]
I've found the error in my tests. I reassigned my `model/store` with a new mock instead of the properties that should change, thus the dependency graph didn't work anymore.

I will close this issue.
