### ISSUE TITLE
forceUpdate(...) warning though not using constructor setting of state (set setting initial state)

### ISSUE THREAD

**Issue by csepulv** [mobxjs/mobx-react#172]
I get the "forceUpdate" warning referenced in the FAQ, but I am not setting any state in the constructor. I am setting state in componentWillUpdate, but this is a constant value that doesn't come from an observable.

I am only using a value from an observable, in render, that is being read from props (nested object read).

I can provide a stripped down version of my project that would reproduce the error. (Let me know and I will create/share a github repo.)

Attached is my package.json (named package.txt to make github accept it), in case this indicates anything immediate. [package.txt](https://github.com/mobxjs/mobx-react/files/612606/package.txt)

I am rendering client side, with a create-react-app.
(This is a follow up from a a [comment](https://disqus.com/by/disqus_ZnnCW8fQkO/) on transactions -- I thought computed values were an issue, but that turned out to not matter, nor do transactions. )

Thanks

**Comment by mweststrate** [comment]
@csepulv please provide a reproduction :)

**Comment by csepulv** [comment]
I invited you to a repo. let me know if you have any questions

**Comment by mweststrate** [comment]
Sorry for the late response and thanks for the clear reproduction! Just checked the repo and the issue is correct. You are actually doing side effects in your rendering, which should be avoided. Use lifecycle hooks like `componentWillMount` instead. The following components are confusing their rendering with actions they want to invoke when being rendered:

```
const LoadEmptySearch = () => {
    stores.searchStore.reset(); // Side effect in render! use lifecycle hook
    return NewAppFrame();
};

const SearchRoute = (props) => {
    if (props.location.query) {
        stores.searchStore.search(props.location.query.q); // Side effect in render! use lifecycle hook
    }
    return NewAppFrame();
};
```

**Comment by csepulv** [comment]
Thanks for the reply. I think I am confused on lifecycle. In the following,
```
const LoadEmptySearch = () => {
    stores.searchStore.reset(); // Side effect in render! use lifecycle hook
    return NewAppFrame();
};
```
...my understanding is that **reset**, which changes state, updates all observers synchronously. The observing components only reference their props, so I would have thought they are only referencing  stable state, as render would occur after the synchronous state update. 

What am I missing? I am sorry if I am asking more of a react question than a mobx question. I am not sure how using `componentWillMount ` helps as I am not calling `setState`, but only using props (as noted). 

Thanks for the help.

**Comment by mweststrate** [comment]
What you are missing here is that you want is _technical_ not incorrect, but _conceptually_ it is and goes against one of the core principles of react: render is side effect free. React it smart enough to detect that, and hence it warns you.

As a direct effect of your rendering `LoadEmptySearch`, you change the state, causing a new render. With this pattern it is trivial to trigger an 'unendless' render and you make it very hard to optimize renderings for the framework. You cannot make any assumptions anymore about render once it starts doing side effects. If it can't do side effects, one can make assumptions like: "If the state looks the same as the previous one, you can skip render". But such optimizations will break your application if you have side effects, as that could mean that suddenly your `reset` code is not triggered anymore! So _first_ you should compute and do everything you need to do to render (by using lifecycle hooks), then you should _actually_ render. But those phases should not be mixed up! See also: https://facebook.github.io/react/docs/react-component.html#render (although there are probably more extensive elaborations on this principle)

**Comment by csepulv** [comment]
Thanks for the info. You can consider this closed (at least from my perspective).
