### ISSUE TITLE
Issues with Inject while using enzyme's shallow mount for testing

### ISSUE THREAD

**Issue by Niryo** [mobxjs/mobx-react#176]
Hi, 
Im trying to use enzyme's shallow mount for testing a component, but the problem is that shallow mount can only have one children so I can't wrap the tested component with a provider, what causes the inject function to throw an exception.

Is there a way to make Inject fail gracefully?
In my tests I want to create the component without the provider and just pass a mocked store directly via the component props. 
Any suggestions?
Thanks!

**Comment by mweststrate** [comment]
In it self `inject` can work without provider, just pass in the store explicitly as properties with the same name when creating the component.

However in this specific case that probably won't do, as shallow rendering will then just render the higher order Inject component, and not your original component. So instead you should use the `wrappedComponent` property. Example:

```javascript
@inject("myStore") @observer
export class MyComponent extends React.Component {

}

---

shallowMount(<MyComponent.wrappedComponent myStore={someStore} />)
```

should do the trick

**Comment by Niryo** [comment]
Perfect, thanks!

**Comment by pieterdv** [comment]
Hi,

I'm trying to write a test in typescript, App.wrappedComponent is not accepted are there workarounds for typescript?
 
![image](https://cloud.githubusercontent.com/assets/1443286/23298032/42cc5230-fa7c-11e6-956d-40620d2e75f5.png)

KR

**Comment by kresli** [comment]
Am I right if I say you need to add `myStore` props when testing for all child components even if you are not using `@inject` directly on child component?

**Comment by xiaosunJessica** [comment]
I use shallow (<MyComponent.wrappedComponent myStore={someStore} />), but myStore can not inject success

**Comment by phillipwhelan** [comment]
My team is running into this issue now, in our move from mobx 3 -> mobx .  We use the Provider/Inject pattern.  I tried providing the component with all the items it injects as @mweststrate mentioned above but we are not having any luck with it.  We are hitting the following type of error.
```Invalid hook call. Hooks can only be called inside of the body of a function component. This could happen for one of the following reasons:
    1. You might have mismatching versions of React and the renderer (such as React DOM)
    2. You might be breaking the Rules of Hooks
    3. You might have more than one copy of React in the same app
    See https://fb.me/react-invalid-hook-call for tips about how to debug and fix this problem.

      34 |              const wrapper = shallow(
      35 |                      <JobBasicRunOptions dialog={{}} JobUIStore={{ canUseScheduling: jest.fn() }} glassContext={{}} JobStore={{ isSequenceProcessing: true, canWrite: true }} StringResource={aRes} />
```
We are using snapshot testing as part of our unit testing, doing a full mount in that scenario doesn't make sense since we do not want to bring in the entire component tree.  Short of re-writing our code to not use Provider, does anyone have a viable work around.

**Comment by FredyC** [comment]
Please, refrain from commenting on old and closed issues as only a few people will see that. Open new issue with all necessary details. Thank you.
