### ISSUE TITLE
Enzyme's shallow() doesn't recognise the component when decorated with both @observer and @inject

### ISSUE THREAD

**Issue by leudanielm** [mobxjs/mobx-react#178]
So the workaround for this was usually to use `@observer(['store1', 'store2'])`. Since this approach is now deprecated and probably will be removed at some point, this will be quite an issue.

This is the error:
`Invariant Violation: Component(...): A valid React element (or null) must be returned. You may have returned undefined, an array or some other invalid object.`

As soon as I remove one of the decorators, everything works as expected.

**Comment by mweststrate** [comment]
see the recently closed issues

Op vr 9 dec. 2016 15:17 schreef Daniel Leu <notifications@github.com>:

**Comment by mweststrate** [comment]
(on mobile) short answer use .wrappedComponent

Op vr 9 dec. 2016 16:38 schreef Michel Weststrate <mweststrate@gmail.com>:

**Comment by leudanielm** [comment]
Thank you!
