### ISSUE TITLE
@autorun/reaction() decorators on component methods

### ISSUE THREAD

**Issue by JabX** [mobxjs/mobx-react#181]
I know this is a duplicate of #122, but I'd like to make a real proposal instead of just describing how to achieve the behaviour using "vanilla" MobX autorun/reaction.

Currently, to create custom reactions on a component, we have to do something like this:
```ts
@observer
class Test extends React.Component {
    reaction = autorun(() => console.log(foo.prop);
    
    componentWillUnmount() {
         this.reaction();
    }
}
```
This works fine, but it's not exactly convenient and as easy to use as it could be. Moreover, the use of MobX with React allow us to drastically reduce our usage of lifecycle methods, especially annoying stuff like `componentWillReceiveProps`/`componentWillUpdate` which are in most cases best handled by MobX (post-render events will forever remain since they are our only point of access to the DOM, which is stricly React's business). So being forced to keep a `componentWillUnmount` around as *boilerplate* code, especially when MobX's main advantage over something like Redux is that it requires none, is simply disappointing.

@mweststrate speaks a lot about how using `componentWillMount` is an anti-pattern and that we should react to state changes instead, and he is exactly right. The problem is that using `componentWillMount` requires no boilerplate or does not require that reactions occur outside of the component, and it achieves most of the time the same behaviour. And is what people know and use. Another strong point of MobX is that it's unopinionated, so it shouldn't indirectly enforce some application structure over another. For instance, injecting stores into components is the better approach to using them directly, but I can still do very easily the latter if I believe setting up dependency injection isn't worth it.

We also have a weird `componentWillReact` lifecycle hook for which I never found a use (the exemple on the readme simply calls `console.log`), and is basically a worse `componentWillUpdate`.It does not have access to the old values and simply triggers any time an observable used in the render method is updated, which is not very precise and all in all very alien to how MobX reactions work.

My proposal is simple: I'd like to have some kind of decorator, which probably won't be called `@autorun` or `@reaction` for name-clashing reasons, that I can put on any method inside an `@observer` component, that will add the reaction boilerplate for me. It should have both `autorun` and `reaction` signatures, maybe `@classReaction` for `autorun` behaviour and `@classReaction(selector, fireImmediately?)` for `reaction` behaviour (I don't like that name, we'll need a better one).

That way, I can replace
```ts
async componentWillMount() {
      this.data = await server.load(this.props.id);
}
```
by
```ts
@classReaction
async load() {
     this.data = await server.load(this.props.id);
}
```
which is in all respects a better solution, and one that you'll have no problem convincing people to use.

I used the `componentWillMount` replacement exemple because it's the simplest use case for it, but I have a lot of more advanced uses of reactions that would definitely benefit from something like this too.

With this, I think we would be able to definitely relegate lifecycle methods to pure React-uses only (DOM events/manipulation is the big thing I see), which would help consolidate the roles of each framework in a React-MobX application.

**Comment by mweststrate** [comment]
@JabX thanks for the suggestion, I see more requests for this. Not sure but it might fit in the following package as well: https://github.com/farwayer/mobx-decorators

It might be interesting to add and `@autorun` decorator to either that package or the mobx package. Using that decorator one or multiple times on an instance should then also create a disposer method that cleans all disposers for that instance. Either `instance.mobxDisposeReactions()` or disposeInstanceReactions(instance)`  or something similar. 

If that instance method present, mobx-react could easily invoke it, if it is on the component instance that is being unmounted.

**Comment by JabX** [comment]
@mweststrate 
I think it belongs more into `mobx-react` because it will be tied to React itself (relying on `componentWillUnmount`) and because I suppose it would reach a broader audience it it were packaged. Not to mention the implemention would probably be simpler since it would fit right in the `observer` enhancements instead of in an additional layer that would probably require an extra decorator on the class.

**Comment by ehartford** [comment]
I just tried to use @autorun decorator simply assuming it would be there, since @observable and @computed is there.  I want to maintain an @observable backed [crossfilter](https://github.com/square/crossfilter/wiki/API-Reference), and I need to explicitly dispose my dimensions and groups and recreate them when the data changes.

**Comment by mweststrate** [comment]
Follow up question, how should these decorators be called? i think it will be very confusing if both `mobx` and `mobx-react` expose `reaction` and `autorun`

Another solution could be providing an utility to easily setup disposers, so that one could write:

```javascript
@observer
class Test extends React.Component {
   componentWillMount() {
      this.addDisposer(reaction(() => stuff, () => { stuff(); }))
   } 
}
```

I do like 
```javascript
import {reaction, observer} from "mobx-react"

@observer
class Test extends React.Component {
   @reaction(() => this.props.id)
   fetchData(id) {
      
   }
}
```

better indeed, but I fear import `reaction` from mobx-react might be very confusing....

**Comment by mweststrate** [comment]
See #561: Mobx-react 5.3.0 introduced the `disposeOnUnmount` decorator: https://github.com/mobxjs/mobx-react#disposeonunmountcomponentinstance-propertykey--function--function
