### ISSUE TITLE
Error when sending a mobx store in a Jest snapshot test

### ISSUE THREAD

**Issue by hybrisCole** [mobxjs/mobx-react#186]
"mobx": "2.7.0",
"mobx-react": "4.0.3",
"react": "~15.3.2",
 "react-native": "0.33.1",

```
const messageState = require('../../../../stores/message/').default;
messageState.mapThreadData([sampleMessage], '585c990579d78b11a4f97ad1');

test('MessageListView', () => {
  const tree = ReactTestRenderer.create(
    <MessageListView messageState={messageState} />
  ).toJSON();
  expect(tree).toMatchSnapshot();
});
```

The following throws:
`Invariant Violation: ReactUpdates: must inject a reconcile transaction class and batching strategy`

But, if I do

```
test('MessageListView', () => {
  const tree = ReactTestRenderer.create(
    <MessageListView messageState={{
    threads : [{
      id : '585c990579d78b11a4f97ad1',
      messages : [sampleMessage],
    }],
    threadMessages : [sampleMessage],
  }} />
  ).toJSON();
  expect(tree).toMatchSnapshot();
});
```

It won't fire errors, any ideas?

**Comment by mweststrate** [comment]
There is probably a cleaner solution by using a difference test renderer or something, but this might help: https://medium.com/@wietsevenema/using-jest-with-react-native-and-mobx-34949ea7d2cf#.v11m3rh84

Apologies for the late response!

**Comment by mweststrate** [comment]
@cpojer does the exception `Invariant Violation: ReactUpdates: must inject a reconcile transaction class and batching strategy` ring a bell? Searched for it but couldn't find anything tangible. Mobx-react uses `reactNative.unstable_batchedUpdates` internally, could that give potential issues with the test-renderer?

**Comment by cpojer** [comment]
yeah might be an issue with the test renderer; it's best to bring this up with the react team.

**Comment by winterbe** [comment]
@mweststrate @cpojer I'm facing the same problem after updating my ReactNative apps to Mobx 3. The linked medium article whatever solves the error by adding the following:

```js
jest.mock('mobx-react/native', () => require('mobx-react/custom'));
```

This works great with Jest watch mode but when using Jest without watch the process hangs forever after executing all tests.

Here's a simple open source projects to reproduce this problem: https://github.com/winterbe/RNTimerExample

Running `npm test` on this project results in the following output but the process hangs forever at the last line:

```
❯ npm test

> RNTimerExample@0.0.1 test /Users/winterbe/Projects/RNTimerExample
> jest

 PASS  test/App.test.js
  ✓ renders correctly (115ms)

Test Suites: 1 passed, 1 total
Tests:       1 passed, 1 total
Snapshots:   1 passed, 1 total
Time:        0.992s, estimated 1s
Ran all test suites.
```

**Comment by cpojer** [comment]
This means that you aren't properly disabling and unsubscribing from your resources, such as network requests or database connections. Clean up after yourself and it'll work properly!

**Comment by winterbe** [comment]
@cpojer Thanks for your comment. However the only test is a simple Jest snapshot test: 

```js
jest.mock('mobx-react/native', () => require('mobx-react/custom'));

it('renders correctly', () => {
    const component = renderer.create(
        <App />
    );
    const tree = component.toJSON();
    expect(tree).toMatchSnapshot();
});
```

I guess it's something Mobx related, e.g. observer reactions not properly closed!? @mweststrate

**Comment by cpojer** [comment]
Yep, seems like that is MobX then. Jest has an escape hatch with `--forceExit` but we encourage people to fix the underlying issues.

**Comment by mweststrate** [comment]
Will investigate. Might be that the renderer triggers different lifecycle
hooks then expected. Is e.g. componentWillUnmount for `component`?

Op di 24 jan. 2017 om 11:46 schreef Christoph Pojer <
notifications@github.com>:

**Comment by cpojer** [comment]
It's also possible that this particular component that is rendered sets up an interval or something like that.

**Comment by mweststrate** [comment]
Fair point, if @winterbe does't find something obvious, I'll dive into it
later this week

Op di 24 jan. 2017 om 11:57 schreef Christoph Pojer <
notifications@github.com>:

**Comment by winterbe** [comment]
@mweststrate IIRC it's the reaction scheduler which is not disposed at the end of the test suite. When using the following code before test, the message gets logged indefinitely:

```js
jest.mock('mobx-react/native', () => require('mobx-react/custom'));
mobx.extras.setReactionScheduler(() => console.log("scheduling"));
```

**Comment by winterbe** [comment]
Good point. I'm using this hook in the tested component. I'll check later
if calling he hook manually from test solves the issue.


Michel Weststrate <notifications@github.com> schrieb am Di. 24. Jan. 2017
um 11:51:

**Comment by mweststrate** [comment]
Could you try with: mobx.extras.setReactionScheduler((f) => { console.log("
scheduling") f()}); That is the correct signature from the top of my head

Op di 24 jan. 2017 om 12:55 schreef Benjamin Winterberg <
notifications@github.com>:

**Comment by winterbe** [comment]
OK, it was my fault. Sorry for the inconvenience. I have to unmount the component manually for the test renderer to call `componentWillUnmount` which in my case has side effects to a mobx store.

So, everything's fine with using the workaround: `jest.mock('mobx-react/native', () => require('mobx-react/custom'));`

However it would be nice if this workaround won't be necessary.
