### ISSUE TITLE
Unexpected rendering behaviour after update

### ISSUE THREAD

**Issue by chrisrichard** [mobxjs/mobx-react#187]
I'm running into a bit of unexpected behaviour re-rendering after an action. I've put together a simple repro at https://github.com/chrisrichard/mbox-react-timing-issue

It's based on the mobx-react-boilerplate and simply outputs the current timer value once the value is > 3. The issue is that the first time the component (Something) renders it sees the timer value as 3 even though it's not rendered until its parent component (Condition) sees the timer value as 4. The Something component re-renders immediately with timer equal to 4 but I didn't expect that Something would ever be rendered with props.timer = 3 and in a more complex scenario I want to be able to assume that's the case.

I feel like there's a reasonable chance this is expected withe the setup I have but at least hoping to figure out how I should rework it.

**Comment by mweststrate** [comment]
@chrisrichard If I remember correctly this question was already answered on gitter? If that isn't the case, let us know :). If it is the case, please close the issue ;-)

**Comment by chrisrichard** [comment]
@mweststrate You suggested I open an issue after adding an additional @observer annotation didn't solve the problem.

**Comment by mweststrate** [comment]
Sorry for not coming back earlier on this one. Closing as this problem is probably not urgent anymore? Otherwise feel free to reopen

**Comment by chrisrichard** [comment]
@mweststrate Just read https://github.com/facebook/react/issues/11527#issuecomment-360199710 and I think that's what I was running into here. The 'Condition' component contains the Mobx observable and the child 'Something' receives a prop containing the value. So Condition renders immediately and outputs the Something component which displays the stale value.

>I don’t know why MobX users haven’t bumped into this, but my intuition is that they might be bumping into such scenarios but consider them their own fault.

Heh.
