### ISSUE TITLE
Support method decorator

### ISSUE THREAD

**Issue by aihornmac** [mobxjs/mobx-react#191]
Support syntax like this:
```jsx
@observer class List extends React.Component {
  ...
  @observer Auth = () => <div>this.props.state.name</div>
  ...
  render () {
    return <Root><this.Auth /></Root>;
  }
}
```

**Comment by mweststrate** [comment]
Thanks for the idea! I think this could be done, but note that at least you should be able to achieve the same with `Observer` regions.

```javascript
import {Observer, observer} from "mobx-react" 

// as-is

Auth = () => <Observer><div>this.props.state.name</div></Observer>
```

**Comment by aihornmac** [comment]
@mweststrate Yes, but as far as I reviewed [the source code](https://github.com/mobxjs/mobx-react/blob/master/src/observer.js#L311), `Observer` only accepts `function` (stateless component) as children.

In fact above code can be written like this:
```jsx
Auth = observer(() => <div>this.props.state.name</div>)
```

Sometimes there might be cases like this, where `Observer` could be less graceful:
```jsx
// method decorator
@observer Home = () => {
  const { auth: { user }, userList } = this.props.state;

  if (user.is('admin')) {
    return <UserList ui={userList} />;
  }

  if (user.is('editor')) {
    return <div>editor</div>;
  }

  return <div>Unauthorized</div>;
}

// Observer
Home = () => <Observer children={() => {
  const { auth: { user }, userList } = this.props.state;

  if (user.is('admin')) {
    return <UserList ui={userList} />;
  }

  if (user.is('editor')) {
    return <div>editor</div>;
  }

  return <div>Unauthorized</div>;
}} />
```

**Comment by mweststrate** [comment]
Correct, sorry, bad example. 

Note that using `observer` in the property is a bit less clean; it will create a new component type for each instance of your Home component.

**Comment by mweststrate** [comment]
Closing for now as it should be encouraged to separate instead of nest components in general, and there is  viable alternative: `Auth = observer(() => <div>this.props.state.name</div>)` / Auth = <Observer>{() => <div>this.props.state.name</div>}</Observer>`
