### ISSUE TITLE
When to call useStaticRendering, and how many times?

### ISSUE THREAD

**Issue by ryancole** [mobxjs/mobx-react#192]
Should `useStaticRendering` be called once, as part of the server application's init routine? Should it be called once for each request? Should it be called at some point in every component that is an observer? The docs explain the function and why it's needed, but I'm unclear as to when and where to call it.

Thanks!

**Comment by mweststrate** [comment]
Should be called only once :)

Op di 10 jan. 2017 om 20:19 schreef Ryan Cole <notifications@github.com>:

**Comment by ryancole** [comment]
Great, thanks!
