### ISSUE TITLE
Testing Async Rerenders

### ISSUE THREAD

**Issue by mjewell** [mobxjs/mobx-react#194]
We have a component which has an asynchronous action inside it triggered by a click. We wanted to test that after the action is completed, the component re-renders in the way we expect. A simple example looks like this:

```jsx
import React, { Component } from 'react';
import { action, observable } from 'mobx';
import { observer } from 'mobx-react';

@observer
export default class MyButton extends Component {
  @observable submitting = false;

  @action
  save() {
    this.submitting = true;
    return new Promise(resolve => {
      setTimeout(resolve, 100);
    })
      .then(action(() => {
        this.submitting = false;
      }));
  }

  render() {
    return (
      <button
        onClick={() => this.save()}
        disabled={this.submitting}
      >
        I'm a button
      </button>
    );
  }
}
``` 

```jsx
import { mount } from 'enzyme';
import React from 'react';
import { expect } from 'chai';
import { describe, it } from 'mocha';
import MyButton from './myButton';

describe('<MyButton />', () => {
  it('should have the correct state when submitting', done => {
    const myButton = mount(<MyButton />);
    let button = myButton.find('button').first();
    button.simulate('click');

    let buttonProps = button.props();
    expect(buttonProps.disabled).to.equal(true);

    // how can we know when the component has re-rendered without waiting?
    // the timeout must be greater than the timeout in the button component to
    // make this pass
    setTimeout(() => {
      button = myButton.find('button').first();
      buttonProps = button.props();
      expect(buttonProps.disabled).to.equal(false);
      done();
    }, 200);
  });
});
```

Is there a recommended way to test this behaviour? Or a recommendation for another way to write components which makes this kind of thing easier to test?

Thanks

**Comment by mweststrate** [comment]
This is always tricky to test, as there is some hidden timeout, and no promise or something to chain in the react world (not that without timeouts, renders happens in sync in tests). One thing I could think of is to pass a callback to the component for testing purposes, and call it from `componentDidUpdate` or `componentWillReact` lifecycle hooks, e.g. `this.props.onRenderCompleted && this.props.onRenderCompleted()`

**Comment by mjewell** [comment]
Thanks for the quick response. Based on what you said it looks like I can get the test working by changing the `setTimeout` part of the test to this:

```jsx
whenWithTimeout( // from 'mobx-utils'
  () => !myButton.get(0).submitting,
  () => {
    setTimeout(() => {
      buttonProps = button.props();
      expect(buttonProps.disabled).to.equal(false);
      done();
    }, 0);
  },
  1000,
  () => done(new Error('fail'))
);
```

However, it does not work if i remove the `setTimeout`, although in this case it is less of an issue since it has 0 timeout. Do you know why that `setTimeout` is required? Since the re-render should be synchronous the only thing I can think is that the `onTimeout` callback of `whenWithTimeout` is being scheduled before the render, although I'm not sure how that order is determined.

**Comment by mjewell** [comment]
But we are waiting for the submitting state to be false again which happens in the `then` of the promise... shouldn't changing that cause the re-render to happen synchronously?

**Comment by mweststrate** [comment]
Your button starts in state `submitting` false, so your whenWithTimeout will probably succeed before anything has happened at all, instead, what you are probably expecting, after the promise has resolved

**Comment by mjewell** [comment]
Just to clarify, here is the full test after the edit:

```jsx
describe('<MyButton />', () => {
  it.only('should have the correct button text and submitting state when submitting', done => {
    const myButton = mount(<MyButton />);
    const button = myButton.find('button').first();
    button.simulate('click');

    let buttonProps = button.props();
    // submitting is true here
    expect(buttonProps.disabled).to.equal(true);

    whenWithTimeout(
      () => !myButton.get(0).submitting,
      () => {
        setTimeout(() => {
          buttonProps = button.props();
          expect(buttonProps.disabled).to.equal(false);
          done();
        }, 0);
      },
      1000,
      () => done(new Error('fail'))
    );
  });
});
```

So the when with timeout is definitely started after the submitting state is set to true and waiting correctly. Additionally, the test is definitely waiting the full setTimeout specified:

  <MyButton />
    ✓ should have the correct button text and submitting state when submitting (104ms)


  1 passing (106ms)

**Comment by mweststrate** [comment]
Double check: what mobx-react version are you using? I think the behehavior you might see is actually correct, because you are asserting a side effect of another reaction (namely changing a prop of button). 

Your test (without timeout) is assuming that `whenWithTimeout` runs after `render` and not before. But since there is no relation between those two reactions, MobX could run them in either order (they both react to a change in `submitting`, but that your `whenWithTimeout` depends on a side effect of your render, eg. updating `disabled` is something MobX cannot know. So the problem is probably not that they they run async, both run in sync, but not just not in the order you need :)

In that sense, I think my original proposal; passing a callback to the component and call that in `componentDidUpdate` is a more safe approach.

**Comment by mjewell** [comment]
I am on version 3.5.9. And yeah, ok, that sounds like what I was thinking then. Thanks for all the help.
