### ISSUE TITLE
Inject precludes using TransitionGroup

### ISSUE THREAD

**Issue by mcav** [mobxjs/mobx-react#196]
Since `inject` creates an intermediate component, react-addons-transition-group is unable to see the wrapped component's method hooks (e.g. `componentWillEnter`/`componentWillLeave`). I'm not sure what the best solution is; we could special-case these hooks since they're popular lifecycle addons, but that doesn't seem ideal. I wonder if we could hoist them similarly to how we already `hoistStatics`?

**Comment by mweststrate** [comment]
Note that you can access the wrapped component / instances through `wrappedInstance` / `wrappedComponent`. Hoisting by default is quite confusing and lead to quite some issues in the past. You could consider using `<Observer>` section instead of `observer` decorator

**Comment by mweststrate** [comment]
Also note that the order of decorators / HoCs is very important. See also this answer: https://github.com/mobxjs/mobx-react/issues/228#issuecomment-290348396
