### ISSUE TITLE
Can stores return json objects and array directly?

### ISSUE THREAD

**Issue by rodryquintero** [mobxjs/mobx-react#20]
I am doing my first projecdt with Mobservable and I realized that data returned from the store is an observable.

I would like to have the store transform the data to a JSON object/array so that I don't have to call `.toJSON()` everytime.

**Comment by mweststrate** [comment]
You can simply start by putting the `.toJSON()` in an autorun and triggering the action that need the json from there (like storing it on the server). 

A bit more advanced and powerful approach is to combine `autorun` with `createTransformer` to create a json representation of your complete state which is always kept up to date, see the first example on: http://mweststrate.github.io/mobservable/refguide/create-transformer.html
