### ISSUE TITLE
@observable throws error on older Tablet OS

### ISSUE THREAD

**Issue by centinel3** [mobxjs/mobx-react#201]
I am loving mobx, and have implemented a small app on some tablets and ran into an issue with older javascript on the Android WebView (which I can't upgrade due to the age of the tablet). 

Android Tablet: Nexus 4.4 (lollipop)

The error is below, though it looks like at around 2740 in the mobx.js file (function below) is having issues with @observables with older javascript engines.

I'm currently using webpack (see below) to transpile my js. Any help with this would be much appreciated as I really would like to use mobx moving forward. 

Sincerely,
Chris

line 2740 in mobx.js
function isES6Map(thing) {
    if (thing instanceof getGlobal().Map)
        return true;
    return false;
}

console Error:
[mobx] Catched uncaught exception that was thrown by a reaction or observer component, in: 'Reaction[CustomerFeedback#0.render()] 
TypeError
message: "Expecting a function in instanceof check, but got locations-page"
stack: (...)
get stack: function () { [native code] }
set stack: function () { [native code] }
__proto__: Error
 mobx.js:1284
Reaction.reportExceptionInDerivation

**webpack:**
'use strict';

const autoprefixer = require('autoprefixer');
const copyWebpackPlugin = require('copy-webpack-plugin');
const extractTextPlugin = require('extract-text-webpack-plugin');
const path = require('path');

const scssLoaders = [
    'css-loader',
    'postcss-loader',
    'sass-loader?indentedSyntax=false&includePaths[]=' + path.resolve(__dirname, './application')
];

const config = {
    debug: true,
    devtool: 'source-map',
    entry: ['babel-polyfill', './index.js'],
    module: {
        loaders: [
            {
                test: /\.(js|jsx)$/,
                exclude: /node_modules/,
                loader: ['babel-loader'],
                query: {
                    cacheDirectory: true,
                    plugins: [
                        'transform-decorators-legacy',
                        'transform-class-properties',
                        'mobx-deep-action'
                    ],
                    presets: ['es2015', 'stage-0', 'react'],
                    babelrc: false
                }
            },
            {
                test: /\.scss$/,
                loader: extractTextPlugin.extract('style-loader', scssLoaders.join('!'))
            },
            {
                test: /\.(svg|jpg|png)$/,
                loader: 'file-loader?name=/media/[name].[ext]'
            }
        ]
    },

    output: {
        path: path.join(__dirname, './build'),
        publicPath: '/build',
        filename: '[name].js'
    },

    plugins: [
        new extractTextPlugin('[name].css')

    ],

    postcss: [
        autoprefixer({
            browsers: ['last 2 versions']
        })
    ],

    resolve: {
        extensions: ['', '.js', '.jsx', '.scss'],
        modulesDirectories: ['./node_modules/'],
        root: [path.join(__dirname, './application')]
    }
};

module.exports = config;

**appState File:**
import { action, computed, extendObservable, toJS } from 'mobx';

class CustomerFeedbackState {
    constructor() {
        // Initializes all observables
        this.initializeStoreData();
    }

    /* ACTIONS */
    // Initialize the store's state, allowing a reinitialization of the app as needed (reset to default state)
    @action initializeStoreData() {
        extendObservable(this, {
            // Keeps track of what page the user is on - 'locations-page' is the start page
            currentPageName: 'locations-page',

            // Keeps track of what question is being asked
            currentQuestionNumber: 0,

            // Set to true when the JSON data comes back successful
            dataFetched: false,

            // sets the active state for the next button
            disableNextPage: true,

            // Keeps track of page history
            lastPageVisitedArray: [],

            // Current Location Id
            locationId: 0,

            // Mood link active states
            moodLinkHappyIsActive: false,
            moodLinkNeutralIsActive: false,
            moodLinkSadIsActive: false,

            // Next page available
            nextPage: '',
            
            // User mood
            userMood: ''
        });
    }

    [...]
}

**Comment by andykog** [comment]
Are you using the latest mobx@3.0.2?   Should be already fixed

**Comment by centinel3** [comment]
I'm using NPM through Visual Studio and that version doesn't look like it's available. I tried to just type in the version and that didn't work. What is the best way to get the latest version of Mobx so that this issue goes away on older machines running older js runtimes?

**Comment by centinel3** [comment]
Thank you @andykog, I'll give that a try. -Chris
