### ISSUE TITLE
componentDidMount vs componentWillMount

### ISSUE THREAD

**Issue by chrisdrackett** [mobxjs/mobx-react#202]
I have a component that was setting some mobX state within `componentWillMount`. This worked fine. However, for some reason the other properties that this component is observing do not cause the component to re-render. This can be fixed by either taking out the  `componentWillMount` or replacing it with `componentDidMount`. We're fine using `componentDidMount` but I'd really like to know what the issue with `componentWillMount` was.

**Comment by mweststrate** [comment]
Is what you are describing the same as #195 ?

**Comment by chrisdrackett** [comment]
yeah, this looks the same as what we ran into

**Comment by mweststrate** [comment]
Does this solution apply to your case as well? https://github.com/mobxjs/mobx-react/issues/195#issuecomment-290358014

**Comment by mweststrate** [comment]
Released 4.1.4, feel free to re-open if not resolved
