### ISSUE TITLE
Debounce observer like autorunasync in mobx

### ISSUE THREAD

**Issue by ckwong90** [mobxjs/mobx-react#203]
To my understanding, observer wraps the render method in react with autorun and automatically re-renders as observables are changed. AutorunAsync has a debouncing option. Wrapping render around autorunasync when an option is specified so observable changes can be debounced and render after some specified interval.

Is there already an existing solution to debouncing react observers?

Example:
```
@observe(16) //debounce 16ms
class ReactElement extends Component {...}
```

**Comment by mweststrate** [comment]
What benefit would that yield? Do you have a real life usecase for such a
scenario?

Op zo 12 feb. 2017 om 00:26 schreef Chris Kwong <notifications@github.com>:
