### ISSUE TITLE
Testing nested @inject components

### ISSUE THREAD

**Issue by scriby** [mobxjs/mobx-react#204]
Hi,

I'm running into an issue trying to test a component which _uses_ components that are decorated with `@inject`. As a quick example:

```
const TestComponent = () => <div><DatePicker /></div>

@inject('something')
class DatePicker extends React.Component {
  render() {
    ...
  }
}
```

When using enzyme to do a shallow render on TestComponent, I can't "find' the DatePicker component because the name was changed to "inject-DatePicker-with-something".

I am wondering if there is any standard advice or best practice for this scenario.

Thanks,

Chris

**Comment by scriby** [comment]
I found that I can refer to the wrapped component's displayName property to locate the component. That works well enough for my purposes.

**Comment by mweststrate** [comment]
Consider mounting the `DatePicker.wrappedComponent` instead and pass in the
`something` property explicitly

Op di 14 feb. 2017 om 04:24 schreef scriby <notifications@github.com>:

**Comment by scriby** [comment]
I'm not testing the DatePicker component directly. I'm testing a component that contains the DatePicker, and I want to verify that some props got passed to it.

**Comment by scriby** [comment]
I'll go ahead and close this since I have an acceptable workaround

**Comment by sjonner** [comment]
@scriby Can you elaborate on what acceptable workaround you used?

**Comment by scriby** [comment]
Instead of .find('DatePicker'), you can do .find(DatePicker.displayName)
