### ISSUE TITLE
@observer swallowing render stack traces

### ISSUE THREAD

**Issue by icodeforlove** [mobxjs/mobx-react#206]
When I place the `@observer` decorator at the top of a react class the stack traces for errors becomes useless.

```
.render(): A valid React element (or null) must be returned. You may have returned undefined, an array or some other invalid object.
```

When it should actually break before it even tries to look at the results of the render method, and provide a useful stack trace.

Has anyone else got this working properly or am I doing something wrong? 

This is happening with the following modules installed

```
"react": "15.4.2",
"mobx": "3.1.0",
"mobx-react": "4.1.0"
```

**Comment by mweststrate** [comment]
In MobX 3 the behavior of errors in reactions has changed indeed, to avoid that apps crash completely / get into an inconsistent state if a single reaction (in this case component) stops working. In this case we should probably attach a custom error handler to the reaction and communicate the error back to react. Thanks for reporting!

**Comment by tekacs** [comment]
This is making the process of upgrading to MobX 3 very difficult, as things stand.

Due to the breaking changes, upgrading MobX to version 3.x necessarily introduces some errors which need to be found. Finding them is tricky however, when mobx-react is swallowing errors (I'm having to use Chrome's JS debugger to find errors).

Would be really great to see a fix to this. Thanks!

**Comment by chemzqm** [comment]
This behaviour makes debug much harder

**Comment by mweststrate** [comment]
On it!

**Comment by mweststrate** [comment]
Version `4.1.2` should fix it, can somebody verify?

**Comment by tekacs** [comment]
@mweststrate I can confirm that this now works. :) Thanks!

**Comment by chemzqm** [comment]
Works now, I can get the correct error stack when render function throws.
For people want the error stack to support source map, this module https://github.com/chemzqm/stack-source-map would be helpful.

**Comment by icodeforlove** [comment]
@mweststrate 👍
