### ISSUE TITLE
Typo? `unanymous`

### ISSUE THREAD

**Issue by david-davidson** [mobxjs/mobx-react#207]
Hi there,

The README contains this sentence:
> Observer is a React component, which applies observer to an unanymous region in your component.

`unanymous` _looks_ like a typo; I can't find any definition online. Is that the case? If so, happy to put in a PR. :)

Thanks!

**Comment by mweststrate** [comment]
It's a typo indeed :) Feel free to create a PR :)

**Comment by david-davidson** [comment]
@mweststrate Will do! It's meant to be `anonymous`?

**Comment by mweststrate** [comment]
yep :)
