### ISSUE TITLE
Autorun/reaction triggered with any state changes, not just observed properties

### ISSUE THREAD

**Issue by all-iver** [mobxjs/mobx-react#209]
It seems that when I have an autorun or reaction set up to observe some property in my component's state, the handler gets run whenever any state property changes rather than just the one I care about.  For example:

```
  componentWillMount() {
    this.disposer = reaction(
      () => { return { prop1: this.state.prop1 } },
      () => {
        var handler = result => this.setState({ prop2: result });
        someAsyncFunction(this.state.prop1).then(handler);
      }
    );
  }
```

In the above code, doing a this.setState({ prop1: 'something' }) causes the reaction to trigger.  The callback invokes an async network call, which itself calls back to the handler.  The handler sets an unrelated state variable, prop2.  That operation causes the whole thing to re-run for some reason.  If the handler doesn't change prop2, then the reaction doesn't get re-run.  Is this normal behavior?  How can I run a callback only when prop1 changes?

I have also tried setting prop2 in unrelated code and verified that it also causes the reaction to run.

**Comment by diondirza** [comment]
have you tried change your code into this one 

```
this.disposer = reaction(
      () => this.state.prop1,
      () => {
        var handler = result => this.setState({ prop2: result });
        someAsyncFunction(this.state.prop1).then(handler);
      }
    );
```

If the problem still occured I think the problem is react's setState function, it's better to use mobx observable object instead of react's state.

**Comment by all-iver** [comment]
Since my original comment I switched to using mobx observables instead of react state, so I'm not sure if your code would have fixed the problem or not, sorry.  Using observables does seem like a better pattern.

**Comment by mayorovp** [comment]
This happens because `{ prop1: this.state.prop1 }` is always a new object, which is not equals to old one.

You should use compareStructural option if you want override this behavior:

    componentWillMount() {
        this.disposer = reaction(
          () => { return { prop1: this.state.prop1 } },
          () => {
            var handler = result => this.setState({ prop2: result });
            someAsyncFunction(this.state.prop1).then(handler);
          }, 
          { compareStructural: true }
        );
      }
