### ISSUE TITLE
render() is not in sync with autorun

### ISSUE THREAD

**Issue by iotch** [mobxjs/mobx-react#212]
Hello. The following example is very simplified case of responding to api call. When the fetch is async - component renders on both action results, which is expected, but when the actions are going synchronously, 
only the last action result is rendered. In contrast, autorun calls its callback correctly, on every state update. 

https://jsfiddle.net/jvL9w0zj/3/

Is this expected behavior? Thanks!

**Comment by mweststrate** [comment]
This is indeed the expected behavior, as react components are rendered async and both changes are rendered by the same 'tick'. Note that wrapping the update code in an `action`, which is strongly recommended, makes the `autorun` only run once as well, only reacting to the latest value.

**Comment by iotch** [comment]
Please, see the updated example with `action()` - it behaves the same https://jsfiddle.net/jvL9w0zj/5/
Correct me, please, if I'm doing it wrong.

**Comment by mweststrate** [comment]
`fetchCached`  should be an action itself, otherwise it are still two consecutive actions

**Comment by iotch** [comment]
well, that's the point - `<ObserverChild />` should render both on fetch start and fetch end. I don't need to create a transaction for `isFetching` property, I need to render depending on it.
When using same approach with, for example, redux and it's `connect()`, the connected component renders on both `true` and `false` values.

**Comment by mweststrate** [comment]
why should it render? you won't be able to ever observe the difference as user? It is not that the rendering is not scheduled by mobx if you don't use actions, it is react itself which optimizes the rendering away because they are caused in the same tick

**Comment by iotch** [comment]
> why should it render? you won't be able to ever observe the difference as user?

This is just a demonstration, the component should render on any prop change, no matter what is causing this change or will user notice it or not. Unfortunately my english is weak for expressing my point of view, I'll try to provide another example.
