### ISSUE TITLE
Observer not reacting to changes in observable ref

### ISSUE THREAD

**Issue by jamsea** [mobxjs/mobx-react#214]
When upgrading for 2.x to 3.x, observers no longer react to React component refs that are observers. I created a demo here:
https://github.com/mobxjs/mobx-examples/pull/9

I couldn't figure out how to get it working in JS fiddle, but it works on my local version of chrome.

The expected behaviour is the phrase "This should console log" should be present in the chrome console when a user clicks the checkbox.

**Comment by mattruby** [comment]
See my response under mobx-examples: https://github.com/mobxjs/mobx-examples/pull/9 
Feel free to follow up on the gitter channel if you'd like more help.

**Comment by mweststrate** [comment]
Also note that `this.foo` was nowhere declared to be an observable. I expect at least something like `extendObservable(this, { foo: observable.ref(null) })` in `componentWillMount`. 

Besides that it is indeed strictly discouraged / bad practice to expose component state to the outside world. If you want to access some state in a parent; either pass callbacks to the child, or pass a data structure to the child which the child could update.

**Comment by mweststrate** [comment]
Closing question for inactivity. Feel free to revive

**Comment by anusree-mmlab** [comment]
I have an array of observable which has form elements , its value, validation result etc are stored. An observer has this values. Whenever the form element is changed, the observer prints the validation results. It works fine with @observable.

But i want to use @observable.shallow with them. Now the observer is not reacting with the changes.

What is the @observable.shallow for?
