### ISSUE TITLE
[proposition] improve observer component naming with React Perf

### ISSUE THREAD

**Issue by iotch** [mobxjs/mobx-react#215]
Hello. Will be great to have the more descriptive observer component name to indicate that original component wrapped with observer HOC in React Perf:
![perf](https://cloud.githubusercontent.com/assets/2292500/23653285/0bd84bca-033d-11e7-9354-805a45d257bb.gif)

@mweststrate, what do you think? Thanks!

**Comment by mweststrate** [comment]
Note that `@observer` is not a HoC but that it mixes in behavior. Personally I don't see much added value, on the other hand it might be useful for debugging purposes, to earlier signal that people have forgotten `@observer`. 

What do others think?

**Comment by iotch** [comment]
> Note that @observer is not a HoC but that it mixes in behavior

Of course, I'm in a rush now with some projects, have to keep lots of things in my head, please, do not take in account, please...

**Comment by andykog** [comment]
Don't think there is much sense in changing original component's name, this can be a little confusing.

**Comment by mweststrate** [comment]
Nonetheless, I can see how it might help people with debugging/ have a quick view on which components are observer etc?

Would this be a breaking change? Don't think so?

**Comment by JabX** [comment]
As it was pointed out earlier, `@observer` is not a HoC so it doesn't carry its own name, and changing the original name would be confusing I believe.

I'm not even sure how much value it would bring since the overhead is negligible and there are a lot of visible signs that an `@observer` decorator is missing.

**Comment by mweststrate** [comment]
Closed as there is no real consensus on this proposal
