### ISSUE TITLE
[NFR] redux connect-like function

### ISSUE THREAD

**Issue by iotch** [mobxjs/mobx-react#217]
Hello. Currently referencing observable props in a decorated `render()` to  trigger an update and lacking the ability to have a `componentWillReceiveProps()` sometimes may be not enough for some use cases and feeling a bit like a "non-react" way.
What do you think about providing a redux' connect-like function that will take "the data function" from `reaction()` API, will return a wrapped component with observed and injected props, and will react and update its state on props changes? Is there a reason not to have one? Thanks!

**Comment by mweststrate** [comment]
Can you elaborate with an example?

**Comment by iotch** [comment]
Quck and dirty: https://jsfiddle.net/b9rtm11t/

**Comment by iotch** [comment]
What was the reason to not to go that path? Is there any cons?

**Comment by mweststrate** [comment]
`@observer` does all that for you already; simply writing 

```
const Test = observer(() => <div>{state.count}</div>)
```

does all the connecting already for you. 

And if you want to pass using context instead of closure, just use `Provider` / `inject` like in redux

**Comment by iotch** [comment]
For example, I have a component `<Test count={}, {...restProps} />`. That relies on props but has internal state to, say, control a modal. Also, on some condition it needs to prevent rendering. It is totally standalone, I can reuse it even without mobx.
Now, with the current `observer()` implementation I have to wrap it with SFC, like: 
````js
Test = observer((props) => <Test count={state.count},  {...props} />);
````
So I have to instantiate it manually and take care of handling all the props. Instead of:
````js
Test = observer(() => { return {count: state.count} })(Test);
````
Am I wrong?

**Comment by iotch** [comment]
Ok, since its turns to monologue, I shall continue :) What I'm trying to say is that triggering a component update from within a render() method is a not the optimal way. Going this way mobx-react is limiting the possibilities to control the rendering flow. For example, you can not navigate away depending on observed properties, you'll get a 'forceUpdate' warning. No matter of syntax - using as component decorator or wrapping a component with another component by hand (which adds unneded verbosity) you are still staying within a render() with all its limitations. Also, using things like React.createClass() and mixins feels a bit atavistic. 
I read somewhere that stores is like Controllers from MVC and the React components are Views. But for me stores, in their basic implementation, are more like Models with added interactivity. What I'm proposing is to add a thin Controller layer between the store (Model) and React component (View) that will handle collecting data from multiple stores, will dereference values to trigger updates and will return an updated props object to the controlled component. This way we can do what we want in controller as far we are not returning the props object (returing false, for example), we're not triggering the update. And our controlled React component will rely only on pure values.

Example:

````js
const Controller = () => {
    if(userStore.loggedIn) {
        routingService.navigate('home');
        return false;
    }

    return {
        isFetching: userStore.isFetching,
        errors: userStore.fetchErrors,
    }
}

View = connect(Controller)(View);
````

Will be great to hear about a disadvantages that I've missed, or maybe a brief motivation why mixins were chosen instead of composition.

**Comment by jamiewinder** [comment]
I'm not sure if I'm understanding, but it feels somewhat incompatible with some of the MobX concepts... This for example:
```typescript
class User {
    @observable name;
}

const Controller = () => {
    return {
        user: userStore.currentUser
    };
}

const View = ({ user }) => {
    return <div>Hello, {user.name}!</div>;
};

View = connect(Controller)(View);
```
If the user changed, and if controllers are made reactive, then the view could update with new props, however, without `render` being made a reactive function, it won't be able to track if only the user name has changed (since that isn't accessed in the controller, it is only accessed in the view).

I might be wrong.

**Comment by iotch** [comment]
Yes, in a such 'basic' implementation it wouldn't update. You have to create a sub-component and connect it too or dereference name in a controller, just like you need to do it now, if you need an observable prop value anywhere outside render(), for example if you need it in componentDidUpdate().

**Comment by mweststrate** [comment]
>  Also, on some condition it needs to prevent rendering. 

I think you are missing the concept of MobX here: MobX implements sCU for you and makes sure it renders under exactly the right conditions. Deliberately trying to skip rendering is deliberately freezing your UI. I don't think there is any good use case for that. If you don't want to update your UI then don't change your data :) If you want to change data, but not update your UI, your probably not rendering the proper data in the first place!

**Comment by mweststrate** [comment]
> What I'm proposing is to add a thin Controller layer between the store (Model) and React component (View) that will handle collecting data from multiple stores, will dereference values to trigger updates and will return an updated props object to the controlled component.

This is roughly what passing a function to `@inject(fn)`  does. (Or I am misunderstanding the question)


> snippet

```
const Controller = () => {
    if(userStore.loggedIn) {
        routingService.navigate('home');
        return false;
    }
``` 

This imho goes against the philosophy of both React and MobX, as you are trying to chain your logic with side effects, while you could perfectly computed which page you should be on from the two facts `userStore.loggedIn` and the current URL, as demonstrated here: https://medium.com/@mweststrate/how-to-decouple-state-and-ui-a-k-a-you-dont-need-componentwillmount-cc90b787aa37

**Comment by iotch** [comment]
Unfortunately I can't show you the app we're trying to move from redux to mobx, its about 20k loc itself, but I'll try to describe its structure.
We had Services (routing, api calls, storage, etc.), State (data), UI (which is React components). There was a Listeners layer, that used to listen to the redux actions and do some logic - connect to push when user logs in, broadcast some actions between tabs, redirect on successful navigation, etc. Now we're trying to go from functional approach that was pretty painful to extend and maintain, to a more "classical" MVC with OP style that we used to and successfully using on our non-JS backend.

Regarding routing. In a simplified form: we have a routingService, which handles browser history, routes activation/deactivation, url parameters, etc. We have a routingStore, which is updated by the routingService with route name, path, params, etc. when route changed. We have the routing component somewhere at the top of our UI tree, which listens to routingStore state changes and renders the corresponding page components mapped to route name. So far so good.

UserStore from example above looks something like this:
```js
class PseudoUserStore {

    @observable token = null;

    constructor(apiService) {
        this.apiService = apiService;
    }

    @computed get loggedIn() {
        return !!this.token;
    }

    @action login(data) {
        apiService.getToken(data).then(() => {
            this.setToken(token);
        });
    }

    @action setToken(token) {
        this.token = token;
    }
}
```

Now regarding the login page example. Login page component is basically just a form:
````js
class Login extends Component {
    render() {
        return <Form onSubmit={this.props.onSubmit} errors={this.props.errors} {/*...etc*/}>{/*...*/}</Form>;
    }
}
````
Now we need to take some action on submit, and now comes the earlier Controller example:

````js
const LoginController = () => {

    const onSubmit = (data) => {
        // we don't want to call then() here to redirect, 
        // but want to react to loggedIn change above, as it feels more idiomatic way
        userStore.login(data); 
    }

    if(userStore.loggedIn) {
       // this will validate route name, set url in browser, update active route in routingStore, 
       // which will trigger the routing component to render the mapped page
        routingService.navigate('home'); 
        return false;
    }

    return {
        onSubmit,
        errors: userStore.fetchErrors,
    }
}

ConnectedLogin = connect(LoginController)(Login);
````
Now we don't need to have a separate autorun somewhere that will call `routingService.navigate()` in reaction to `userStore.loggedIn` change. So we don't have to have a "listeners" or "reactions" layer and our Login component stays "pure".  
Does this makes more sense now?

**Comment by iotch** [comment]
BTW `React.createClass()` will be marked as deprecated in v15.5 and removed from v16. https://github.com/facebook/react/issues/8854 
So maybe it's time to rework the observer?

**Comment by urugator** [comment]
@iotch some thoughts:

> So I have to instantiate it manually and take care of handling all the props. Instead of:

```javascript
Test = observer(() => { return {count: state.count} })(Test);
```

At this point the `Test` component is statically bound to a specific `state` object.
So you don't have to manually instantiate and pass all the props, but on the other hand you also can't easily pass different `state` object in case the `state` object should be provided dynamically.
To do that you either have to create new `Test2` component "connected" to new `state` object. That means rendering different component -> loosing the state of original component. 
Or you have to do the `state` object switching inside controller, but thats actually nothing more than moving the "manual instantiation and prop handling" into controller. The benefit here is that component doesn't have to directly depend on `state` (but "relies on pure values"), but at the cost of providing controller as a mediator, so it's not cost free (as any abstraction).
       
**Component composition VS component patching**
I think that component patching is used exactly because it doesn't require introduction of any additional abstraction. From implementation perspective it's the most "intrusive" solution, but from usage perspective, it's the most simple one - you don't have to provide any additional information or be aware of any other concepts like "props binder" (controller).

> Going this way mobx-react is limiting the possibilities to control the rendering flow. For example, you can not navigate away depending on observed properties, you'll get a 'forceUpdate' warning.

I am not aware of these problems, can someone enlighten me? When should 'forceUpdate' warning occure?

**Comment by mweststrate** [comment]
@iotch I see why you like the pattern, but I don't think it should be part of mobx-react, but rather implemented in userland / as third party lib. The core mobx libraries should be as lean as possible and not introduce too many new abstractions / architectural decisions. Therefore closing for now.
