### ISSUE TITLE
[bug?] Dereference in WillReact is not observerd

### ISSUE THREAD

**Issue by ggarek** [mobxjs/mobx-react#219]
Found a strange behaviour, which seems to be a bug.

**Short**: If observable is dereferenced in `componentWillReact`, the change is not observed.

First [fiddle/1/](https://jsfiddle.net/garek/ssd68hLs/1/), has two components, one reads observable in `render`, other - in `componentWillReact`. The latter does not observe change.

Second [fiddle/2/](https://jsfiddle.net/garek/ssd68hLs/2/) contains the same example, but the latter component uses another observable variable in render. To make `componentWillReact` trigger at least once. Result is the same.

----

My guess is if it is by design (which, imo, is arguable), it should be documented. Otherwise we need to think on a fix.

Thanks! The project is great. 👍 

*p.s.: The example may seem contrived, and there are several workarounds. But it demonstrate the possible case nevertheless.*

**Comment by mweststrate** [comment]
As per docs, https://mobx.js.org/refguide/observer-component.html, that is indeed the intended behavior. _only_ `render()` (and everything called from there) is tracked
