### ISSUE TITLE
exclude values from observing

### ISSUE THREAD

**Issue by dropfen** [mobxjs/mobx-react#220]
Is there a way to exclude some values from being observing?

For example a computed array of ids which should set some initialValues

```
const allIds = ['1', '2'];
@observable settings = "";
@computed get ids() {
  const ids = allIds.filter(id => id !== '1' || this.settings !== 'exclude 1' )
  // How to exlude it from running into a cycle?
  this.setInitialValues(ids);

  return ids;
}

@action setInitialValues(ids) {
  ids.forEach(id => {
    this.values[id] = initialValues[id];
    this.isFine[id] = true;
  });
}

// Other functions should only react on the change of ids, not the values, which are changed by setInitialValues
@computed get allFine() {
  return this.ids.every(id => this.isFine[id] )
}
```

If there would be way of ignoring all the underlying values inside ids, then all the other computations would just run because ids was changed

```
@computed get ids() {
  const ids = allIds.filter(id => id !== '1' || this.settings !== 'exclude 1' )
  ignoreObserables(() => this.setInitialValues(ids));

  return ids;
}

```

Does it make sense?

**Comment by urugator** [comment]
Side effects inside `computed` are forbidden. If observable `this.values` is already observed by something and you will try to change it inside computed, mobx will throw. (it's like calling `setState` inside `render`)
You CAN prevent from subscribing with [untracked](https://mobx.js.org/refguide/untracked.html)
You CANNOT prevent from notifying observers when modifying observables.

**Comment by dropfen** [comment]
Okey, thanks.
