### ISSUE TITLE
Exceptions in render don't get passed into `extras.onReactionError`

### ISSUE THREAD

**Issue by le0nik** [mobxjs/mobx-react#221]
This issue came up after this change https://github.com/mobxjs/mobx-react/commit/456bf475c33b3fdd003dfdb7d8871d1e58e4edcf

Or is there another way to attach logging behavior for these exceptions?

**Comment by mweststrate** [comment]
Correct, the exceptions don't escape anymore indeed. Where do you use this for? Logging exceptions in prod? Would a global onError hook for mobx-react specifically help?

**Comment by le0nik** [comment]
I send exceptions like this to `sentry` in production. Yes, global `onError` in `mobx-react` would definitely help! It's a bit inconsistent in my opinion, though. Docs for `extras.onReactionError` state that all errors inside reactions get there, but it's not the case for errors in `mobx-react` render. Instead they bubble up to the global scope.

**Comment by mweststrate** [comment]
global `onError` in mobx-react package is now available in 4.2.1
