### ISSUE TITLE
Property wrappedComponent does not exist when use @inject in Typescript

### ISSUE THREAD

**Issue by suzuki11109** [mobxjs/mobx-react#223]
I have code declare react component like this.
```
@inject("store")
@observer
export class PhoneList extends React.Component<{store?: any}, any> {
```

And I imported it in another file which is test file
```
import {PhoneList} from "../src/PhoneList";

describe("PhoneList", () => {
  it("renders table head with 3 columns", () => {
    const store = {phones: []};
    const wrapper = shallow(<PhoneList.wrappedComponent store={store} />);
    expect(wrapper.find("table")).toHaveLength(1);
  });
});
```

And it failed when type checking.
```
Property 'wrappedComponent' does not exist on type 'typeof PhoneList'
```

But the test isn't failed. I think wrappedComponent works but it's just not valid when type checking.

Help me please.
Thanks :)

**Comment by mweststrate** [comment]
Which version of mobx-react are you using?

**Comment by suzuki11109** [comment]
I use mobx-react version 4.1.3

**Comment by suzuki11109** [comment]
I changed how to declare the component to stateless like this.
```
export const App = inject("store")(observer((props: AppProps) => {
  return <div>
    <h1>Hello</h1>
    { props.store.phones.map((e: string) => <div>{e}</div>) }
  </div>;
}));
```

The error is different 
```
Property 'wrappedComponent' does not exist on type 'ClassicComponentClass<AppProps>'
```

**Comment by mweststrate** [comment]
Just released 4.1.5, should address the later case. The decorator version cannot be fixed withing typescript boundaries, as decorators cannot change the type of the thing they decorate. Using `inject` as function are any casting should work for these cases.

**Comment by g-wozniak** [comment]
I am using 5.15.4 and get the same message: `Property 'wrappedComponent' does not exist on type 'typeof RenderTranslation'.`
where my code is:

`const comp = shallow(<RenderTranslation.wrappedComponent locale={locale} />)`

and component obviously has:
@observable
@inject('locale')

**Comment by FredyC** [comment]
Please, refrain from commenting on old and closed issues as only a few people will see that. Open new issue with all necessary details. Thank you.

**Comment by mweststrate** [comment]
also, make sure to use observer, not observable :)
