### ISSUE TITLE
How to make the store injected by Provider read-only?

### ISSUE THREAD

**Issue by yeze322** [mobxjs/mobx-react#224]
Assuming we are developing a website with login function.
We have a store called `userStore` which is used to storage `userId`, `userName`, etc.
The `userStore` is passed through `<Provider>` like this:
```
<Provider store={userStore}>
    <Router>
        <TabA />
        <TabB />
    </Router>
</Provider>
```
What I want is, only share `userStore` among tabs but forbid modifying its property in some children such as `TabA`
```
@inject('store') @observer
class TabA extends Component {
    render () {
        // want to forbid operations like this
       <button onClick={() => {this.store.userName = 'newUserName'}}>Change global store</button>
    }
}
```
I'm wondering if MobX provides any native solutions to implement a read-only store, such as
`@injectReadonly('store')
`or should I use other libraries like `immutable.js` to do this?

Thanks :)

**Comment by leader22** [comment]
How about `useStrict()`?
Use `action()`(or `@action`) with `useStrict(true)`.

> https://github.com/mobxjs/mobx/blob/gh-pages/docs/refguide/api.md#usestrict
> https://mobx.js.org/refguide/action.html

**Comment by mweststrate** [comment]
Besides strict mode Mobx doesn't offer a build in abstraction to make something read only. `intercept` can be used for that, but does not make something deeply read-only. 

If you are using typescript, it is easy though; just expose your store as interface with `readonly` properties and the compiler will do it for you.
