### ISSUE TITLE
How to code splitting mobx?

### ISSUE THREAD

**Issue by bodyno** [mobxjs/mobx-react#225]
As I see. There is no way to denamic append store to Provider now. I don't want all store file go into as I first in. So I asking How to do with it?

**Comment by mweststrate** [comment]
Sorry, but the question is completely unclear to me. I don't think mobx in itself is not of any influence on code splitting. It's probably all depends on your state design

**Comment by bodyno** [comment]
Like redux. It has asyncReducers helps code spliting very simple.
So I was wondering is mobx has the same api? but don't have. That's why I ask.

**Comment by lavrton** [comment]
@bodyno what is `asyncReducers`?

**Comment by bodyno** [comment]
It can async reducer in other file when application is runing. Not like now first load all in.

**Comment by andykog** [comment]
@bodyno, inability to add/change stores, passed via context is the limitation by react itself, not by mobx-react. But there is nothing prevents you to pass some kind of container store, in which you can append other stores asynchronously, something like:
```jsx
class RootStore = {
  @observable usersStore = undefined;
}
var rootStore = new RootStore;
//...
<Provider rootStore={rootStore}></Provider>

// ... later:
rootStore.usersStore = new UserStore()
```

**Comment by bodyno** [comment]
Thanks. I see.

**Comment by svssrinivas** [comment]
> @bodyno, inability to add/change stores, passed via context is the limitation by react itself, not by mobx-react. But there is nothing prevents you to pass some kind of container store, in which you can append other stores asynchronously, something like:
> 
> ```js-jsx
> class RootStore = {
>   @observable usersStore = undefined;
> }
> var rootStore = new RootStore;
> //...
> <Provider rootStore={rootStore}></Provider>
> 
> // ... later:
> rootStore.usersStore = new UserStore()
> ```

Is there some way to make the `UserStore` file load lazily as well? I am using typescript and i need to annotate types.

**Comment by FredyC** [comment]
Please, refrain from commenting on old and closed issues as only a few people will see that. Open new issue with all necessary details.
