### ISSUE TITLE
Optional @injected store

### ISSUE THREAD

**Issue by LeonardoGentile** [mobxjs/mobx-react#232]
Hello,
if using @inject decorator applied to a react component like `@inject('myStore')` then `myStore` should exist and should be passed using `Provider`

```
<Provider {myStore}>
  <App/>
</Provider>
```

But there are certain cases (for example a mobx-react plugin in my case) when we don't know or we are not sure if `myStore` was really passed from the Provider.

In this case I would just check if it exists in the component props and if not just do the appropriate things.

The problem is that if the store is not passed to the the Provider then mobx-react will throw an error.

Would it be possible to make it into a warning and let the developer handle the case when the store doesn't exist?

**Comment by mweststrate** [comment]
I think you can use `@inject((props, stores, context) => props)` for these
specific cases

Op di 4 apr. 2017 om 17:48 schreef LeonardoGentile <notifications@github.com
