### ISSUE TITLE
Question on option of preventing observer from firing in some cases.

### ISSUE THREAD

**Issue by jpiepkow** [mobxjs/mobx-react#236]
I have an advanced case where I would like to be able to override internal variables in a store of a singleton so that multiple components with their own unique store could still share some variables across the states.

Here is an example:
var sharedState = observable({pause});
var singleton = function(inject){return observable({pause:inject.pause||true})}

<componentOne store={new singleton(sharedState)}/>
<componentTwo store={new singleton(sharedState)}}/>
<componentThree store={new singleton()}/>

So that component one and two would share paused between them but component three has its own pause state.

This would work fine in a normal non mobx situation but it seems when pause is changed in either componentOne or componentTwo it re-initializes the singleton and everything in it is reset back as if it was recreated because the passed in state changed.

Is there any was to go about this? Maybe a way to prevent update on change at the constructor level?

**Comment by mweststrate** [comment]
Please provide testable use case which makes it simple to reason about or propose another solution. For example fork https://jsfiddle.net/mweststrate/wv3yopo0/

**Comment by jpiepkow** [comment]
https://jsfiddle.net/a683z68p/2/

The idea being on TodoList I would like to stub out todos with another classes todos(inject). The issue I ran into is that added todos(because it now added's them using the injected todo's array..triggered an update on the new TodoList() that reinitializes it. I am sure this is designed as intended and not a bug as its somewhat expected behavior but I am wondering if there is any way to reason about what I want to do here... as stated above have a singleton state with an injected state that stubs out methods so that part of the state is shared across components even though the rest of the state is only available per component.

**Comment by mweststrate** [comment]
Sorry for the delay. However, I have to admit I don't get the problem yet. Could you indicate whether the problem has been solved in the mean time, or try to explain another time what you want to achieve ;-)? If you produce fresh stores it seems correct to me that anything needs to react to that?

**Comment by jpiepkow** [comment]
I ended up tossing the idea out because I do believe you are correct in the regard that everything should react to changes in a store. Just a little weird that the passed in store reset each time a change happened in the store it was inject into. You can close this issue though as it is no longer relevant to me. Thanks to your time!
