### ISSUE TITLE
React.createClass is deprecated

### ISSUE THREAD

**Issue by marbemac** [mobxjs/mobx-react#237]
https://facebook.github.io/react/blog/2017/04/07/react-v15.5.0.html

It's been moved into a separate package. Perhaps it might be worth considering moving to an es6 class or functional component?

**Comment by marbemac** [comment]
Same thing for usage of PropTypes.

**Comment by mweststrate** [comment]
Fixed in `4.1.6`

**Comment by andykog** [comment]
Correction: fixed in 4.1.7
