### ISSUE TITLE
Error wrongly assumes the component is an observer

### ISSUE THREAD

**Issue by LeonardoGentile** [mobxjs/mobx-react#245]
I was unit testing a component being decorate only with `@inject`, not with `@observer`.
For the sake of test I did not passed the store to my component either by `Provider` or passing directly the `prop` to the component.

Inside my component constructor I do check that the required store is indeed passed correctly, otherwise I throw an error. That was the whole point of my test.

The problem is that I can't reach my component constructor because mobx-react throws another error before my component could, that is:

```
Error: MobX observer: Store 'myStore' is not available! Make sure it is provided by some Provider
```

Now given that my component is not an observer I had a hard time to figure out from where that error was really coming from. 

In the end I've reached the conclusion that it is just a matter of message content, that is from [this line ](https://github.com/mobxjs/mobx-react/blob/master/src/inject.js#L78) it is assumed that the component decorated with `@inject` are also decorated with `@observer`, but that's not necessarily true, isn't it?

So maybe the error message could be changed not to be misleading?

**Comment by andykog** [comment]
@LeonardoGentile, yeah, you definitely right, thanks for noticing! Fixed in https://github.com/mobxjs/mobx-react/commit/8dfa5c84e29f984c659039f6bfafb52e6ec5f979
