### ISSUE TITLE
Support React 16 alpha in order to support latest React Native

### ISSUE THREAD

**Issue by cia48621793** [mobxjs/mobx-react#248]
Given a minimal example:
`components/Timer.js`
```
import { observer, inject } from 'mobx-react/native'
import React from 'react'
import { Text } from 'react-native'

@inject(['timer'])
@observer
export class Timer extends React.Component {
  constructor(props) {
    super(props)
    this.props.timer.startTimer()
  }

  componentWillMount() {
    console.log("I will mount!");
  }

  componentWillReact() {
    console.log("I will re-render!");
  }

  render() {
    return (<Text>{this.props.timer.time}</Text>)
  }
}

```
`model/ModelTimer.js`
```
import {
  observable,
  action,
} from 'mobx'

export class ModelTimer {
  @observable time = "";

  @action startTimer() {
    setInterval(() => {
      this.refreshTime()
    }, 1000);
  }
  @action refreshTime() {
    this.time = Date.now()
  }
}
```
`index.android.js`
```
import { observer, Provider } from 'mobx-react/native'
import React from 'react'
import { Router, Scene } from 'react-native-mobx';

import { Timer } from './components/Timer'
import { ModelTimer } from './model/ModelTimer'

import { AppRegistry, View } from 'react-native'

const stores = {
  timer: new ModelTimer(),
}

class Main extends React.Component {
    render() {
      return (<Provider {...stores}>
        <View><Timer /></View>
      </Provider>)
    }
}

AppRegistry.registerComponent('test', () => Main);
```
Nothing was rendered unless hot-reloaded. componentWillReact in Timer wasn't called..Seems strange to me...It should update every time ModelTimer::time was modified...
The latest version of React Native was used at the time of creating the issue: 0.43.2.

**Comment by cia48621793** [comment]
The same example works in DOM-equivalent version of React + MobX. I find it really hard explain why it wouldn't run in React Native at all.

**Comment by cia48621793** [comment]
Well, I did managed to fix it myself.
```
import { observer, inject } from 'mobx-react/native'
import React from 'react'
import { Text } from 'react-native'

@inject(['timer'])
@observer
export class Timer extends React.Component {
  constructor(props) {
    super(props)
    this.props.timer.startTimer()
    setInterval(() => this.setState({}), 1);
  }

  componentWillMount() {
    console.log("I will mount!");
  }

  componentWillReact() {
    console.log("I will re-render!");
  }

  render() {
    return (<Text>{this.props.timer.time}</Text>)
  }
}

```
Kinda dangerous but it was an enough workaround. MobX + React Native is fundamentally broken with React 16.0 Alpha.

**Comment by cia48621793** [comment]
Yep, it's a confirm.

Falling back to React Native 0.42.3, my provided example was perfectly running and rendering without problems. 

Please consider adding a PSA that the React 16 breaks the compatibility with mobx-react.

The actual reason of this incompatibility is still unknown, probably because of the reconciliator introduced in this 'edgy' React 16, which is basically a task scheduler plus React, and so the tasks of mobx-react requested was assigned to the lowest priority and hence ignored and reduced by the reconciliator?

I don't have much knowledge about React and this React Fiber, I'm no differ than ordinary user, but please, fix this as quick as possible.

**Comment by kesha-antonov** [comment]
+1 for React 16 support!

**Comment by mweststrate** [comment]
Any volunteers on investigating this issue? Not sure what the issue is, as there will be some test library upgrades be required first to React 15.5 / 16 (e.g. ReactTestRenderer etc). I'm quite full packed in the next two weeks so if someone could create a more in-depth analysis first that would be awesome :)

I'm pretty sure this is something fixable.

**Comment by mweststrate** [comment]
@andykog / @A-gambit / @Strate / @benjamingr  interested?

**Comment by mweststrate** [comment]
Ok, started fiddling, seems that Enzyme does not support React 16 yet: https://github.com/airbnb/enzyme/issues/893

Currently throws errors like:

```
test_bundle.js:14685 Uncaught TypeError: Cannot read property 'getPublicInstance' of undefined
    at WrapperComponent.getWrappedComponent (test_bundle.js:14685)
    at new ReactWrapper (test_bundle.js:13163)
    at mount (test_bundle.js:17140)
```

**Comment by kaifaust** [comment]
Any update on this? Is there a schedule to fix this?

**Comment by mweststrate** [comment]
See above comments, basically this is blocked on the fact that enzyme does not support react 16 yet, which the test suite highly depends on. It should be possible to factor enzyme out the test suite, but that will be quitte an effort. If somebody is willing to modernize the test setup to e.g. just Jest; a PR is more then welcome!

**Comment by cia48621793** [comment]
For some reason my example worked miraculously.
```
"react": "16.0.0-alpha.6",
"react-native": "0.44.0"
```
Maybe it's not about React Library itself but React Native instead. Case closed.
