### ISSUE TITLE
Nested components observing store

### ISSUE THREAD

**Issue by newuser** [mobxjs/mobx-react#25]
Is it ok to use nested components(routes) as observers, when using react-router or something else ? I decorated page with observer and got updates from store,  it worked fine for me.  Perhaps, there should be some sample or documentation notice about usage with react-router.

**Comment by mweststrate** [comment]
Yup that should work fine afaik. (Didn't use react-router much personally, but I didn't hear any complaints from my collegues when combing it with mobservable).
