### ISSUE TITLE
How to use @inject without decorators

### ISSUE THREAD

**Issue by gate3** [mobxjs/mobx-react#250]
Hi, this is a wonderful project you have here, thank you very much. I wish to use @inject without decorator. I am using create-react-app and it doesn't allow generators. Please any help will be greatly appreciated.

**Comment by urugator** [comment]
It's in the [README](https://github.com/mobxjs/mobx-react#inject-as-function)

**Comment by gate3** [comment]
I checked it out. Could not find inject.

**Comment by jamiewinder** [comment]
https://github.com/mobxjs/mobx-react/blob/master/README.md#inject-as-function

**Comment by gate3** [comment]
Thank you very much. Been searching for this.

**Comment by reywright** [comment]
how would you inject and observe on a class? That isn't in the readme.

**Comment by urugator** [comment]
The `observer` component observes observable things, which are accessed in `render`. [Detailed explanation](https://mobx.js.org/best/react.html)

**Comment by reywright** [comment]
This was what I was looking for. I'll leave this here for anyone who is searching
```
const App = inject("store")(
  observer(({ store }) => (
    <div>{store.foo}</div>
  ))
);
```

**Comment by mweststrate** [comment]
@Lunada no, it is the _class_ that needs decorating, not the instance, so:

```
class _App extends Component {
  /* class code here */
}
const App = inject('store')(observer(_App))
```

Typically this is done:

```
class App extends Component {
  /* class code here */
}
export default inject('store')(observer(App))
```
