### ISSUE TITLE
Type error when used with SFC type from react

### ISSUE THREAD

**Issue by mattoni** [mobxjs/mobx-react#253]
Given the following:

```
...
import { SFC } from 'react';

const SFComponent: SFC<ISFComponent> = observer((props) => { ...})
```
There is a type error: 
```
[ts]
Type 'ClassicComponentClass<{}>' is not assignable to type 'StatelessComponent<ISFComponent>'.
  Type 'ClassicComponentClass<{}>' provides no match for the signature '(props: ISFComponent & { children?: ReactNode; }, context?: any): ReactElement<any>'
```

Looks like the types need adjusted slightly. Reason for this approach is so that children can be typed automatically.

**Comment by urugator** [comment]
Not sure if it relates to the problem, but `observer` have to (in order to work) create a standard component even if you pass plain function, so the returned component is no longer SFC...

**Comment by makeitrein** [comment]
Check out https://github.com/mobxjs/mobx-react/blob/master/test/ts/compile-ts.tsx for all the right ways to use Typescript + observers. 

```
const T3 = observer((props: { hamburger: number }) => {
	return <T2 cake={props.hamburger} />;
});
```

That should fit your use case, no?

**Comment by mattoni** [comment]
Yep, that's how I've been doing it. Weird that it doesn't fit the <SFC> definition because I don't want to have to type the child props.

**Comment by mweststrate** [comment]
@mattoni feel free to create a PR if you feel the typings can be improved

**Comment by mweststrate** [comment]
Closing, a lot of typing improvements have been made lately
