### ISSUE TITLE
How to react to a prop without render it

### ISSUE THREAD

**Issue by thiagoxvo** [mobxjs/mobx-react#257]
I have a situation where I have a component that does not render anything because is all based on a 3rd party map API, but I need to react to some store property changes:

```js
componentDidMount() {
   mapApi.doSomething(this.props.store.value)
}

componentWillReact() {
   mapApi.doSomething(this.props.store.value)
}

render () {
   //workaround to make componentWillReact trigger
   console.log(this.props.store.value) 
   return null
}
```

Is there an elegant way to implement this?

**Comment by mweststrate** [comment]
use mobx.autorun or reaction. Don't forget to dispose in unmount

Op do 18 mei 2017 17:02 schreef Thiago Xavier <notifications@github.com>:
