### ISSUE TITLE
How can explain the behavior between the three kinds of action?

### ISSUE THREAD

**Issue by tsaohucn** [mobxjs/mobx-react#259]
I have a component has componentWillReact() and I use it test how much times the component will re-render, when I use the first action in componentDidMount(), the result show only one re-render, the second action also show only one re-render, but the third action show five times re-render, how can explain the behavior, I know the reason maybe cause the async, but I don't know how's the async detail run in mobx action clearly, the reason I wanna know because I want to know what's the best plan for change state in a action? Is each one state-change in each one action? or I can set many state-change in only one action, if can set many state-change in only one action then how mobx re-render? Is it re-render once when all state changed or re-render when each state changed?

# re-render once
````  
@action test(){
    this.loading = 'A'
    this.loading = 'B'
    this.loading = 'C'
    this.c = 'V'
    this.x = 'V'
  }
````
# re-render once
````  
@action test(){
    this.loading = 'A'
    this.sleepSynchronize(2000)
    this.loading = 'B'
    this.sleepSynchronize(2000)
    this.loading = 'C'
    this.sleepSynchronize(2000)
    this.c = 'V'
    this.sleepSynchronize(2000)
    this.x = 'V'
  }

  sleepSynchronize(milliseconds) {
    const start = new Date().getTime();
    for (let i = 0; i < 1e7; i++) {
      if ((new Date().getTime() - start) > milliseconds){
        break;
        }
      }
  } 
````
# re-render five times
````
@action async test(){
    this.loading = 'A'
    await this.sleep(2000)
    this.loading = 'B'
    await this.sleep(2000)
    this.loading = 'C'
    await this.sleep(2000)
    this.c = 'V'
    await this.sleep(2000)
    this.x = 'V'
  }

  sleep(ms) {
    return new Promise(resolve => setTimeout(resolve, ms));
  } 
````
# My render
````
  componentWillReact() {
    console.warn("Re-render FateContainer!!");
  }

  componentDidMount(){
    this.props.fate.test()
  }
  
  render() {
    return(
      <View>
      <Text>{this.props.fate.loading}</Text>
      <Text>{this.props.fate.x}</Text>
      <Text>{this.props.fate.c}</Text>
      </View>
    );
  }
````

**Comment by mweststrate** [comment]
Mobx will run reactions after mutation. So basically after any modifcation.

However, if actions are used, all reactions are only scheduled at the end of the action, so action automatically batch the updates. 

That is the reason your first two examples only render once. 

It is also the reason why your third example renders 5 times, as after the `test()` function finishes, which is after the first assignment, the components will update. Remember; async / await is just some nice syntax around an asynchronous process. Your next awaits "jump into the middle" of that `test()` function again, so actually (a part of) your test action is run 5 times, that is why you see the the 5 updates. 

This is conceptually correct; not updating between the intermediate promises would cause your UI to be stale (with respect to the mutation that did happen already) in other words, to "hang".

**Comment by tsaohucn** [comment]
@mweststrate, very clear explanation,  thanks, and can I ask if I have a situation, I mean just suppose the situation I really need the async third example to re-render just once, is there any possibility or syntax can get it?

**Comment by tsaohucn** [comment]
I find I can use runInAction wrap multi state-change in a action, but in my third case the best solution is like below, but it still will re-render five times and has no meaning, right?

````
@action async test(){
    runInAction("loading",() => { this.loading = 'A'})
    await this.sleep(2000)
    runInAction("loading",() => { this.loading = 'B'})
    await this.sleep(2000)
    runInAction("loading",() => { this.loading = 'C'})
    await this.sleep(2000)
    runInAction("c",() => { this.c = 'V'})
    await this.sleep(2000)
    runInAction("x",() => { this.x = 'V'})
  }

  sleep(ms) {
    return new Promise(resolve => setTimeout(resolve, ms));
  }
````

**Comment by mweststrate** [comment]
@tsaohucn if you want only one render; just don't modify the data used by the rendering until the whole process is completed and it won't rerender. Save changes until the last await as temporarily data. Mobx does not rerender because you invoked an action, but because you modified that was used in render. Not modifying the `this.loading` but using a temp var makes much clearer how you intend your component  to behave than any magic flags :)

**Comment by tsaohucn** [comment]
@mweststrate , it's a good idea, thanks.
