### ISSUE TITLE
Version 4.2.0 published under wrong tag

### ISSUE THREAD

**Issue by lgeiger** [mobxjs/mobx-react#264]
Hey @mweststrate,

thanks for maintaining this awesome package. It looks like a bug slipped through the latest release.

On [`npm`](https://www.npmjs.com/package/mobx-react) version `4.2.0` is published as `4.2.0-rollup`:
<img width="364" alt="bildschirmfoto 2017-05-29 um 15 00 46" src="https://cloud.githubusercontent.com/assets/13285808/26550819/cb8f9ac6-447f-11e7-8418-4884d94ea114.png">

This causes `npm i mobx-react@^4.2.0` to fail.

Found by Greenkeeper in https://github.com/nteract/hydrogen/issues/821 see [Travis log](https://travis-ci.org/nteract/hydrogen/jobs/237146828#L143).

**Comment by andykog** [comment]
Unpublished `mobx-react@4.2.0-rollup`

**Comment by mweststrate** [comment]
Thanks @andykog! Something went wrong indeed, it was both the `latest` and `beta` tag...

**Comment by lgeiger** [comment]
Thanks a lot for the super fast fix!
