### ISSUE TITLE
@computed not updating properly on observer change

### ISSUE THREAD

**Issue by Shooshte** [mobxjs/mobx-react#268]
I have an array that gets populated from a network request:
```
@observable result = []

@action async updateResult() {
        const newResult = await axios.get(url)
        this.result.push(newResult)
}
```

Then I have a computed:
```
@computed get getResults() {
   return this.result
}
```

But when I console.log getResults in the render function of my component, I only get the empty array. The @computed does not trigger again after the value of @observable has changed.

This only happens when using the latests version of mobx-react. Downgrading the version to 4.1.8 removes the issue.

**Comment by Shooshte** [comment]
Hi,

Sorry this took a while:
https://codesandbox.io/s/R6rwVwJOR

Hope you have everything you need here, if not, let me know.

**Comment by rchanou** [comment]
I'm getting this bug too! And it indeed works correctly in 4.1.8. I'll see if I can create a minimal case too.

**Comment by rochakgupta** [comment]
@Shooshte any further update on this? This issue has been open for quite a while.

**Comment by Shooshte** [comment]
@rochakgupta sorry, I updated the mobx version that I am using and the problem went away, so this issue can probably be closed.
