### ISSUE TITLE
Tests are not passing 

### ISSUE THREAD

**Issue by Havunen** [mobxjs/mobx-react#269]
Travis is reporting build succeeded, but its not running tests (intended?).
Anyway running tests manually reports 24 of them failing. 

steps to reproduce 1:
```
npm install
npm test
=> 
 using a custom injector is not too reactive
 TypeError: Cannot read property 'appendChild' of null
 and execution stopped.
```
steps to reproduce 2:
```
npm install
npm run test:build
npm run test:open
=> Couldn't get a file descriptor referring to the console
```

steps to reproduce 3:
```
npm install
npm run test:build
http-server -p 8080
navigate to http://localhost:8080/test/browser/

# tests 277
test_bundle.js:83707 # pass  253
test_bundle.js:83707 # fail  24
```

Full test log from repro3:
[react-mobx-test.txt](https://github.com/mobxjs/mobx-react/files/1050503/react-mobx-test.txt)

I used Ubuntu 16.04.2 LTS, NodeJS 8.0.0  npm 5.0.2 for the above trials, but also using Windows 10 + nodeJS 6 failed to run tests.

**Comment by mweststrate** [comment]
Could you retry? Fixed some test setup issues last week: @Havunen

**Comment by Havunen** [comment]
@mweststrate tests passing now, thanks :)
