### ISSUE TITLE
Mobx in Production error  (Heroku)

### ISSUE THREAD

**Issue by BenBenz** [mobxjs/mobx-react#272]
Hello,

When I start my production server with mobx it fails .. 

I have this error

static/js/main.8254710b.js from UglifyJs Unexpected token: name (BaseAtom) [./~/mobx/lib/mobx.module.js:8,0][static/js/main.8254710b.js:25309,6]

I don't know if it is from me or heroku or mobx 

When I start my server in my computer it works well

**Comment by nicmyers** [comment]
We just started getting this in our CI platform. Most likely related to some of the recent Mobx updates relating to a change in their build system.

**Comment by mweststrate** [comment]
This is probably an issue with the module setup: the error links to `mobx.module.js`, which is the ES6 module, probably not supported by your browser and should be transpiled by e.g. webpack.

**Comment by BenBenz** [comment]
The same code works in dev, how I can do that ?

**Comment by peterkle** [comment]
+1
We are getting the same error from UglifyJs plugin, even after transpiling from ES6 => ES5 via webpack + babel

```
"mobx": "^3.1.7",
"mobx-react": "^4.1.3",
```

**Comment by BenBenz** [comment]
Do you use react-scripts ?

**Comment by peterkle** [comment]
no...

**Comment by BenBenz** [comment]
When I use npm run build on my laptop it wotks fine, but on heroku I get,

> react-scripts build
Creating an optimized production build...
Failed to compile.
Module build failed: SyntaxError: Unexpected token (19:1)
  17 | 	}
  18 | 
> 19 | 	@observable connected = false;

**Comment by peterkle** [comment]
@BenBenz try clearing out the `node_modules` directory and `npm install` again on your laptop. I suspect you are not using the latest mobx locally. Run `npm ls --depth=0` to see your current package versions to confirm.

**Comment by peterkle** [comment]
pinning to `mobx@3.1.11` worked for me.

**Comment by BenBenz** [comment]
@peterkle thanks for your reply

On my laptop it have
├── mobx@3.1.13
├── mobx-react@4.2.1

On heroku I have 
+-- mobx@3.1.11
+-- mobx-react@4.2.1

This is my  package.json
{
  "version": "0.2.0",
  "private": true,
  "dependencies": {
    "bootstrap": "^4.0.0-alpha.6",
    "mobx": "^3.1.9",
    "mobx-react": "^4.2.1",
    "parse": "^1.9.2",
    "prop-types": "^15.5.10",
    "react": "^15.5.4",
    "react-bootstrap": "^0.31.0",
    "react-dom": "^15.5.4",
    "react-router": "^4.1.1",
    "react-router-dom": "^4.1.1",
    "react-transition-group": "^1.1.3",
    "reactstrap": "^4.6.2"
  },
  "devDependencies": {
    "custom-react-scripts": "0.0.23",
    "react-app-rewire-mobx": "^1.0.3",
    "react-app-rewired": "^1.0.2",
    "babel-cli": "^6.24.1",
    "babel-plugin-transform-decorators-legacy": "^1.3.4",
    "babel-preset-es2015": "^6.24.1",
    "babel-preset-react": "^6.24.1",
    "babel-preset-stage-1": "^6.5.0"
  },
  "scripts": {
    "start": "react-scripts start",
    "build": "react-scripts build",
    "test": "react-scripts test --env=jsdom",
    "eject": "react-scripts eject"
  }
}

Why the version is not the same ?

**Comment by peterkle** [comment]
@BenBenz the caret(^) before the version # means that when you run (or heroku runs) `npm install` it will grab the latest package from the repo matching a minor release. So `^3.1.9` will install the latest version of `3.X.X`. Read this [cheatsheet about semantic versioning](https://bytearcher.com/goodies/semantic-versioning-cheatsheet/Semantic%20Versioning%20Cheatsheet.pdf).

**Comment by mweststrate** [comment]
Check if you have hidden, non versioned .env file. Seems decorators are not
enabled in your prod build. So maybe your config are not in the repo

Op vr 9 jun. 2017 22:53 schreef Peter Le <notifications@github.com>:

**Comment by andykog** [comment]
Also, custom-react-scripts has problems with decorators in recent versions: https://github.com/kitze/custom-react-scripts/issues/81

**Comment by timothyallan** [comment]
Urggg. Just started getting this too on my production build after updating MobX to 3.1.13
`
ERROR from UglifyJs
Unexpected token: name (BaseAtom)
`

Reverting to MobX 3.1.11 fixes it.

**Comment by mweststrate** [comment]
Could someone try whether mobx@3.1.13-fixcra fixes the issue? Unpublished .12 and .13 for now

**Comment by mweststrate** [comment]
Released 3.1.14. Please let us know if this causes trouble again!

@BenBenz note that the error in [this](https://github.com/mobxjs/mobx-react/issues/272#issuecomment-307479986) comment is probably unrelated to that

**Comment by BenBenz** [comment]
@peterkle  Thank you for this information 

@mweststrate In fact my env was not in my git ! Sorry for this stupid problem ... 
@mweststrate I have try with theses 2, and it works ! 🥇 Thank you

@nicmyers 
@peterkle 
@andykog 
@timothyallan 
@mweststrate 
Thank you for you help !

So my first problem was a real bug ?

**Comment by mweststrate** [comment]
@BenBenz yep, first one was a bug indeed.
