### ISSUE TITLE
MobX-React does not navigate with React Router 4

### ISSUE THREAD

**Issue by alexwasner** [mobxjs/mobx-react#274]
I'm not sure if this is a bug with RR or MobX, but when I upgrade to `^4.2.1` of Mobx-react, my navigation no longer works with React Router 4. The URL still changes, but a breakpoint is not hit in the render function.

**Comment by rossipedia** [comment]
How are you integrating `react-router` with `mobx` / `mobx-react`? AFAIK both libs are independent and shouldn't directly affect each other. Can you possibly post some code that demonstrates the issue?

**Comment by mweststrate** [comment]
@alexwasner from which version are you upgrading? Please provide a reproduction indeed

**Comment by alexwasner** [comment]
Turns out I had to add `@withRouter` to my main component. I upgraded from  `mobx`: `^2.5.2` and `mobx-react`: `^3.5.7` to  `mobx`: `^3.1.11` and `mobx-react`: `^4.2.1`. All of this used the `latest` of `react-router-dom`.

Here is what it looks like now for anyone in the future:

```
@inject("store")
@withRouter
@observer
export default class App extends Component {
	render() {
		return (
			<div className="wrapper">
				{/*<DevTools />*/}
				<Route exact path="/" render={props => (
						<LazyRoute {...props} component={import("../components/Home")} />
					)}
				/>
				<Route exact path="/page" render={props => (
						<LazyRoute {...props} component={import("../components/Page")} />
					)}
				/>
			</div>
		);
	}
}
```

I'm not sure if there are any action items aside from maybe some documentation to prevent future headaches.

**Comment by chemitaxis** [comment]
Hi @mweststrate I have detected that if you use it, you have a side effect... some stores are not updating. We have a problem with our language store, it's not triggering the @observer. 

If we get out the route from our Main component and put it on our App component, with the router and other stuff all works fine. We are using MST, but if we change our store to a simple MobX store, it fails too. We are using react-loadable for importing the routes in async way (https://github.com/thejameskyle/react-loadable).

I will try to do tomorrow a small repo with the problem. Thanks!

**Comment by chemitaxis** [comment]
Hi @mweststrate and @alexwasner here you have a repository when you can check the problem:

https://github.com/chemitaxis/error-mobx (created with CRA)

If you move this code from ListRoutes.jsx to App.js it works:
```

<Switch>
        <Route exact path="/" name="Page1" component={AsyncPage1} />
        <Route path="/Page2" name="Page2" component={AsyncPage2} />
</Switch>
```

Is this an error? Or a bad use of MobX? Thanks!

**Comment by chemitaxis** [comment]
Maybe this is related #210 #296

**Comment by dmitryk-dk** [comment]
HI, @chemitaxis! Can you check the problem in this issue, i create comment with my simple app https://github.com/mobxjs/mobx-react/issues/296

**Comment by bin16** [comment]
i met something similar. i have some navs in App.jsx, controlled by computed values.
and i have a Login.jsx, you know, login -> success -> set token -> history replace redirect -> toast
all of them works well, before

---

now i want to add a nav to logout into App.jsx, so i need a history replace too, here is the point:

- After `@withRouter` is added to App.jsx, redirect of Login.jsx not working anymore(url changed, and other functions are ok)
- However, i can move my pointer onto the nav, immediately, navs updated, page changed

**Comment by uhoh-itsmaciek** [comment]
For anyone else running across this, I found https://github.com/ReactTraining/react-router/blob/master/packages/react-router/docs/guides/blocked-updates.md (linked [in this related issue](https://github.com/mobxjs/mobx-react/issues/296#issuecomment-356241404)) to be a really good explanation of the core issues, complete with a couple of different workarounds.
