### ISSUE TITLE
rootNodeID is always 0

### ISSUE THREAD

**Issue by hediet** [mobxjs/mobx-react#278]
React's rootNodeID is used to generate a friendly name for debugging (see [here](https://github.com/mobxjs/mobx-react/blob/4177daa6685dc6c40a232aeb297f93ee27675bde/src/observer.js#L120)).
However, that always seems to be zero. `_reactInternalInstance._rootNodeID` seems to be depricated anyways.

**Comment by mweststrate** [comment]
I think it can simply be dropped. Willing to open a PR?

**Comment by mweststrate** [comment]
Fixed through #368
