### ISSUE TITLE
Reference Component in Reaction

### ISSUE THREAD

**Issue by hediet** [mobxjs/mobx-react#279]
It would be very handy for debugging tools if the reaction created [here](https://github.com/mobxjs/mobx-react/blob/4177daa6685dc6c40a232aeb297f93ee27675bde/src/observer.js#L166) has an explicit reference to the component that is being rendered.
Something like `reaction.react_component = this;` would do it.

**Comment by mweststrate** [comment]
Feel free to create a PR. Note that the reverse link is already created (from component to the reaction)

**Comment by hawkins** [comment]
Since no one else has yet, I went ahead and opened a PR for this at #305
