### ISSUE TITLE
Jest tests

### ISSUE THREAD

**Issue by bartonhammond** [mobxjs/mobx-react#28]
Anyone got Jest working?

**Comment by mweststrate** [comment]
Personally didn't do anything significantly with tape yet, but I think you would at least need to avoid stubbing of the `mobservable` and `mobservable-react` packages to test anything useful?

**Comment by bartonhammond** [comment]
I don't use Tape, but rather Jest, and I do have those packages called out not to not mock them automatically but I can't get a single test to run.  Not sure what the problem is at this time.

**Comment by mweststrate** [comment]
Do you have a shareable branch somewhere? I can take a look

**Comment by bartonhammond** [comment]
Just updated 

* npm install
* npm test

[https://github.com/bartonhammond/mobservable-react-native-counter](https://github.com/bartonhammond/mobservable-react-native-counter)

**Comment by mweststrate** [comment]
I saw that some other teams in our company have Jest / React / Mobservable tests, so it is possible at least :)

**Comment by bartonhammond** [comment]
I've had nothing but trouble keeping my Jest tests working in my other
project - seems every release of RN breaks something.

Hopefully you find a team that can provide some insight

Thanks for looking at it.



On Tue, Feb 16, 2016 at 8:48 AM, Michel Weststrate <notifications@github.com

**Comment by mweststrate** [comment]
Wow, Jest is a real horror to setup, I changed the setup a bit that got me at least beyond the initial "FAIL" I got without any further error when including components.  

See: https://github.com/mweststrate/mobservable-react-native-counter/commit/76dba47625d0062e4f7fc652e1a4ba26ee48596f

The script preprocesser seems to fix it that at least the tests start when referring to a component. But after that it throws compile errors. Note sure how to setup multiple preprocessors. It seemed that the `require('react-native')` import in the `mobservable-react` module broke without the preprocess. But so far Jest is one big mistery for me. I happily continue not using it :wink:

**Comment by bartonhammond** [comment]
Rats!  Sorry to hear you didn't make any headway!  I had all my fingers and toes crossed.

The ReactJS Conf is going on now - I've been watching it.  They haven't mentioned Jest.  No surprise -it's the read headed step child.

Once I get my server stuff settled down I want to pick up the mobservable rewrite w/ my Snowflake/Redux app.  It would be nice to run tests.  Maybe by then I'll have some insights.

**Comment by kitze** [comment]
@mweststrate is there any chance that compatibility with Jest will be fixed soon?

**Comment by mweststrate** [comment]
@kitze  From your tweets it seems the question has been answered, but for future reference

`jest.mock('react-dom');` seems to be needed (https://github.com/facebook/react/issues/7386). See also https://semaphoreci.com/community/tutorials/how-to-test-react-and-mobx-with-jest
