### ISSUE TITLE
Where should I put useStrict?

### ISSUE THREAD

**Issue by chobo2** [mobxjs/mobx-react#286]
Hi

I am wondering where is it best to put "useStrict'? should I be putting it in every file? Or should I just put it in  my app.js(root react component)

Also do I get it from mobx package? I am having trouble finding much info about this tag.

**Comment by vict-shevchenko** [comment]
If you want a flow where only methods decorated with `@action` can modify your state. You should enable strict mode.

Once in your app, likely in `index.js`.
```
import { useStrict } from 'mobx';

useStrict(true);
```
