### ISSUE TITLE
4.2.1?

### ISSUE THREAD

**Issue by gigafied** [mobxjs/mobx-react#287]
`package.json` in `master` lists the version as `4.2.0` yet the latest published version on NPM is `4.2.1`

**Comment by andykog** [comment]
@mweststrate

**Comment by mweststrate** [comment]
On it, forgotten push, but don't want to merge & force push as somebody might have a living fork ;-)

**Comment by mweststrate** [comment]
Pushed (and created fresh release). Thanks for noticing.
