### ISSUE TITLE
Injected Stores not referenced in render() method are not reactive.

### ISSUE THREAD

**Issue by Andrew1431** [mobxjs/mobx-react#288]
Hey there. I replaced a buddies application from redux to mobx, as he found for his simple small application redux was hugely overkill. I totally agreed with him, and suggested mobx. It was a learning experience for me so that I could have good debates with people why to use redux vs mobx and vice versa. All in all I thoroughly enjoyed my adventure learning how mobx works, and must say I do love it, this conversion resulted in a PR that was -900, and +150 lines of code, with the EXACT same functionality. That's pretty stellar! Though obviously we lose all the fun tidbits that redux offers.

Anyways the point of the matter:

In this higher order authentication verification component that ensures a user is logged in before displaying the page, I pretty straight-forwardly injected auth, and routing stores. I reference `this.props.auth.isAuthenticated` in `componentWillMount()` and `componentDidUpdate()` (I agree, it should be `componentWillReceiveProps()`, but hush for now, this gets the job done).

Anywhoo, it wasn't 'reactive' meaning when I set `this.isAuthenticated = false` in the `@action signOut() { ... }` store action, it wasn't redirecting the user to the `/login` page. I couldn't figure out the difference between this component and others, except for one tiny thing which I really hoped wasn't the case: It needed to be referenced in the render() method. Upon literally just placing the text `this.props.auth.isAuthenticated;` inside the render method, my problem was solved, and this component proceeded to function exactly as it should. So my question is:

If I'm wrapping this class with `@observer`, why doesn't the whole component react to changes made in `'auth'` and `'routing'` stores. Now to be fair I'm kind of relieved that changes to routing and auth that aren't referenced won't cause an additional rerender, but I'm curious what the proper approach would be to tell inject to specifically watch for a specific key and trigger prop changes explicitly when that value changes, even when it is not referenced in the `render()` method as that line of code being there serves no other purpose than to trigger the tracker, which I think is very dirty.

Thanks for the tips! I really like how easy mobx is to use.

``` jsx
...
import { inject, observer } from 'mobx-react';

const userIsAuthenticated = (Component) => {
  @inject('auth', 'routing')
  @observer
  class AuthenticatedComponent extends React.Component {

    componentWillMount() {
      this.checkAuth();
    }

    componentDidUpdate() {
      this.checkAuth();
    }

    checkAuth() {
      if (!this.props.auth.isAuthenticated) {
        this.props.routing.push('/login');
      }
    }

    render() {
      this.props.auth.isAuthenticated;
      return <Component { ...this.props }/>;
    }

  }

  return AuthenticatedComponent;
};

const routes = (history) => (
  <Router history={ history }>
    <Route path="/login" component={ Blank }>
      <IndexRoute component={ LoginView }/>
    </Route>

    <Route path="/" component={ userIsAuthenticated(Main) }>
      <IndexRedirect to="/orders"/>
      <Route path="discounts" component={ DiscountsView }/>
      <Route path="users" component={ UsersView }/>
      <Route path="orders" component={ OrdersView }/>
    </Route>
  </Router>
);

export default routes;
```

**Comment by leader22** [comment]
How about this pattern?

```js
const userIsAuthenticated = (Component) => {
  @inject('auth', 'routing')
  // @observer may not be needed.
  class AuthenticatedComponent extends React.Component {

    componentDidMount() {
      // use mobx.reaction to check observable props.
      this.checkAuthReaction = reaction(
        () => this.props.auth.isAuthenticated,
        isAuthenticated => {
          if (isAuthenticated === false) {
            this.props.routing.push('/login');
          }
        }
      );
    }

    componentWillUnmount() {
      // dispose reaction.
      this.checkAuthReaction();
    }

    render() {
      return <Component { ...this.props }/>;
    }

  }

  return AuthenticatedComponent;
};
```

**Comment by Andrew1431** [comment]
It doesn't seem right to me to be coupling mobx functionality right inside a component, as it should be react that manages based on props how certain things are. This would be seemingly impossible for me to spec / mock. That being said, I could probably turn that into a decorator quite simply that just maps part of state to props and puts it through the expected react lifecycle methods. Is there a decorator from mobx-react that does such a thing? Or should I make my own.

**Comment by urugator** [comment]
I think you should rethink the design as there are multiple problems imho:
`componentWillUpdate` shouldn't contain side effects (`this.props.routing.push('/login')`)
`componentDidUpdate` runs after the component has been already rendered, whats the point of checking `isAuthenticated` here?
It seems like you're trying to shortcircuit component update, by redirecting to login inside lifecycle method, this is not possible.
It can be done like this:
```javascript
render() {
  if (this.props.auth.isAuthenticated) {
    // render requested page  
  } else {
    // render login page
  }
}
```
or like this:
```javascript
@computed pageToDisplay() {
  if (this.page.requiresAuthentication && !this.auth.isAuthenticated) {
    return loginPage;
  }
  return this.page;
}
```
I am not a react router user, but you should be able to google up the appropriate solution.

Here: `<Route path="/" component={ userIsAuthenticated(Main) }>` you dynamically create new component class. I am not familiar with react router, but if that code runs during render, it will break react reconciliation process. 

Also be careful about your sign out logic, you should purge and recreate the whole state here, otherwise you are risking the exposure of data requiring authentication. The easiest way is to sign out user at server and let the page completely reload.

**Comment by Andrew1431** [comment]
Alright, I'm not concerned about the security stuff, that won't be hard to fix. (Including doing what you said in the render() method) but I program a lot with reusable components that should be agnostic of what their container is, and rely 100% on the stream of props coming in, so I was mostly just curious if there was a way to force injecting certain properties that will be treated as 'tracked' regardless of their use in the component. But thanks! I think you've given me what I need to achieve this.

**Comment by Andrew1431** [comment]
Trying to keep mobx entirely out of my components, so I'm not sure how that would help me either. I want a complete UI application, with no dependencies on anything but the props they receive. (basically just callbacks which tie to actions, and the data they should display.)

Redux doesn't require me to put any redux logic inside my components. It simply displays what props it receives (mapStateToProps), and has callbacks (mapDispatchToProps). In my JEST react unit tests, I can mount a react component, and test that all functionality works, without having to mock redux / mobx / children(<Observer>). 

So I am going to do what you've suggested, but I am going to work with it to make them high order functions / components / decorators so that in the application layer i can just slap on any decorators that I need to to make the react components function the way they should, and re-use those throughout the app, to avoid coupling my UI with any external frameworks.

All of my arguing is mostly just based around the fact that when I switched the application from redux to mobx, I didn't touch a single UI component. It legitimately was a drop-in replacement. That should continue to be how it is were I to switch from MobX to the next amazing state container solution that comes out ! :P 

As such that's why I'm pushing for a non-coupled way, and my solution will just be coming up with my own decorators to satisfy my drop-in capabilities. Then I can just delete my decorators when I move to the next framework.

**Comment by urugator** [comment]
Well you need to establish a link between the store and component.
Redux has a `connect` abstraction, but has to be managed manually. 
Mobx is more opinionated and invasive as it has to patch the component, but the linkage is managed automaticaly.
It's your call which level of abstraction is required for your use case.

**Comment by mweststrate** [comment]
Didn't read the entire thread in detail, but @Andrew1431 you might find the right level of abstraction by using `inject((props, stores, context) => childProps)(component)`, which is more similar to `connect` and allows you to put logic in a more decratoring place. The inject function itself is tracked btw, so you could dereference all the data you need there and pass it as plain(?) props to your component. So I have a hunch you could leverage that to build the nice HoC you need.

**Comment by mweststrate** [comment]
P.S. @urugator thanks for all your awesome answers and long term support in the MobX repos! I couldn't find your mail address anywhere (or any other PM mechanism for that matter), but if I can thank you in any way just drop me a line (mweststrate `@`  gmail,com) ! Like sending a stash of stickers, recommendation etc :wink:.

**Comment by urugator** [comment]
Np, I will keep that in mind
