### ISSUE TITLE
shouldComponentUpdate don't diff context

### ISSUE THREAD

**Issue by reoszo** [mobxjs/mobx-react#292]
reactiveMixin.shouldComponentUpdate don't diff context, just props and state.
when parent Component change store, but don't change subComponent's props and state, subComponent don't re-render, ....

**Comment by urugator** [comment]
> Values provided through Provider should be final, to avoid issues like mentioned in React #2517 and React #3973, where optimizations might stop the propagation of new context. Instead, make sure that if you put things in context that might change over time, that they are @observable or provide some other means to listen to changes, like callbacks. However, if your stores will change over time, like an observable value of another store, MobX will warn you. To suppress that warning explicitly, you can use suppressChangedStoreWarning={true} as a prop at your own risk.

https://facebook.github.io/react/docs/context.html#updating-context

https://medium.com/@mweststrate/how-to-safely-use-react-context-b7e343eff076

**Comment by reoszo** [comment]
I have read these two articles already. I think mobx-react observer is an invisible HOC, isn't business middle component, so the default behavior of shouldComponentUpdate should not be changed.
If mobx-react is design ignores this, that's ok, i can write my own shouldComponentUpdate.

**Comment by mweststrate** [comment]
Yep, this is as designed. The solution to this is not to fix sCU's, but to properly use context within the given contstraints described in my article; libraries cannot do optimizations / abstractions if they have to deal with your app's contexts. Note that this doesn't held for just MobX, but for many other libraries you might use in your app, so it is better to fix this issue it on the context side of things. (You can use ready-to-use abstractions for that like mobx-react Provider / inject, or react-broadcast)
