### ISSUE TITLE
How to access an Observer/Injected component from parent

### ISSUE THREAD

**Issue by LeonardoGentile** [mobxjs/mobx-react#294]
Hello,
I've hit an unusual use case where this happens:

```
<Parent>
   <Child/>
</Parent>
```

Where Child is something like this:
```
@inject('myStore')
@observer
class Child extends Component { 
  constructor(props){
    super(props);
   }
   // Other things here..
}
```

Now from the Parent I need to access its child with:
```
import Child from './Child'

class Parent extends Component { 
  render(){
    const {children} = this.props;
    React.Children.map(children, child => {
      // This does NOT work
      if (child.type === Child) {
        // things in here with the child
      }
    }
  }
}
```

Now of course while accessing the children with `React.Children.map` the type will never be `Child` because of the HOC introduced by `inject` and `observer`.

I've tried `child.type.wrappedComponent === Child` or `child.WrappedComponent === Child` or `child.wrappedInstance === Child` but none of these actually works.

How do I access the original Child component from the parent?

**Comment by mweststrate** [comment]
I would expect `child.wrappedInstance.type` to be `Child`

**Comment by LeonardoGentile** [comment]
Apparently in the Injector element there isn't a wrappedInstance properties:
![image](https://user-images.githubusercontent.com/412061/27907827-7b1b1790-6249-11e7-91a3-b346476379c3.png)

**Comment by mweststrate** [comment]
Which mobx-react version?

**Comment by LeonardoGentile** [comment]
mobx-react@4.1.8

**Comment by mweststrate** [comment]
Could you setup a fiddle / codesandbox reproducing this problem? Here is a simple starting point: https://codesandbox.io/s/2vmzpM0wK

**Comment by mayorovp** [comment]
Seems like wrappedInstance is present only after render

**Comment by mweststrate** [comment]
Hmm. that is correct I think, render creates instances or reconciles an
existing one, wrappedComponent is probably the interesting one

Op do 6 jul. 2017 om 16:30 schreef mayorovp <notifications@github.com>:

**Comment by LeonardoGentile** [comment]
Ah, that is probably it then.
I've tried to reproduce this all afternoon and I couldn't. 

The structure and relationship between parent/child is created within a loop (outside any render).

```
const navItems = menuConfig.sections.map((section, sectionIdx) => {
  return (
    <li key={sectionIdx.toString()} 
      <Parent> <Child /> </Parent>
    <li/>
})

// later..
class Container extends React.Component {
  render() {
    {navItems}
  }
}

**Comment by LeonardoGentile** [comment]
As explained above my structure is generated outside a render method, so apparently this can't be solved, I've changed my app structure to fix this in another way. 
I'm closing this, thanks for your help 👍
