### ISSUE TITLE
Should you be passing in Stores into your Domains?

### ISSUE THREAD

**Issue by chobo2** [mobxjs/mobx-react#295]
Hi

I am still confused on what is the best practices with using mobx, from what I read you can and  should be passing in  stores into other stores but what about classes?

say if I have a ToDoStore and a ToDo class, should ToDo class take in ToDoStore?

**Comment by urugator** [comment]
If you're refering to [these best practices](https://mobx.js.org/best/store.html), I think that passing the store to domain object is the only way to:

> makes your domain concepts easier to use stand-alone

**Comment by mweststrate** [comment]
Closing, assuming that an accepted answer has been provided :)

**Comment by chobo2** [comment]
How about  passing a domain object to a store object?

**Comment by urugator** [comment]
If you want to:

>Make sure there is only one instance of each of your domain objects. The same user, order or todo should not be twice in your memory. This way you can safely use references and also be sure you are looking at the latest instance, without ever having to resolve a reference. This is fast, straightforward and convenient when debugging.

then passing domain object alone to other store may be problematic ... passing a store as a domain object provider instead is probably a better idea

**Comment by chobo2** [comment]
Hmm, I am going to have to play around with that and see. I  have to look at my code again, I might only be passing the store around.
