### ISSUE TITLE
Reacting to store events when component renders nothing

### ISSUE THREAD

**Issue by IljaDaderko** [mobxjs/mobx-react#297]
I've got following react native implementation to show notification based on mobx store, but it is not working

```
import { Component } from "react";
import { observer, inject } from "mobx-react/native";
import { Alert } from "react-native";

@inject("notification")
@observer
class Notification extends Component {
  // -- methods ------------------------------------------------------------- //
  componentWillUpdate({ notification }) {
    if (notification.shown)
      Alert.alert(notification.type, notification.message, [
        { text: "Close", onPress: notification.hideNotification }
      ]);
  }

  // -- render -------------------------------------------------------------- //
  render() {
    return null;
  }
}

export default Notification;

```

I am trying to wrap my head around functions like autorun, do I need to use it here if I am not rendering anything? Essentially I need something like `componentWillreceiveProps` to trigger native alert, but I don't seem to be getting mobx updates, however using `spy()` indicates that they are being dispatched correctly.

**Comment by IljaDaderko** [comment]
Also, this is store connected to above component

```
import { observable, action } from "mobx";

const ERROR = "notification/ERROR";
const SUCCESS = "notification/SUCCESS";

class NotificationStore {
  // -- store --------------------------------------------------------------- //
  @observable type = ERROR;
  @observable message = "";
  @observable shown = false;

  // -- actions ------------------------------------------------------------- //
  @action
  errorNotification(message) {
    this.type = ERROR;
    this.message = message;
    this.shown = true;
  }

  @action
  successNotification(message) {
    this.type = SUCCESS;
    this.message = message;
    this.shown = true;
  }

  @action
  hideNotification() {
    this.shown = false;
  }
}

export default NotificationStore;
```

it seems to be dispatching actions despite me using `@action` decorator or not, making me question when is it really needed?

**Comment by urugator** [comment]
If you're not rendering anything, no observable was accessed, therefore the component isn't subscribed for anything. You can create a `reaction/autorun` in `componentDidMount` and dispose it in `componentWillUnmount`

Regarding `action` [this](https://github.com/mobxjs/mobx/issues/1010#issuecomment-303804877) may help.

Also note that `spy/intercept/observe` doesn't take `actions` into consideration, every single observable mutation is captured by these.

**Comment by IljaDaderko** [comment]
@urugator somewhat got it working with autorun, but it is only showing notification once when this is fulfilled

```
componentDidMount() {
    autorun(() => {
      if (this.props.notification.shown)
        Alert.alert(
          this.props.notification.type,
          this.props.notification.message,
          [{ text: "Close", onPress: this.props.notification.hideNotification }]
        );
    });
  }
```

i.e. when `this.props.notification.shown` is true, when I close it I can see `this.props.notification.hideNotification` sets shown back to false, I trigger notification again, but this time it is not showing :/

**Comment by urugator** [comment]
Check: https://codesandbox.io/s/2RGMpExAW

**Comment by urugator** [comment]
Probably unrelated:
`onPress: this.props.notification.hideNotification` 
=>
`onPress: () => this.props.notification.hideNotification` 
or
`@action.bound  hideNotification() { /*...*/ }`

**Comment by IljaDaderko** [comment]
@urugator cool, managed to get it going, 2 things I changed (not sure which one fixed it) were to change my store actions from

```
 @action
  errorNotification(message) {
    this.type = ERROR;
    this.message = message;
    this.shown = true;
  }
```

to

```
@action
  errorNotification = message => {
    this.type = ERROR;
    this.message = message;
    this.shown = true;
  }
```

Don't think these were binded correctly before. Secondly I added that dispose you shown in example and it works fine now with reaction!!! Thank you.

I'm still confused why it only triggers once with `when()` is when only supposed to be executed once? and am I understanding these correctly in this case:

autorun - used to run function for every observable change injected into component
reaction - used to run function for specific observable change
when - used to run once when certain check is passed

**Comment by urugator** [comment]
The "tracking/observing" logic is the same in all of them:
All accepts a function, in which you access some observables.
If at least one of the accessed observable is later modifier, the function is invoked (again).
They only differ in what happens after:
autorun - nothing
reaction - takes the value returned from the function, if value differs from the previous run, an "effect" function is invoked (the function passed as second arg)
when - takes the value returned from the function, if the value is *true* (not-falsy), runs the "effect" function and immediately disposes (so yes the effect is invoked only once)
