### ISSUE TITLE
how to force an array to be an ObservableArray?

### ISSUE THREAD

**Issue by suziesirena** [mobxjs/mobx-react#298]
Here is my code:

```
@observable myObjects = {}

myObjects = {
  object1 : {
    myArray : ['value1', 'value2']
  }
}

```
All is fine, myArray is an ObservableArray.
Then I want to add an other object to myObjects: 

```
myObjects.object2 = {
  myArray : ['value1', 'value2']
}
```

My problem is that myArray of object2 is a simple array, not an ObservableArray

How can I force myArray of object2 to be an ObservableArray ?

**Comment by mattruby** [comment]
Try extendObservable https://mobx.js.org/refguide/extend-observable.html

**Comment by mattruby** [comment]
If you're still having trouble, please create a small example of your issue using this [codesandbox.io](https://codesandbox.io/s/2vmzpM0wK) I'll take another look.

**Comment by mweststrate** [comment]
@suziesirena note that you create new keys (`object2`) dynamically. Either declare your keys upfront (e.g. `myObjects= { object1: { .... }, object2: { myArray: [] } }`, or use observable maps if you want to be able to add items under new keys later on, and have mobx react to it.
