### ISSUE TITLE
[RN] FlatList extraData

### ISSUE THREAD

**Issue by andfk** [mobxjs/mobx-react#299]
Hi!
This library works perfect in almost everywhere BUT im stuck with the new `FlatList` component. I need to force re-render, so using the `extraData` with the reference to where it changes in the store is not working. For example
```
class Store {
  @observable items = []
  addItem(item) {
    this.items.push(item)
  }
}

render() {
  return (
    <FlatList
    keyExtractor={item => item.id}
    data={Store.items}
    extraData={Store.items}
    renderItem={(item) => <Text>{item.description}</Text>}
    />
  )
}
```
The only way to force a re-render is using the component state instead of mobx. I´ve an alternative untested that in resume, is to use a reaction in the `items` and update a flag in state `this.setState({ listUpdated: true })` to make it happen.

Did anyone had this issue or im missing something?
Many thanks!

**Comment by andfk** [comment]
Okay. Calling `.slice()` does the trick and `extraData` prop is not needed. This behaviour is similar to what happened in `ListView` which was already reported and solved.

Example:
`
<FlatList
    keyExtractor={item => item.id}
    data={Store.items.slice()}
    renderItem={(item) => <Text>{item.description}</Text>}
    />
`

**Comment by urugator** [comment]
If the array contains other observables and you want to re-render the List when these observables change as well (not just the array itself) use [`mobx.toJS(Store.items)`](https://mobx.js.org/refguide/tojson.html). It will visit these observables causing the subscription...
