### ISSUE TITLE
Nested components with stores gives error "MobX injector: Store 'store' is not available! Make sure it is provided by some Provider" when trying to mount component in enzyme

### ISSUE THREAD

**Issue by sikemausa** [mobxjs/mobx-react#300]
**What I'm trying to do**
I'm trying to test a component with nested components, some of which have the store injected. I'm receiving the error "MobX injector: Store 'store' is not available! Make sure it is provided by some Provider" when trying to mount the component using enzyme. If I comment out the nested components which have the store injector, the error goes away. I am testing using Enzyme and Jest.

**Example**

Search component

```
import SearchBar from '../SearchBar';
import SearchButton from '../SearchButton';

@inject('store') @observer
export default class Search extends Component {
  render() {
    <div>
      <SearchBar />
      <SearchButton />
    </div>
  }
}
```

SearchBar component:

```
@inject('store') @observer
export default class SearchBar extends Component {
  render() {
    <div>
      <h1>Hi</h1>
    </div>
  }
}
```

SearchInput component:

```
@inject('store') @observer
export default class SearchInput extends Component {
  render() {
    <div>
      <h1>Hey</h1>
    </div>
  }
}
```

Test:

```
import Search from '../Search';
import { mount } from 'enzyme';

store = { searchTerm: '' }

describe('Search', () => {
  it('has a searchBar', () => {
    const component = mount(<Search store={store} />);
  });
});
}
```

The above test is what returns the error when run (given any assertion / test etc.). If I SearchBar and SearchInput out, the test runs fine - so I'm guessing that the error is due to the nested component's injection of the store?

Shallow rendering fixes the issue, but will not work for the tests I need to write, as I am testing lifecycle methods.

**Comment by mweststrate** [comment]
@sikemausa inject relies on context, so you have basically 4 options to pick here:

1. Do shallow rendering (as you mentioned), and pass in store explicitly, bypassing the outer inject
2. Use Provider in your tests: e.g. `mount(<Provider store={store}><Search /></Provider>`
3. Don't use `inject` on the deeper components, but pass `store` via props from `Search` to all the relevant descendants
4. You could also put a `Provider` inside the `Search` component, (re)injecting the `store` in the tree, but I think that is an ugly thing to do just for the sake of testing

**Comment by sikemausa** [comment]
Perfect - using the Provider in my test is precisely what I needed to do. I appreciate the response - thank you.

**Comment by mweststrate** [comment]
Kind request: close solved issues 😉
