### ISSUE TITLE
Mobx observer: You are trying to use 'observer' on a component that already has 'inject'. Please apply 'observer' before applying 'inject'

### ISSUE THREAD

**Issue by cbll** [mobxjs/mobx-react#308]
This warning is tossed at me a lot of times when rendering my main page which contains a bunch of React classes.

Am I misunderstanding something - because in cases where I use the observer AND inject decorators, I do it as such:

```
@observer @inject("store")
export default class SomeClass extends React.Component {
// Class stuff here.. 
```

I can invoke functions and receive data from the store without any issues. I just get this warning over and over and over. It really bugs me :)

**Comment by nassimbenkirane** [comment]
Hi @cbll,
You can use `observer` and `inject` together, you just need to invert them :
```
@inject("store") @observer
export default class SomeClass extends React.Component {
// Class stuff here.. 
```
Hope that helps :)

**Comment by cbll** [comment]
I'll give it a try, but isn't that the exact opposite of what it's telling me to do?

**Comment by nassimbenkirane** [comment]
Basically, using `@myDecorator class SomeClass` is more or like doing : `myDecorator(SomeClass)`

So in our case it would be :
`inject('store')(observer(SomeClass))`
so you would be applying observer _before_ applying inject.

**Comment by heqifang** [comment]
@nassimbenkirane 
Hi my question is a little complex

I build a High Order Component  use the mobx-react

like:      observer(Enhancer)

then use like:

@myHighOrderComponent
@inject('mystore') @observer
class mypageComponent extends Component{
....
}

mobx-react  finish the data logic perfect

but it think  the inject  is in font of the observer which in my high order component

but if I use the my high order component before the mobx-react , the data logic would wrong

and i can not remove the observer from the high order component ; it would let me can not get the data before the page render


how can I fix it and  what the way to use mobx-react in the self-high high component

**Comment by nassimbenkirane** [comment]
Hi @heqifang,
could you provide an example of what your Higher Order Component does ?
or maybe the code of your HOC ?

I don't get why you need the observer part inside of your HOC...

P.S: I'm not a maintainer / contributor to this project, just a happy user of MobX and mobx-react :)

**Comment by heqifang** [comment]
Hi @nassimbenkirane 

my customer want to use the API data to generate Dynamic table columns

so I use the high order component to add a new props to table page component (antd table props)

the code like:

HOCFactoryFactory(storeName) {
        // do something with params
        return function HOCFactory(WrappedComponent) {
            class Enhancer extends WrappedComponent {
              
                render() {
                    const elementsTree = super.render();

                   let tableConfig= elementsTree.props[storeName].tableConfig;
      
                   //here  use the tableConfig generate the columns
                   //then I just need use the self-high order components in the page
                   //the antd table columns props would Dynamic generate
                   //customer can use config page change the server table config to change the page table
                    
                    let newProps = {};
                    if (elementsTree) {
                        newProps = {
                            columns: columns
                        }
                    }
                    const props = Object.assign({}, elementsTree.props, newProps);
                    return React.cloneElement(elementsTree, props, elementsTree.props.children);
                }
            }
            Enhancer.displayName = `HOC(${utils.getDisplayName(WrappedComponent)})`;
            return observer(Enhancer);
        }
    };



that is my high order components,
use like:
@utils.HOCFactoryFactory('myStore')
@inject('myStore') @observer
class myPageTable extends Component {
    componentWillMount() {
        this.props.myStore.loadDataAndConfig(params);
    };

    render() {....}
}

so the mobx-react can get the data rightly
but if I remove the observer in the self-HOC 
the elementsTree.props[storeName].tableConfig  would be empty

Now it's just a warning of that warning
But as the page increases, there are more and more warnings

**Comment by pleerock** [comment]
> You can use observer and inject together, you just need to invert them :

strange requirement
