### ISSUE TITLE
Uncaught TypeError: Cannot assign to read only property 'toJSON' of object '[object Object]'

### ISSUE THREAD

**Issue by brothaakhee** [mobxjs/mobx-react#310]
Started getting this error randomly thrown from this location in mobx. Only happens occasionally on a hard refresh, other times it loads fine. Currently on `mobx-react@4.1.8`. Tried updating to 4.2.x with no luck. Anyone seen anything similar?

```
ObservableArray.prototype.toJSON = function() {
     // Used by JSON.stringify
     return this.toJS();
}
;
```

`Uncaught TypeError: Cannot assign to read only property 'toJSON' of object '[object Object]'`

**Comment by mweststrate** [comment]
Reproduction? Are you using polyfills? Or using `toJSON` without a binding context?

**Comment by mweststrate** [comment]
Closing in the absence of a reproduction

**Comment by aslamplr** [comment]
@brothaakhee were you able to resolve this?

**Comment by aschmoe** [comment]
@mweststrate just ran into this issue in the wild.  A FreshDesk chat plugin is calling some code along the lines of

```
var jsonStringify = JSON.stringify;
JSON.stringify = function() {
    var a = Array.prototype.toJSON;
    delete Array.prototype.toJSON;
    var b = jsonStringify.apply(this, arguments);
    Object.defineProperty(Array.prototype, "toJSON", {
        enumerable: true,
        value: function () {
            return [...this];
        },
        configurable: false
    });
}
```

which if it runs before mobx, will cause `Uncaught TypeError: Cannot assign to read only property 'toJSON' of object '[object Object]'` in mobx@4.1.1

```
ObservableArray.prototype.toJSON = function () {
        // Used by JSON.stringify
        return this.toJS();
    };
```
