### ISSUE TITLE
Problem with observer saving state of last mounted component instance

### ISSUE THREAD

**Issue by sampurcell93** [mobxjs/mobx-react#312]
Hi all, I'm using mobx and mobx-react with React Native. I have a standard controller component that looks like this:

```
@observer
class MyComponent extends React.Component<{store: MyStore}, any> {
  componentDidMount() {
    console.log('MOUNT', this.props.store.id);
  }
  componentDidUpdate() {
    console.log('UPDATE', this.props.store.id);
  }
  render() {
    console.log('RENDER',  this.props.store.id);
    return (<Text>{this.props.store.id}</Text>);
  }
}
```

Every time this scene is mounted, a new MyStore() is created and passed to MyComponent as a prop. The first time I navigate to the scene, all is well - the store id (a `guid()`) renders correctly. If I then dismount this component (pop it off using react navigation) and re-navigate to it, the render function displays the PREVIOUS id value.

The strange thing is that the `console.log`s for MOUNT and UPDATE show the correct new id on second mount. Only in the render function is the old store referenced. Log output:

```
MOUNT id2
RENDER id1
UPDATE id2
```

Here are the steps I have tried to resolve so far:

1. Use the `<Observer/>` component instead. Same issue.
2. Use the non-decorator version of `@observer`. Same issue. I am using typescript so I thought it could be a problem with decorator compilation, but it seems not.
3. Binding the generated store (`new MyStore`) to the root store, as opposed to leaving it 'dangling'. Same issue.

I'd appreciate any guidance as to why the value of the prop would be different in the render function than in the other lifecycle functions. That would help me solve this problem.

Thanks!
Sam

**Comment by urugator** [comment]
If the new store instance is created and passed on every mount it should work out of the box without the need for `@observer`, because the update is caused by recieving new props and not by MobX. Does it work if you remove the `@observer`?

**Comment by sampurcell93** [comment]
The specific issue of render having the wrong value does not occur when I remove @observer. But then, of course, my component does not react to changes.

**Comment by mweststrate** [comment]
@sampurcell93 best create a reproduction. To me it sounds like there are actually two instances of the same component, one getting reconciled and never rendered, or something like that. Is `id` property declared as an observable?

**Comment by sampurcell93** [comment]
`store.id` is not declared as observable. But this is a reduction of the larger problem in my app, which occurs with ALL properties of MyStore (observable or not). And the problem persists when I mark `id` as observable. I suspect it has to do with react-navigation but nothing has turned up in my search for the answer :/.

I'll work on making a repo with this issue isolated.

**Comment by sampurcell93** [comment]
Could it be possible that the new version of React would be upsetting mobx? Perhaps something in the reconciliation process has changed that breaks the lib. I am currently using `react@16.0.0-alpha.12`. I'll investigate but perhaps someone has encountered trouble.

**Comment by sampurcell93** [comment]
This issue is resolved. It was a problem with the `autobind-decorator` package. Even when not using observer as a decorator, it seems that the `autobind-decorator` package conflicts and causes the described behavior. Be wary!
