### ISSUE TITLE
JSBin examples no longer work

### ISSUE THREAD

**Issue by jarecsni** [mobxjs/mobx-react#313]
The following line won't work in JSBin:

`const {observer} = mobxReact`

JSBin says:
ReferenceError: Can't find variable: mobxReact

Would be good to understand/fix this as it impedes people (like me :)) who want to make their first steps in Mobx.

**Comment by andykog** [comment]
Seems to work fine for me https://jsfiddle.net/Sl1v3r/24thewxu/

**Comment by jarecsni** [comment]
Thanks - I didn't have any script tags to reference mobx I guess 🤣

**Comment by andykog** [comment]
YW

**Comment by jarecsni** [comment]
Just for completeness, JSBin seems to find mobx without any script tags, which is weird. So you can say 

const {observable} = mobx; 

and observable will be initialised to a meaningful value. 

This contributed to my confusion I think (and also I tried codesandbox.io recently which automatically imports any packages you reference with import statements so I kind of expected this from JSBin too). Thanks again
