### ISSUE TITLE
Problem Unit Testing a Parent Component whose Child Inject a Store

### ISSUE THREAD

**Issue by samuelalvin** [mobxjs/mobx-react#315]
Hi,
So I have this simple App which structured like this:
1. _Parent Component_
```
class Parent extends React.Component {
    render() {
        return (
            <div>
                <h1>Parent</h1>
                <Child></Child>
            </div>
        );
    }
}
```
2. _Child Component_
```
@inject("someStore")
@observer
class Child extends React.Component {
    render() {
        const { someStore } = this.props as any;
        return (
            <p>{ someStore.text }</p>
        );
    }
}
```
3. _Main App_
```
const someStore = SomeStore.create({
    text: "This is a text."
});

const mainApp = (
    <Provider someStore={ someStore }>
        <Parent></Parent>
    </Provider>
);

ReactDOM.render(
    mainApp,
    document.getElementById("main")
);
```

Now if I test the _Child Component_ using this code:
```
describe("child", function () {
    it("should be created without any problem", function () {
        let child = TestUtils.renderIntoDocument(<Child someStore={someStore}></Child>) as React.Component;
        expect(child).toBeDefined();
    });
})
```
The test will be successful..
But if I test the _Parent Component_ using this code:
```
describe("parent", function () {
    it("should be created without any problem", function () {
        let parent = TestUtils.renderIntoDocument(<Parent></Parent>) as React.Component;
        expect(parent).toBeDefined();
    });
})
```
The test fails with this message:

> Error: MobX injector: Store 'someStore' is not available! Make sure it is provided by some Provider

I assume the problem is because the _Child Component_ need to have _someStore_ injected to it. But I've tried replacing `<Parent></Parent>` in the test file with `<Parent  someStore={someStore}></Parent>` and it will also fails. I believe this happen because the _Child Component_ got the _someStore_ from its props and the _Parent Component_ doesn't pass the _someStore_ to the _Child Component_'s props.

The test will be successful if I replace `<Parent></Parent>` in the test file with `<Provider someStore={someStore}><Parent></Parent></Provider>`, but then the `TestUtils.renderIntoDocument()` method will returns `Provider` instead of `Parent` Component. I don't want it since I need to test the `Parent` Component.

This app is able to run without any error. Any advice to unit test the _Parent Component_ whose _Child Component_ inject _someStore_? I can't seem to find the solution in the documention (Or maybe I missed it somewhere in the docs).

Best Regards,
Samuel

**Comment by urugator** [comment]
One way to solve it would be to avoid this situation altogether by making the parent independent of it's children. Quite common way to do that is to pass *render callback* in place of children:
```javascript
class Parent extends React.Component {
    render() {
        return (
            <div>
                <h1>Parent</h1>
                {this.props.children()} // any prop can be used e.g. this.props.renderContent()      
            </div>
        );
    }
}

describe("parent", function () {
    it("should be created without any problem", function () {              
        let renderChild = () => <Child someStore={someStore}></Child>; // or simply () => <span>children</span>
        let parent = TestUtils.renderIntoDocument(<Parent>renderChild</Parent>) as React.Component;
        expect(parent).toBeDefined();
    });
})
```

**Comment by samuelalvin** [comment]
@urugator Thanks I've tried it and that solved the injection problem!
