### ISSUE TITLE
How to add an observable member to a fat-arrow React component?

### ISSUE THREAD

**Issue by Tsury** [mobxjs/mobx-react#317]
I would like to add an observable member to a fat-arrow component.
I know that with classes I can just use the@observable decorator before a declaration, like:

```
@observable
myBool: false
```

But how to do it in a fat-arrow function?
I don't want to convert it to a class...

**Comment by urugator** [comment]
These fat-arrow functions are called ***stateless** functional components* ...
Once you add any state (`myBool`), it's no longer stateless and can't be expressed as a function.
However you can still pass an observable state by props.

**Comment by Tsury** [comment]
When you say pass by props, you mean observables from another class?

**Comment by urugator** [comment]
Any observable object passed by props, for example an instance of another class (usually referred to as "store").

**Comment by Tsury** [comment]
Thanks
