### ISSUE TITLE
Add support for Initializing mobx-react with a specific mobx instance

### ISSUE THREAD

**Issue by Niryo** [mobxjs/mobx-react#319]
Im building an internal library that uses mobx and mobx-react [(remx)](https://github.com/wix/remx) and I ran across the multiple Mobx instances issue.
To overcome the issue, I think mobx-react should expose a "setMobxInstance" function, and then in my index.js of my library I could just initialize mobx-react with a specific mobx instance. 

I tried to implement it on a local mobx-react clone and it seems to work, but I can't create a PR because Im struggling with the rollup mechanism and the compilation for all the different targets.

Anyway, what do you think about the change?
Am I missing something? #

**Comment by urugator** [comment]
[`mobx.extra.runInIsolation` is not usable](https://github.com/mobxjs/mobx/issues/1082)?

**Comment by Niryo** [comment]
nope, because mobx-react just import mobx like this:
`import * as mobx from 'mobx';`

There is'nt any guarantee for what mobx instance you are going to get.
The library Im working on is a wrapper for mobx, so I don't want to add mobx as a peer dependancy. This means that if a project is using my library, and at the same time has a dependency for mobx (in a different version),  mobx-react can get the wrong instance of mobx. 

What I did in my local mobx-react clone was to change every `import * as mobx from 'mobx'` to: `const mobx = MobxProvider.getMobxInstance();`
  MobxProvider by default just import mobx and return it, but if you explicitly call to "setMobxInsctance()" it will return the given instance. 
this way I can control exactly which mobx instance mobx-react will work with.

**Comment by mayorovp** [comment]
Why you cannot bundle mobx and mobx-react inside your library package? It does not require any changes in sources.

**Comment by Niryo** [comment]
@mayorovp I can do this, but it's more of a patch than really solving the problem. It took me lots of time to find this bug (and yes, I really think it is a bug), and some day it will surely effect other people as well. 
@mweststrate What do you think?

**Comment by mweststrate** [comment]
> The library Im working on is a wrapper for mobx, so I don't want to add mobx as a peer dependancy. This means that if a project is using my library, and at the same time has a dependency for mobx (in a different version), mobx-react can get the wrong instance of mobx.

Peer dependency is on 98% of the cases the best solution for this. You don't have to worry about incompatible version, as npm / yarn themselves will actually will verify the versions are compatible. The problem with two mobx versions loaded is that they won't "talk" to each other, so if you are using mobx-react, with one mobx instance, and remx with another, the `@observer`  components will not react anymore to observables created by remx. Which will lead to bugs that are pretty impossible to debug.

Besides the fact that consumers have to install two additional deps (which they will be warned about), what are the actually problems precisely which you run into when using mobx as peer dep? The exact reason why you run into two installs is exactly that you didn't specify a peer dep but a normal dep instead. 

This is basically exactly how you are supposed to use other libraries like React itself as well. See https://github.com/mobxjs/mobx/blob/master/CHANGELOG.md#mobx-will-no-longer-share-global-state-by-default or #621 / #1082 for some more background. Let me know if I misunderstood anything

**Comment by Niryo** [comment]
> Peer dependency is on 98% of the cases the best solution for this

I agree, our case is definitely an end case.

> with one mobx instance, and remx with another, the @observer components will not react anymore to observables created by remx. Which will lead to bugs that are pretty impossible to debug.

This is actually not a problem for us because remx is not exposing its Mobx observables.

Anyway, even though I still think that it's a real issue with mobx-react, I understand that a bigger change is needed for supporting the case when there are multiple mobx-react version in the project, so ill just add a mobx-react clone bundled inside remx. 

Im closing the issue.
Thanks a lot!
