### ISSUE TITLE
React stateless components and render calls

### ISSUE THREAD

**Issue by rickmed** [mobxjs/mobx-react#32]
As I understand it, when setState is called in react, the component's render method is called and the component and its children will update the vDOM tree so that reactDOM.render can diff (only that section of the tree) and patch it to the real DOM...

With stateless components wrapped in observer, since they don't have a render method, will reactDOM diff the whole vDOM?

**Comment by mweststrate** [comment]
no, that work as expected as well, as long as you wrap sub components in (`@`)`observer` as well. They will still have the normal lifecycle for props etc.

**Comment by rickmed** [comment]
@mweststrate awesome! thanks!
