### ISSUE TITLE
Observer does not trigger a render when using refs

### ISSUE THREAD

**Issue by dangerousdan** [mobxjs/mobx-react#325]
It seems as though the observed component doesn't update when properties are changed, if there is no reference to the props in the render method.

See the example below:
```javascript
@observer
class Foo extends Component {
  componentDidMount() {
    this.draw()
  }
  
  componentDidUpdate() {
    this.draw()
  }
  
  draw() {
    this.el.innerHTML = `Value is ${this.props.data.t}`
  }
  
  render() {
    return (<div ref={el => {this.el = el}} />)
  } 
}
```
When props change, this content of the component should update.
This works fine in pure React, but breaks when props are controlled by MobX

[Codepen example with MobX](https://codepen.io/anon/pen/oGbgJY?editors=0011)
[Codepen example without MobX](https://codepen.io/anon/pen/oGbgrZ?editors=0010)

**Comment by urugator** [comment]
The problem is not ref, but the fact that `observer` uses *PureRenderMixin*.  Therefore passed props (`data`) are compared only shallowly - the modified `t` is ignored and update does not occur.

**Comment by dangerousdan** [comment]
Okay, got it, thanks. 
It seems like I missed a few key points in the docs.

So my `@observer` was doing nothing then, as there were no observables used in the render function.
