### ISSUE TITLE
Is it possible to track nonexisting properties?

### ISSUE THREAD

**Issue by luco** [mobxjs/mobx-react#331]
Let's give an example. I have a observable map:

`const data = observable.map({});`

And I want to dinamically add values to it and and track its changes. Is it possible?
Thanks

**Comment by mattruby** [comment]
https://jsfiddle.net/gh/get/library/pure/mattruby/mobx-examples/tree/master/mobx-standalone/40-map

**Comment by luco** [comment]
Can I replace the entire stats with a object and it still being observable?

**Comment by mattruby** [comment]
See https://mobx.js.org/refguide/map.html there's replace and merge. I think you should start there.

**Comment by luco** [comment]
I'm really struggling here. 

This is my code:

`
var data = observable({
  inset: observable.map({})
});

class TestAction {
 @action change(value, key) {
    var currentStats = data.inset.toJS();
    _.set(currentStats, key, value);
    data.inset.replace(currentStats);
   }

  getValue(key) {
    var currentStats = data.inset.toJS();
    _.set(currentStats, key, 'test');
    data.inset.replace(currentStats);
    autorun(() => {
        console.log(data.inset);
    });
  }

}

`

I'm getting a maximum stack here.

**Comment by mattruby** [comment]
Try to re create your issue using codesandbox.io. I'll try to look at it
later today.

**Comment by luco** [comment]
I got it.

```
getValue(key) { 
    autorun(() => {
    });
    var currentStats = data.inset.toJS();
    var v = _.get(currentStats, key);
    return v;
  }
```


Question: Can I simply call `autorun()` without params? When I do, it gives me error.

**Comment by mattruby** [comment]
I think you're using autorun all wrong. I'm still not sure what you're
trying to do. If you're firing up an autorun in a get value for some
reason, at least call the dispose on the previous autorun. Cut a small
codesandbox.io example, that should make things much more clear.

**Comment by mweststrate** [comment]
@luco I saw you asked a few quite basic questions and made proposed complicated solutions that showed you didn't grasp the mobx basics yet. 

Note that mobx is extensively documented on http://mobx.js.org. Use it to your advantage to make yourself comfortable with mobx. Or if you want a more structured walk-trough, follow the [free egghead tutorial](https://egghead.io/courses/manage-complex-state-in-react-apps-with-mobx) or follow one of the many other tutorials [here](https://github.com/mobxjs/awesome-mobx#tutorials). 

That should answer most of your questions on how to get started with mobx and help you to adopt the reactive mental model behind.

**Comment by luco** [comment]
@mweststrate Thanks a lot. I'm gonna take a look.

@mattruby It seems that my render method on gets re-rendered when I use an `autorun`. What I'm trying to achieve is tracking nonexisting object properties. For that, Im using an observable.map, as defined this way:

```
var data = observable({
  inset: observable.map({})
});
```

The `getValue` action simply returns my data.inset values for the path specified. But it's only returning the updated values when I run an `autorun`.

```
@action change(value, key) {
    var currentStats = data.inset.toJS();
    _.set(currentStats, key, value);
    data.inset.replace(currentStats);
}

getValue(key) { 
    autorun(() => {
      //console.log(data.inset);
    });
    var currentStats = data.inset.toJS();
    var v = _.get(currentStats, key);
    return v;
  }
```

These actions takes effect on here:

```<Input label={'Street'} value={addReport.getValue('data.location.street')} onChange={(data) => addReport.change(data, 'data.location.street')}/>```

**Comment by luco** [comment]
@mattruby Sure. Thanks.

**Comment by luco** [comment]
@mweststrate I read a bit on the resources you pointed, and modified and reduced my code considerably. I'm declaring my `observable.map` this way:

`var data = observable.map({});`

And when I want to change the values, i'm using this function:

```
@action change(value, key) {
    _.set(data, key, value);
    autorun(() => {
      console.log(value);
    });
}

@action getValue(key) { 
    return _.get(data, key);
  }

```

As I can see, without `autorun`, my o`bservable.map` doesn't react to changes. Is this right?

**Comment by mweststrate** [comment]
No, and also, you create on the fly autoruns and never clean them up inside
`change`. It does not belong there. What makes you conclude that the
observable map doesn't react? Maps never react to changes, they are just
data structures. Things can react to maps, but maps themselves don't react
to anything. I also don get what `_` is in your code. As your map is called
`data`. Why not just `data.set(key, value)` ?

Op vr 22 sep. 2017 om 16:51 schreef Lucas Veiga <notifications@github.com>:
