### ISSUE TITLE
get a warning when use "observer" with Component that extends React.PureComponent

### ISSUE THREAD

**Issue by wanglam** [mobxjs/mobx-react#333]
Today, I upgrade React Version to 16.0, then I get a warning like this:
```txt
Warning: Foo has a method called shouldComponentUpdate(). shouldComponentUpdate should not be used when extending React.PureComponent. Please extend React.Component if shouldComponentUpdate is used.
```
My component code is:
```typescript
import { observer } from "mobx-react";

@observer
export default class Foo extends React.PureComponent<{}, {}> {
    render(){
        return <div>bar</div>
    }
}

``` 

When I change React.PureComponent To React.Component, this warning gone.
Should I always use React.Component when I use observer?

**Comment by mweststrate** [comment]
Correct. (For now at least :-)). observer roughly implements PureComponent,
but not literally :-D.

Op wo 27 sep. 2017 om 05:54 schreef wanglam <notifications@github.com>:

**Comment by wanglam** [comment]
Ok, thanks.
I will close this issue.

**Comment by mweststrate** [comment]
Why do you want a PureComponent to be observer as well?

Op di 7 nov. 2017 om 11:40 schreef Adam Stankiewicz <
notifications@github.com>:

**Comment by sheerun** [comment]
not exactly, I want to create new component from PureComponent by attaching an observer to it. observer doesn't change the state of components, it passes props from above, totally fine.

something like: ConnectedComponent = observe(PureComponent)

**Comment by mt-micky** [comment]
Ideally, I would like to only use PureComponent in my app. Why this restriction?

**Comment by jalooc** [comment]
Same here, PureComponent should be a default choice for stateful components.

**Comment by mweststrate** [comment]
The restriction is there just because nobody took the effort to create
tests and to remove it. Probably because it doesn't matter much in the end
because the bindings will practically turn the component into a pure one.

In other words, if someone wants to dive into this, a PR is welcome.

Op do 26 jul. 2018 20:56 schreef jalooc <notifications@github.com>:
