### ISSUE TITLE
Clean up test suite

### ISSUE THREAD

**Issue by mweststrate** [mobxjs/mobx-react#335]
The test suite is quit a mess, especially around tooling. The current tooling relies on browserify / tape-run. But this stack is quite uncommon and it becomes increasingly hard to keep all the tools working :)

Things to improve:

* [ ] Use async / await / delay where applicable
* [ ] Migrate to jest
* [ ] Run most or all tests in a stub dom
* [ ] Re-enable error tests (see also https://github.com/facebook/react/issues/10474#issuecomment-332812890 and onward)

PR's are welcome!

**Comment by Sunshine168** [comment]
hi, i try working migrate the test suite to jest  i will pr soon

**Comment by mweststrate** [comment]
Completed by @Sunshine168 trough #388. Thanks a lot!
