### ISSUE TITLE
@inject not working with react 16?

### ISSUE THREAD

**Issue by scriby** [mobxjs/mobx-react#336]
I'm getting an error on the first use of @inject in my app. Here's the error:

```
Uncaught TypeError: Cannot set property wrappedComponent of function Injector() {
            var _ref;

            var _temp, _this, _ret;

            classCallCheck(th...<omitted>... } which has only a getter
```
The error is getting triggered from this line:

https://github.com/mobxjs/mobx-react/blob/70718a389854e27fc9e0834fed1be182587221fe/src/inject.js#L78

I'm using mobx-react 4.3.3.

**Comment by mweststrate** [comment]
Can you plz share your component definition as well?

Op do 28 sep. 2017 om 21:01 schreef scriby <notifications@github.com>:

**Comment by scriby** [comment]
I see the issue. My component defined a static getter called `wrappedComponent`, which was added so typescript could understand the type of the inner component in unit tests.
