### ISSUE TITLE
What is the reason to use @observable in the TodoModel.js

### ISSUE THREAD

**Issue by changLiuUNSW** [mobxjs/mobx-react#338]
I am a little bit confused about example project [mobx-react-todomvc](https://github.com/mobxjs/mobx-react-todomvc)
Here is ```TodoModel.js```:
https://github.com/mobxjs/mobx-react-todomvc/blob/master/src/models/TodoModel.js
```
import {observable} from 'mobx';

export default class TodoModel {
	store;
	id;
	@observable title;
	@observable completed;

	constructor(store, id, title, completed) {
		this.store = store;
		this.id = id;
		this.title = title;
		this.completed = completed;
	}

	toggle() {
		this.completed = !this.completed;
	}

	destroy() {
		this.store.todos.remove(this);
	}

	setTitle(title) {
		this.title = title;
	}

	toJS() {
		return {
			id: this.id,
			title: this.title,
			completed: this.completed
		};
	}

	static fromJS(store, object) {
		return new TodoModel(store, object.id, object.title, object.completed);
	}
}
```
I am new to Mobx, just want to know why we need use ```@observable``` inside model. 
I think they are redundant because we already use ```@observable``` inside ```TodoStore.js```.
```
export default class TodoStore {
	@observable todos = [];
......
```
If we remove ```@observable``` from the model, does the application still work?

**Comment by urugator** [comment]
Mobx doesn't autoconvert class instances, only plain objects (+ array, Set, Map). Compare:

`todoStore.todos.push({ title: "Title", completed: true })`
**observable copy** is pushed to `todos`

`todoStore.todos.push(new TodoModel())` 
TodoModel instance is **left as is** and pushed to `todos`

**Comment by changLiuUNSW** [comment]
@urugator Thanks.
What is the best practice to handle ```observable``` array without introducing ```observable```` to the model?

**Comment by urugator** [comment]
Not sure what you mean, can you be more specific?

**Comment by changLiuUNSW** [comment]
I mean how to make it work if I remove @observable from @TodoModel

**Comment by urugator** [comment]
Not sure why you want to do it, but some alternatives:

Don't make TodoModel observable and treat it as immutable.

Don't make state part of a TodoModel, but pass state to actions:
```javascript
toggle(state) {
	state.completed = !state.completed;
}
```

**Comment by mweststrate** [comment]
Closing this issue. The question so far sounds to me like "how can I write a component class without extending from `React.Component`"?. If you don't want to use the api, don't use the tool :wink:
