### ISSUE TITLE
inject stores overwriting passed props

### ISSUE THREAD

**Issue by rossipedia** [mobxjs/mobx-react#339]
Per the [README](https://github.com/mobxjs/mobx-react/blob/master/README.md#provider-and-inject):

> * If a component asks for a store and receives a store via a property with the same name, the property takes precedence. Use this to your advantage when testing!

This does not seem to be true in my testing:

``` js
import * as React from 'react';
import { render } from 'react-dom';
import { inject, Provider, observer } from 'mobx-react';
import { observable } from 'mobx';

const injector = inject(() => ({ a: 'store a' }));

const C = injector(
  observer(props => <pre>{JSON.stringify(props, undefined, 2)}</pre>)
);

const B = () => <C a="prop a" b="prop b" />;

render(<B />, document.getElementById('root'));
```

This will output:

```json
{
  "a": "store a",
  "b": "prop b"
}
```

[(sandbox)](https://codesandbox.io/s/v6lm5ovwv7)

There's even a test that verifies this behavior:

https://github.com/mobxjs/mobx-react/blob/70718a389854e27fc9e0834fed1be182587221fe/test/inject.js#L137-L151

The documentation seems to lead one to believe that a passed prop will take precedence over an `inject`ed store, but it looks like the opposite is happening. 

What's the intended behavior here? Which needs to be changed, code or docs?

**Comment by urugator** [comment]
[The behavior differs if `<Provider>` is used](https://codesandbox.io/s/82p3n54n7j)

[Here is relevant discussion](https://github.com/mobxjs/mobx-react/issues/80).

**Comment by rossipedia** [comment]
To be clear, it doesn't seem to do with `Provider` at all, rather how one invokes `inject()`:

```js
import * as React from 'react';
import { render } from 'react-dom';
import { inject, Provider, observer } from 'mobx-react';
import { observable } from 'mobx';

const DumpProps = observer(props => (
  <pre>{JSON.stringify(props, undefined, 2)}</pre>
));

const InjectedSelector = inject(({ a }) => ({ a }))(DumpProps);
const InjectedNamed = inject('a')(DumpProps);

const App = () => (
  <Provider a="provided">
    <div>
      <InjectedSelector a="prop a" b="prop b" />
      <InjectedNamed a="prop a" b="prop b" />
    </div>
  </Provider>
);

render(<App />, document.getElementById('root'));
```

output:
```
{
  "a": "provided",
  "b": "prop b"
}
{
  "a": "prop a",
  "b": "prop b"
}
```

https://codesandbox.io/s/6j70j3ypyn

**Comment by urugator** [comment]
Yea, I edited the commnet to make it more clear just seconds after... If you gimme a sec I will try to explain what I think is the reasoning behind the current behavior

**Comment by urugator** [comment]
The "function based dynamic inject" was introduced to provide full control over props.
So for example, you can provide "navBgColor" via Provider, but your Nav component can remain independent on context and accept just prop "bgColor".
In general you are able to "intercept" the passed props and completely customize the parent-context-child props relation.
This is useful, but also annonying in cases, where you want to "customize/re-map" only a subset of props.
Therefore the merging was introduced, instead of the need to provide full list of new props.
So the "overwriting/customizing behavior" is basically the idea behind the mapper function from the beginning and merging was introduced only to make this "overwriting/customizing" less verbose.

**Comment by urugator** [comment]
Btw notice that props are passed to inject function as well, so you can still use them as default, while still having the ability to rewrite them.

**Comment by rossipedia** [comment]
Great explanation, thanks. I think I agree with the reasoning there, even though the behavior is a bit surprising. I'll see about submitting a PR for clarifying the docs a bit more on this point.

**Comment by rossipedia** [comment]
Hmmm looks like there already is a blurb about that in the docs. I'm going to think about it a bit to see if the wording there needs to improve, or if it really is just a lack of RTFM on my part. Either way, thanks for clearing things up @urugator!
