### ISSUE TITLE
failed with jest SyntaxError: Unexpected token import

### ISSUE THREAD

**Issue by iwater** [mobxjs/mobx-react#341]
jest@21.2.1
mobx-react@4.3.3
react-native@0.48.4

  ● Test suite failed to run

    /Users/iwater/Codes/JiJiaApp/new4/JiJiaApp/node_modules/mobx-react/native.js:1
    ({"Object.<anonymous>":function(module,exports,require,__dirname,__filename,global,jest){import { Atom, Reaction, extras, isObservableArray, isObservableMap, isObservableObject, spy, untracked } from 'mobx';
                                                                                             ^^^^^^
    
    SyntaxError: Unexpected token import
      
      at ScriptTransformer._transformAndBuildScript (node_modules/jest-runtime/build/script_transformer.js:305:17)

**Comment by mweststrate** [comment]
Seems like ES6 source code transpilation is not set up (correctly) in your project. How to set up transpilation can be found in the jest documentation.
