### ISSUE TITLE
JSX element type 'Provider' is not a constructor function for JSX elements.

### ISSUE THREAD

**Issue by chenshuai2144** [mobxjs/mobx-react#342]
The problem  upgrade the version to react16。Whether it is related to the official description of the document

JSX element type 'Provider' is not a constructor function for JSX elements.
  Types of property 'render' are incompatible.
    Type '() => string | number | false | Element | Element[]' is not assignable to type '{ (): string | number | false | Element | Element[]; (): false | Element; }'.
      Type 'string | number | false | Element | Element[]' is not assignable to type 'false | Element'.
        Type 'string' is not assignable to type 'false | Element'.

**Comment by farzer** [comment]
meet the same problem

**Comment by chenshuai2144** [comment]
react16 caused by the problem 。
can install  @tyeps/react 15.6

**Comment by farzer** [comment]
I fixed the problem by updating
- "@types/react": "^16.0.10",
- "@types/react-dom": "^16.0.1",
- "mobx": "^3.2.2",
- "mobx-react": "^4.3.3",
- "react-dom": "^16.0.0",
- "react": "^16.0.0"

although I don't know which one is the key of this problem

**Comment by chenshuai2144** [comment]
@ types/react: "^16.0.10"  is the key of this problem

**Comment by mweststrate** [comment]
As far as I can see this behaves correctly in the test suite. Could you try to reproduce it in our test suite? Maybe the compiler settings are different? See this [test](https://github.com/mobxjs/mobx-react/blob/a5c675bb5be8297be82fb61d82745f3000d77e30/test/ts/compile-ts.tsx#L85) (use `npm run test:ts` to run it)

**Comment by chenshuai2144** [comment]
![image](https://user-images.githubusercontent.com/8186664/31980621-553eb6ba-b980-11e7-8ff0-d1d09914df70.png)
![image](https://user-images.githubusercontent.com/8186664/31980626-5b7b34c2-b980-11e7-8f90-a42b4272075c.png)
Unfortunately！

i use @types/react@16.0.18

**Comment by mweststrate** [comment]
Closing here, assuming the official types will be / are fixed? Feel free to reopen if it ain't in the near future

**Comment by timjroberts-inty** [comment]
I'm getting a similar error with the latest @types/react types, however, rather than `Types of property 'render' are incompatible.`, I'm getting the error `Property 'render' is missing in type 'Provider'.`.

The full error is:

```text
/.../web-components/UIStateMachine.tsx(20,13): error TS2605: JSX element type 'Provider' is not a constructor function for JSX elements.
Property 'render' is missing in type 'Provider'.
/.../UIStateMachine.tsx(20,13): error TS2607: JSX element class does not support attributes because it does not have a 'props' property.
```

I'm just using `Provider` like this:

```typescript
public render(): JSX.Element {
    let children = this.props.children as React.ReactNode[];

    children = children && children.length > 0
        ? children
        : [<UIStateMachineView />];

    return (
        <Provider stateTransitionable={this.props.stateTransitionable}>
            { children }
        </Provider>
    );
}
```

**Comment by qborreda** [comment]
Same here, using React 16.2 and Redux 3.7.2
```
ERROR in [at-loader] ./src/index.tsx:54:13
    TS2605: JSX element type 'Provider' is not a constructor function for JSX elements.
  Types of property 'render' are incompatible.
    Type '() => ReactNode' is not assignable to type '{ (): Element | null; (): ReactNode; (): ReactNode; (): ReactNode; }'.
      Type 'ReactNode' is not assignable to type 'Element | null'.
        Type 'undefined' is not assignable to type 'Element | null'.
```
and then others ..

**Comment by timjroberts-inty** [comment]
As a work around, I've created my own Component that simply wraps the `Provider`:

```typescript
/**
 * A component that hoists its 'props' into context that can be injected into child components
 * via the MobX 'inject' decorator or function.
 * 
 * This component is an adapter for the MobX 'Provider' component and is a workaround because of the typing
 * issue reported in https://github.com/mobxjs/mobx-react/issues/342.
 */
export class InjectionProvider extends React.Component<any> {
    /**
     * Renders the [[InjectionProvider]] into the component tree.
     * 
     * [[InjectionProvider#render]] simply creates a MobX 'Provider' component and supplies it with the
     * current props.
     */
    public render(): JSX.Element {
        const stores = { ...this.props };

        // Remove the 'children' because we don't want that passed around via React's Context mechanism
        delete stores.children;

        return React.createElement(Provider as any, stores, this.props.children);
    }
}
```

**Comment by Ishirak** [comment]
If anyone is still experiencing this issue and is using `yarn`, make sure that you clear `node_modules` and delete `yarn.lock`. That fixed it for me. 

```
rm -rf node_modules && rm yarn.lock && yarn
```

It could be the same for NPM's `package-lock.json`, but I didn't test it.

See https://github.com/DefinitelyTyped/DefinitelyTyped/issues/21242 for details.
