### ISSUE TITLE
[question / bug | feature] multiple observer wraps

### ISSUE THREAD

**Issue by aretecode** [mobxjs/mobx-react#344]
https://github.com/mobxjs/mobx-react/blob/master/src/observer.js#L290 this check is done for provide

https://github.com/mobxjs/mobx-react/blob/master/src/observer.js#L324 this property is not checked before wrapping the class again, is this a bug or a feature?

**Comment by mweststrate** [comment]
Ehh.. feature I guess. Can't remember asking anyone for it before :). You basically want to warn against `observer(observer(Component))` correct?

**Comment by ItamarShDev** [comment]
is it still relevant?

**Comment by mweststrate** [comment]
probably not
