### ISSUE TITLE
observer: props is, itself, observable when only each prop should be

### ISSUE THREAD

**Issue by adamabeshouse** [mobxjs/mobx-react#347]
EDITED because original query was not coherent:

[In this jsfiddle](https://jsfiddle.net/xpd2remq/1/), there's a toy model of a scenario I'm facing: I have multiple subcomponents in `render` which I want to not re-compute unnecessarily, and I was hoping to be able to use the observable nature of props together with the Observer tag to implement this. However, because [its not the properties of props which are tracked, but the reference to `this.props` itself](https://github.com/mobxjs/mobx-react/blob/master/src/observer.js#L143), both subcomponents will recompute every time any props change, regardless of which props are actually used in each subcomponent.

The class in the fiddle is duplicated below:
```
@observer 
class Person extends Component<{ firstName:string, lastName:string }, {}> {
    constructor(props) {
        super(props);
        this.getFirstName = ()=>{
            return (<span>{this.props.firstName}</span>);
        };
        this.getLastName = ()=>{
            return (<span>{this.props.lastName}</span>);
        };
    }
    render() {
        return (
          <div>
              <Observer>{this.getFirstName}</Observer>
              <Observer>{this.getLastName}</Observer>
          </div>
        );
    }
}
```

There are two possible solutions to regain the desired functionality:
(1) Use components (decorated with `@observer`), and pass in desired data through props, in order to regain the shallow comparison functionality in `shouldComponentUpdate`, e.g.
```
@observer
class FirstName extends Component<{name:string},{}>{

...

<FirstName name={this.props.firstName}/>
```

(2) Wrap all prop accesses in `@computed`'s, e.g.
```
 this.getFirstName = ()=>{
            return (<span>{this.firstName}</span>);
};


@computed get firstName() {
    return this.props.firstName;
}
``` 

Both are more unwieldy than if the props object were observable, thus each prop tracked individually, instead of the reference to the props object.

**Comment by mweststrate** [comment]
Could you setup a fiddle / sandbox demonstrating this issue?

Op do 19 okt. 2017 om 00:35 schreef Adam Abeshouse <notifications@github.com

**Comment by adamabeshouse** [comment]
Sorry my original post was actually wrong, I should have made a fiddle first.

https://jsfiddle.net/qqsow33p/5/ shows the situation. In fact in both cases I included above, it would be rendered twice. The only time it would only be rendered once is if the <span> in render() is wrapped by an <Observer>, AND the prop access is wrapped by a @computed.

**Comment by adamabeshouse** [comment]
@mweststrate sorry for the sloppy initial query, please see my updated post above.

**Comment by urugator** [comment]
The problem is that props object is immutable and the whole props object is replaced when new props arrives. The props are not updated individually, therefore making them observable is useless.
The relevant discussion can be found [here](https://github.com/mobxjs/mobx-react/issues/124)

**Comment by adamabeshouse** [comment]
@urugator that's a good point. However, even so, it could be accomplished using getters and setters.

**Comment by adamabeshouse** [comment]
It could also be accomplished by having an observable props object which is, key by key, updated w the values of the immutable object coming in.

**Comment by urugator** [comment]
Prop keys are dynamic, keys of observable object not...

**Comment by adamabeshouse** [comment]
This can be handled with observable map :)

**Comment by urugator** [comment]
How? You need to translate `this.props.something` into `this._propsMap.get("something")`

**Comment by adamabeshouse** [comment]
`observable.map` wouldn't be necessary. The code could look something like this:

```
const valueHolder = {};
const getSetProxy = {};

Object.defineProperty(this, "props", {
    configurable: true,
    enumerable: true,
    get: function() {
        return getSetProxy;
    },
    set: function set(v) {
        for (const key of Object.keys(v)) {
            if (!getSetProxy.hasOwnProperty(key)) {
                installKey(getSetProxy, valueHolder, key);
            }
            getSetProxy[key] = v[key];
        }
    }
});

function installKey(getSetProxy, valueHolder, key) {
    const atom = new Atom("reactive props."+key);
    Object.defineProperty(getSetProxy, key, {
        configurable: true,
        enumerable: true,
        get: function() {
            atom.reportObserved();
            return valueHolder[key];
        },
        set: function set(v) {
            if (valueHolder[key] !== v) {
                valueHolder[key] = v;
                atom.reportChanged();
            }
        }
    });
}
```

**Comment by urugator** [comment]
You need to "subscribe" also for prop keys, which were used in render, but weren't passed by props yet. These keys should be observed, but are not installed yet, therefore the subscription won't happen.

**Comment by adamabeshouse** [comment]
Good catch. I wasn't aware of this functionality but it looks like you can also define getters with computed property names. So here's an updated (simpler) version that handles the issue you raised:

```
const atoms = {};
const valueHolder = {};

function getAtom(atoms, key) {
    atoms[key] = atoms[key] || new Atom("reactive props."+key);
    return atoms[key];
}

Object.defineProperty(this, "props", {
    configurable: true,
    enumerable: true,
    get [key]() {
        getAtom(atoms, key).reportObserved();
        return valueHolder[key];
    },
    set: function set(v) {
        for (const key of Object.keys(v)) {
            if (valueHolder[key] !== v[key]) {
                valueHolder[key] = v[key];
                getAtom(atoms, key).reportChanged();
            }
        }
    }
});
```

**Comment by urugator** [comment]
> getters with computed property names

Computed prop name is not a param passed to function. It simply means that you can do this:
```javascript
let propName = a ? "a" : "b";
const o = { 
  get [propName]() {....} // propName must be defined here
}
```
The Proxies are the only way to do this.

**Comment by adamabeshouse** [comment]
@urugator ah my mistake. Yes Proxy seems to be what I'm looking for. I think it's clear that would be possible with not much change to the code I've written above.

**Comment by urugator** [comment]
Unfortunately, we can't use Proxy currently.

Note that what you do is not a typical or recommeded usage.
You should not pass primitive values (string/reference/etc), but observable objects and dereference them as late as possible (when the values are actually needed).
That way you will not only prevent unnecessary re-render of subcomponent, but also the parent component (or any intermediate component), which re-renders unnecessarily as well.
The `@observer` is usually completely useless if your component does not accept any observable object (like in your example) - making props observable is not the point of `@observer`.
The standard (React) way to achieve the desired behavior is to make your subcomponents `extends React.PureComponent` (or implement `shouldComponentUpdate` if required).

Which doesn't mean that it can't be useful in some situations...

**Comment by adamabeshouse** [comment]
That makes sense, thanks for your responses.
