### ISSUE TITLE
Create react app and mobx combination issue (Unexpected character '')

### ISSUE THREAD

**Issue by ghost** [mobxjs/mobx-react#348]
I am not sure in which repo to open this issue but I would really appreciate help as I 
have problem just compiling a simple create-react-app project with mobx. (been trying for few hours
already!).

1)I created a project using create-react-app
2)installed mobx and mobx-react
3)I also ejected the project to allow decorators as described here:
https://swizec.com/blog/mobx-with-create-react-app/swizec/7158
4) But here is the error I am getting:
https://ibb.co/hUfYgR 
5) I only have two source files in code, both can be viewed here:
index.js: http://codepad.org/VpNYEsaF
todostore.js: http://codepad.org/qqafksot

Help greatly appreciated!

(PS the source code is copied from Mobx so unlikely the issue is with .js files).
I have a suspicion it can be lint related but can't fix it by myself......

**Comment by mweststrate** [comment]
Could you create a repository others could check out?

**Comment by mweststrate** [comment]
Also note that ejecting is not necessarily, create-react-app-rewired or custom-react-scripts are packages that can be used to further customize CRA without ejecting, like using decorators.

**Comment by FreyaNoir** [comment]
I have the same error now like mentioned above. Did you find a solution?
