### ISSUE TITLE
Typescript error for inject function - Type '{}' has no property 'storeA' and no string index signature.

### ISSUE THREAD

**Issue by avivr** [mobxjs/mobx-react#353]
Hey,

Since version 4.3.4 we are getting these errors:

> ERROR in ./src/components/Totals/Total.tsx
> (30,25): error TS2459: Type '{}' has no property 'cartStore' and no string index signature.
> 
> ERROR in ./src/components/Totals/Total.tsx
> (30,36): error TS2459: Type '{}' has no property 'siteStore' and no string index signature.

The code is:
```
export default inject(({cartStore, siteStore}) => ({siteStore, cart: cartStore.cart}))
  (translate(null, {wait: true})
  (Total));
```

I this is related to this change:
https://github.com/mobxjs/mobx-react/commit/f478d5e77203c8ad4516bfe17ab6e2c5ec422466

It doesn't happen in 4.3.3

Please advise

**Comment by mweststrate** [comment]
Could you include the component (type) definition?

Op vr 3 nov. 2017 om 13:49 schreef Aviv Rosental <notifications@github.com>:

**Comment by mweststrate** [comment]
also, what is the line 30 referred to?

Op vr 3 nov. 2017 om 14:32 schreef Michel Weststrate <mweststrate@gmail.com

**Comment by avivr** [comment]
line 30 is the export statement i pasted here.

component definition:

```
interface CompProps extends InjectedTranslateProps {
  storeA?: StoreAModel;
  storeB?: StoreBModel;
}

const Comp = observer( ({storeA, storeB, t}: CompProps) => (
  <div>....</div>
)
```

* InjectedTranslateProps is from react-i18next

**Comment by mweststrate** [comment]
@avivr could you check if things change if in the `node_modules/mobx-react/index.d.ts` you change 

`export type IStoresToProps<S extends IValueMap = {}, P extends IValueMap = {}, I extends IValueMap = {}, C extends IValueMap = {}> = (stores:S, nextProps: P, context: C) => I`

to

`export type IStoresToProps = (stores:any, nextProps: any, context: any) => any`

Also, note that the behavior how TS infers types can differ based in whether you have `implicitAny` enabled or not

**Comment by avivr** [comment]
Changing to:

`export type IStoresToProps = (stores:any, nextProps: any, context: any) => any
`
doesn't produce errors.

also, i'm running with `"noImplicitAny": false`

**Comment by mweststrate** [comment]
yikes. Ok, will revert to the simpler definition. Would you mind creating a
PR with a similar test case in the typescript tests?

Op vr 3 nov. 2017 om 22:45 schreef Aviv Rosental <notifications@github.com>:

**Comment by romabelka** [comment]
added test for this case https://github.com/mobxjs/mobx-react/pull/355

**Comment by kingdaro** [comment]
I just ran into this issue myself. Here're the relevant typing definitions:

```ts
export type IStoresToProps<S extends IValueMap = {}, P extends IValueMap = {}, I extends IValueMap = {}, C extends IValueMap = {}> = (stores:S, nextProps: P, context: C) => I

export function inject(
    fn: IStoresToProps
): <T extends IReactComponent>(target: T) => T & IWrappedComponent<T>
```

Here, the `inject` function has a parameter `fn` of type `IStoresToProps`, however defining the type this way will automatically set each default generic type in `IStoresToProps` to `{}`, since it's being used in a vacuum without any parameters given to it.

This would be the correct way to type the injection function:
```ts
export function inject<S, P, I, C>(
    fn: IStoresToProps<S, P, I, C>
): <T extends IReactComponent>(target: T) => T & IWrappedComponent<T>
```
I've tested it, and it does seem to solve the error described by OP.

**Comment by mweststrate** [comment]
@kingdaro confirmed, that fixes the issue. Thanks for finding out! Will release asap
