### ISSUE TITLE
Using static contextTypes is confusing

### ISSUE THREAD

**Issue by richtera** [mobxjs/mobx-react#354]
normally having a class like
```javascript
class SomeComponent extends Component {
   static contextTypes = {
     router: PropTypes.object.isRequired
   }
   render() {
     return <div>Something</div>
   }
}
```
works normally but trying to use @inject and @observable on it will no longer work. I see that instead of contextTypes using SomeComponent.wrappedComponent.contextTypes = { } works but it doesn't seem very good style. Is there no way to pickup the fact that there was a static contextType on the class about to wrapped?

**Comment by mweststrate** [comment]
Yeah I think it should be possible to mix in. Feel free to PR. Although
note that in edge cases it can lead to very subtle bugs when not using the
`static` keyword:

@inject class SomeComponent extends Component {

}

SomeComponent.contextTypes = { somethign } // break inject context types






Op za 4 nov. 2017 om 02:14 schreef Andreas Richter <notifications@github.com

**Comment by mweststrate** [comment]
Closing, since `contextTypes` will disappear anyway
