### ISSUE TITLE
Clarification in doc: Don't copy observables properties and store them locally

### ISSUE THREAD

**Issue by ghost** [mobxjs/mobx-react#360]
It has been a while I am trying to understand what the section "Don't copy observables properties and store them locally" on https://mobx.js.org/best/pitfalls.html tries to say.
I would like to submit a request to expand that section in documentation and explain it in a more elaborate way (for people less experienced with mobx); or maybe someone can clarify it here.

e.g. does what is written there apply also in the case when the `name `property refers to a object?

Also I have seen in example of mobx making copy of the props e.g.
```

@observer
class TodoList extends React.Component {
  render() {
    const store = this.props.store; // makes a copy of reference
    return (
      <div>
        { store.report }
        <ul>
        { store.todos.map(
          (todo, idx) => <TodoView todo={ todo } key={ idx } />
        ) }
        </ul>
        { store.pendingRequests > 0 ? <marquee>Loading...</marquee> : null }
        <button onClick={ this.onNewTodo }>New Todo</button>
....
```

Why is this case allowed and the one I mentioned in the beginning of this post (from docs), not?

**Comment by mweststrate** [comment]
Because `store` in the above example is not _stored_ locally, the reference is only kept during the time of the `render`, during which it can't change anyway. So in the next render it is again picked from the props.
