### ISSUE TITLE
[Question] How do you test, a component that has child components that use injection?

### ISSUE THREAD

**Issue by boshdmg** [mobxjs/mobx-react#366]
When we have components like this:

```
const ParentComponent = () => {
	return (
		<div>
			 <ChildComponent />
		</div>
	);
};
```

```
@inject('injectedThing')
@observer class ChildComponent extends Component {
	render() {
		return (
			<div>
				//stuff
			</div>
		);
	}
}
```

How do you do an integration style test with them? aka test multiple components together?

When we try something like this with enzymes mount :

```
describe('when blah balh',() => {	
	let wrappedComponent = mount(<Provider><ParentComponent/></Provider>);
})
```

We get this error:

>  Invariant Violation: Element type is invalid: expected a string (for built-in components) or a class/function (for composite components) but got: object. Check the render method of `WrapperComponent`.

**Comment by urugator** [comment]
https://github.com/mobxjs/mobx-react/issues/315

**Comment by mweststrate** [comment]
Closing as duplicate
