### ISSUE TITLE
mobx-react or mobx-react/native in react native what is the difference?

### ISSUE THREAD

**Issue by khomyakov42** [mobxjs/mobx-react#367]

**Comment by mweststrate** [comment]
mobx-react/native doesn't expose the devtool api's which require
interaction with the DOM

Op do 23 nov. 2017 om 11:05 schreef Sergey Khomyakov <
notifications@github.com>:

**Comment by khomyakov42** [comment]
it can as that affect performance

**Comment by mweststrate** [comment]
Sorry, I don't get the question
