### ISSUE TITLE
Alternative pattern to setState callback?

### ISSUE THREAD

**Issue by jmca** [mobxjs/mobx-react#369]
I'm in the midst of complex animations and transitions. React's `setState` supplies the callback that guarantees the DOM to be updated. Since mobx doesn't have a post re-render callback, what is a common pattern to use?

The only three viable solutions I came up with are:
- `setTimeout`, I'm not confident in the reliability of this in most use cases
- `componentDidUpdate` conditional triggers based on instance variables, but this gets messy and breaks the flow of animation instructions
- Basic "nextRenderQueue" instance variable that's an array of functions (self-rolled quasi-callback) that's executed/emptied in `componentDidUpdate`. This works in my situation but seems sort of hacky.

I looked through SO, mobx repo, and mobx-react repo, but I can't seem to find an agreed upon solution.

**Comment by mweststrate** [comment]
For animations I would go for using `mobxUtils.now('frame')` (an observable
that produces the current time on every available requirestAnimationFrame)
in your rendering and interpolate. But with componentDidUpdate it should be
possible to achieve it as well indeed.

Op za 2 dec. 2017 om 03:38 schreef Justin Abene <notifications@github.com>:

**Comment by jmca** [comment]
@mweststrate With my current scenario I'm mainly dealing with GSAP, so I don't need to tap into`requestAnimationFrame` yet. Mostly it's `onComplete` GSAP handlers in sequences. There's a lot of situations where DOM elements are added/removed mid-animation chain via `isVisible...` observables. Moving things into `componentDidUpdate` breaks that logic chain, but also adds other logic to figure out where/when to resume or what not to animate since `componentDidUpdate` will fire for numerous reasons unrelated to animation.

**Comment by mweststrate** [comment]
The problem is not entirely clear without example of what you are trying to achieve, but it is not possible in the Mobx model to attach callback about when something has rendered beyond componentDidUpdate. Mobx-react relies on the internal mechanism in React to batch and schedule renders, and doesn't keep track of whether and when something is rendered but relies on the eventual consistency of the rendering instead.
