### ISSUE TITLE
React events are not firing using SSR

### ISSUE THREAD

**Issue by etiennemtl** [mobxjs/mobx-react#370]
Hi,

I'm not 100% sure if I should ask this issue here or in the Reactjs.Net project, but here is the current situation.

I'm using Reactjs.Net in my project with SSR (server side rendering). I wanted to add this wonderful librairy (mobx) into my project, has one of page container is really becoming overly complicated. I've been able to render my components by providing an initial state, the issue is when the client code is being executed, events do bind correctly, but are never fired. Here is my setup:

**server.js**
````
var mobxReact = require('mobx-react');
mobxReact.useStaticRendering(true);
var Components = require('expose-loader?Components!./components');
````

**client.js**
````
var Components = require('expose-loader?Components!./components');
````

**Store.js**
````
import { observable } from 'mobx'

export default class Store {
  @observable metadata;
  @observable aggregations;
  @observable context;
  @observable filters;

  static fromJS(object) {
    const store = new Store();
    store.metadata = object.metadata;
    store.context = object.context;
    store.filters = object.filters;
    store.aggregations = object.aggregations;
    return store;
  }
}
````

**app.js**
````
import React, { PureComponent } from 'react'
import { Provider, useStaticRendering } from 'mobx-react'
import DevTool from 'mobx-react-devtools'

import SearchContainer from './SearchContainer'
import Store from './store/Store';

const App = (props) => (
  <Provider store={Store.fromJS(props)}>
    <div>
      <DevTool />
      <SearchContainer />
    </div>
  </Provider>
)

export default App
````

** SearchContainer.js**
````
import { Component } from 'react'
import { observer } from 'mobx-react'

@observer
export default class SearchContainer extends Component {
  handle = (e) => {
    alert(e);
  }

  render() {
    return (
      <div>
        <button onClick={this.handle}>Alert</button>
      </div>
    )
  }
}

````
As you can see my initial state is provided by Reactjs.net from the `App` props.
If i remove the observer decorator on `SearchContainer`, events are fired correctly (`onClick={this.handle}`). I'm not sure if it's the way I initialize my store or if I missed something in the documentation.

Thanks.

**Comment by etiennemtl** [comment]
Ok so when importing `observer` from `mobx-react/custom` the events are working. I don't quite understand this behaviour. Any explanation would be appreciated.

**Comment by mweststrate** [comment]
`observer` doens't interact with events so it shouldn't really relate. Is the issue sever or client side?  Do you see any warnings or errors in the log?

In other words, please provide a small reproduction. I have no clue what React.net is, but if it ain't the normal DOM based react, then probably the custom bindings should be used indeed.

**Comment by mweststrate** [comment]
Closed for a lack of information
