### ISSUE TITLE
Alternative to using `componentWillReact` with `setState`?

### ISSUE THREAD

**Issue by elie222** [mobxjs/mobx-react#371]
Is there an alternative to using `componentWillReact` with `setState`?

We just updated to the latest version of this package and componentWillReact now gets run on setState too, so we end up getting into an infinite loop.

Is there an easy way around this? Or a way to avoid this?

**Comment by mweststrate** [comment]
Can you describe your use case / problem?

Op di 5 dec. 2017 om 20:24 schreef Eliezer <notifications@github.com>:

**Comment by elie222** [comment]
We're updating the mobx store with a list of players and then setting it as the state for a container component in order to render the list of these players in the child component.

The code got a little messy trying to hack our way around not using Apollo Client for hundreds of documents since it had performance issues.

This is legacy code I'm not fully familiar with however.

**Comment by elie222** [comment]
I see `Date.now()` is being set as a state item, so that's going to lead to an infinite loop very easily

**Comment by elie222** [comment]
Figured out a solution for now. The code continues to look incredibly hacky. I just avoid setting state when it hasn't changed.

**Comment by ihaichao** [comment]
I also ran into this problem.
When I run `setState` in `componentWillReact ` , It will get into a infinite loop.
