### ISSUE TITLE
How to avoid forceUpdate current component and its children?

### ISSUE THREAD

**Issue by acrazing** [mobxjs/mobx-react#372]
For example:

```ts
@observer
class Parent extends Component {
  render() {
    return <Child/>
  }
}

@observer
class Child extends Component {
  render() {
    return <div/>
  }
}
```

How to avoid calling `forceUpdate` in `Child` component if its relative store updated i `Parent` component? Currently I can only find the way to avoid updating the current component by use `shouldComponentUpdate`.

**Comment by mweststrate** [comment]
Sorry the question is completely unclear to me. Please state questions in
terms of observed and expected behavior

**Comment by mweststrate** [comment]
Closed for a lack of information
