### ISSUE TITLE
[Question/Problem] Second injected module is "undefined"

### ISSUE THREAD

**Issue by simeon-petrov-5** [mobxjs/mobx-react#373]
Hello guys,
I have a problem - I'm injecting two components and I have all the access to the first one, but everything from the second one is "undefind" and can't wrap my head around why. 
the idea of the app is to have a sidebar section (gray color) and when you click on the link/name of the note to load the info in the NoteField section (lightblue color). Here's a photo of Chrome with the console after clicking on a note
![image](https://user-images.githubusercontent.com/15708352/33653846-f5f40f4e-da76-11e7-8223-30844922cee5.png)

This is the main "holder module"
![image](https://user-images.githubusercontent.com/15708352/33653637-56bf3c5a-da76-11e7-8fd3-c1e15a0525c8.png)

Here we make a note and deal with add/del
![image](https://user-images.githubusercontent.com/15708352/33653688-82b7eb04-da76-11e7-9c8b-b258c9f6ef25.png)

This is the NoteField - makes the component for reading/writing
![image](https://user-images.githubusercontent.com/15708352/33653752-acf74ee6-da76-11e7-8f08-222c97f1d603.png)

And here's the problematic part - the sidebar.. where on click has to change the values in the NoteField. I work with Note.jsx without any problem, but with NoteField.jsx is the problem. Tried with @inject('NoteEngine', "NoteField") if using inject two times was causing the issue, but no success..
![image](https://user-images.githubusercontent.com/15708352/33653772-bc15aeb8-da76-11e7-8436-723d1252c50a.png)

An additional question:
Where we render the link we have onClick={() => this.handleClick(index)}> Why should I have this "() =>" arrow function at all? I'm binding this at the function with the special syntax, but when I remove this part from the link the "handleClick" is firing only once at the beginning (without me clicking) and then on click it doesn't work.

I'm sorry if it's a stupid/basic question, but I just can't see what's wrong.

**Comment by urugator** [comment]
injected `NoteField` is a `React.Component` (class) not an instance...
