### ISSUE TITLE
'react-dom' does not contain an export named 'unstable_batchedUpdates'.

### ISSUE THREAD

**Issue by JZLeung** [mobxjs/mobx-react#374]
when i try to build my project, it doesn't work:
```bash
./node_modules/mobx-react/index.module.js
972:11-34 'react-dom' does not contain an export named 'unstable_batchedUpdates'.
```

my project dependencies:
```json
{
"dependencies": {
    "mobx": "^3.4.0",
    "mobx-react": "^4.3.5",
    "mockjs": "^1.0.1-beta3",
    "node-sass-chokidar": "^0.0.3",
    "npm-run-all": "^4.1.2",
    "react": "^16.1.1",
    "react-dom": "^16.1.1",
    "react-scripts": "1.0.17"
  }
}
```

**Comment by linonetwo** [comment]
Can't build now!

**Comment by mweststrate** [comment]
The release notes of react (
https://github.com/facebook/react/blob/master/CHANGELOG.md) don't make any
mention about these api's having been removed or renamed. Something else
might be wrong in your setup. Are using a not officially released version
of React? Please provide a setup reproducing the problem.

Op di 16 jan. 2018 om 13:38 schreef lin onetwo <notifications@github.com>:

**Comment by linonetwo** [comment]
I got to know.

It's due to ```config = rewirePreact(config, env);``` in ```react-app-rewired```. Preact don't have ```unstable_batchedUpdates``` yet.

**Comment by mweststrate** [comment]
Ah, not that there are separate mobx preact bindings, which you should use
when using preact. https://github.com/mobxjs/mobx-preact

Op ma 29 jan. 2018 om 06:47 schreef lin onetwo <notifications@github.com>:
