### ISSUE TITLE
Better type definition for component returned by observer

### ISSUE THREAD

**Issue by ascariandrea** [mobxjs/mobx-react#375]
Hi guys,
I wanted to write a more type-safe `inject` function like discussed here: https://github.com/mobxjs/mobx-react/issues/256#issuecomment-335301953.

This definition works well for me, but I wanted to make even stricter, ensuring the passed component is wrapped by an `observer`.
The problem is that the `observer` function doesn't change the type of the wrapped component, while it actually changes its structure.

Would you mind to define an `ObservedReactComponent` type or something similar?
I can work on this if you think it's a good idea.

Let me know!

**Comment by AlexGalays** [comment]
Same issue with @observable. It makes the decorator useless when using TS imo as I always have to use the function equivalent to benefit from the extended APIs of observable (arrays)

**Comment by ascariandrea** [comment]
Guys?

**Comment by mweststrate** [comment]
>  ensuring the passed component is wrapped by an observer.

The injected component is not necessarily an observer, there are many exeptions like:
1. Other HoCs in between
2. Not needing observer at all

**Comment by ascariandrea** [comment]
@mweststrate  maybe I expressed myself in a wrong way.
To ensure the component passed to `inject` function is wrapped by an `observer` is solved by the type I've defined.
But to achieve that, I need `mobx-react` to return a different type when the component is wrapped by an `observer`.

**Comment by mweststrate** [comment]
But why do you want to ensure that it is an observer?

Op vr 26 jan. 2018 14:48 schreef Andrea Ascari <notifications@github.com>:

**Comment by ascariandrea** [comment]
Cause I'm injecting only containers, so they need to be wrapped in `observer`.

**Comment by mweststrate** [comment]
If you are using `observer` as function, you can simply create your own wrapper, that adds intersects the type with some nominal type. If you use it as decorator; decorators cannot influence the type of the thing they are put on, so in that case you cannot really fix that.
