### ISSUE TITLE
undefined is not an object (evaluating '_react.PropTypes.object')

### ISSUE THREAD

**Issue by sumesh1993** [mobxjs/mobx-react#382]
Getting the above error. Searched in my project directory for "'_react.PropTypes.object". It was being used mobx-react folder only.

What might be the issue ? Any kind of help is appreciated.

I am using
 "react": "16.0.0",
 "react-native": "0.51.0",

**Comment by mweststrate** [comment]
React propTypes are used nowhere in the mobx-react sources. Please specify
the issue a bit further. Which version, in which file did you find it etc...

Op ma 25 dec. 2017 om 12:24 schreef sumesh1993 <notifications@github.com>:

**Comment by mswokk** [comment]
I get the same error from mobx-react/native.js after I upgrade react-native 0.44.0 to 0.51.0.
Getting this error because of React.PropTypes has moved into a different package since React v15.5

I solved this error in my project as a workaround.
1. install latest `prop-types`, `mobx` and `mobx-react` in your project.
2. Add followings before using mobx (ex. Head of index.js)
```
import React from 'react';
import PropTypes from 'prop-types';

React.PropTypes = PropTypes;
```

This is a just temporal workaround.
I'm waiting for an update on this issue.

**Comment by akshgods** [comment]
same issue undefined is not an object (evaluating '_react.PropTypes.object') 

package json

{
  "name": "txmpp",
  "version": "0.1.0",
  "private": true,
  "devDependencies": {
    "babel-preset-react-native-stage-0": "^1.0.1",
    "jest": "^23.4.2",
    "jest-react-native": "^18.0.0",
    "react-test-renderer": "16.3.1"
  },
  "scripts": {
    "start": "react-native start",
    "android": "react-native run-android",
    "ios": "react-native run-ios",
    "test": "jest"
  },
  "jest": {
    "preset": "react-native"
  },
  "dependencies": {
    "autobind": "^1.0.3",
    "mobx": "^5.0.3",
    "mobx-react": "^5.2.3",
    "prop-types": "^15.6.2",
    "react": "16.3.1",
    "react-native": "~0.55.2",
    "react-native-button": "^2.3.0",
    "react-native-invertible-scroll-view": "^1.1.1",
    "react-native-mobx": "^0.3.1",
    "react-native-router-flux": "^4.0.0-beta.42",
    "react-native-xmpp": "^1.0.3"
  }
}


issue on line mobx-react\native.js : 887

**Comment by mweststrate** [comment]
Please refrain from commenting on closed issues, but open a new one, including reproduction instead
