### ISSUE TITLE
use enzyme to test wrappedComponent will change the context

### ISSUE THREAD

**Issue by xiaosunJessica** [mobxjs/mobx-react#390]
TodoList component
    @inject(allStore => ({
       todoStore: allStore.todoStore,
     }))
    @observer
    export default class TodoList extends React.Component {
        render() {
    return (
      <div>
        <ul>
          {this.props.todoStore.todos.map(todo => {
            return <Todo todo={todo} key={todo.id} />
          })}
        </ul>
        Tasks left: {this.props.todoStore.unfinishedTodoCount}
      </div>
    )
  }
    }

todoList.test.js

describe('<TodoList />', () => {
  it('should render the todolist', () => {
    const todoStore = [{title: '', todos: []}]
    const component = shallow(<TodoList.wrappedComponent todoStore={todoStore} />, {context: todoStore});
    expect(component.find('ul').length).to.be.equal(1);
  })
})

TypeError: Cannot read property 'map' of undefined。the props todoStore can not inject to the todoList,

**Comment by mweststrate** [comment]
Can you please format questions properly? 

The additional context passed to `shallow` should not be necessary

**Comment by mweststrate** [comment]
Closed for a lack of information
