### ISSUE TITLE
Route component cannot render but Link component can work, Why???

### ISSUE THREAD

**Issue by xiaosunJessica** [mobxjs/mobx-react#392]
index.js
  import React from "react";
import { render } from "react-dom";
import { BrowserRouter as Router } from "react-router-dom";
import createBrowserHistory from "history/createBrowserHistory";
import { RouterStore, syncHistoryWithStore } from 'mobx-react-router';
import { Provider } from 'mobx-react';
import DevTools from "mobx-react-devtools";

import TodoListModel from "./models/TodoListModel";
import TodoModel from "./models/TodoModel";
import App from './components/app';

const store = new TodoListModel();

render(
  <Provider store={store}>
    <Router>
      <App />
    </Router>
  </Provider>
  ,
  document.getElementById("root")
);

app.js
import React, { Component } from 'react';
import { inject, observer } from "mobx-react";
import { withRouter, Route, Link, } from 'react-router';

import Header from './header';
import SideBar from './side-bar';

import Test from './test/index1';
import Test2 from './test/index2';
import Test3 from './test/index3';

class NoMatch extends Component {
  render() {
    return (
      <div>
        no match!
      </div>
    );
  }
}

@inject("store")
@observer
class App extends Component {
  render() {
    return (
      <div className="warpper">
        <Header />
        <SideBar />
        <Link to="/test">test</Link>
        123456
        <Link to="/">home</Link>
        <Switch>
          <Route path="/test" render={props =>{
            return <div>test</div>
          }
          } />
          <Route path="/test2" component={withRouter(Test2)} />
          <Route path="/test3" exact component={Test3} />
        </Switch>
      </div>
    )
  }
}

export default withRouter(App)

when I input the location 'localhost://8080/test' in browser, The Test Component can not match,But When I click the test to link to 'localhost://8080/test', It's working

**Comment by mweststrate** [comment]
Please file a better issue. Explain why this is reported in this repository
in the first place, secondly; if it belongs here, please make a minimal
reproduction that shows the problem in a codesandbox for example

Op wo 17 jan. 2018 om 11:29 schreef xiaosunJessica <notifications@github.com

**Comment by mweststrate** [comment]
Closed for a lack of information
