### ISSUE TITLE
Pull request to update README.md regarding React lifecycle methods

### ISSUE THREAD

**Issue by JaxCavalera** [mobxjs/mobx-react#393]
As per discussed with @mweststrate on gitter, I have put together a new feature which consists of the following code change on a new local branch that I would like to create a pull request for.

Please advise if I am to request permissions to push my local branch to the remote and create the PR that way or if I will need to wait for a new branch to be created on my behalf.

Thanks

Change README.md (line 227)
```markdown
* If updates to an observable store are not triggering `render()`, make sure you are using Class methods for React lifecycle hooks such as `componentWillMount() {}`, using `componentWillMount = () => {}` will create a property on the instance and cause conflicts with mobx-react. See [mobx-react #195](https://github.com/mobxjs/mobx-react/issues/195) for more details.
```

**Comment by mweststrate** [comment]
@JaxCavalera just navigate to the Readme file (https://github.com/mobxjs/mobx-react/blob/master/README.md), press the small edit pencil, and github will guide you through the rest of the process
