### ISSUE TITLE
React v16 error boundaries and error handling within observer

### ISSUE THREAD

**Issue by ynejati** [mobxjs/mobx-react#394]
I'm looking for a solution or possible workaround for using React Fiber error boundaries with Mobx-React observer. Currently I am receiving the error `[mobx] Encountered an uncaught exception that was thrown by a reaction or observer component`.

```
observer(class WrapperComponent extends React.Component {

   componentDidCatch() {
    this.setState({ hasError: true })
    // handle error
    }

    render() {
        const errorStyle = { border: '2px dashed red'}

        if(this.state.hasError) {
             return (
                 <div style={errorStyle}>
                      // commenting out the line below will render without error
                     <FallbackComponent  {...this.props} />
                 </div>
              )
         } else {
              return (
                  <Component {...this.props} />
              )
         }
```

I have dug around the mobx-react internals in order to understand how mobx-react handles errors and to derive some sort of solution, possibly using the global error handler `onError()`, but have only fallen short.

From our brief conversation on Mobx's Gitter, you mentioned that it might already be possible to have these errors rethrown.

Any help or suggestions would be greatly appreciated. 

I am more than happy to contribute if pointed in the right direction.
 
Thank you!

**Comment by urugator** [comment]
Try `this.render.$mobx.onError(error => { throw error })` in `componentDidMount`, not sure what will happen though.

**Comment by ynejati** [comment]
Thank you for the response.  Sorry for getting back to you so late.  I did try hacking at it in componentDidMount, like you've suggested, and other places and unfortunately it did not work.  Any other ideas?

Response to EDIT: You make a very valid point regarding the error state and rendering logic I've provided.  I think ideally I would like to render a transparent overlay of some sort on top of the children in their pre-error'd state.  Obviously, this would require me to save a snapshot of the children as DOM at render and then apply this snapshot as the fallback ui.  The components can be pretty complex and may result in performance hits, so I haven't decided yet if it's worth it to do so.  (I have edited my initial comment to clarify upon the issue in question.)

**Comment by urugator** [comment]
> require me to save a snapshot of the children as DOM

Hmm, can't we just re-render the wrapper, while preventing the update of errornous children? 
Something like:
```javascript
class UpdateOverride extends React.Component {
  shouldComponentUpdate(nextProps) {
    return nextProps.update;
  }
  render() {
    this.props.render();
  }
}

class Wrapper extends React.Component {
  render() {
    if (this.state.hasError) {
      return (
        <div style={errorStyle}>
          <UpdateOverride
            update={false}
            render={() => <Component {...this.props} />}
          />
        </div>  
      )
    } else {
      return (        
        <UpdateOverride
          update={true}
          render={() => <Component {...this.props} />}
        />        
      )
    }      
  }
}
```

**Comment by mweststrate** [comment]
Closing for now, there seems no real consensus that this is actually needed yet
