### ISSUE TITLE
mechanism to manually subscribe component to observables?

### ISSUE THREAD

**Issue by opensrcken** [mobxjs/mobx-react#395]
I'm a newcomer to mobx, and the "magical" elements are a roadblock to adoption. Would it be difficult to manually set up observable subscriptions for a component? I have a deadline and would really love to not have to learn to dance around the implicit rules of mobx in order to get reactions to work.

**Comment by urugator** [comment]
Automatic dependency tracking (subscription management) is basically the whole idea behind MobX, these are not "implicit rules" it is how MobX is designed. If that's a roadblock I don't see a point in adopting MobX.
You can sort of "manually subscribe" by simulating normal MobX subscription, but you would end up dancing around MobX and you would still have to understand how MobX subscription works.
