### ISSUE TITLE
Remove reliance on React's deprecated _rootNodeID

### ISSUE THREAD

**Issue by flakmonkey** [mobxjs/mobx-react#397]
```
//index.module.js
...
686: var rootNodeID = this._reactInternalInstance && this._reactInternalInstance._rootNodeID;
...
732: var initialRender = function initialRender() {
            reaction = new Reaction(initialName + "#" + rootNodeID + ".render()", function () {
...
```

As you can see, mobx-react attempt to capture React's _rootNodeID property in order to provide a friendly name for a Reaction. I believe React has deprecated this property starting in v0.15 and removed it completely in v16. I noticed this issue when setting up mobx-react-devtools, as it prints this value to the console.

**Comment by mweststrate** [comment]
Addressed in 4.4.0
