### ISSUE TITLE
React Native Component Re-constructing on store state changed

### ISSUE THREAD

**Issue by 3210jr** [mobxjs/mobx-react#399]
Hey guys,

Not sure whether this is a mobx issue of its a mobx-react issue.

I have a store that is listening to firebase. Whenever a value in firebase changes, the whole component gets constructed again, running all the code in the constructor. How can I prevent it?

```
import { observer, inject } from 'mobx-react/native';

@inject('store', 'store1')
@observer
export default class AppComponent extends Component {
```

react-native: 0.5.1
react:  16.0.0
mobx: 3.4.1
mobx-react: 4.3.5

How can I stop that from happening? its resetting my store and forcing everything to rerender!

Thanks.

**Comment by mweststrate** [comment]
@3210jr sorry, but that is no way to file an issue. Please provide much more information and a small reproduction. It is not even clear for me why it would be incorrect that the component gets reconstructed, from the information you are providing here.

**Comment by 3210jr** [comment]
hey @mweststrate sorry about that. It turns out one of our interns thought it would be smart to customize the code in directly in the node modules. A fresh install of the package solved easily.

Thanks for your time, and I will for sure file better issues in the future.
