### ISSUE TITLE
Uncaught TypeError: Assignment to constant variable. Only in electron release

### ISSUE THREAD

**Issue by barbalex** [mobxjs/mobx-react#400]
This happens when the start page loads.

In dev mode everything works fine. Also: last time I built the app everything worked fine in dev mode and in release. Since then I have only updated some dependencies, including mobx and mobx-react.

This is an electron app: https://github.com/barbalex/kapla3.

This is the output in the console: 
<img width="627" alt="error" src="https://user-images.githubusercontent.com/669783/35440729-f516795c-02a0-11e8-8dc9-5d7cfd3b5511.png">

The output mentions `The above error occurred in the <NavbarStammdatenNav>`. Here is that component: https://github.com/barbalex/kapla3/blob/30d330b297755c155232f032770f2e40c0724ac4/app/components/Navbar/StammdatenNav.js

I am using:
- mobx: 3.4.1
- mobx-react: 4.3.5

**Comment by mweststrate** [comment]
Did you verify whether down-grading mobx / mobx-react removes the item again? Where does the debugger end if you make it break on (caught) exception?

**Comment by barbalex** [comment]
> Did you verify whether down-grading mobx / mobx-react removes the item again?

Yes, I tried using mobx v3.31 and mobx-react v4.3.3. Same error.

But I just realized: I updated mobx and mobx-react a few weeks ago. I have since once built a new release that _did_ work.

So could it be that other updates caused mobx-react to error?

I have updated:

devDependencies:
-  electron: 1.7.10 > 1.7.11
- electron-builder: 19.52.1 > 19.55.2

dependencies:
- exceljs: 0.8.1 > 0.8.2
- react-bootstrap: 0.32.0 > 0.32.1
- react-dropzone: 4.2.3 > 4.2.7
- react-virtualized: 9.16.1 > 9.18.0
- source-map-support: 0.5.0 > 0.5.3
- styled-components: 2.3.0 > 3.0.2

**Comment by barbalex** [comment]
> Where does the debugger end if you make it break on (caught) exception?

Don't know how to do that. Is it possible in electron?

**Comment by barbalex** [comment]
I now added an error boundary. The weird thing is that everything else seems to work. Only the navbar has this error.

**Comment by barbalex** [comment]
And I am 100% sure that nothing changed in that code

**Comment by barbalex** [comment]
I decided to try changing how values are passed in that component. Just in case... 

Not passing the `table` value to the `stammdatenTitle` function solved the issue.

I am completely baffled.

This is the refactored version of the component: https://github.com/barbalex/kapla3/blob/30d330b297755c155232f032770f2e40c0724ac4/app/components/Navbar/StammdatenNav.js

**Comment by mweststrate** [comment]
Note that in the initial screenshot the error didn't came from mobx but from one of your own components

**Comment by barbalex** [comment]
Sorry if I misinterpreted that and wasted your time.

Thanks for your great help. And for the incredible tools you develop.

**Comment by mweststrate** [comment]
N.p.!

Op vr 26 jan. 2018 16:00 schreef Alexander Gabriel <notifications@github.com
