### ISSUE TITLE
Add example for rootStore + inject

### ISSUE THREAD

**Issue by developer-lindner** [mobxjs/mobx-react#406]
Just had a look at https://mobx.js.org/best/store.html and was interested in using the rootStore concept. 

`<Provider rootStore={new RootStore()}><App /></Provider>`

Unfortunately it's not clear to me how this works with inject, because it doesn't actually.

```
interface IComponentProps {
    // injected props
    userStore?: UserStore;
}

@inject("userStore")
```

how does it work than? Using a function inside the inject?

**Comment by mweststrate** [comment]
> because it doesn't actually

Is quite vague. Please elaborate by providing expected behavior, observed
behavior, and enough code so that others can understand your setup.

Op wo 31 jan. 2018 om 09:26 schreef developer-lindner <
notifications@github.com>:

**Comment by developer-lindner** [comment]
Usually one would do something like this:

```
const stores = {
    storeA,
    storeB,
    storeC,
    storeD,
    storeE
};

<Provider {...stores}>
    <App />
</Provider>


interface IComponentProps {
    // injected props
    storeA?: StoreA;
}

@inject("storeA")
```

But by using:

`<Provider rootStore={new RootStore()}><App /></Provider>`

inject doesn't know about the other stores?! So how can i inject parts of the rootStore?

`@inject("storeA", "storeB")`

won't work...

**Comment by mweststrate** [comment]
You can either still Provide rootstore.storeA and rootstore.storeB
separately, or always inject rootStore, whatever you prefer. (Probably the
first). The point of the root store is that the stores themselves know how
to find each other. How they are provided / injected in the component is
orthogonal to that.

Op wo 31 jan. 2018 om 10:11 schreef developer-lindner <
notifications@github.com>:

**Comment by developer-lindner** [comment]
This seems to work:

```
const dependencies = { rootStore: new RootStore(data) };
const element = document.getElementById("someIdOfContainer");

if (dependencies.rootStore) {
    ReactDOM.render(
        <Provider {...dependencies.rootStore}>
            <App />
        </Provider>
        , element
    );
} else {
    ReactDOM.render(
        <Provider {...dependencies}>
            <App />
        </Provider>
        , element
    );
}
```

What do you think ?

**Comment by mweststrate** [comment]
I don't get the if / else? In your code the else branch is never taken?

Op wo 31 jan. 2018 om 10:39 schreef developer-lindner <
notifications@github.com>:

**Comment by developer-lindner** [comment]
The else branch is just old way of doing it in some older components (which gets obsolete as soon as all entry points are using rootStore concept).

**Comment by mweststrate** [comment]
ok, yeah than this should work indeed

Op wo 31 jan. 2018 om 10:44 schreef developer-lindner <
notifications@github.com>:
