### ISSUE TITLE
Bundle names: using mobx-react instead of index

### ISSUE THREAD

**Issue by AviVahl** [mobxjs/mobx-react#408]
This one is not a bug, but more of an annoyance.

When using `mobx-react` from a public npm-based CDN (e.g. https://unpkg.com/mobx-react), it is harder to distinguish its network requests, since the bundles are named `index.*.js`

Both Chrome and Firefox dev tools show only `index.js` in the corresponding row of the network log. Even in expanded mode, searching the url for the package name takes more time.

Would it be possible to change the bundle names to `mobx-react.*.js`?
(this issue is also true for `mobx-react-devtools`)

**Comment by mweststrate** [comment]
That can be done indeed. But not for the next major as that would basically
be a breaking change for people loading from CDN :)

Op wo 31 jan. 2018 om 17:48 schreef Avi Vahl <notifications@github.com>:

**Comment by cmorrow-tg** [comment]
Are there any special contributing guidelines to follow if I wanted to work on this issue?

**Comment by mweststrate** [comment]
No not specifically, but it is already solved in the v6 branch :)

**Comment by cmorrow-tg** [comment]
Ha, I see that now; my bad. Thanks though.

**Comment by mweststrate** [comment]
N.p, and thanks for being willing to pick this up :)

**Comment by FredyC** [comment]
Changed in V6, closing :)

https://unpkg.com/mobx-react@6.0.3/dist/
