### ISSUE TITLE
Allow inject specify an observable according literal object path.

### ISSUE THREAD

**Issue by zheeeng** [mobxjs/mobx-react#409]
Assuming we have a rootStore which contains other stores and is injected into Provider:

```
class Root {
  bookStore = new Book()
  foodStore = new Food()
}

<Provider rootStore={new Root()} />
```

wish we cloud access bookStore by this way:

```
@inject('rootStore.bookStore')
@observer
class Component extends React.Component {
   render () {

    }
}
```

**Comment by mweststrate** [comment]
Fur such cases you can use the function variant of `inject`, see: https://github.com/mobxjs/mobx-react#customizing-inject
