### ISSUE TITLE
Update README with babel plugin ordering

### ISSUE THREAD

**Issue by mgcrea** [mobxjs/mobx-react#41]
Had a hard time today figuring out why a very simple mobx react sandbox app did not work.

Turned out that the issue was due to the order of babel plugins in my `.babelrc`.

`transform-decorators-legacy` has to appear first in the list, otherwise it will break with at least either `transform-function-bind` or `transform-class-properties` plugins if they defined before it, with the wrong orders, observables are not triggered at all.

Would be great to update README to clarify this.

**Comment by mweststrate** [comment]
wow, never noticed that the order is relevant. thanks for reporting, I'll update it

**Comment by mgcrea** [comment]
Maybe that's something that mobx could catch? (like if the class property decorator gets a function instead of an object/array ref), would be great to add a console warning if it can be safely catchable.

**Comment by mweststrate** [comment]
good one, I'm gonna check whether it is detectable

**Comment by SamHH** [comment]
Thank you so much for posting this, I've been tearing my hair out trying to understand why nothing was working.
