### ISSUE TITLE
Discussion about sCU()=false problem

### ISSUE THREAD

**Issue by Gvozd** [mobxjs/mobx-react#414]
See #411 

>Also from a timeline perspective I am not sure whether this intermediate step adds value, as we can just move to the new React context api in a next major, and simply support changing stores without any further problems.

At now peerDependencies is `"react": "^0.13.0 || ^0.14.0 || ^15.0.0 || ^16.0.0"`
If only the new context is to be maintained, then users will have to forcefully update.
Alternatively, you can support both context API, and if used the old (and save the sCU problem), show a warning, and the recommend to update the react

> I have some doubts about this PR, as, if I interpret the change correctly, with the above change it is still not possible to inject new things in a component if there is a false returning `sCU in one of it's parents. (One could argue that the warning should probably be an error)

In my PR
`<Provider> -> <sCU()=false> -> <Injector>` - worked correctly, and Injector updated
`<sCU()=false> -> <Provider> -> <Injector>` - not working, because `<Provider>`(and his sibling) not upate. But this is normal and expected behavior

You can test and compare this behavior with the new context API - there is the same situation
Also, as in my PR, if the Provider is in a bad sCU()=false, then the Consumer will not be updated, because the Provider itself has not updated
https://codesandbox.io/s/github/Gvozd/research-react-context

PS As it turned out, in my PR the problem of sCU is solved already in a known way
https://github.com/reactjs/rfcs/blob/master/text/0002-new-version-of-context.md#shifts-complexity-to-user-space

**Comment by Gvozd** [comment]
@mweststrate, any news about this?

**Comment by mweststrate** [comment]
Eh..., what is the question part in the above enumeration :)?

**Comment by Gvozd** [comment]
I ask you to approve my PR #411 
For this I opened this issue to discuss the changes as you requested

**Comment by mweststrate** [comment]
The implementation seems correct, but I think there is at this point no need to further push this on, as there is a viable alternative to achieve this: React.createContext (or injecting mutable stores). For simplicity purposes I think it is clearer to keep Provider / inject to what it was: a light-weight dependency injection mechanism, not a mechanism to propage state changes. 

If this turns out an omission that many run into, we can definitely reconsider.
