### ISSUE TITLE
Using props on an <Observer> component

### ISSUE THREAD

**Issue by carlosagsmendes** [mobxjs/mobx-react#419]
Hi,

I have a very simple functional component where I'm using `inject` and `observer`:

```
const MobxFunctionalComponent = inject("store")(
  observer(({ store, title }) => (
    <div>
      {title} {Date.now()}
      &nbsp;{store.color}
    </div>
  ))
);
```

I'm trying to move away from the decorators and use the <Observer> component instead. But the `title` property is no longer working and the component is being re-rendered even when I don't update the `title` and `color` props:

```
const MobxFunctionalComponentObserver = () => (
  <Observer
    inject={(stores) => ({ store: stores.store })}
    render={props => (
      <div>
        {props.title} {Date.now()}
        &nbsp;{props.store.color}
      </div>
    )}
  />
)
```

I'm a newbie to react and mobx and must be missing something. Can you help? 

Here's the link to an online [example on CodeSandBox](https://codesandbox.io/s/k378jn3817)

**Comment by Sunshine168** [comment]
emmm  i feel sorry 
it is a bug because https://github.com/mobxjs/mobx-react/blob/master/src/observer.js#L360
i will fix it soon

**Comment by urugator** [comment]
Following works, but it's a bit confusing...
```javascript
const MobxFunctionalComponentObserver = props => ( // this is where "title" originally comes from
  <Observer
    inject={(stores) => ({ title: props.title, color: stores.store.color })} // inject provides "props" for "render" so we have to pass the "title" here
    render={props => ( // "props" returned from "inject"
      <div>
        {props.title} {Date.now()}
        &nbsp;{props.color}
      </div>
    )}
  />
);
```

**Comment by Sunshine168** [comment]
emm  confusion in mine new test suit  


```js
// test1
    test("use render with inject should be correct", async () => {
        const person  = mobx.observable({
            first:'hello',
            second:'world',
        })
        const Comp = () => (
            <div>
                <Observer
                    inject={['person']}
                    render={props => <span>{`${props.person.first} ${props.person.second}`}</span>}
                />
            </div>
        )
        const A = () => (
            <Provider person={person}>
                <Comp />
            </Provider>
        )
        await asyncReactDOMRender(<A />, testRoot)
        expect(testRoot.querySelector("span").innerHTML).toBe("hello world")
        person.first = 'hi'
        await sleepHelper(100)
        expect(testRoot.querySelector("span").innerHTML).toBe("hi world")
    })
   // test 2
    test("use children with inject should be correct", async () => {
        const person2  = mobx.observable({
            first:'hello',
            second:'world',
        })
        const Comp = () => (
            <div>
                <Observer inject={store => ({ first: store.person.first, second: store.person.second })}>
                    {props => <span>{`${props.first} ${props.second}`}</span>}
                </Observer>
            </div>
        )
        const A = () => (
            <Provider person={person2}>
                <Comp />
            </Provider>
        )
        await asyncReactDOMRender(<A />, testRoot)
        expect(testRoot.querySelector("span").innerHTML).toBe("hello world")
        person2.first = 'hi'
        expect(testRoot.querySelector("span").innerHTML).toBe("hi world")
    })
```
when using children with inject did not wrapper the observer ， it can work 
but using render with inject did not wrapper the observer, it did not work
[code](https://github.com/mobxjs/mobx-react/pull/420/files#diff-08f3e9ab539253c87ea111cc61c69e29L360)
```js
const InjectComponent = inject(observerInject)(component)

```
![image](https://user-images.githubusercontent.com/15126380/36074245-5f2fb2f2-0f78-11e8-8ee5-f8bce49dfdeb.png)

**Comment by carlosagsmendes** [comment]
Thanks @urugator, I've updated the example and now I can use the ´title´ property.

@Sunshine168 should I leave this open due to the bug of the component being re-rendered?

**Comment by urugator** [comment]
@Sunshine168 test 2 works because children doesn't react to observables (`props.person.first`) but to new props `props.first`, you have to make sure that both `render` and `inject` are reactive in both test cases

**Comment by Sunshine168** [comment]
@urugator  emm got it  person is observable but person.first not .
@carlosagsmendes  can you close this issue and open a new issue to describe your problem to avoid mine misleading comment

**Comment by carlosagsmendes** [comment]
Reopened the re-render issue on #423
