### ISSUE TITLE
Don't require react-dom

### ISSUE THREAD

**Issue by Kasu** [mobxjs/mobx-react#42]
I use a custom react renderer that is not targeting the DOM thus I don't have the `react-dom` package in my project at all. This ends up giving me this error:

```
ERROR in ./~/mobx-react/index.js
Module not found: Error: Cannot resolve module 'react-dom' in D:\Code\symphony\node_modules\mobx-react
 @ ./~/mobx-react/index.js 198:8-71
```

Looking at `mobx-react/index.js` it doesn't look like `react-dom` is critical. How about making the package optional and permanently disabling your developer tools unless you have react-dom available?

A future improvement could be to support devtools with an arbitrary react renderer.

**Comment by mweststrate** [comment]
Cool :) Could you check whether `import {observer} from "mobx-react/native"` works for you? In React Native the DOM isn't available either, so in the native build the dependency is stripped out. I think there is nothing React Native specific in there, so it might work out of the box in your case.

**Comment by Kasu** [comment]
That produces the same problem since it instead of `react-dom` requires `react-native`. Since I have a custom renderer, I have neither.

```
ERROR in ./~/mobx-react/native.js
Module not found: Error: Cannot resolve module 'react-native' in D:\Code\symphony\node_modules\mobx-react
 @ ./~/mobx-react/native.js 198:8-65
```

**Comment by mweststrate** [comment]
Ok, I'll setup a "mobx-react/no-dom" build in the next few days. In the
meantime you could try testing with all the ReactDOM stuff stripped out (if
you didn't do that already). Shouldn't be that much.

Op wo 27 apr. 2016 om 20:07 schreef Kasper Sandin <notifications@github.com

**Comment by Kasu** [comment]
What I did to work around it was to just add an empty module named "react-dom.js" to node_modules. After that mobx was able to run fine!

**Comment by mweststrate** [comment]
I just pushed a patch to master. Would you mind testing it by cloning this repo and after that, in your own repo, run `npm install <checkoutpath>`, and use the `mobx-react/custom` as import.

**Comment by Kasu** [comment]
It works fine! Thanks for the quick support!

I'm not a big fan of patches though, but that's a question for another issue :). GG~

**Comment by Niryo** [comment]
Can you explain in more details what should I do in order to eliminate this problem? 
Im getting:
`webpackHotDevClient.js:233 Error in ../test/~/mobx-react/index.js
Module not found: 'react-dom' in /Users/niryo/git/test/node_modules/mobx-react`

The error comes from this line:
` @ ../test/~/mobx-react/index.js 2:116-136`

I tried using: `import { observer } from 'mobx-react/custom'; `
but it doesn't work.

**Comment by mweststrate** [comment]
using /custom is the correct approach.After that your stacktraces should
mention `mobx-react/custom.js` not `index.js`. If that is still the case,
you are still referring to the wrong variation somehow

Op zo 3 sep. 2017 om 10:24 schreef Nir Yosef <notifications@github.com>:

**Comment by Niryo** [comment]
@mweststrate What is the actually difference between the different renderers?
Is it only for development purpose? what will be the implications of using mobx-react/custom.js? 
Im building a library that would be used from both react and react-native projects, and Im exposing mobx-react observer func. 
what is the suggested way to do this? exposing observer from mobx-react/custom?

**Comment by mweststrate** [comment]
From top of my head the main difference is dev tool integration, which uses
real dom nodes for highlighting. So custom should be safe in that case. But
you could asks advice to always use the standard, and set up a webpack
alias when targeting RN

**Comment by ProteanDev** [comment]
import { observer } from 'mobx-react/custom' Does work! Thanks! :)
