### ISSUE TITLE
Fyi, componentByNodeRegistery is misspelled

### ISSUE THREAD

**Issue by mattflix** [mobxjs/mobx-react#421]
The correct spelling is componentByNodeRegistry.

**Comment by aap82** [comment]
https://en.oxforddictionaries.com/definition/registery

**Comment by mweststrate** [comment]
Feel free to create a PR :). But note that it will be a breaking change so
we won't release it soon.

Op ma 12 feb. 2018 om 16:24 schreef amit p <notifications@github.com>:

**Comment by mattflix** [comment]
You could expose both, the correctly- and incorrectly-spelled (so it won't break anybody), but only document the correctly-spelled one.

**Comment by mweststrate** [comment]
Fixed, and will be part of next release
