### ISSUE TITLE
How to use observer in myself high order component

### ISSUE THREAD

**Issue by heqifang** [mobxjs/mobx-react#422]
Hi  

my customer want to use the API data to generate Dynamic table columns
so I use the high order component to add a new props to table page component (antd table props)

the code like:
```
HOCFactoryFactory(storeName) {
        return function HOCFactory(WrappedComponent) {
            class Enhancer extends WrappedComponent {
              
                render() {
                    const elementsTree = super.render();

                   let tableConfig= elementsTree.props[storeName].tableConfig;
      
                   //here  use the tableConfig generate the columns
                   //then I just need use the self-high order components in the page
                   //the antd table columns props would Dynamic generate
                   //customer can use config page change the server table config to change the page table
                    
                    let newProps = {};
                    if (elementsTree) {
                        newProps = {
                            columns: columns
                        }
                    }
                    const props = Object.assign({}, elementsTree.props, newProps);
                    return React.cloneElement(elementsTree, props, elementsTree.props.children);
                }
            }
            Enhancer.displayName = `HOC(${utils.getDisplayName(WrappedComponent)})`;
            return observer(Enhancer);
        }
    };
```
that is my high order components,
use like:
```
@utils.HOCFactoryFactory('myStore')
@inject('myStore') @observer
class myPageTable extends Component {
    componentDidMount() {
        this.props.myStore.loadDataAndConfig(params);
    };

    render() {....}
}
```

so the mobx-react can get the data rightly
but if I remove the observer in the self-HOC 
the elementsTree.props[storeName].tableConfig  would be empty in refresh
I think I use the Observable variable in the HOC so I should observer the HOC

Now it's just a warning of that -- 'You are trying to use 'observer' on a component that already has 'inject'. Please apply 'observer' before applying 'inject'';
as the page increases, there are more and more warnings
it may be like:   `observer(inject('myStore')(observer(myPageComponent))`

I need the high Order Component to generate Dynamic table columns, and the page have different render can write different table (like rowselection, page, and so on )
Whether it is the order of the exchange decorator or the removal of the observer, the configuration data can not reach the higher order component.

If it is used in this way, it will have an appellate warning;  So is the use of the above wrong? Do you have a better use
It's my trouble and I'm glad to get any advice.

**Comment by heqifang** [comment]
Hi
I read some code in the mobx-react

I set like self-HOC like:

```
class Enhancer extends WrappedComponent{}
Enhancer.displayName = `HOC(${utils.getDisplayName(WrappedComponent)})`;
Enhancer.isMobxInjector = false;
return observer(Enhancer);
```

the warning is disappear，  Data flow correct，
Is it right to use this?

**Comment by urugator** [comment]
I think you don't have to extend WrappedComponent:
```javascript
function HOCFactoryFactory(storeName) {
  return function HOCFactory(WrappedComponent) {
      class Enhancer extends React.Component { //<== don't extend Wrapped
        
          render() {
            const elementsTree = React.createElement(WrappedComponent, this.props); //<== render Wrapped

             let tableConfig= elementsTree.props[storeName].tableConfig;

             //here  use the tableConfig generate the columns
             //then I just need use the self-high order components in the page
             //the antd table columns props would Dynamic generate
             //customer can use config page change the server table config to change the page table
              
              let newProps = {};
              if (elementsTree) {
                  newProps = {
                      columns: columns
                  }
              }
              const props = Object.assign({}, elementsTree.props, newProps);
              return React.cloneElement(elementsTree, props, elementsTree.props.children);
          }
      }
      Enhancer.displayName = `HOC(${utils.getDisplayName(WrappedComponent)})`;
      return observer(Enhancer); //<== now it doesn't apply to Injector
  }
};
```
However I suggest to avoid manipulating rendered elements. Not exactly sure what the goal is, but there is probably cleaner solution. 
If you want to be able to customize rendering logic of individual table parts use render callbacks:
```javascript
const Cell = ({ cell }) => React.createElement("td", { className: "cell" },
  cell.content
);

const Row = ({ row, renderCell }) => React.createElement("tr", { className: "row" },
  row.cells.map(
    cell => renderCell(cell)
  )
);

const Table = ({ table, renderRow }) => React.createElement("table", { className: "table"},
  table.rows.map(
    row => renderRow(row)
  );
) 

// Now you can create custom tables by composing individual parts together (it can be done dynamically based on some config)
const MyTable = ({ table }) => React.createElement(Table, {
  table,
  renderRow: row => React.createElement(Row, {
    row,
    renderCell: cell => React.createElement(Cell, { cell }),
  })
})  
```

**Comment by heqifang** [comment]
hi @urugator 

happy new year

I test creating high - order components without reverse inheritance;

```
const elementsTree = React.createElement(WrappedComponent, this.props); //<== render Wrapped

let tableConfig= elementsTree.props[storeName].tableConfig;
```
 can not  get the tableConfig from the store too; (get from API save in the page store)

I'm not very clear about what you said cleaner solution；

i need the rendered elements to generate antd table, And now it's hard to remove antd table to create homemade table；

I'm going to try the context API provided by react 16.3. Is there a new way to get a cleaner solution？

**Comment by urugator** [comment]
> can not get the tableConfig from the store too

Since `Enhance` and `WrappedComponent` are now different components, you have to apply observer and inject to both independently (the advantage is they can have different depedencies), so following should do the trick I quess:
```javascript
return inject(storeName)(observer(Enhancer));
```
 
Or you could probably apply inject once again to Enhancer returned from factory 
```javascript
@inject('myStore') // injects to HOCFactoryFactory
@utils.HOCFactoryFactory // now parameterless
@inject('myStore') // injects to myPageTable
@observer
class myPageTable extends Component {}
``` 
> antd

Not familiar with antd, can't serve sry.

**Comment by heqifang** [comment]
OK , it work fine;

I understand that when I use reverse inheritance, The high - order component is the inheritance component of the page component

when i does not use reverse inheritance, I just need to use the high - order components like mobx-react in the general component

thanks your suggestion  and I will continue to think about a cleaner solution。
