### ISSUE TITLE
Question

### ISSUE THREAD

**Issue by OlekRia** [mobxjs/mobx-react#424]
Hello, Here is a code using mobx. It works properly and as expected.
https://github.com/OlekRia/rmso/blob/master/Rmso/Rmso.Web/ClientApp/pages/TodoList.tsx

But, instead of function renderTodoList() I would like to use a component <Checklist /> :
https://github.com/OlekRia/rmso/blob/master/Rmso/Rmso.Web/ClientApp/shared/CheckList.tsx

Unfortunately, my behavior's become totally wrong. And work only when I change filter field. No check box able to be clicked for example.

Help needed.

**Comment by urugator** [comment]
You have to use `@observer` on `CheckList` as well
