### ISSUE TITLE
Local Component State and getDerivedStateFromProps

### ISSUE THREAD

**Issue by bradenhs** [mobxjs/mobx-react#425]
React 16.3 will introduce a new static method called `getDerivedStateFromProps` which is meant to eventually replace `componentWillReceiveProps`.  I use mobx to manage local component state and sometimes changes in props translate to updating local component state as well. The new static method and deprecation of `componentWillReceiveProps` looks like it'll potentially break using mobx like this. Is there a better way to update local state in response to prop changes? Should this concern be raised with the react team? Any other thoughts?

**Comment by mweststrate** [comment]
@bradenhs could you set up a code sandbox that demonstrates how this could break / would lead to unexpected results?

**Comment by urugator** [comment]
@mweststrate `componentWillReceiveProps` allows state modifications, so you can call stadard `setState()` or modify mobx's state, which in turn can call `forceUpdate/setState`.
But `getDerivedStateFromProps` which is going to replace `componentWillReceiveProps` requires you to return new state instead of modifying it, therefore you can't modify mobx's state there (it may work, but mainly it doesn't make sense semantically).

```javascript
// Deprecated?
componentWillReceiveProps(props) {
  // state modifications are allowed
  // standard usage 
  this.setState({ a: props.a + this.state.a })
  // external state management (mobx)
  this.a += props.a; // mobx calls forceUpdate  
}
// Replaced by
getDerivedStateFromProps(props, state) {
  // instead of state modifications, new state should be returned
  // standard usage 
  return { a: props.a + state.a };
  // what about mobx? does it make sense and is it possible?
  this.a += props.a;
  // what should we return?
  return null; // null means no state modifications 
}
```

**Comment by bradenhs** [comment]
@urugator `getDerivedStateFromProps` is actually going to be a static method so you won't have access to the specific component instance. No access to `this` in `getDerivedStateFromProps` will make it so you can't update mobx's state even in a semantically nonsensical way. And @mweststrate I'll get a demonstration repo setup sometime today or tomorrow.

**Comment by urugator** [comment]
> you can't update mobx's state even in a semantically nonsensical way

Well, the observable can be passed (injected) as prop `props.store.a += props.a;` or exposed via `state` so I quess it's technically doable, but yea that's not relevant...

**Comment by bradenhs** [comment]
Just put together an example repo. Check it out here: https://github.com/bradenhs/getDerivedStateFromProps-mobx. How would you keep the local state managed by mobx in sync with the props without the `componentWillReceiveProps` method?

**Comment by urugator** [comment]
Possible workaround for example in repo (hope I am not missing something):
Idea is to allow internal `this._currentPage` being temporalily out of bounds and move the correction to derivations (render/computed) and actions:
```javascript
@observable _currentPage = 0;
 
@computed get totalPages() {
  return getTotalPages(this.props.rows.length) -1;
}

@computed get maxPage() {
  return this.totalPages - 1;
}

// Returns corrected _currentPage
@computed get currentPage() {     
  return this._currentPage > this.maxPage
    ? this.maxPage  
    : this._currentPage     
}

// Corrects internal _currentPage
@action goToNextPage() {
  this._currentPage = this.currentPage; // correct internal
  if (this._currentPage < this.maxPage) { // this check is missing in original?
    this._currentPage++;      
  }   
}
```

**Comment by bradenhs** [comment]
You’re work around seems very problem specific. I guess what I’m looking for is a general solution that can be applied when state needs to be updated in response to a change in props. React’s componentWillReceiveProps and it’s new getDerivedStateFromProps provides this general solution. Unfortunately, while componentWillReceiveProps integrates with MobX nicely, getDerivedStateFromProps does not.

**Comment by urugator** [comment]
Sure, that certainly wasn't meant as a solution for the issue.

**Comment by bradenhs** [comment]
No worries @urugator. Thanks for the input. @mweststrate do you see the issue?

**Comment by mweststrate** [comment]
Some observations so far:

1. This is not a technical issue with MobX (which doesn't rely on this hook), but not an uncommon pattern

Possible solutions that come to mine mind

1. Use componentDidUpdate (as suggested in https://github.com/facebook/react/issues/12310)
2. Use `setState` for the local component state
3. Since `state` and `props` are observables as well in `observer` components one can set up a reaction instead: `reaction(() => this.currentPage >= this.props.rows.length, outOfBounds => { if(outOfBounds) this.currentPage--})`. (Don't forget to clean up the reaction)

**Comment by bradenhs** [comment]
@mweststrate thanks for the suggested workarounds! I'll probably end up using option 2 or 3 when these changes are introduced in React. Are there any resources out yet that talk about how MobX will work with React's async rendering? From what I've read so far async rendering seems pretty closely coupled to `setState`. I don't know enough about React or `forceUpdate` to have a clear idea of what impact these changes will have on MobX.

**Comment by mnpenner** [comment]
I just ran into this issue. Some of my components aren't re-rendering. My setup is similar to [this](https://stackblitz.com/edit/react-eotdaf):

```js
import React, { Component } from 'react';
import { render } from 'react-dom';
import Hello from './Hello';
import './style.css';
import {observable} from 'mobx';
import {observer} from 'mobx-react';
import ReactDOM from 'react-dom';


@observer
class App extends React.Component {

    constructor(props) {
    	super(props);
        this.state = {bar: 999}
    }

	static getDerivedStateFromProps(nextProps, prevState) {
    	return {
        	bar: store.foo*nextProps.multiplier
        }
    }

	render() {
    	return <div>{this.state.bar}</div>
    }
}

const store = observable({
	foo: 1
})

setInterval(() => {
	++store.foo;
},1000)

ReactDOM.render(<App store={store} multiplier={3} />, document.getElementById('root'));
```

I'll see if I can work around it, but being able to use `getDerivedStateFromProps` sure would have been nice.

**Comment by urugator** [comment]
@mnpenner This is expected. Your props aren't changing (`store` and `multiplier` are same all the time), therefore App component isn't updated and `getDerivedStateFromProps` doesn't run. You need a parent component which actually subscribes for observable and sends new props, eg:

```javascript
ReactDOM.render(
  <Observer>{() => <App foo={store.foo} multiplier={3} />}</Observer>,
  document.getElementById('root')
);
```
Or you can use `computed` instead of `getDerivedStateFromProps`:
```javascript
@computed bar() {
   return this.props.store.foo * this.props.multiplier;
}
```
It will recompute on `store.foo` change or when new props are recieved (like `getDerivedStateFromProps`).

**Comment by guiguan** [comment]
@mweststrate should put this sentence in `mobx-react` documentation: `state` and `props` are observables as well in `observer` components :P

**Comment by mweststrate** [comment]
PR?

Op ma 9 jul. 2018 08:48 schreef Guan Gui <notifications@github.com>:

**Comment by guiguan** [comment]
@mweststrate here it is #516

**Comment by mnpenner** [comment]
> `this.props` and `this.state` are also observables themselves

Do you mean they get converted into MobX observables or that they behave like observables in that React [regardless of MobX] will re-render a component when they change?

**Comment by gouravr-94** [comment]
I have implemented getDerivedStateFromProps in my component and it's changing component's state only once after receiving new props from the reducer.
