### ISSUE TITLE
Rollup error: Module does not export observer

### ISSUE THREAD

**Issue by Nedlinin** [mobxjs/mobx-react#43]
Trying to work mobx-react into one of my projects but I'm having issues getting it to play nicely with Rollup.

     Error: Module c:\Users\cheath\Desktop\front-end\node_modules\mobx-react\index.js does not export observer

Trying to import the lib and decorate a class:

    ....
    import {observer} from "mobx-react";

    @observer
    class Header extends React.Component {
    ....

I can seemingly make it work by making the following mods:

    //mobx-react/index.js
    // Move the export order around.  This project uses Dojo and if the AMD define is before the common we get some issues..
    // UMD
     if (typeof exports === 'object') {
        module.exports = mrFactory(require('mobx'), require('react'), require('react-dom'));
     } else if (typeof define === 'function' && define.amd) {
		define('mobx-react', ['mobx', 'react', 'react-dom'], mrFactory);
     } else {
        this.mobxReact = mrFactory(this['mobx'], this['React'], this['ReactDOM']);
     }

And changing my usage in my component to:

     ....
    import * as MobX from "mobx-react";

    @MobX.default.observer
    class Header extends React.Component {
    ....

Obviously this is a bit of a clunky fix and I am hoping for a better solution.

My Rollup config:

    gulp.task("bundle", function () {
	return rollup.rollup({
		entry: "./src/main.js",
		plugins: [
			nodeResolve({
				main: true,
				skip: [ "esri" ] // Let Dojo handle Esri
			}),
			commonjs(),
			rollupPostcss({
				plugins: [
					require("autoprefixer"),
					require("precss")
				]
			}),
			replace({
				"process.env.NODE_ENV": '"development"'
			}),
			babel({
				exclude: "node_modules/**"
			})
		]
	}).then(function(bundle) {
		bundle.write({
			format: "amd", // AMD is Dojo compatible
			dest: "build/app/main.js",
			sourceMap: true
		});
	})
    });

**Comment by mweststrate** [comment]
I just pushed a patch to master. Would you mind testing it by cloning this repo and after that, in your own repo, run `npm install <checkoutpath>`?

**Comment by Nedlinin** [comment]
@mweststrate : This still causes the requirement of having to use:

    ....
    import * as MobX from "mobx-react";

    @MobX.default.observer
    class Header extends React.Component {
    ....

Which feels very clumsy to me.

What I ended up doing was rewriting part of the index.js file as an ES2016 input/export and running it through Babel to give me a CommonJS module which Rollup then handles gracefully.  Obviously this would mean a Babel dev dependency for your project but it allows a very nice consistent way of generating UMD/AMD/CJS/etc modules by simply using the Babel presets for them.

Let me know how you feel about Babel and if you'd like I can fork, make the changes and submit a PR.

**Comment by mweststrate** [comment]
Are you sure this isn't an issue in your rollup config? The module itself doesn't provide a default export, so it surprises me that you have to import it through the default. What where the changes you needed to make? 

I like the current simple setup, as each exported file (`index`, `native` and `custom`) are now easily accessible from cdnjs script and node module imports.

**Comment by Nedlinin** [comment]
I think it's actually a combination of things.

Firstly, Rollup sees the module is UMD is decides not to transpile it to AMD as UMD supports AMD.  This causes the output to contain the UMD block still:


    // UMD
        if (typeof define === 'function' && define.amd) {
            define('mobx-react', ['mobx', 'react', 'react-dom'], mrFactory);
        } else if (typeof exports === 'object') {
            module.exports = mrFactory(require('mobx'), require('react'), require('react-dom'));
        } else {
            this.mobxReact = mrFactory(this['mobx'], this['React'], this['ReactDOM']);
        }

In my application, I am using the Esri JS API which uses the Dojo loader.  This loader is an AMD loader.  It sees the AMD call and attempts to load the modules directly since it is still a "require" call rather than an _interopRequireDefault call.  However, the modules aren't actually like a standard module is because it should be built into the Rollup package.

I'm by no means a Rollup expert but I created a super basic test case (literally import {observer} from "mobx-react";).  Running Rollup with a standard config causes:

    Error: Module /Users/cheath/test-case/node_modules/mobx-react/index.js does not export observer 

In the end I ended up with a fork of your project in order to get things moving along.  https://github.com/mobxjs/mobx-react/compare/master...Nedlinin:master

It uses Babel to transpile the index.es6.js file into a CJS format which Rollup and subsequent plugins are handling without issue.  

    babel index.es6.js --out-file "dist/index.js"

Perhaps Rollup just chokes on UMD files.  No idea honestly.

**Comment by mweststrate** [comment]
Doesn't seem to be a pressing issue for someone ATM. Otherwise feel free to reopen.

**Comment by zwhitchcox** [comment]
Is there a workaround for this?

**Comment by zwhitchcox** [comment]
I'm getting this error: 
```
Could not resolve 'react-dom' from /home/zane/src/ashworth-firm/node_modules/mobx-react/index.js
Error: Could not resolve 'react-dom' from /home/zane/src/ashworth-firm/node_modules/mobx-react/index.js
    at Error (native)
    at /home/zane/src/ashworth-firm/node_modules/rollup-plugin-node-resolve/dist/rollup-plugin-node-resolve.cjs.js:78:21
    at /home/zane/src/ashworth-firm/node_modules/browser-resolve/index.js:265:24
    at /home/zane/src/ashworth-firm/node_modules/resolve/lib/async.js:46:14
    at process (/home/zane/src/ashworth-firm/node_modules/resolve/lib/async.js:173:43)
    at ondir (/home/zane/src/ashworth-firm/node_modules/resolve/lib/async.js:188:17)
    at load (/home/zane/src/ashworth-firm/node_modules/resolve/lib/async.js:69:43)
    at onex (/home/zane/src/ashworth-firm/node_modules/resolve/lib/async.js:92:31)
    at /home/zane/src/ashworth-firm/node_modules/resolve/lib/async.js:22:47
    at FSReqWrap.oncomplete (fs.js:123:15)
Type rollup --help for help, or visit https://github.com/rollup/rollup/wiki
```

This is my config:

```js
  1 import babel from 'rollup-plugin-babel'                                                                                                 
  2 import commonjs from 'rollup-plugin-commonjs'                                                                                           
  3 import nodeResolve from 'rollup-plugin-node-resolve'                                                                                    
  4                                                                                                                                         
  5 const babelOpts = {                                                                                                                     
  6   presets: [                                                                                                                            
  7     [                                                                                                                                   
  8       'es2015',                                                                                                                         
  9       {                                                                                                                                 
 10         modules: false                                                                                                                  
 11       }                                                                                                                                 
 12     ],                                                                                                                                  
 13     'stage-0',                                                                                                                          
 14     'react',                                                                                                                            
 15   ],                                                                                                                                    
 16   exclude: 'node_modules/**',                                                                                                           
 17   plugins: [                                                                                                                            
 18     'external-helpers',                                                                                                                 
 19     'transform-decorators-legacy',                                                                                                      
 20   ],                                                                                                                                    
 21   babelrc: false,                                                                                                                       
 22 }                                                                                                                                       
 23                                                                                                                                         
 24 export default {                                                                                                                        
 25   entry: 'src/app.js',                                                                                                                  
 26   dest: 'build/assets/bundle.js',                                                                                                       
 27   sourceMap: 'true',                                                                                                                    
 28   plugins: [                                                                                                                            
 29     babel(babelOpts),                                                                                                                   
 30     nodeResolve({                                                                                                                       
 31       jsnext: true,                                                                                                                     
 32       main: true,                                                                                                                       
 33       browser: true,                                                                                                                    
 34       extensions: [ '.js', '.jsx' ],                                                                                                    
 35     }),                                                                                                                                 
 36     commonjs({                                                                                                                          
 37       include: 'node_modules/**'                                                                                                        
 38     }),                                                                                                                                 
 39   ],                                                                                                                                    
 40 };  
```

**Comment by mweststrate** [comment]
react-dom is a peer dependency, so you need to explicitly depend on react-dom yourself (when building a web-app, for react native or custom renderers it isn't needed).

**Comment by zwhitchcox** [comment]
Thank you! That worked

**Comment by mull** [comment]
I'll second this. Would it be possible to what rollup suggests here? https://github.com/rollup/rollup/wiki/jsnext:main

**Comment by mweststrate** [comment]
@mull feel free to open a PR? don't have any particular experience with rollup

**Comment by KaySackey** [comment]
```
import {default as mobxReact} from "mobx-react";

@default.observer(SomeReactComponent)
```

Appears to work. The issue here is that co-mingling UMD and CJS into a single class confuses rollup---partly because of the immediately invoked function---partly because determines what type of class is exported via a heurestic rather than say executing the function and reading the output.

Interestingly, mobx itself works perfectly with rollup because the UMD is exported into a totally separate file.

I think if that approach were taken here and in serializr, then both packages would work with rollup perfectly as well.

The other option is do nothing, but that forces roll-up users to list single function they might use from the package as a named export manually.

E.g.

```
{
entry: 'test.js'
        commonjs({
              include: 'node_modules/**',  // Default: undefined
              ignoreGlobal: true,          // Default: false
              sourceMap: false,
              namedExports: {
                  'serializr': ['update', 'serializable', 'list', 'object', 'identifier', 'createSimpleSchema', 'deserialize']
              }
        }),
``` 

This is pretty tedious and error-prone, but I've been okay with it because (a) the API has been really stable and (b) mobx-react / serializr are really useful and can't really be tree shaken too well in any case.

Any thoughts on this?

I'm not a roll-up expert but I am using it in production.

**Comment by geiszla** [comment]
I also have a similar problem when trying to pack `mobx-react` with `rollup`.

My config:
```javascript
entry: 'src/index.jsx',
plugins: [
  stylusCssModules({
    output: 'www/styles.css'
  }),
  babel({
    exclude: 'node_modules/**'
  }),
  nodeResolve({ jsnext: true, main: true }),
  commonjs({
    namedExports: {
      react: [
        'PropTypes',
        'createElement'
      ]
    },
    sourceMap: true
  }),
  replace({
    'process.env.NODE_ENV': JSON.stringify('development')
  })
  // uglify()
]
```

When I try to run rollup, it gives me an error:
> (node:32512) UnhandledPromiseRejectionWarning: Unhandled promise rejection (rejection id: 1): **Error: 'observer' is not exported by node_modules\mobx-react\index.js (imported by src\components\Login.jsx)**. For help fixing this error see https://github.com/rollup/rollup/wiki/Troubleshooting#name-is-not-exported-by-module

When I try to manually give it the name of the exported module to commonjs using
```
commonjs({
  namedExports: { 'mobx-react': 'observer' }
})
```
it gives back the following:
> (node:53236) UnhandledPromiseRejectionWarning: Unhandled promise rejection (rejection id: 1): TypeError: **Error transforming D:\User\Project\node_modules\mobx-react\index.js with 'commonjs' plugin: customNamedExports.forEach is not a function**

I think it has something to to do with the fact that it's an UMD module (this is the only UMD dependency and the only one which I have problem with), but I can't really figure out what it is. Any suggestions?

**Comment by Nedlinin** [comment]
I think you're config is slightly off.  Module names should be defined in
an array.


namedExports: { './module.js': ['foo', 'bar' ] }  // Default: undefined


Thanks,
Chris Heath
--

**Comment by geiszla** [comment]
@Nedlinin I thought if there's only 1 element in the array the brackets can be omitted. It works now, thanks a lot :)
