### ISSUE TITLE
React-Hot-Loader blows up MobX

### ISSUE THREAD

**Issue by theKashey** [mobxjs/mobx-react#430]
I came here from React-Hot-Loader. Out issue is quite simple - we wrap React Component `render` method, and __could call render from a render__.

> This is a part of hot replacement process - react-hot-loader just renders element by itself to understand what was changed. 

Yet again - inside the component.render we could call some react-hot-loader internals, which will call component.render second time.

## The problem
The problem is with `trackDerivedFunction`.
- on the first enter it creates `derivation.newObserving`
- on the second enter it overrides it
- on the first exit it __resets it to null__
- on the second exit it will throw an arrow.

Recursion is prohibited.

We will try not to call render from a render, we still could use any other lifecycle method. But may be you also have some ideas how to mitigate the issue.

Link to the MobX problem: https://github.com/mobxjs/mobx/blob/4a629bc87da84ecf26dffe60503d18ab834fc141/src/core/derivation.ts#L135
Broken repo from our issue: https://github.com/theKashey/mobx-react-quick-starter
Our issue: https://github.com/gaearon/react-hot-loader/issues/882

**Comment by mweststrate** [comment]
@theKashey could you link to the relevant sources in hot-loader?

**Comment by theKashey** [comment]
@mweststrate - https://github.com/gaearon/react-hot-loader/blob/master/src/proxy/createClassProxy.js#L139
`proxiedUpdate` will call the same `proxiedRender` in some cases, and proxiedRender is a Component.render method.

We are going to just break this cycle, by extracting the "second" part of proxiedRender into the separate function. So you don't have to solve __this__ issue, as long it is just easier for us to solve it.
But, as I understand, the problem is with any recursion call, and should be solved anyway.

**Comment by theKashey** [comment]
Was fixed from react-hot-loader side.
