### ISSUE TITLE
shouldComponentUpdate not getting invoked

### ISSUE THREAD

**Issue by simoami** [mobxjs/mobx-react#432]
Hello,
I'm building up a notification component which wraps a [Snackbar](https://material-ui-next.com/demos/snackbars/). The component is setup to observe changes to a notificationStore. I'm not able to get `shouldComponentUpdate` to get called.

My goal is to allow incoming notifications to be queued if there's an active notification on screen. This is to chain 2 consecutive notifications by a slide out of the old message and slide in of the new one. You can see the visual concept here: 

https://storage.googleapis.com/material-design/publish/material_v_12/assets/0B6Okdz75tqQsX3VhUHNoaWVEbDQ/components-snackbars-usage-consecutivesbdifferenttype-005.webm

To do this, my plan is to catch the render request before it happens in `shouldComponentUpdate`. if a previous message is actively showing, queue notificationStore data and return false to cancel render. Hide/ Slide out old notification and wait for completion before displaying the queued message.

My problem is that `shouldComponentUpdate` isn't triggering. Here's my component:

```
@inject('notificationStore')
@observer
class Notifications extends React.Component {

  show = false;
  queue = [];

  shouldComponentUpdate() {
    console.log('shouldComponentUpdate');

    const { show, message } = this.props.notificationStore;
    if (this.show && !show) {
      // queue new message because another one is already showing
      this.queue.push({ message });
      // Don't render immediately. wait for slide out
      return false
    }
    return true;
  }

  onClose = (event, reason) => {
    this.props.notificationStore.clear();
  };

  onExited = () => {
    // process/show queued messages, in a fifo pattern
    if (this.queue.length > 0) {
      const { message } = this.queue.shift();
      this.props.notificationStore.show(message);
    }
  };

  render() {
    const { classes, notificationStore, ...otherProps } = this.props;
    const { message, show } = notificationStore;
    this.show = show;
    return (
      <Snackbar
        open={show}
        message={message}
        onClose={ this.onClose }
        onExited={ this.onExited }
        {...otherProps}
      />
    );
  }
}

export default withStyles(styles)(Notifications);
```

To show 2 consecutive notifications, I call these sequentially:
```
notificationStore.show('Message 1');
notificationStore.show('Message 2');
```

**Comment by simoami** [comment]
I got it to work without using local state or using shouldComponentUpdate. I realized `shouldComponentUpdate` is only invoked when the local state changes. Not when using mobX! That's a crippling fact because user doesn't have a say to proceed with the dom update or not. 
To get it to work, I now push all incoming messages to a queue. I don't drive render content directly from the store.

**Comment by Kielan** [comment]
@simoami how did you store the queue in order to trigger shouldComponentUpdate? please answer.

**Comment by simoami** [comment]
@Kielan I no longer rely on `shouldComponentUpdate`. It doesn't work for me to hook to.
I define my queue in the class, just like we define the `state` prop. So I refer to the queue from the methods using `this.queue`.
