### ISSUE TITLE
render is not called after observable change

### ISSUE THREAD

**Issue by vladimir-vg** [mobxjs/mobx-react#435]
Can't make it work =(

I've create array and wrapped it into `observable`, created a component and wrapped it into `observer`.
I do call function that is wrapped into `action` that does changes observed array. Array does change, but render is not fired.

In original code I was using decorators, but removed them for the sake of using jsfiddle.

Deps:
```
    "babel-plugin-transform-decorators-legacy": "^1.3.4",
    "babel-preset-env": "^1.6.1",
    "babel-preset-react": "^6.24.1",
    "mobx": "^3.6.1",
    "mobx-react": "^4.4.3",
    "react": "^16.2.0",
    "react-dom": "^16.2.0",
```

```
    babel: {
      presets: ['env', 'react'],
      plugins: ["transform-decorators-legacy"]
    }
```

I've set up an example: https://jsfiddle.net/hdzx3rzv/26/

```
const { observable, action } = mobx;
const { observer } = mobxReact;




class Store {
  constructor() {
    this.instances = observable([]);
  }

  fetchInstancesList() {
    setTimeout(action(() => {
      console.log("set new instances");
      this.instances = [1,2,3];
    }), 3000);
  }
}

class TestPage extends React.Component {
  componentDidMount() {
    this.props.store.fetchInstancesList();
  }

  render() {
    return React.createElement('div', null, this.props.store.instances.length);
  }
};

TestPage = observer(TestPage);

const store = new Store();
ReactDOM.render(
  React.createElement(TestPage, {store: store}, null),
  document.getElementById('container'));
```

**Comment by mweststrate** [comment]
You should either make `this.instances` an observable (you are now only
make it's value an observable, but not the property), or consider
`this.istances` as readonly and only replace values. So either use
extendObservable(this, instances: []) to make the prop observable, or use
this.instances.replace([1,2,3]) to not throw away your observable but
update it instead. For more details, check
https://mobx.js.org/best/react.html

Op vr 9 mrt. 2018 om 16:12 schreef Vladimir Gordeev <
notifications@github.com>:

**Comment by vladimir-vg** [comment]
Thanks! Will try.

**Comment by vladimir-vg** [comment]
Okay, I went with .replace() solution, looks more obvious.
Thanks!
