### ISSUE TITLE
observable change component not re-render

### ISSUE THREAD

**Issue by zedwang** [mobxjs/mobx-react#439]
Hi, @mweststrate .
I found the case from[ docs](https://mobx.js.org/refguide/observer-component.html).But the component not re-render, Please help me, thank you!~
#### dependencies
"react": "^16.2.0",
"mobx": "^3.5.1",
 "mobx-react": "^4.4.1",

```js
import {observer} from "mobx-react"
import {observable} from "mobx"

@observer class Timer extends React.Component {
    @observable secondsPassed = 0

    componentWillMount() {
        setInterval(() => {
            this.secondsPassed++
console.log(this.secondsPassed) // output NaN
        }, 1000)
    }

    render() {
        return (<span>Seconds passed: { this.secondsPassed } </span> )
    }
}

render(<Timer />, document.body)
```

**Comment by mweststrate** [comment]
Please provide a reproduction, probably something in your project setup

Op wo 14 mrt. 2018 17:01 schreef Woox.wzd <notifications@github.com>:

**Comment by zedwang** [comment]
@mweststrate I‘ve pushed the code into repo.[https://github.com/zedwang/mobx-demo](https://github.com/zedwang/mobx-demo)

**Comment by zedwang** [comment]
Oh,I found a solution. `@babel/plugin-proposal-class-properties` must be used in loose mode to support the `@babel/plugin-proposal-decorators`. To use` @babel/plugin-proposal-class-properties` in spec mode with decorators, wait for the next major version of decorators (Stage 2).
Rrong
```js
{
  "plugins": [
    "@babel/plugin-proposal-class-properties",
    "@babel/plugin-proposal-decorators"
  ]
}
```
Right

```js
{
  "plugins": [
    "@babel/plugin-proposal-decorators",
    ["@babel/plugin-proposal-class-properties", { "loose" : true }]
  ]
}
```
So for now closing the issue

**Comment by MatthewHerbst** [comment]
@zedwang the [Babel docs](https://babeljs.io/docs/en/next/babel-plugin-proposal-decorators.html) say `plugin-proposal-class-properties` only needs to be in loose mode when using the `legacy` mode of `plugin-proposal-decorators`. Did your "right" solution actually work for you?
