### ISSUE TITLE
Changelog / migrate guide for 5.0?

### ISSUE THREAD

**Issue by hyperknot** [mobxjs/mobx-react#440]
I've read the Medium article about changelog for MobX 4.x, thanks for the detailed explanation. 

On the other hand, I found absolutely nothing about mobx-react 5.0.0. The changelog is not updated and the GitHub release doesn't provide any readme either.

Is it safe to use it, and if so, what do we need to take care about when upgrading?

**Comment by mweststrate** [comment]
Good question :). MobX-react 5 works literally the same as 4, and doesn't
introduce API or semantic changes. It is just an update to reflect the
internal api changes in MobX 4 itself.

Op za 17 mrt. 2018 om 00:22 schreef Zsolt Ero <notifications@github.com>:

**Comment by swrobel** [comment]
There should still be a CHANGELOG entry for it...

**Comment by Rootre** [comment]
Yeah since I have a problem in my project with mobx 5 when using along with new mobx-react 6 lib for hooks. mobx 4 works fine

**Comment by FredyC** [comment]
@Rootre Please open a new issue if you have some specific issues with that combination of libraries.
