### ISSUE TITLE
Simple CodeSandbox of react-transition-group `CSSTransition, TransitionGroup` playing nicely with mobx?

### ISSUE THREAD

**Issue by corysimmons** [mobxjs/mobx-react#442]
I'm running into https://github.com/mobxjs/mobx-react/issues/196

I tried what you said here: https://github.com/mobxjs/mobx-react/issues/196#issuecomment-276602979

But I'm a newb so I have no idea what I'm doing.

Would someone mind making a barebones example to add to docs since animation is a pretty common use case with React? You can fork off this https://codesandbox.io/s/jlwy9qq5vw

**Comment by urugator** [comment]
Your snippet doesn't work properly because it uses indices instead of unique ids as product element keys, check this: https://codesandbox.io/s/oq0y3mrorz

Please create snippet (non-working) with `@inject` if it's causing trouble...

**Comment by corysimmons** [comment]
Oh I should've thought of that. I'm sorry! Thank you for your help!

**Comment by jacobweber** [comment]
@corysimmons Just curious -- how has this been working out for you? I've been trying a similar setup, but keep running into cases where MobX tries to re-render the components like Product while they're transitioning out. This happens after the data they need has been removed from the store, so they end up crashing. Just wondering if you've dealt with similar issues.

**Comment by corysimmons** [comment]
I moved to GraphQL/Apollo.
