### ISSUE TITLE
Passing JSX elements to a mobx store requires manual keys to be present

### ISSUE THREAD

**Issue by hyperknot** [mobxjs/mobx-react#443]
I opened this issue in React but got told this behaviour is because of using mobx:
https://github.com/facebook/react/issues/12409

How can I make mobx treat that element as a static element?

**Do you want to request a *feature* or report a *bug*?**
Bug/feature

**What is the current behavior?**
React requires manual keys present on each tag when passing an element via a function to render. If not, it gives a key warning.

I'm passing an element created from JSX via a mobx store. This element requires manual keys to be present on each child tag. Even for simple example this is incredibly hard to do, and doesn't allow using any child component, thus severely limiting this functionality.

The passed JSX can be considered static, so the key requirement shouldn't apply here at all.

Is it possible to tell React to consider an element as static?

Codesandbox minimal case:
https://codesandbox.io/s/4qm2p107r7

```
export class OverlayStore {
  @observable activePopup = null

  @action
  setPopup(element) {
    this.activePopup = element
  }
}

@observer
export class App extends React.Component {
  render() {
    return <div>{overlayStore.activePopup}</div>
  }
}

const overlayStore = new OverlayStore()
render(<App />, document.getElementById('root'))

overlayStore.setPopup(
  <p>
    Long<br key="1" />
    Text<br key="2" />
    <a href="/link" key="3">
      Link
    </a>
  </p>
)
```

**What is the expected behavior?**
Should not require manually setting keys to values like 1, 2, 3, etc.

**Which versions of React, and which browser / OS are affected by this issue? Did this work in previous versions of React?**
Latest stable dependencies via Codesandbox. Chrome / macOS but doesn't matter.

**Comment by urugator** [comment]
Just change `@observable` to `@observable.ref`. 

However I don't recommend storing elements to state (observable), usually it's better to store render callback.

**Comment by hyperknot** [comment]
@urugator cool, works perfectly with ref! Can you explain (or modify the Codesandbox) how to use a render callback for this usecase?

**Comment by urugator** [comment]
```javascript
const renderPopup = () => (
  <p>
    Long<br/>
    Text<br/>
    <a href="/link">
      Link
    </a>
  </p>
);
overlayStore.setPopup(renderPopup)
```
```javascript
return <div>{overlayStore.activePopup()}</div>
```
got it?

**Comment by hyperknot** [comment]
Ok, cool I get it! And this doesn't needs ref?

**Comment by hyperknot** [comment]
Doesn't work for me:
https://codesandbox.io/s/1zynjkp7w7

**Comment by urugator** [comment]
No... the thing is that react element looks like a plain object/array for mobx, so mobx automatically attempts to convert it into observable. `.ref` turns this autoconverting behavior off. 
Function won't be converted by Mobx, but thats not the reason why I suggest to store callback instead of element...
Please close the issue when answered.

**Comment by urugator** [comment]
You have to provide some initial value `@observable activePopup = () => {}` ... or check before rendering

**Comment by hyperknot** [comment]
Sorry I thought you've closed the issue already. OK, for function passing I just needed to test it before with an additional &&.
