### ISSUE TITLE
Typescript errors with inject and render

### ISSUE THREAD

**Issue by vnugent** [mobxjs/mobx-react#450]
I'd like to use `<Observer inject={} render{} />` to keep our components props signature untouched.  However I'm having a hard time getting typescript to play nice with `inject` and `render`.

--App.tsx
```
      <Provider namespaceStore={namespaceStore}>
        <App/>
      </Provider>
```

--SomeComponent.tsx
```

render() {
...
          <Observer
            inject={stores => ({ namespaceStore: stores.namespaceStore })} // <-- TS doesn't like this
            render={() => {
              return <div>hello </div>;
            }}
          />
```

### Error:  [ts] Property 'namespaceStore' does not exist on type '{}'

Inject props to render like the example in README
```
   <Observer
            inject={stores => ({ namespaceStore: stores })} // remove .namespaceStore to make TS happy
            render={props => {        // TS doesn't like (props) => signature
              return <div>{props}</div>;
            }}
```

 ### Types of property 'render' are incompatible.
 ###     Type '(props: any) => Element' is not assignable to type '(() => ReactNode) | undefined'.
###        Type '(props: any) => Element' is not assignable to type '() => ReactNode'.

package.json
```
"dependencies": {
    "mobx": "^4.1.0",
    "mobx-react": "^5.0.0",
    "react": "~16.2.0",
...
"devDependencies": {
    "@types/react": "~16.0.41",
    "@types/react-dom": "~16.0.4",
```

**Comment by urugator** [comment]
It's not an answer to your question, but don't use `inject` prop on `Observer`, [it's broken](https://github.com/mobxjs/mobx-react/issues/423) and it will be probably removed. I wonder why it hasn't been deprecated/removed yet?

**Comment by mweststrate** [comment]
The error on `render={props => ...` is correct, the render callback doesn't take any properties. (`Observer` doesn't pass any props to it's render function, those can be accessed from the closure instead).

`Observer inject` combo will be removed in the next release. Beyond, the current typings of React are not flexible enough to express store injection completely accurate, see #256.
