### ISSUE TITLE
After upgrading to mobx-react 4 (mobx 5), changes to observable map no longer trigger rerenders

### ISSUE THREAD

**Issue by pselden** [mobxjs/mobx-react#451]
I am probably using observable maps wrong, but this is was working for me in react-mobx 3 and now not working in 4.

```js
// Store.js
class Store {
   @observable map = new Map();

   loadData(id) {
      setTimeout(() => this.addData(id, data), 100);
   }

   @action
   addData(id, data) {
      this.map.set(id, data);
   }
}
```

```js
@inject('root');
@observer
class DataLoader extends React.Component {
   componentDidMount() {
     this.props.rootStore.store.loadData(1);
   }

   render() {
       const data = this.props.store.map.get(1);
       return data || 'loading';
   }
}
```

The DataLoader component will not rerender when data is added to the map and will forever be stuck at "loading".

**Comment by pselden** [comment]
Ack... I just realized my minimal test case actually works fine. I have to figure out why this doesn't work in my real app now.

**Comment by pselden** [comment]
One thing I did notice after upgrading was I wasn't able to use .values().filter() on my map created with the observable decorator-- I needed to do Array.from(map.values()).filter(). Maybe somehow related to how I'm setting it up?

**Comment by urugator** [comment]
> Array.from(map.values()).filter()

Check https://github.com/mobxjs/mobx/issues/1488
