### ISSUE TITLE
a new gotcha when using with the latest react-apollo 2.1.0 components

### ISSUE THREAD

**Issue by capaj** [mobxjs/mobx-react#452]
Unfortunately the hot new feature of apollo-client is incompatible with mobx-react. You can preview the problem here:

[![Edit React Apollo 2.1 example](https://codesandbox.io/static/img/play-codesandbox.svg)](https://codesandbox.io/s/k033ok476v?initialpath=%2Flist.js)

When the observable read is moved from the mutation children out to the direct descendant it works as always.
Since the new `Mutation` and `Query` component use render children and the render seems to happen in a different stack than rendering of the observer component so it does not register that the observable was read.

Has anyone got an idea how it could be fixed from our side? I will try to report it as issue with react-apollo, but I am really unsure if they will act on it.

**Comment by mweststrate** [comment]
@capaj referring to this?

```
{() => {
              <div>not counting here {obs.b}</div>;
            }}
```

The following pattern should fix that: 

```
{() => <Observer>{() => <div>not counting here {obs.b}</div>}</Observer>}
```

(or just extract the component if possible)

**Comment by mweststrate** [comment]
This is just how react works :), all components are rendered independently and one-by-one. So the graphQL component is rendered at a different moment then the component that owns it, and so would require it's own observer or this approach.
