### ISSUE TITLE
Why don't you pass-on the props from Observer down ?

### ISSUE THREAD

**Issue by theodorDiaconu** [mobxjs/mobx-react#455]
Observer takes in an "Argumentless" function, but what if I want to use this with props injected ?

Why not this:
```jsx
<Observer {...someprops}>
    {(someprops) => {...}}
</Observer>
```

**Comment by mweststrate** [comment]
Do you have a good use case? You can access them from the closure anyway. I don't see a real need and I do see potential confusion :-)

**Comment by theodorDiaconu** [comment]
You're right, you can access them from the closure. I don't remember the exact use-case I had, I used observer() in the end to solve the issue.
