### ISSUE TITLE
observer always triggering render?

### ISSUE THREAD

**Issue by opensrcken** [mobxjs/mobx-react#457]
I have code that looks like this:

```
@inject((stores: any) => ({
    highlightedComponentId: stores.treeStore.highlightedComponentId,
    setHighlightedFolder: stores.treeStore!.setHighlightedFolder.bind(stores.treeStore),
}))
@observer
export class TreeNode extends React.Component<Props, State> {
...
}
```

Mobx forces the re-rendering of a component any time `highlightedComponentId` (an observable) is changed. I was hoping the custom injection of a property from the store would allow me to control the re-rendering of a component via `shouldComponentUpdate`, but to no avail.

There could be hundreds, or thousands of nodes, in a tree, so re-rendering them all every time I need to update a single node is not acceptable performance-wise.

What is the recommended way of ensuring that only the relevant nodes are re-rendered?

**Comment by opensrcken** [comment]
Update: I've tried changing the code around so that the `render` function no longer references any observables. Instead, I've set up an `autorun` that uses the value of `highlightedComponentId` to trigger a call to `setState`, and only the `state` is now referenced by `render`.

The component *still* re-renders every time `treeStore.highlightedComponentId` is updated via an action.

I assume I'm misunderstanding how mobx works here.

**Comment by urugator** [comment]
Have you consulted https://mobx.js.org/best/pitfalls.html#dereference-values-as-late-as-possible ?

**Comment by opensrcken** [comment]
Update: I've figured out how to circumvent this issue by using `autorun` and only referencing state in the `render` function -- no observables. Is this still the recommended way of handling these situations? It's a bit cumbersome, and it's a shame that mobx's great automagic abilities can only be used when a small number of components are at play...

**Comment by mweststrate** [comment]
The proper way to express these kind of things is to use a computed property like

```
@computed isHighlight() {
   return this.props.treeStore.highlightedComponentId = this.whereEverThatIdIsComingFrom
}
```

and use that computed in your rendering. This makes sure that only two components re-render when the higlighted component id changes, as it effects only changes the _output_ of the computed that is was highlighted, and the one that should become higlighted. For all others the output is still false and a re-rendering is avoided.

**Comment by mweststrate** [comment]
Closing as question is answered, feel free to reopen if stuff is still unclear.
