### ISSUE TITLE
Call and re-render only if value changes, not on any set

### ISSUE THREAD

**Issue by natew** [mobxjs/mobx-react#458]
Is this not the default? I may actually just be doing something wrong so I wanted to check. If I set an observed value, but it's the same value (eg: `obj.x = 1; obj.x = 1`), will it render twice?

Sorry to spam here. My google search didn't turn anything clear up, so I wanted to make a question for poor readers like myself.

**Comment by mweststrate** [comment]
No. But you can simply test these kind of tests by trying?

Op do 19 apr. 2018 01:24 schreef Nate Wienert <notifications@github.com>:

**Comment by natew** [comment]
Ah thought I had seen this happening but didn't investigate enough... apologies.
