### ISSUE TITLE
'mobx' does not contain an export named 'Atom'.

### ISSUE THREAD

**Issue by renyaoxiang** [mobxjs/mobx-react#459]
I run into a problem with the warning  'mobx' does not contain an export named 'Atom'.
I used the mobx-react@5.0.0 and mobx@4.2. What should I do?

**Comment by mweststrate** [comment]
Read the release notes😊?

Op do 19 apr. 2018 02:02 schreef renyaoxiang <notifications@github.com>:

**Comment by renyaoxiang** [comment]
I changed the tsconfig.json, it works. It seems that tsc used the file index.module.js instead of index.js of mobx-react. 
Maybe the file index.module.js is something wrong, I'm not sure, however it works for me now. 

tsconfig.json
```
{
...
		"module": "commonjs", //  "esnext"  will make an error
...
}
```


Thank you.

**Comment by mweststrate** [comment]
closing, as this is an error in the dependency setup, not in mobx-react.
