### ISSUE TITLE
Using inject and observer in components that extend other components

### ISSUE THREAD

**Issue by bellostom** [mobxjs/mobx-react#460]
Hi

I have a base component which is decorated by inject and observer
I extend this base component and since I need the inject and observer, I add them to the child class
However, I am getting these warnings
_**You are trying to use 'observer' on a component that already has 'inject'**_

How can I achieve the desired functionality without mobx complaining?

Below is a sample code

`
@inject("RootStore")
@observer
export default class BaseMeasures extends Component{
}

@inject("RootStore")
@observer
export default class AverageSales extends BaseMeasures {}
`

I get the warning in the AverageSales component

Thanks

**Comment by bellostom** [comment]
@mweststrate Any help?

**Comment by mweststrate** [comment]
Long story short: don't use inheritance for React components. There is no
need for it as they are composable already, and the above code won't do
what you think it does: it doesn't extend BaseMeasures, it extends the HoC
that is generated around your original BaseMeasures component. One think
you could do is first declare the classes, and then export the decorated
versions of them. But not extending components is generally a better way
out of future trouble :)

Op vr 20 apr. 2018 om 10:11 schreef Thomas Bellos <notifications@github.com

**Comment by bellostom** [comment]
Thanks for the help
I understand your point for not using inheritance, however our use case needs it in some cases.
With some refactoring I can remove inheritance from some components, but not entirely. Maybe I need to use both approaches you mention

**Comment by mweststrate** [comment]
yeah, decorating late should be fine in that case, just don't decorate your
base classes

Op vr 20 apr. 2018 om 11:31 schreef Thomas Bellos <notifications@github.com

**Comment by bellostom** [comment]
Any implications if I use

export default class AverageSales extends BaseMeasures.wrappedComponent {}

Other than the obvious caution needed if BaseMeasures inject being removed :)

**Comment by mweststrate** [comment]
The wrapped component is the original, non injected one, so that might not
work as you expect.

Op vr 20 apr. 2018 om 14:02 schreef Thomas Bellos <notifications@github.com

**Comment by bellostom** [comment]
Hmm. But I do want the original one, so that the inheritance works correctly
Tested it and seems fine, unless I am missing something

**Comment by mweststrate** [comment]
That makes sense indeed😁

Op vr 20 apr. 2018 14:22 schreef Thomas Bellos <notifications@github.com>:

**Comment by bellostom** [comment]
Thanks for the valuable input and also for mobx :)
Much appreciated

**Comment by mweststrate** [comment]
Closing as question has been answered
