### ISSUE TITLE
How would be the most efficient way to setState onSuccess hook?

### ISSUE THREAD

**Issue by fedecryto** [mobxjs/mobx-react#461]
I would like to set a state of the parent component onSuccess hook.
I cant find a proper way to do this... Should I do something like this? 

```
constructor(props) {
	    super(props);
            this.handler = this.handler.bind(this)
	    this.state = {
	      myState: 'init'
	    };
	 };

	handler(newState) {
    	    this.setState({myState: newState});
  	};

.....

<Form form={form}  handler={this.handler}/>

```

if this is the right approach, then I'm stuck... don't know how to pass handler to form.onSubmit

**Comment by urugator** [comment]
How does it relate to Mobx?

**Comment by mweststrate** [comment]
Typically you would pass down a callback from parent to child, so that child can call the callback causing the parent to update it's state. These concepts are extensively described in the react docs and don't really relate to MobX indeed.
