### ISSUE TITLE
inject HOC display name

### ISSUE THREAD

**Issue by SimeonC** [mobxjs/mobx-react#466]
Before running around creating PR's everywhere I thought I'd ask why the inject HOC has a non-standard display name wrapper? https://github.com/mobxjs/mobx-react/blob/ab90ae65991c95da73406accd1048e225e63f02e/src/inject.js#L37-L43

Currently this means when we debug we get a wrapper like `inject-Component` or `inject-Component-with-storeA`. This is inconsistent with the rest of the HOC components like `observer(Component)`.

Why isn't inject using displayName like `inject(Component)` or `inject-with-storeA(Component)`?

**Comment by mweststrate** [comment]
wasn't aware there was a standard for it :). Feel free to PR

**Comment by SimeonC** [comment]
AFAIK the PR is kinda in PR hell thanks to it being a breaking change. No idea when it’ll be merged in.

**Comment by ItamarShDev** [comment]
And isn't there any way to add it as a non breaking change?

I'm asking to learn, and not to lecture. I am new to the library

**Comment by SimeonC** [comment]
Not really. Though in this case "Breaking Change" shouldn't affect running code but it will affect any dev tools that rely on it. If you were to look at the Display Name (normally in React dev tools) currently you would see something like the following examples.

Before Change (Current)
```
<inject>
  <Component>
...
```
With this change it changes to;
```
<inject(Component)>
  <Component>
...
```
Or something like that (I'm a little fuzzy on the details - it has been 6 months).

**Comment by ItamarShDev** [comment]
should be added the label Breaking change?

**Comment by mweststrate** [comment]
Yeah, added it on the PR. I think this could be merged into the v6 branch
once that stabilizes a bit.
