### ISSUE TITLE
Alternative to makeComponentReactive, broken after upgrading to 5.1.0

### ISSUE THREAD

**Issue by sammy-tam** [mobxjs/mobx-react#469]
While it is understood that React Components should not be using inheritance, but unfortunately our current code base being maintained uses a ``ReactiveBaseComponent`` class that is decorated by observer(), that overloads the lifecycle method like:
```
componentWillMount() {
        if (super.componentWillMount)
        {
            super.componentWillMount();
        }
    }
```

However, the render() method is not overloaded and therefore the new changes https://github.com/mobxjs/mobx-react/pull/463/commits/b981d6727ff65fedab164a5db64ac091372ec26e essentially broke the current code-base.  

Is there known workaround/alternative that would make it work, while not requiring to go and decorate all the current components?  (it is a large and old code base that is not easy to go back and change all components)

**Comment by mayorovp** [comment]
Try this crutch:

```
class ReactiveBaseComponent 
{
    constructor() {
        this.render = reactiveRender;
    }
    render() { 
        return this.constructor.prototype.render.call(this);
    }
}
observer(ReactiveBaseComponent); 
var reactiveRender = ReactiveBaseComponent.prototype.render;
delete ReactiveBaseComponent.prototype.render; // avoid accidental recursion
```

**Comment by mweststrate** [comment]
If you know the name of the (non-observer) base class is known, `Class.prototype.render.call(this)` should do the trick as well without the class patching
