### ISSUE TITLE
render() not being triggered in 5.1.X; works in 5.0.0

### ISSUE THREAD

**Issue by mikevaleriano** [mobxjs/mobx-react#473]
TL;DR, simple store and component used to work flawlessly using mobx-react 5.0.0; after updating to 5.1.X, render method of component is not triggered on change.

Debug info shows that the observable property `ready` is being updated correctly at the `componentDidMount` method, but render() is not being called after.

This is an oversimplified version of my code; the component has many other parts, but these are the ones important to mobx-react. There is absolutely no change other than the mobx-react version from 5.0.0 to 5.1.X (tried 5.1.0, 5.1.1, 5.1.2)

```js
// the store

import { action, observable } from "mobx";

class AppData{
  @observable ready = false;

  @action
  changeState = state => {
    this.ready = state;
  };
}

export default new AppData();
```

```js
// the component

import { inject, observer } from "mobx-react";
import PropTypes from "prop-types";
import React from "react";

import Layout from "./parts/Layout";
import Loader from "./parts/Loader";

@inject("AppData")
@observer
export default class App extends React.Component {
  static propTypes = {
    AppData: PropTypes.object
  };

  render = () => {
    let display = this.props.AppData.ready ? (
        <Layout>
          Test
        </Layout>
    ) : (
      <Loader />
    );

    return display;
  };

  componentDidMount = () => {
    this.props.AppStore.changeState(true);
  };
}

```

**Comment by tiagowippel** [comment]
Hi, same here...

**Comment by tiagowippel** [comment]
Think that i've just found the solution...

Don't use arrow function on your render function...


```
@inject("AppData")
@observer
export default class App extends React.Component {
  static propTypes = {
    AppData: PropTypes.object
  };

  render() { // <= don't use arrow function
    let display = this.props.AppData.ready ? (
        <Layout>
          Test
        </Layout>
    ) : (
      <Loader />
    );

    return display;
  };

  componentDidMount = () => {
    this.props.AppStore.changeState(true);
  };
}
```

**Comment by mikevaleriano** [comment]
@tiagowippel  Wow, this works but... Why did it work in 5.0.0 in the first place?

I was autobinding things in my components and didn't even realize I did the same with `render()` by using an arrow function in it as well, and that's the root of the issue. Thanks for pointing it out. Closing.

**Comment by tiagowippel** [comment]
Well, I think maybe it is because of this..

https://github.com/mobxjs/mobx-react/commit/b981d6727ff65fedab164a5db64ac091372ec26e

**Comment by ertejaspatel** [comment]
Hi Michel,

Thanks for the awesome library. 

Just a quick question - Is there any particular reason why render method can't be an arrow function? 

Thanks:)
