### ISSUE TITLE
Undefined `this` when calling `observer` on a pure function

### ISSUE THREAD

**Issue by gangeli** [mobxjs/mobx-react#477]
To reproduce:

1. Create an observed React component from a pure function, e.g.,:

       export default observer((props: {}) => { return <div>Hello world</div> });

2. Render the component
3. An error appears:

      ```
      index.module.js:220 Uncaught TypeError: Cannot call a class as a function
          at classCallCheck (index.module.js:220)
          at _class (index.module.js:898)
      ```

The underlying cause appears to the that `this` is undefined in the `observer()` function.

My workaround has been to change index.modules.js:891 from:

```javascript
if (typeof componentClass === "function" && (!componentClass.prototype || !componentClass.prototype.render) && !componentClass.isReactClass && !Component.isPrototypeOf(componentClass)) {
```

to:

```javascript
if (this != null && typeof componentClass === "function" && (!componentClass.prototype || !componentClass.prototype.render) && !componentClass.isReactClass && !Component.isPrototypeOf(componentClass)) {
```

Which seems to be generated from [Observer.js:312](https://github.com/mobxjs/mobx-react/blob/6d76b09f19a00d9362fe5180615bebaacd554e4a/src/observer.js#L312). Perhaps this is a compile error, because the source code looks ok, but certainly in the compiled code `this` can be undefined:

```javascript
function observer(arg1, arg2) {
    ...
    if (typeof componentClass === "function" && (!componentClass.prototype || !componentClass.prototype.render) && !componentClass.isReactClass && !Component.isPrototypeOf(componentClass)) {
        var _class, _temp;

        var observerComponent = observer((_temp = _class = function (_Component) {
            inherits(_class, _Component);

            function _class() {
                classCallCheck(this, _class);
                return possibleConstructorReturn(this, (_class.__proto__ || Object.getPrototypeOf(_class)).apply(this, arguments));
            }

            createClass(_class, [{
                key: "render",
                value: function render() {
                    return componentClass.call(this, this.props, this.context);
                }
            }]);
            return _class;
        }(Component), _class.displayName = componentClass.displayName || componentClass.name, _class.contextTypes = componentClass.contextTypes, _class.propTypes = componentClass.propTypes, _class.defaultProps = componentClass.defaultProps, _temp));
        hoistNonReactStatics(observerComponent, componentClass);
        return observerComponent;
    }
    ....
}
```

**Comment by mweststrate** [comment]
Can you create a small reproduction in code sandbox?

**Comment by urugator** [comment]
Observer always wraps stateless functional component into a component class, because it has to patch lifecycle methods. So you either have to use `React.createElement(Hello, {name: "Bill"})` or expose a factory `React.createFactory(Hello)`

**Comment by urugator** [comment]
Only way to instantiate react component is to pass it to `React.createElement`. If you simply call `Hello` as a plain function, then you're not using it as react component.

**Comment by gangeli** [comment]
Yes, but my understanding is that this is part of what the `observer()` function is intended to do -- wrap a pure function in a React component. If my example is not a supported use case, can we at least print a more informative error stating the reason? Currently, the observed behavior is that the code works fine without `observer`, and breaks at Runtime when wrapped in an `observer` (despite type-checking with Flow)

**Comment by urugator** [comment]
`observer()` accepts any **react component** (component class of function) and produces **react component**.
Again... only way to render **react component** is to pass it to `React.createElement`.
So either `Hello` is **react component** and therefore must be passed to `React.createElement`.
Or `Hello` isn't **react component**  and therefore can't be passed to `observer()`.

**Comment by gangeli** [comment]
Great. Then can I submit a suggestion to have `observer()` wrap a pure function as a React component internally? "No" is a perfectly valid answer -- I already have my workarounds for this. But, when I encountered this behavior I was surprised, and figured I'd take the time to document it in an issue.

**Comment by urugator** [comment]
> to have observer() wrap a pure function as a React component internally?

Not sure what you mean?

To me it seems there is some misconception about functional components. Functional components are not meant to be called directly, whether you use JXS or not. If you do, then it's not a component, it's simply a function returning element, like any other helper function (`renderSomething()`) you usually use inside actual `render`.
If you call the function directly, there is no component created (the virtual DOM is different), therefore nothing that could be turned into `observer`.

Sidenote just to get the naming straight:
**pure function**: any function without side-effects, returning the same result for the same set of arguments
**stateless functional component**: react component defined as function
**pure component**: react component rendering the same result for the same set of props

**Comment by mweststrate** [comment]
@gangeli for all clarity; the problem here is on the _call_ site. Even without `observer`, you thought you were creating a Pure component, but you were not calling it as component, but as function. Although it works in the sense that the output is correct, that would already result in different semantics (namely, the rendering of the child would became part of the parent, rather that it resulting in a react instance of the pure component). 

What you are doing is roughly this (using component syntax to make the problem more clear)

```
class A extends PureComponent {
  render()  { /* something */ }
}

class B extends PureComponent {
  render() {
     return A.prototype.render(stuff)
     // this is something completely different from
     return <A {...stuff}/>
     // in the first case *you* invoke render, bypassing all of reacts lifecycle etc
     // in the second case you properly construct a component instance that will cause React to manage the rendering
  }
}
```

**Comment by urugator** [comment]
@mweststrate Just a nitpick - stateless functional components are usually pure functions, but not pure components as your example suggests (extends `PureComponent`)...

**Comment by gangeli** [comment]
In that case, would it be possible to have this either not type check, or at least print a more informative error message?
