### ISSUE TITLE
MobX swallowing fatal errors in React Native Release build

### ISSUE THREAD

**Issue by marcshilling** [mobxjs/mobx-react#481]
Scenario: A component's `render()` method has some invalid code in it that causes an error/crash. Attempting to load that component in a debug build pops up a RedBox error, as it should. However, in a release (bundled) build when that error occurs, the app does not crash as it should, it simply renders an all-white screen where the user has no choice to but force-quit the app. If an exception occurs somewhere other than in a `render()` method (for example, a button handler), the exception correctly makes its way to native code - so this seems isolated to `render()` exceptions.

I tracked this down to MobX because removing the `<Provider>` around my app component made the app correctly crash in release mode. After that, I saw the note regarding `onError` in the README, which sounded exactly like what I needed. At first, I tried to implement it like so:
```
import { onError } from 'mobx-react';
onError((error) => {
    console.log("throw the error");
    throw error;
});
```
This resulted in the same outcome. "throw the error" was logged, so I knew onError was called, but explicitly `throw`ing still did not crash the app. So I dug deeper into how exceptions get sent to native code, and landed on this implementation:
```
const { ExceptionsManager } = require('NativeModules');
const parseErrorStack = require('parseErrorStack');

let exceptionId = 0;
onError((error) => {
  const stack = parseErrorStack(error);
  exceptionId += 1;
  ExceptionsManager.reportFatalException(error.message, stack, exceptionId);
});
```
This is how React Native explicitly makes the native code aware of the exception, causing the crash. This seems to produce the outcome I'd expect, but it seems very unnecessary.

Can anyone shed some light on why MobX is behaving this way in React Native? Obviously, I could fix my render method to correctly handle the exception, but this seems like a no-brainer. Anything that would throw a RedBox in debug mode should cause a crash in release mode.

**Comment by mweststrate** [comment]
Mobx-react doesn't behave differently for native or non-native, and for production or development. Are you sure that removing the Provider didn't appear to work because it actually caused a completely different error, in a different lifecycle, giving the impression that first exception was caught? (Just removing a Provider will make all connected `inject`'s throw for example). 

Best create a small isolated project demonstrating the correct and faulty behavior, when using / not-using mobx-react

**Comment by marcshilling** [comment]
My apologies, you're right. After some more digging it appears it may be react-navigation swallowing the exceptions - I'll take my issue over to them!
