### ISSUE TITLE
Component rerender only the first time

### ISSUE THREAD

**Issue by sidux** [mobxjs/mobx-react#482]
Refreshing `GameStore.heroes` data only triggers dom change the first time, even though the render function is proprely called every time

Here is my ts code

```jsx
@observer
export default class Arena extends React.Component {

    @autobind @action
    private play() {
        GameStore.heroes = Arena.randomHeroes(5);
    }

    @autobind @action
    private reset() {
        GameStore.heroes = [];
    }

    private static randomHeroes(count: number): Array<Hero> {
        let heroes = [];
        for (let i = 0; i < count; i++) {
            const randomId = Math.round(Math.random() * (HeroesData.length - 1) + 1);
            heroes.push(HeroesData[randomId])
        }

        return heroes;
    }

    public render() {
        return (
            <div className={styles.container}>
                <button onClick={this.play}>Play</button>
                <button onClick={this.reset}>Reset</button>
                { GameStore.heroes.map((hero) =>
                    <Card hero={hero}/>
                )}
            </div>
        );
    }
}
```

**Comment by mweststrate** [comment]
Please provide a reproduction in a code sandbox as prescribed by the issue
template

Op wo 23 mei 2018 15:06 schreef Ahmed Lebbada <notifications@github.com>:

**Comment by sidux** [comment]
Here is one https://codesandbox.io/s/3q847xr2xm

**Comment by urugator** [comment]
Use `key` attribute on `Card` component as console suggests.

**Comment by sidux** [comment]
@urugator thx, i had to use a unique id as a key for it to change each time, but i don't get it, isn't it supposed to get changes in objects ?

**Comment by urugator** [comment]
Don't assign hero to `this` in Card constructor, react sends another hero with props, but your card still uses the old one...

**Comment by sidux** [comment]
Got it thx
