### ISSUE TITLE
Observer doesn't work with List component from react-virtualized

### ISSUE THREAD

**Issue by schabluk** [mobxjs/mobx-react#484]
Hi,

When working with List component from react-virtualized library, I can't get the items to update when the state is changing: https://codesandbox.io/s/olwz1lk5xq

The List component implements [render-props pattern](https://reactjs.org/docs/render-props.html) in the 'rowRenderer' property, which takes a function, that handles items rendering.

I tried to wrap the List component with 'observer', but it does not work, plus I'm getting this warning:

`Warning: List has a method called shouldComponentUpdate(). shouldComponentUpdate should not be used when extending React.PureComponent. Please extend React.Component if shouldComponentUpdate is used.`

[The List component extends PureComponent](https://github.com/bvaughn/react-virtualized/blob/master/source/List/List.js#L99).

Neither the render-props pattern, nor PureComponent is the issue here, as I have the same example implemented with component extending PureComponent and implementing render-props, and it's working fine despite the warning message: https://codesandbox.io/s/l2w6mzolzl.

**Comment by urugator** [comment]
When using 3rd party libs: 

To subscribe for any observable accessed inside render callback, wrap render callback into `Observer`:
`() => <Observer>() => renderCallback()</Observer>`

To subscribe for modifications of array itself, pass a shallow copy to 3rd party component instead: 
`<List items={array.slice()}`/>

To subscribe for modifications of array and anything inside, pass a deep copy to 3rd party component instead:
`<List items={mobx.toJS(array)}>`
To preserve original item references inside passed array, create deep copy as suggested, but pass the original array:
```javascript
render() {
  mobx.toJS(array); // subscribes
  return <List items={array}>
}
```

**Comment by schabluk** [comment]
@urugator thank you for clarification. This helped:

```
<AutoSizer>
  {({ height, width }) => (
    <List
      height={height}
      rowCount={items.length}
      rowHeight={36}
      rowRenderer={({ index, key, style }) => (
        <Observer>
          {() => this.renderItems({ index, key, style })}
        </Observer>
      )}
      width={width}
    />
  )}
</AutoSizer>
```

**Comment by SkunSHD** [comment]
In my case I was getting a warning from `react-virtualized`: 

> Rendered cell should include style property for positioning.

I fixed that just by adding a `div` wrapper:
```
rowRenderer = ({ key, index, style }) => {
    return (
      <div style={style}>
        <Observer>
          {() => (
            <NodeWithDnD
              key={key}
              index={index}
              node={this.items[index]}
            />
          )}
        </Observer>
      </div>
    );
  };
```
