### ISSUE TITLE
Store properties are undefined in component called with Route via react-router

### ISSUE THREAD

**Issue by rottenoats** [mobxjs/mobx-react#485]
I've tried with the decorators and via import statement for the component called with Route component (HomeComponent) from react-router.

The parent component works completely fine, I'm using decorators and I'm able to access the properties of my store (only in the top component that is not called via Route).

No error is thrown, I can access my store but the @observables are undefined.

My store:

```
class AuthenticationStore {

    @observable isAuthenticated = false;

    /** more code here **/

}
const authenticationStore = new AuthenticationStore();
export default authenticationStore;
```

Component called via Route:

```
@withRouter @inject('authenticationStore') @observer
class HomeComponent extends Component {

    constructor(props){
        super(props);
    }

    render(){
        let { classes } = this.props;
        const {authenticationStore} = this.props;
        //can access, but isAuthenticated is always undefined
        console.log(authenticationStore.isAuthenticated);
        return (
            <div className={classes.root}>
                <div>
                    <h1>Home</h1>
                </div>
            </div>
        )
    }
}

export default withStyles(styles)(HomeComponent);
```
entry point component:

```
class App extends Component {

    render(){
        return (
                <Router>
                    <Provider {...stores}>
                        <RefluxMainComponent/>
                    </Provider>
                </Router>

        );
    }
}

```

Route called in my top component (RefluxMainComponent):

`<Route key={0} path="/" component={()=><HomeComponent/>} exact={true}/>
`
What am I missing?

**Comment by mweststrate** [comment]
A reproduction and much more details :)

Op do 24 mei 2018 om 17:10 schreef rottenoats <notifications@github.com>:

**Comment by kikoseijo** [comment]
Dont inject, just use the imported class in you component.


```
import AuthenticationStore from '@libs/AuthenticationStore';
...

render(){
const {isAuthenticated} = AuthenticationStore;
```

in javascript seems all class are singletons.

Im I right?

**Comment by rottenoats** [comment]
@mweststrate I'll provide a reproduction in a bit.
@kikoseijo doesn't work, I already tried that.

**Comment by rottenoats** [comment]
Hmmmm, I created a general same setup in codesandbox and it worked.
https://codesandbox.io/s/91q23369kr

In my environment, I'm using Symfony4 with webpack-encore. Would it have anything to do with my configuration? Otherwise, I have really no idea where to go with this.

I'll keep thinking about it, maybe I forgot to include something in the codesandbox.

Here is a snippet of my webpack.config.js:

```
// webpack.config.js
var Encore = require('@symfony/webpack-encore');

Encore
// the project directory where all compiled assets will be stored
    .setOutputPath('public/build/')

    // the public path used by the web server to access the previous directory
    .setPublicPath('/build')

    // will create public/build/app.js and public/build/app.css
    .addEntry('app', './assets/js/app.js')

    .addStyleEntry("calendar", "./node_modules/react-big-calendar/lib/css/react-big-calendar.css")

    .configureBabel(function(babelConfig) {
        babelConfig.plugins = [
            "transform-object-rest-spread",
            "transform-class-properties",
            "transform-decorators-legacy",
            "transform-runtime",
        ]

        // no plugins are added by default, but you can add some
        // babelConfig.plugins.push('styled-jsx/babel');
    })
    // enable source maps during development
    .enableSourceMaps(!Encore.isProduction())

    // empty the outputPath dir before each build
    .cleanupOutputBeforeBuild()

    // show OS notifications when builds finish/fail
    .enableBuildNotifications()

    .enableReactPreset();

// export the final configuration
module.exports = Encore.getWebpackConfig();
```

**Comment by mweststrate** [comment]
Decorators plugin should be first

Op do 24 mei 2018 20:28 schreef rottenoats <notifications@github.com>:

**Comment by rottenoats** [comment]
@mweststrate can't believe it was just that. Thanks. Spending hours trying to figure this out.

**Comment by emilgpa** [comment]
When I change the language by the user's interaction, it works well but I need to try it more. I remember that I did not always translate all the texts. For the moment, such an error no longer happens.

**Comment by davidgolden** [comment]
Yep.. here's what I needed to get this working:

`plugins: [['@babel/plugin-proposal-decorators', {
                            legacy: true,
                        }], ["@babel/plugin-proposal-class-properties", {"loose": true}],],`

**Comment by infantopratik** [comment]
Thanks, @mweststrate and @davidgolden, just moving the following to the top of the plugins array in the babel.config.js solved the problem for me.

`["@babel/plugin-proposal-decorators", { legacy: true }],
["@babel/plugin-proposal-class-properties", { loose: true }],`
