### ISSUE TITLE
changing any prop makes computed re-evaluate even if they don't use that prop directly

### ISSUE THREAD

**Issue by xaviergonz** [mobxjs/mobx-react#486]
https://stackblitz.com/edit/react-difmls

I just found out today that if we change any prop (say that we only change prop X), this will also trigger a computed value that only uses prop.Y to re-evaluate (see code edit above)

While I see why it happens (basically props becomes a whole new object ref every time a single prop changes), would there a way for observer to be smarter and just assume that the reference to this.props does not "change" while still reacting to this.props.FOO changes?

This makes it kind of pointless to try to create optimized computed values based on any prop since any little change in the props obj will make them be re-evaluated.

**Comment by xaviergonz** [comment]
Ok, I managed to do it

https://stackblitz.com/edit/react-nawn64

but I was wondering, maybe this behaviour could be added to observer itself (probably via some parameter?)

**Comment by urugator** [comment]
Something to read: https://github.com/mobxjs/mobx-react/pull/436
I suggest to go through the issues referenced in that pull request.

**Comment by FredyC** [comment]
Closing as stale. I think we got better tools at our disposal now with `useLocalStore` and friends.
