### ISSUE TITLE
Root React component is not observing changes in store

### ISSUE THREAD

**Issue by jhonnymichel** [mobxjs/mobx-react#488]
In version 5.1.2, This piece of code does not work (the store changes its values but the App component does not trigger a rerender)

```
@observer
class App extends Component {
  render = () => (
    <div className="app container-fluid">
      {this.props.store.auth.status === 'authenticated'
        ? <p> Hello, world </p>
        : <p> We're not ready yet </p>
      }
    </div>
  );
}

document.addEventListener('DOMContentLoaded', () => {
  ReactDOM.render(
    <App store={ AdminStore }/>,
    document.querySelector('#app'))
});
```

When I roll back to version 5.0.0, everything works as expected: Once I trigger any action that changes the auth.status in the store, the component renders the 'Hello, world' message. 

Additional info:
- React version: 16.4.0
- Mobx version: 4.3.0

**Comment by urugator** [comment]
Don't use arrow function with render. More info here: https://github.com/mobxjs/mobx-react/issues/473

**Comment by jhonnymichel** [comment]
Thanks. I'm closing this now.
