### ISSUE TITLE
index.js should try catch in some method.

### ISSUE THREAD

**Issue by luosong** [mobxjs/mobx-react#49]
index.js 
current patch function:
``` javascript
function patch(target, funcName) {
            var base = target[funcName];
            var mixinFunc = reactiveMixin[funcName];
            if (!base) {
                target[funcName] = mixinFunc;
            } else {
                target[funcName] = function() {
                    base.apply(this, arguments);   // (1)
                    mixinFunc.apply(this, arguments);  // (2)
                }
            }
        }
```
if  (1) or (2) throw exception then other observer component will no effect never!

I fix this issues when surround try catch:
``` javascript
       function patch(target, funcName) {
            var base = target[funcName];
            var mixinFunc = reactiveMixin[funcName];
            if (!base) {
                target[funcName] = mixinFunc;
            } else {
                target[funcName] = function() {
                    try {
                        base.apply(this, arguments);
                        mixinFunc.apply(this, arguments);
                    }
                    catch (err) {
                        console.error('mobx-react error ', err);
                    }
                }
            }
        }
``` 
another same issues in 
``` javascript
var reactiveMixin = {
            componentWillMount: function() {
                ......
                function initialRender() {
                    reaction = new mobx.Reaction(name, function() {
                        if (!isRenderingPending) {
                            isRenderingPending = true;
                            // should surround try catch
                            if (typeof self.componentWillReact === "function")
                                self.componentWillReact();
                            React.Component.prototype.forceUpdate.call(self)
                        }
                    });                
            }
}
```

**Comment by mweststrate** [comment]
Can you elaborate a bit on why you would need this try / catching?

I think the interesting question is, why should the component succeed if an exception is thrown? The react docs don't give any indication that throwing from lifecycle methods is a supported scenario, and component behavior will be unpredictable (in my experience, react usually stops working after throwing). So catching errors will just hide these problems and add confusion, in contrast to failing fast.

**Comment by luosong** [comment]
Everything will be OK when a react component throw exception in rendering not use @observer.

``` javascript
class Foo extend Component {
	render() {
		// throw exception but everything will ok
	}
}
```

``` javascript
@observer
class Foo extend Component {
	render() {
		// throw exception
	}
}

``` javascript
@observer
class Bar extend Component {
	render() {
		// when Foo render failed
		// Bar's render will suspend!!!
	}
}

```

**Comment by mweststrate** [comment]
I think you are right, I'm gonna test a bit to see what exactly React's default behavior is and mimic it.

**Comment by mweststrate** [comment]
@luosong I just ploughed through some issues in the React repo, and as far as I can see the behavior of what should happen when a component throws an exception from render or one of the life cycle hooks is actually quite undefined, up to any error boundary you introduce in a parent component. It just logs the error and they might be able to work after they, but it is, as far as I see, nowhere defined what semantics should be after an exception.

So I think in that sense `@observer` components should adhere to the same rules as normal react components; they should not modify state and they should not throw. And hence have no dedicated error handling support (the main reason why that isn't in react as well is performance). If dedicated boundary support is needed somehow we could further investigate that path.
