### ISSUE TITLE
mobx-react 5.2.0 fails to build with Webpack 3.x (create-react-app)

### ISSUE THREAD

**Issue by lvpro** [mobxjs/mobx-react#493]
Failed to compile.

./node_modules/mobx-react/index.module.js
599:24-29 'mobx' does not contain an export named '$mobx'.

**Comment by mweststrate** [comment]
Upgrading mobx to 5.3.1 or downgrading mobx-react to 5.1.0 should solve the issue.

Sorry for the inconvenience! In some build setups combining mobx-react 5.2.0 with MobX <= 4.3.0 will yield this problem.

**Comment by mweststrate** [comment]
Sorry, yes 4.3.1 indeed

Op ma 4 jun. 2018 21:24 schreef Alan Rubin <notifications@github.com>:
