### ISSUE TITLE
global is not defined

### ISSUE THREAD

**Issue by Fred2MTL** [mobxjs/mobx-react#503]
Context:
- Migrating existing code in mobx 4.x to mobx : 5.0.0 / mobx-react : 5.2.2
- Testing under FF Developer Edition : 61
- Compiling under Gulp 4.0 / Rollup 0.60.1 / Babel 6.26

Error:
- Message on the web console : global is not defined ... into createSymbol -> index.module.js:615

Workaround used (and validated):
- Replacing global.Symbol by Symbol into function createSynbol as [standard built-in objects](https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Global_Objects)

**Comment by mweststrate** [comment]
Should be fixed with `5.2.3`
