### ISSUE TITLE
Mobx action has no reaction

### ISSUE THREAD

**Issue by lvLokkie** [mobxjs/mobx-react#507]
Hi, i started develop my pet project on React,ReactToolbox + Mobx and met a problem. React component don`t do re-render after store prop changed its value. A spent a lot of time for solution searching but I cant solve it and, now, i have no idea what to do. May be u can help me? 

HallEditor-> Push the button -> must call rerender, but dont do this
[Rep](https://github.com/lvLokkie/kto)

**Comment by kikoseijo** [comment]
Dont assign your prop to a local var.

This is one of the things you should not do, and its documented.

use it directly from props.

Or just import the storage and us it as it comes.

**Comment by kikoseijo** [comment]
https://mobx.js.org/best/pitfalls.html

**Comment by lvLokkie** [comment]
@kikoseijo o, thanks. I removed local variables but this isn`t solves my problem

**Comment by kikoseijo** [comment]
If its a promise, like a button, needs to `@action.bound`,

Check that `$this` its whats suppose to be, if its `null` problems its the .bound....

BTW: setup [https://flow.org](https://flow.org) on your react!!!! (Wont solve the problem right now,,, but will help you get typesafe..

**Comment by lvLokkie** [comment]
@kikoseijo YEAAAH! I won it after two weeks! Problem was in webpack config

Webpack redefines .babelrc settings

Was:
```
  plugins: [
              '@babel/plugin-proposal-class-properties',
   ],
```
Became:
```
{
        test: /\.(js|jsx)$/,
        exclude: /(node_modules|bower_components)/,
        use: {
          loader: 'babel-loader',
          options: {
            presets: [
              '@babel/preset-env',
              '@babel/preset-react',
            ],
            plugins: [
              ['@babel/plugin-proposal-decorators', { legacy: true }],
              ['@babel/plugin-proposal-class-properties', { loose: true }],
            ],
          },
        },
      },
```
Created [Boilerplate](https://github.com/lvLokkie/react-mobx-webpack-react-toolbox-boilerplate)
