### ISSUE TITLE
store is Empty object

### ISSUE THREAD

**Issue by appbanana** [mobxjs/mobx-react#509]
changeNameStore:
ChangeNameStore{…} Empty object
children:
{…}
countStore: CountStore{…} Empty object

I used the Provider component to inject the store and found that the store is empty.Can you tell me why and how  can  I  solove it?

The source code is as follows:
// APP.js
import React, {Component} from 'react';
import {Provider} from "mobx-react"
import './App.css'
import Home from './component/index'
import {BrowserRouter} from 'react-router-dom'
import stores from './mobx'

class App extends Component {
    render() {
        return (
            <Provider {...stores}>
                <BrowserRouter>
                    <div className="App">
                        <Home/>
                    </div>
                </BrowserRouter>
            </Provider>
        );
    }
}
--------------------------------------
// mobx folder -- index.js
import ChangeNameStore from './ChangeNameStore'
import CountStore from './CountStore'

class Store {
  constructor() {
      this.changeNameStore = ChangeNameStore
      this.countStore = CountStore
  }
}
export default new Store()
---------------------------------------------------
// ChangeNameStore.js
import {observable, action} from 'mobx'

class ChangeNameStore {

    @observable name = "sun"

    @action
    changeName() {
        if (this.name === "sun") {
            this.name = "wen"
        } else {
            this.name = "sun"
        }
    }
}

export default new ChangeNameStore();

------------------------------------------------
// CountStore.js
import {observable, action} from 'mobx'

class CountStore {

    @observable startNum = 10

    @action
    inc() { this.startNum += 1 }

    @action
    dec() { this.startNum -= 1}

    @action
    reset() { this.startNum = 0 }
}

export default  new CountStore();

**Comment by appbanana** [comment]
https://github.com/appbanana/react-mobx-demo.git 
 This is the address.I have uploaded to githup. My problem is  that I used the Provider component to inject the store and found that the store of state is empty().I found it through the Google React tool. This is the state of store . You can find that the changeNameStore and countStore are all Empty object. 
When you have time, please help to find where the problem with my store is and how I can solove it.Thank you!

`
changeNameStore:
ChangeNameStore{…}
Empty object
children:
{…}
countStore:
CountStore{…}
Empty object
routerStore:
RouterStore{…}
Empty object
`

**Comment by xiao11lang** [comment]
这个问题你解决了吗？我遇到一样的问题不知道怎么回事
