### ISSUE TITLE
how to get observable of the B store.js again at A store.js

### ISSUE THREAD

**Issue by ctyyy** [mobxjs/mobx-react#519]

**Comment by ctyyy** [comment]
I want to get the observable of B store.js directly from A store.js

**Comment by mweststrate** [comment]
Try to imagine someone else is reading this issue. How is he supposed to
make sense of it? Please share code, what you observed, what you expected
etc.

Op vr 20 jul. 2018 09:38 schreef ct99610 <notifications@github.com>:

**Comment by frangeris** [comment]
Is it possible to access store B from store A?

Simple use case would be: you make a request to `/user/123` and it give you something like this:

```
{
    ....
    books: [.....]
}
```

What about if you want to save those `books` inside their own store?

```js
// books
export defaut class Books {
     @observable data = []
}

// user
export defaut class User {
     @action get () {
          axios.get('/user/123')
              .then(response => {
                  books.data = response.data.books // <----- HOW DO THIS (ACCESS BOOKS)?
              })
     }
}
```

**Comment by mweststrate** [comment]
Please note that you are responding to a closed issue, meaning that most
won't see it.

You can do what you want in as many ways as javascript has. For example,
pass a books instance to the get function. Or to the User constructor when
creating it. Or make books a singleton and import it. It doesn't matter for
the technical working of mobx so just organize your stores in the way you
think is appropriate

Op zo 29 jul. 2018 08:19 schreef Frang Peguero <notifications@github.com>:

**Comment by mweststrate** [comment]
Can you open a fresh issue first before continuing the conversation?

Op zo 29 jul. 2018 15:28 schreef Frang Peguero <notifications@github.com>:
