### ISSUE TITLE
React should not be imported from react-native in RN 0.25+

### ISSUE THREAD

**Issue by tlvenn** [mobxjs/mobx-react#52]
React and all components that belong to it are no longer provided by React Native (0.26) and it's deprecated in 0.25.X.

`import React from 'react-native' -> import React from 'react'`

**Comment by mweststrate** [comment]
Thans for notifying. This means in the future it will be possible to use the generic `import {observer} from `mobx-react/custom` as well :) (the standard version has a dependency on the DOM, i'll investigate whether that could be factored out as well)

**Comment by mweststrate** [comment]
@tlvenn fixed and released as 3.2.0. Thanks for reporting.

**Comment by tlvenn** [comment]
Thanks @mweststrate !
