### ISSUE TITLE
Observer component doesn't work without @observer in parent container

### ISSUE THREAD

**Issue by knightlore** [mobxjs/mobx-react#521]
I've tried using the Observer component alone and the render is never triggered, I need to mark the parent class with the @observer decorator to make it work.

The documentation doesn't show that, I'm doing something wrong?

**Comment by mattruby** [comment]
Please create a codesandbox.io example

**Comment by knightlore** [comment]
I've created a sandbox and it works, but not in a test I'm working on. Really no idea why, there is nothing too complex or weird to cause this, maybe weback and its dev server...
I will try to create a simple repository to show the issue, in case it is an issue to report.
Thanks

**Comment by mweststrate** [comment]
Is the decorator's plugin the first one?

Op vr 27 jul. 2018 14:23 schreef knightlore <notifications@github.com>:

**Comment by knightlore** [comment]
I'm using Typescript 2.9.2 with target es6, no other transpilers.

**Comment by knightlore** [comment]
Seems to work under certain circumstances, but fails in others.
Will try to isolate the issue and if it is a real issue will post here again.
Thank you all for the support.
