### ISSUE TITLE
How to access/inject others stores from store

### ISSUE THREAD

**Issue by frangeris** [mobxjs/mobx-react#524]
Is it possible to access store B from store A?

Simple use case would be: you make a request to `/user/123` and it give you something like this:

```
{
    ....
    books: [.....]
}
```

What about if you want to save those `books` inside their own store?

```js
// books
export defaut class Books {
     @observable data = []
}

// user
export defaut class User {
     @action get () {
          axios.get('/user/123')
              .then(response => {
                  books.data = response.data.books // <----- HOW DO THIS (SET BOOKS STORE)?
              })
     }
}
```

This is not related specifically to ways in js, in vuex for example we can access/call others actions, mutations from any store, just specifying `{ root: true }` when calling, I need to mutate books and I don't want to depends strictly of  js.

Have mobx any way to do this?

I tried to inject the store `Books` inside `Users` and broke the object, sorry if I'm not understanding right any concept.

Thanks,

**Comment by justinhorner** [comment]
Can you not just import the books store in the User store?

**Comment by makepost** [comment]
Documentation explains how to [combine multiple stores](https://mobx.js.org/best/store.html#combining-multiple-stores) by passing one's dependencies to its constructor. My take on this, which helps in bigger projects with [serverside](https://github.com/makepost/serverside):

```js
export class Services {
  /**
   * @param {typeof window.fetch} fetch
   */
  constructor(fetch, initialState = {}) {
    const translationService = new TranslationService();

    // ---

    const apiService = new ApiService({
      fetch,
      translationService
    });

    // ---

    const blogService = new BlogService({
      apiService,
      translationService
    });

    // ---

    this.apiService = apiService;
    this.blogService = blogService;
    this.translationService = translationService;

    new ClientObservable(this).copyFrom(initialState);
}
```

```js
const services = new Services(fetch.bind(window), window.__INITIAL_STATE__);

// Debug.
Object.assign(window, services);

ReactDOM.render(
  <Provider {...services}>
    <BrowserRouter onUpdate={() => window.scrollTo(0, 0)}>
      <App />
    </BrowserRouter>
  </Provider>,
  document.getElementById("root")
);
```

**Comment by mweststrate** [comment]
There are many issues in the mobx repository already discussing this, and the answer is basically: for mobx itself it doesn't matter, so it is up to you how you organize your state. My recommendation is to indeed pass stores a reference to each other upon, or right after construction. 

But you might also use mobx-state-tree which has opinions on this, use a dependency injection tool like InversifyJS, or just pass stores in when calling actions, and use React context / Provider+inject to pass stores around the component tree
