### ISSUE TITLE
use inject get warning its value is undefined when i set propTypes is required

### ISSUE THREAD

**Issue by bayun2** [mobxjs/mobx-react#525]
index.js
`import React from 'react';
import ReactDOM from 'react-dom';
import 'todomvc-app-css/index.css'
import App from './App';
import TodoStore from './stores/TodoStore';
import ViewStore from './stores/ViewStore';
import {Provider} from 'mobx-react';
import registerServiceWorker from './registerServiceWorker';

const initState = [];
const todoStore = TodoStore.fromJS(initState);
console.log('todoStore', todoStore);
const viewStore = new ViewStore();
console.log('viewStore', viewStore);
ReactDOM.render((
  <Provider viewStore={viewStore} todoStore={todoStore}>
    <App/>
  </Provider>), document.getElementById('root'));
registerServiceWorker();`

app.js
`
import React, { Component } from 'react';
import PropTypes from 'prop-types';
import {observer, inject} from 'mobx-react';
import TodoEntry from './components/TodoEntry';
import TodoOverview from './components/TodoOverview';

@inject(allStores => ({
  viewStore: allStores.viewStore,
  todoStore: allStores.todoStore
}))
@observer
class App extends Component {
  render() {
    return (
      <TodoEntry />
    );
  }
}

App.propTypes = {
  viewStore: PropTypes.object.isRequired,
  todoStore: PropTypes.object.isRequired
}

export default App;`

![image](https://user-images.githubusercontent.com/3183696/43756251-5c1d5b42-9a46-11e8-94b4-ccc7f1fc1d90.png)

**Comment by mweststrate** [comment]
You are now setting the propTypes of the inject wrapped component, which obviously doesn't receive these props as that is the whole point of `inject`. Set the propTypes on the original component instead. use `static propTypes = ...` in your class definition or `App.wrappedComponent.propTypes = `
