### ISSUE TITLE
Performance drops with useStaticRendering(true)

### ISSUE THREAD

**Issue by makepost** [mobxjs/mobx-react#526]
On a server-rendered production website, render methods take much more time with [useStaticRendering](https://github.com/mobxjs/mobx-react#server-side-rendering-with-usestaticrendering) enabled. Seem to recurse a lot when dealing with computed values.

![screen shot 2018-08-08 at 17 21 53](https://user-images.githubusercontent.com/20999066/43843949-4e180b3c-9b31-11e8-98dc-037e4ac6298d.png)

Unfortunately I can't publish the code of the website, but according to the profiler, here's the function beginning to spend all this time:

![screen shot 2018-08-08 at 17 48 21](https://user-images.githubusercontent.com/20999066/43844901-6cd5d692-9b33-11e8-8a10-db54d6ad585a.png)

It's minified but looks like [makeComponentReactive](https://github.com/mobxjs/mobx-react/blob/9fd635890c2cf4f975feb479768d47d3c444fd7f/src/observer.js#L145) from mobx-react.

Versions: mobx@5.0.3, mobx-react@5.2.3, react-dom@16.4.2

**Comment by mweststrate** [comment]
This might be because computeds will become cold if nobody is observing them, in which case every read is a cache-miss. This might be slow if you have computed values which you read a lot, or which are expensive. An option would be to use `keepAlive` from mobx-utils, or the [`keepAlive` option](https://mobx.js.org/refguide/computed-decorator.html#options-for-computed) on the expensive computed values. Depending on what the computeds are about, make sure to take care of the correct lifecycle of your computed values! `keepAlive` from mobx-utils returns a disposer function that you might want to invoke when the current request handling ends, or the current session, or whatever is appropiate :)

**Comment by makepost** [comment]
Definitely what you're saying, `computed` especially helps memoize often accessed but rarely changing heavy getters. For example, localization (1156 calls as of now), and option filtering based on current search and a pattern derived from user input.

Have just tried setting up alive-keeping manually. With app-wide localization this is ok. But with everything else there are too many places, so this quickly becomes dirty.

Maybe `useStaticRendering` could accept `{ keepAlive: true }` as an optional argument, which lets the reactions create, but makes them save their disposers to a private array inside the module? The former would return a function calling all those disposers, clearing the array and resetting the `isUsingStaticRendering` flag.

```js
const disposeObservers = Mobx.useStaticRendering(true, { keepAlive: true });
this.html = Dom.renderToString(root);
disposeObservers();
```

If this doesn't look too hacky to you, will try making a PR.

**Comment by urugator** [comment]
@makepost You would also have to make sure that these created `reactions` are never actually invoked...

Perhaps following could do the trick?
```javascript
Mobx.useStaticRendering(true);
const dispose = reaction(() => {
  const root = React.createElement(App);
  this.html = Dom.renderToString(root);
}, ()=>{})
dispose();
````

**Comment by makepost** [comment]
@urugator Thanks! Indeed, wrapping the `renderToString` call with an `autorun` or `reaction` helps. Whether `createElement` is inside or outside doesn't seem to affect, so should probably keep it outside.

**Comment by maranomynet** [comment]
This makes me wonder if `mobx-react` should provide its own `renderToString/Markup/NodeStream` methods that takes care of all this workaround - including `useStaticRendering()`.

Something along the lines of...

```js
import { renderToString } from 'react-dom/server';

const mobxRenderToString = (element) => {
    mobx.useStaticRendering(true);
    reaction(
        () => { renderToString(root); }, 
        ()=>{}
    )();
}

const mobxRenderToStaticMarkup = (element) => {
    mobx.useStaticRendering(true);
    reaction(
        () => { renderToStaticMarkup(root); }, 
        ()=>{}
    )();
}

export {
    mobxRenderToString as renderToString,
    mobxRenderToStaticMarkup as renderToStaticMarkup,
}
```
