### ISSUE TITLE
React Native 0.56: Using the export keyword between a decorator and a class is not allowed

### ISSUE THREAD

**Issue by oriharellance** [mobxjs/mobx-react#528]
RN 0.56 throws an error when trying to use this code:

```
import { inject } from "mobx-react/native";

@inject("userStore")
export default class SomeComponent extends Component<Props> {
  render() {
    return (
      <View style={styles.container}>
        <Text style={styles.welcome}>Welcome to React Native!</Text>
        <Text style={styles.instructions}>To get started, edit App.js</Text>
        <Text style={styles.instructions}>{instructions}</Text>
      </View>
    );
  }
}
```

The error is: 

> **Using the export keyword between a decorator and a class is not allowed. Please use `export @dec class` instead**

**package.json:**

```
{
  "name": "AwesomeProject56",
  "version": "0.0.1",
  "private": true,
  "scripts": {
    "start": "node node_modules/react-native/local-cli/cli.js start",
    "test": "jest"
  },
  "dependencies": {
    "mobx": "^5.0.3",
    "mobx-react": "^5.2.3",
    "react": "16.4.1",
    "react-native": "0.56.0",
    "react-navigation": "^2.11.2"
  },
  "devDependencies": {
    "babel-jest": "23.4.2",
    "babel-plugin-transform-decorators-legacy": "^1.3.5",
    "babel-preset-react-native": "^5",
    "jest": "23.4.2",
    "react-test-renderer": "16.4.1"
  },
  "jest": {
    "preset": "react-native"
  }
}

```

**.babelrc:**

```
{
  "presets": ["babel-preset-react-native"],
  "plugins": ["transform-decorators-legacy"]
}

```

**Comment by mweststrate** [comment]
The error seems pretty self explanatory?

The actual parsing rules for these construction are still under debate in
TC39, so for now I would just follow what your transpiler prescribes

Op do 9 aug. 2018 om 15:25 schreef oriharellance <notifications@github.com>:

**Comment by oriharellance** [comment]
@mweststrate You mean writing this?

```
import { inject } from "mobx-react/native";

export default @inject("userStore") class SomeComponent extends Component<Props> {
...
}
```

:(

**Comment by mweststrate** [comment]
Yes

Op do 9 aug. 2018 om 21:55 schreef oriharellance <notifications@github.com>:

**Comment by oriharellance** [comment]
This would mean refactoring dozens of components plus ugly red marks in the WebStorm as it doesn't like that. For now I avoided upgrade because of this...

**Comment by EyMaddis** [comment]
You have to set allow this in babel:

```js
plugins: [
  [
      '@babel/plugin-proposal-decorators',
      { 
         legacy: true, 
         decoratorsBeforeExport: true  // <------
      },
    ]
...
]
```

**Comment by mweststrate** [comment]
@oriharellance 

> This would mean refactoring dozens of components plus ugly red marks in the WebStorm as it doesn't like that. For now I avoided upgrade because of this...
 
Refactoring is a big word for a mostly simple find and replace ;-). But this is something to report in the babel repository instead, mobx has no influence on the syntax that is supported by your transpiler.

@EyMaddis tnx!

**Comment by oriharellance** [comment]
Thanks @EyMaddis !
However it now says:

`error: bundling failed: Error: [BABEL] /Users/oriharel/code/AwesomeProject56/App.js: 'decoratorsBeforeExport' can't be used with legacy decorators. (While processing: "/Users/oriharel/code/AwesomeProject56/node_modules/@babel/plugin-proposal-decorators/lib/index.js")`

**Comment by oriharellance** [comment]
@mweststrate I must disagree here, as it's not about the find and replace. this new way of using decorators (which is one of MobX advantages) is making the code less readable - again, something that made MobX so much superior than other solutions. I'm injecting multiple stores inside components which makes this convention even less usable.

I agree there is an argument that this is not a MobX-react issue, however, there is so much usage of decorators in MobX (I myself got to know decorators because of MobX, and I bet a bunch of other developers too) that I'd expect at least a reference if not a solution on this thread. I'd wish you let this issue resolved before closing it.

Thanks.

**Comment by mweststrate** [comment]
Sorry, assumed the proposed solution would work. Beyond that, please open an issue at babel or TC39 instead. 

Beyond that, I don't think there is any solution we can offer, beyond suggesting to downgrade babel? 

Probably documentation should be updated, if this change is going to be persisted. But I think it is still to early for that, as the the final vote hasn't been cast yet. See https://github.com/tc39/proposal-decorators/issues/69 for some background

**Comment by soneymathew** [comment]
I encountered a similar situation while upgrading relay. 
https://github.com/facebook/relay/issues/2505
@oriharellance I can relate to the pain of refactoring large codebases to adapt to this one.

**Comment by soneymathew** [comment]
Here is a rule to help you find the occurrences, if you use eslint
https://astexplorer.net/#/gist/aba9ffaf77d163b5a9b7318e0d3ee455/5200fff2efa44a6e1343b8038628981773b8d7e1

**Comment by mweststrate** [comment]
Closing for now, as this library can't influence it and one has to use whatever syntax the transpiler in use prescribes. Once the proposal has progressed further we can update the documentation accordingly. But the final verdict wasn't made yet in the TC39 whether this will be the final syntax. Once that decision has been made docs can be updated accordingly, but that is still too early now and the error is extremely self explanatory imho.

**Comment by skiritsis** [comment]
Sorry to open this again, but you can add the following in your ESLint configuration to get rid of the error.

```
{
  parserOptions: {
    ecmaFeatures: {
      legacyDecorators: true
    }
  }
}
```

**Comment by mweststrate** [comment]
Also note that `@babel/plugin-proposal-decorators`  has now the option `decoratorsBeforeExport` which can be set to true. However, that is not relevant yet as in `legacy` mode it is not supported yet.

**Comment by adirzoari** [comment]
@skiritsis  where can I see ESlint configuration in visual studio?
here?
![image](https://user-images.githubusercontent.com/20258998/49020437-1a664380-f199-11e8-89d9-9bd27ec27931.png)

**Comment by skiritsis** [comment]
@adirzoari I meant the files that can be in the form of an `.eslintrc.*` file or an `eslintConfig `field in your package.json file, both of which ESLint will look for and read automatically.

You can check the documentation [here](https://eslint.org/docs/user-guide/configuring#specifying-parser-options).

**Comment by trenthogan** [comment]
> @oriharellance You can add the following in your ESLint configuration to get rid of the error.
> 
> ```
> {
>   parserOptions: {
>     ecmaFeatures: {
>       legacyDecorators: true
>     }
>   }
> }
> ```

@skiritsis Thanks for this :)
