### ISSUE TITLE
Add functionality to prevent componentWillReact

### ISSUE THREAD

**Issue by jpmoyn** [mobxjs/mobx-react#529]
I have a case where I am grabbing an array from a mobx store, and sorting the elements within a `Component`, but under certain application states I do not want the `@observer` to update the sorting of the elements.

Similar to `shouldComponentUpdate`, I want the ability to `return false` for the `componentWillReact`, to prevent the re-rendering.

I am able to put the `@observer` functionality into the parent component, pass the data as a prop, and use `shouldComponentUpdate`, but having the ability to manually prevent renders from mobx would be nice.

Could this functionality be added?

**Comment by mweststrate** [comment]
Nope, if some state should not be reflected in your UI, that fact itself should be part of your state rather than implicitly decided. If an object can be in two states at the same time, you should use two objects.

**Comment by jpmoyn** [comment]
Well I am sourcing the elements of the sorted array from a data store, which gets populated reactively with sockets. I don't want to prevent the data store from loading new elements by adding the sort conditional there, but in some cases I want to prevent this from being re-sorted within the component.

I did workaround the issue by loading the data store into the parent component of the sorted list, and passing the data store to the sorted list as a prop. But it seems like there would be a few different use cases outside of my own example where someone would want to say `return false` to `componentWillReact`. Is this always an anti-pattern?

**Comment by mweststrate** [comment]
If your elements can be in two different states of sorting, I would just express this explicitly, I recommend giving the component a local state containing the alternative sorting. Having the rendering deviate from the actual state will just cause confusing down the road, and peers might not grab that this was intentional. Storing such devations explicitly in your state clearly communicates that it is intentional.

**Comment by jpmoyn** [comment]
Beyond my example, I think there are uses for preventing a render within the `componentWillReact` lifecycle function. I saw others sharing this opinion in #50. I just want to be clear that you are saying this is not something that will ever be implemented?

**Comment by mweststrate** [comment]
Nope, I don't think it fits the MobX model :)
