### ISSUE TITLE
Built in support for connecting stores to components

### ISSUE THREAD

**Issue by arahansen** [mobxjs/mobx-react#53]
A common pattern I see arising is the need to connect a component to one or many mobx stores. 

Currently, you need to write your own higher order component that will fetch these stores. While this isn't a monumental task in itself (as mobx makes this type of thing relatively straight forward), it would be great to have this feature built into mobx-react to promote a standardized method to accomplish this.

Looking to react-redux for inspiration, I see a lot of ideas there that could gracefully transfer over to mobx-react.

One approach is to wrap the application's Root component in a higher order store provider component that will inject application stores into the application's context. Then retrieve stores with an `@connect` (or similar) decorator that defines which stores should be connected.

Another approach is to "register" stores with react-mobx at their definition. Then, use a similar `@connect` decorator as described above to fetch one or several registered stores.

I would like to start a discussion as to why this does/doesn't make sense for mobx-react. And if it does make sense, get other thoughts on the table.

**Comment by kuuup** [comment]
Take a look at react-tunnel. It is inspired by redux and a great match for mobx.

**Comment by mweststrate** [comment]
See pull request #65 , build `3.4.0-beta.1` can be used to test and give feedback on the new Provider mechanism. Docs: https://github.com/mobxjs/mobx-react/blob/provider/README.md#provider-experimental

**Comment by mweststrate** [comment]
Released as 3.4.0!
