### ISSUE TITLE
intellisense for mobx stores?

### ISSUE THREAD

**Issue by marialovesbeans** [mobxjs/mobx-react#531]
Is there anyway in **VSCode** to **intellisense** (cmd+click to peek at the definition) of a MobX Store?

Example, in the following code, is there possible to configure **VSCode** to **cmd+click** `userStore` and jumps to the definition of `UserStore` class? Thanks!

```javascript
@inject("userStore")
@observer
class User extends Component {
    render(){
        const { name } = this.props.userStore;
    }
}
```

**Comment by mweststrate** [comment]
This would work:

```
inject((stores: { userStore: UserStore }) => ({ userStore: stores.userStore}))
```

But there is no reliable way to do type lookups based on a string that might be provided in any of your source files.
