### ISSUE TITLE
Question: HOC order important

### ISSUE THREAD

**Issue by creambyemute** [mobxjs/mobx-react#534]
Hey there,

I'm using MobX with the HOCs instead of decorators and have run into a small problem today when I integrated i18next for translations (also with HOC).

I initially had it like 
```
export default inject("navStore", "authStore")(observer(translate(["settings", "i18n"], { wait: true })(SettingsScreen)));
```

Which made the switch/checkbox not rerender on value change.

Then I changed it to:
```
export default inject("navStore", "authStore")(translate(["settings", "i18n"], { wait: true })(observer(SettingsScreen)));
```
Or to (so it's not mixed up anymore)

```
export default translate(["settings", "i18n"], { wait: true })(inject("navStore", "authStore")(observer(SettingsScreen)));
```

Which made the switch/checkbox value change work/rerender again.

Should mobx always be the most inner hoc if the  other hoc isn't depending on mobx?

Should I use some compose utility?

Should I just switch to decorator syntax :P?

Cheers!

**Comment by mweststrate** [comment]
Yes, as stated in the documentation, order is important, that is both the case when using the decorators as function or with decorator syntax. `a(b(c))` is simply not the same as `b(a(c))`. `observer` should always applied first. So the most inner function call / right-most decorator.

**Comment by creambyemute** [comment]
Great, thanks for the quick and clear answer!
