### ISSUE TITLE
MobX isn't working properly with Jest + Enzyme

### ISSUE THREAD

**Issue by yvesbeutler** [mobxjs/mobx-react#538]
Hello everybody!

I'm creating a simple boilerplate consisting of React, MobX and a combination of Jest and Enzyme for testing. Unfortunately I have some issues with getting the components state inside the [ShallowWrapper](http://airbnb.io/enzyme/docs/api/shallow.html).

Normally this would be an Enzyme-related issue, but everything works fine if I don't use `inject` and `observer` from `mobx-react`.

**Button.jsx**
```javascript
import React, { Component } from 'react';
import { inject, observer } from 'mobx-react';

@inject('store')
@observer
export default class Button extends Component {
  constructor(props) {
    super(props);
    this.state = {
      clicked: false,
    };
  }

  handleClick = () => {
    this.setState({
      clicked: !this.state.clicked,
    });
  }

  render() {
    return (
      <div onClick={this.handleClick}>
        have I been clicked: {this.state.clicked}
      </div>
    );
  }
}
```

**Button.test.jsx**
```javascript
import React from 'react';
import { shallow } from 'enzyme';

import Button from './Button';

const sampleStore = {
  foo: 'bar',
};

describe('Organisms Button', () => {
  it('should get the state (even with mobx)', () => {
    const wrapper = shallow(<Button store={sampleStore} />);
    console.log('state', wrapper.state());
  });
});
```

In the screenshot you can see, that the state is always null. If I remove both decorators from the component, then the state is shown correctly. The props by the way are never affected.

![screenshot-jest](https://user-images.githubusercontent.com/17586961/44723096-540eac00-aacf-11e8-9395-58210027a4a7.png)

**Installed packages**
react: 16.4.2
mobx: 5.0.4
mobx-react: 5.2.5
jest: 23.5.0
jest-enzyme: 6.0.3
enzyme: 3.4.4 (with adapter-react-16)

So is this really a mobx issue or am I just not getting the point?

**Comment by mweststrate** [comment]
Inject is a HoC, so in shallow, button will never render. In non shallow,
make sure to find the button rather then grabbing state from the injector.
The most convenient solution is to separately export the injected and not
injected comp

Op di 28 aug. 2018 14:45 schreef Yves Beutler <notifications@github.com>:

**Comment by mweststrate** [comment]
See also: https://github.com/mobxjs/mobx-react#testing-store-injection
