### ISSUE TITLE
Way to detect which observable triggered the re-render?

### ISSUE THREAD

**Issue by scottmas** [mobxjs/mobx-react#539]
In debugging situations with components that touch lots of observables, I haven't found a good way to determine which observable precisely triggered a re-render. There's the `componentWillReact` lifecycle hook but that doesn't give me any insight into what observable precisely triggered the re-render. Is there any good way to determine this?

**Comment by scottmas** [comment]
Or for that matter, to determine precisely what observables the component is currently listening for changes to?

**Comment by mweststrate** [comment]
See mobx.trace()

Op do 30 aug. 2018 21:15 schreef scottmas <notifications@github.com>:
