### ISSUE TITLE
You have typo in defineProperty

### ISSUE THREAD

**Issue by Havunen** [mobxjs/mobx-react#540]
Hi!

I was doing port of this awesome module to Inferno and noticed typo in your code. I though I could contribute it back to you :)

Its here:
https://github.com/mobxjs/mobx-react/blob/master/src/observer.js#L53

It should be `writable`
for reference: https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Global_Objects/Object/defineProperty

:smiley:

**Comment by Havunen** [comment]
There is also another mistake here:
https://github.com/mobxjs/mobx-react/blob/master/src/observer.js#L49

which is missing `.call(....)`

**Comment by mweststrate** [comment]
Thanks for noticing! Fixed.
