### ISSUE TITLE
How to get correct ref，when @inject('store') @observer a Component？

### ISSUE THREAD

**Issue by ldhios** [mobxjs/mobx-react#544]
`
@inject('store')
@observer
 class Aa extends Component {
  
     constructor(props) {
        super(props);

          
     }
     show = () => {
     }
}

@inject('store')
@observer
 class Bb extends Component {
  
     constructor(props) {
        super(props);

          
     }
     show = () => {
       this.refs.aa.show()
     }
    render（）{
       return（
         <Aa ref={'aa'}/>
       ）
  }
}

`
when run these code 。 error is： show not a function。 After my debugging，this.refs.aa is a Injector object.  how to solve ？  thanks

**Comment by mweststrate** [comment]
use `refs.aa.wrappedInstance.show`

**Comment by ldhios** [comment]
Thank you for your reply ！！！

**Comment by mweststrate** [comment]
@ldhios next time be so kind to close the issue when solved :)

**Comment by yuri2peter** [comment]
solved but not good enough.

Please let us use like:

@inject('a', 'b', { refForward: true })
