### ISSUE TITLE
React 16.5.0: It is not recommended to assign props directly to state

### ISSUE THREAD

**Issue by asapach** [mobxjs/mobx-react#545]
After upgrading to [React 16.5.0](https://github.com/facebook/react/blob/master/CHANGELOG.md#1650-september-5-2018) I now see the following warning:

`Warning: Provider: It is not recommended to assign props directly to state because updates to props won't be reflected in state. In most cases, it is better to use props directly.`

This seems to be caused by this line:
https://github.com/mobxjs/mobx-react/blob/54dd1a86cbdfb07f28fd6ce09879eb351b7b92ff/src/Provider.js#L18

Relevant changes in React: https://github.com/facebook/react/issues/11593 and https://github.com/facebook/react/pull/11658

**Comment by mweststrate** [comment]
Could you create a small sandbox isolating the issue?

Op do 6 sep. 2018 21:13 schreef Aliaksei Sapach <notifications@github.com>:

**Comment by asapach** [comment]
Here's the sandbox: https://codesandbox.io/s/z241341v9l?expanddevtools=1
Example taken from the readme.

**Comment by yuminjustin** [comment]
I also met today.

package versions：
![image](https://user-images.githubusercontent.com/8414340/45197583-a486c600-b294-11e8-96d9-1cdd55c7fc1d.png)

It's came from Provider，but it doesn't affect the project running
![image](https://user-images.githubusercontent.com/8414340/45197600-bd8f7700-b294-11e8-94e9-962f32bce9dc.png)

**Comment by urugator** [comment]
Why? The copy is just to satisfy react's check:
https://github.com/facebook/react/pull/11658/commits/4268592b06435d46a6ab826a0e0210e6a5d6dfe5#diff-b69c8f2165f95ef2355ac661c12fa407R679

**Comment by mkhuda** [comment]
This also happened on https://github.com/zeit/next.js/tree/canary/examples/with-mobx (newest NextJS with Mobx store)

**Comment by mweststrate** [comment]
Will investigate early next week, probably not too hard to adjust :)

Op vr 7 sep. 2018 om 18:06 schreef Lek Huda <notifications@github.com>:

**Comment by gaearon** [comment]
Since you're handling that manually later `this.state = {...props}` is fine.

Avoid writing code like this in your apps though, it's usually a bug. :-)

**Comment by mweststrate** [comment]
@gaearon 

>  it's usually a bug. :-)

But since it is always warned about, I guess it is now always a bug (or at least perceived as such, I think most people are not ok with a, for them, unpreventable warning always showing up), or is there a way to disable the warning? (I'm fine setting it up differently, just wondering)

**Comment by mweststrate** [comment]
Fixed and releases as 5.2.8!

**Comment by inoyakaigor** [comment]
@mweststrate why you change `...spread` by `Object.assign`?

**Comment by mweststrate** [comment]
Caused issue in the build, but anyway the next commit I all cleaned it up a
bit :)

Op ma 10 sep. 2018 om 20:48 schreef Igor «InoY» Zvyagintsev <
notifications@github.com>:

**Comment by billysin** [comment]
Thanks mweststrate

**Comment by FishPlusOrange** [comment]
awesome :100:

**Comment by FredyC** [comment]
@FishPlusOrange Seriously? Please refrain from commenting on old and closed issues, especially if you only want to express gratitude...
