### ISSUE TITLE
warnings in Provider with react 16.5

### ISSUE THREAD

**Issue by titouancreach** [mobxjs/mobx-react#549]
React 16.5 has added a new [warning](https://github.com/facebook/react/blob/master/CHANGELOG.md) when state is initialized to props. 
Since the update I can see this warning in my devtools caused by react-mobx Provider

I use version: 5.2.6 and mobx 4.4.0

**Comment by urugator** [comment]
https://github.com/mobxjs/mobx-react/issues/545#issuecomment-419952041

**Comment by titouancreach** [comment]
oops, sorry for duplicate!
Thanks!
