### ISSUE TITLE
[React Native] - Observable property not initialized (empty store)

### ISSUE THREAD

**Issue by corasan** [mobxjs/mobx-react#550]
When I try to use my Mobx stores the observables are not there, not initialized. For example:

**AStore.js**

    class A {
      @observable prop1 = ''
    }

**App.js**
    
    @observer
    class App extends Component {
      constructor() {
        this.store = new A()
      }
    }

When I `console.log(this.store)` its an empty object. I've used Mobx before and have always declared my `@observables` like in `class A`, in fact, I'm literally copying a previous project I used Mobx.

**Comment by mweststrate** [comment]
Don't trust console.log. try printing the actual value,  it is most
probably there

Op do 13 sep. 2018 22:17 schreef Henry Paulino <notifications@github.com>:

**Comment by corasan** [comment]
@mweststrate  Nope, still empty. Nothing in my store

**Comment by corasan** [comment]
Even doing something like this won't work:

```javascript
class App extends Component {
  @observable prop1 = 'hello'

  render() {
    return <Text>{this.prop1}</Text>
  }
}
```

**Comment by corasan** [comment]
I restarted my project and now it works fine, thanks for the support.
