### ISSUE TITLE
Observer HOC breaks HMR in nested components

### ISSUE THREAD

**Issue by tibotiber** [mobxjs/mobx-react#559]
Hi, thanks for the great work on MobX and co. 

I've got what I think is a bug in the `observer` HOC. It looks a lot like #500 but I haven't been able to solve it by following tips there and i'm on latest version of all deps. HMR actually work on my top level component (`App`) but breaks for nested components (i.e. it doesn't re-render on file changes). This happens for all nested components. If I remove `observer` from the nested component and leave it on `App` it re-render properly. 

I've posted a minimal example at https://github.com/tibotiber/mst-hmr-bug. 

Hope you guys can point me in the good direction or I can help identify / fix a bug if any. Happy to provide more context if needed. 

Thanks.

**Comment by theKashey** [comment]
```js
import { AppContainer } from 'react-hot-loader'
....
module.hot.accept('./components/App', () => {
    render()
  })
```
I would suppose - dont use AppContainer, dont use Webpack HMR API.
Wrap `App` with `hot`, and let React-Hot-Loader handle the stuff.
```js
// App.js
import { hot } from 'react-hot-loader'
...
export default hot(module)(observer(App))

**Comment by jiachaosun** [comment]
@theKashey 
Problem is still there.

If a component just has props from outsider, HMR worked
If a component has props and state inside, HMR broken!

**Comment by tibotiber** [comment]
@theKashey thanks for your response and sorry for the late reply, was traveling. I've pushed a branch with the suggested changes (https://github.com/tibotiber/mst-hmr-bug/commits/use-hot). Seems to be having no impact. 🤔

@jiachaosun I haven't been able to observe your "if no state ok, if state not ok". In my minimal example, say you change the `Counter` component which has no state, it doesn't hot reload.

**Comment by theKashey** [comment]
🤞

**Comment by tibotiber** [comment]
@theKashey sorry, I’m not sure what you mean by that..?

**Comment by mweststrate** [comment]
Personally I didn't try to setup HMR anymore for the last few years, it always caused more headaches to me than it actually solved. If anybody wants to investigate or improve, writing a useful guide is welcome. Otherwise, will close this issue in a while.

**Comment by Kruemelkatze** [comment]
The fixes suggested in #500 did not work for me either. But by downgrading mobx-react to ***5.2.8*** I got a minimal setup (where I could consistently reproduce that HMR bug before) to work. See [my comment for additional info](https://github.com/mobxjs/mobx-react/issues/500#issuecomment-436353688).

I don't know if this "fix" will work in more sophisticated projects. So it would also be great for me to have some outside eyes looking at that. :)

**Comment by tibotiber** [comment]
@mweststrate thanks for the honest feedback. I might be taking that way as well. It's really nice to have HMR but indispensable.

**Comment by ConneXNL** [comment]
Considering the rework in 6.*, is there a chance 'react-hot-loader' could get another view?

**Comment by mweststrate** [comment]
If anybody wants to dive into that, help is welcome.

**Comment by yuhongda** [comment]
same problem when using react-refresh
