### ISSUE TITLE
onError should return a dispose function

### ISSUE THREAD

**Issue by superwf** [mobxjs/mobx-react#564]
run onError is to subscribe something
but there is no way to release it now.

**Comment by urugator** [comment]
You sure? 
`export const onError = fn => errorsReporter.on(fn)`
https://github.com/mobxjs/mobx-react/blob/9fd635890c2cf4f975feb479768d47d3c444fd7f/src/utils/EventEmitter.js#L4-L10

**Comment by superwf** [comment]
yes, that is what I mean.
I only read the doc, skip the source. It is my careless.
