### ISSUE TITLE
reaction.bound?

### ISSUE THREAD

**Issue by ShaMan123** [mobxjs/mobx-react#566]
I'm using `mobx`  with `react-native`.
Didn't know if to submit the issue here or in `mobx`.
Basically I'm looking for a `reaction.bound` alias. Reference: [@action.bound](https://mobx.js.org/refguide/action.html#bound-actions)

### Bug
When I try something like this:
```
@observer
class extends Component {
             r = reaction(
                () => someObservableNonStaticArgReturnValue,
                (retVal) => {
                    //  doStuff
                }
            )
}
```
I get an error. Snooping around made me notice that the `this` arg refers to the static class instead of the instance of the class as it should be => meaning I can't access anything useful.

### Work around:
When declaring a `reaction` in the constructor it all works => the `this` arg is referenced correctly.
```
@observer
class extends Component {
   constructor(props) {
      ...
           this.r = reaction(
                () => someObservableArgReturnValue,
                (retVal) => {
                    //  doStuff
                }
            )
   }
}
```

**Comment by mweststrate** [comment]
`Snooping around made me notice that the this arg refers to the static class instead`

That is not in line with what the https://github.com/tc39/proposal-class-fields does, so either the proposal seems to be set up wrong, or there is a mistake in your example.

Please set up an actually runnable reproduction, in for example code sandbox

**Comment by ShaMan123** [comment]
[sandbox](https://codesandbox.io/s/32k7noolop)
comment line 47

**Comment by mweststrate** [comment]
@ShaMan123 the issue in your example is that `this.appState` is not set when you start your reaction (as the reaction is created _before_ the constructor runs. I've pulled out `appState` to a global variable to prove that the reaction itself is created and bound correctly: 

https://codesandbox.io/s/7m8y4z3511

In general, as soon as `this` plays a role in your field initializers, I strongly recommend to do it in a constructor, to avoid issues where you are quite implicitly depending on initialization order of fields.
