### ISSUE TITLE
mobx.trace detects invalidation of render(), but render is not called for transitive dependencies when an HTMLCanvasElement is modified

### ISSUE THREAD

**Issue by mseddon** [mobxjs/mobx-react#568]
I have run into a weird situation where `mobx.trace(true)` is detecting invalidation, but the react component is not being re-rendered.

It seems that unless my `render()` method *directly* references a changed property, while `trace` reports this change, `render()` is not actually called.

Here's a code snippet:

```tsx
@inject("brush")
@observer
export class BrushView extends React.Component<{ brush?: Brush }> {
    render() {
        trace(true);
        console.log("in-render")

        return  <div className="brush-picker">
                    <div className="well"> { /*     /--- Brush.image @computed getter is dereferenced here */  }
                        <img src={this.props.brush.image.toDataURL("png")} width={this.props.brush.size.value} height={this.props.brush.size.value} />
                    </div>                 { /*               \-- Yes I know how slow this is :) */}
                    <div><label>Size</label><NumberField model={this.props.brush.size}/></div>
                    <div><label>Hardness</label><NumberField model={this.props.brush.hardness}/></div>
                    <div><label>Spacing</label><NumberField model={this.props.brush.spacing}/></div>
                </div>
    }
}

// underlying model object for a bounded numeric range
export class RangeModel {
    @observable
    private _value: number;

    constructor(value: number, private _min: number = Infinity, private _max: number = -Infinity) {
        this._value = value;
    };

    @computed get value() { return this._value }

    set value(v: number) {
        this._value = Math.min(this._max, Math.max(this._min, v));
    }
}

// Brush bitmap manager
export class Brush {
    size = new RangeModel(0, 1, 100);
    hardness = new RangeModel(0, 0, 100);
    spacing = new RangeModel(1, 1, 100)

    @computed
    get image() {
        /* ... update internal _image and return it- 
         *     dereferences this.size.value, this.hardness.value,
         *     _image is reused, only it's data is changed */
    }
}
```

Changing the size, which is directly referenced in the render() method, causes the log:
```
[mobx.trace] 'BrushView#113.render()' is invalidated due to a change in: 'RangeModel@4.value'
in-render
```
And the component is updated.
If I change hardness, then mobx.trace reports:
```
[mobx.trace] 'BrushView#113.render()' is invalidated due to a change in: 'Brush@50.image'
```

But render is never invoked, and the component remains stale.
If I add the dummy dereference of:
```ts
let x = this.props.brush.hardness.value
```
Then render will be invoked correctly, so it seems somehow the transitive dependencies, while detected, are not triggering a re-render.
```
> npm ls --depth 0
dodo@1.0.0 C:\code\dodo
...
+-- mobx@5.5.0
+-- mobx-react@5.2.8
+-- mobx-react-devtools@6.0.3
...
+-- react@16.5.2
+-- react-dom@16.5.2
+-- ts-loader@5.2.1
+-- typescript@3.1.1
`-- webpack@4.20.2
```

**Comment by mseddon** [comment]
So- the issue is happening because `BrushView.image` is re-using the same `HTMLCanvasElement`. The question now is- since mobx has detected the change, shouldn't render() be called again anyway?
It feels like an identity comparison (possibly in react) has erroneously considered this change as a NOOP. Is this by design? Or is React getting in the way somehow here?

**Comment by urugator** [comment]
`computed` really means "computed" or "derived", is shouldn't contain any side effects like updating internal _image.  
If the value returned from computed didn't change (you can provide custom comparator to computed), there is no need for invoking observers as their output shouldn't be affected.
The logic is the same as with other observables: `this.value = this.value;` also wouldn't cause re-render, because the value stays the same.

**Comment by mseddon** [comment]
Ah, okay, thanks for the clarification, that helps a lot. So how would I react to invalidating an image like this correctly, an autorun invoking `forceUpdate`?

**Comment by mseddon** [comment]
I guess
