### ISSUE TITLE
Unable to use MobX decorators in React Native 0.57

### ISSUE THREAD

**Issue by DaniAkash** [mobxjs/mobx-react#570]
React Native 0.57 now uses a new preset [metro-react-native-babel-preset](https://github.com/facebook/metro/tree/master/packages/metro-react-native-babel-preset#metro-react-native-babel-preset) which actually removes some used babel helpers in production. 

This was first noticed in 0.56 and referenced in the following issue facebook/react-native#20150 and I have been using the work-around suggested by @farwayer in the [issue's description](https://github.com/facebook/react-native/issues/20150#issue-340235017). However after upgrading to 0.57 the workaround doesn't work any more and following the [official documentation](https://mobx.js.org/best/decorators.html#enabling-decorator-syntax) didn't help. 

As it stands i'm unable to use mobx in my react native project upgraded to 0.57. Is there any plans to overcome this issue? Any workarounds will help too...

**Comment by DaniAkash** [comment]
Managed to figure out the problem was actually with the upgrade... hence closing this issue.

**Comment by vTrip** [comment]
could share any information on what went wrong with your upgrade?

**Comment by DaniAkash** [comment]
@vTrip refer my StackOverflow solution - https://stackoverflow.com/questions/52758721/how-to-use-mobx-with-decorators-in-react-native-0-57/52924449#52924449
