### ISSUE TITLE
Breaking build for apps using React < 16

### ISSUE THREAD

**Issue by saarkuriel** [mobxjs/mobx-react#572]
Hello 

The change introduced in version `5.3.0` and above causing apps using React 15 and typescript to fail build because of changing the type in `src/index.d.ts` line 67 and 69 to use the type `React.Component<any, any, any>`.

The Error: `error TS2707: Generic type 'Component<P, S>' requires between 0 and 2 type arguments.`

This type applies only for React types > 16 and therefore causing my app build (with React 15) to fail.

Thanks a lot and keep the amazing work on this library.

**Comment by xaviergonz** [comment]
@mweststrate just pushed to master a simple fix for this (just removing the last generic since it defaults to any in react 16)

**Comment by mweststrate** [comment]
In that case it is released already as part of 5.3.3 :-).

**Comment by mweststrate** [comment]
For reference: https://github.com/mobxjs/mobx-react/commit/83a5c5729fd7c3a9208bc2148c7abb4480fd7811
