### ISSUE TITLE
ejecting create-react-app v2 with webpack 4 for decorators support

### ISSUE THREAD

**Issue by rudijs** [mobxjs/mobx-react#575]
Hi,

The method of enabling decorators in create-react-app v2 seems to be different.

This doesn't seem to fit in with webpack v4:

```
"babel": {
  "plugins": ["babel-plugin-transform-decorators-legacy"],
  "presets": ["react-app"]
}
```
Anyone able to link to an blog post or suggest how it should be done now?

Thanks!

**Comment by rudijs** [comment]
The simplest way I've found is to:

1. npm eject
2. Update package.json. To the existing babel property add the plugins from the docs:

```
  "babel": {
    "presets": [
      "react-app"
    ],
    "plugins": [
      ["@babel/plugin-proposal-decorators", { "legacy": true}],
      ["@babel/plugin-proposal-class-properties", { "loose": true}]
  ]
  }
```

**Comment by diffractometer** [comment]
@mweststrate `Enable the compiler option "experimentalDecorators": true in your tsconfig.json` no longer works [for me] in a fresh CRA (ejected as of yesterday). Any guidance? Thanks in advance.

**Comment by mweststrate** [comment]
Please open a fresh issue, with sufficient details, such as steps,
versions, errors, etc

Op wo 9 jan. 2019 om 18:07 schreef Hunter Husar <notifications@github.com>:
