### ISSUE TITLE
Add changelog

### ISSUE THREAD

**Issue by th0r** [mobxjs/mobx-react#58]
Hi! Thanks for the great lib but it's very inconvenient to track changes between versions.
It would be great either to add `CHANGELOG.md` or attach this info to new [releases](https://github.com/mobxjs/mobx-react/releases).
Thanks!

**Comment by th0r** [comment]
Ah, sorry, found it in the end of `README.md`.

**Comment by mweststrate** [comment]
you are right though, this is uncommon, I'll move the changelog to a seperate file.
