### ISSUE TITLE
Layered Architecture for React + Typescript + Mobx to ensure SoC

### ISSUE THREAD

**Issue by ryoldash** [mobxjs/mobx-react#584]
Dear community,

It's been long time that I am working with React+Mobx+Typescript. I couldn't find tangible architecture for React+Mobx+Typescript, so I designed my applications with utilizing MVC design pattern and layered architecture as follows: 

- All Backend communications are done by service layer.
- For every Container Component there exists one Store and one Model. 
- Store has state of application so it consumes service [ See "Defining data stores"](https://mobx.js.org/best/store.html). All service functions will be called in store not in Component. Component executes Store actions when state is needed. 
- Presentational Component can use store directly by injecting the store or Props from Container Component can be passed in it. 
- Container or Presentational Component can invoke store actions and automatic rendering of component will be done by Mobx.

I have used InversifyJS IoC container to ensure dependency inversion. All of my services has one interface and one implementation, so I can easily use mocks when writing tests. 

Does this architecture make sense for React+Mobx+Typescript? 

![layered architecture for react mobx typescript single page applications](https://user-images.githubusercontent.com/34941214/47382420-f54e6300-d70a-11e8-890b-0f119b5e9b80.jpg)

**Comment by hamczu** [comment]
Sounds interesting but I'd be great if you could create a small repository that shows all of this in action

**Comment by ryoldash** [comment]
@hamczu and @mweststrate I am preparing a complete project for this proposal. When finished I will share the repo.

**Comment by slesulvy** [comment]
@ryoldash When you finish please share with us, I am looking like this few week ago.
Thank you
