### ISSUE TITLE
Using observer with new React hooks does not work

### ISSUE THREAD

**Issue by FredyC** [mobxjs/mobx-react#591]
https://codesandbox.io/s/vjy5j1xx93

React hooks is still in the oven, I do realize this, but obviously using `observer` as HOC does something strange to make the React think it's not a regular component.

**Comment by Yauheni-blr** [comment]
hope this tweet would help you.
https://twitter.com/mweststrate/status/1055532227939966976

**Comment by FredyC** [comment]
@Yauheni-blr Thanks for the link, it looks great indeed, but I don't know what am I doing wrong then. Is there some unpublished `mobx-react` version that works with hooks? @mweststrate Can you please share it, looks really amazing :)

**Comment by FredyC** [comment]
Closing in favor of #588
