### ISSUE TITLE
Can I call a store action in a stateless component?

### ISSUE THREAD

**Issue by obiwarn** [mobxjs/mobx-react#593]
The JSON prints the content of the current store just fine.
But inside the addNewTodo the store (this in this.todos.push(todo)) is undefined.

```
const MainMenu = inject('store')(
  observer(({ store }: IMainMenuProps) => (
    <Menu>
      {JSON.stringify(store)}
      <Dropdown item={true} text="Datei">
        <Dropdown.Menu>
          <Dropdown.Item onClick={store!.addNewTodo}>Neu</Dropdown.Item>
        </Dropdown.Menu>
      </Dropdown>
    </Menu>
  ))
);
```

**Comment by urugator** [comment]
Is `addNewTodo` bound to `store`?

**Comment by obiwarn** [comment]
Yes Store is a class with @action addTodo.

**Comment by urugator** [comment]
That's not bound, use `@action.bound` or pass `() => addNewTodo()` to event handler instead...

**Comment by urugator** [comment]
For more info: https://reactjs.org/docs/handling-events.html
> You have to be careful about the meaning of this in JSX callbacks. In JavaScript, class methods are not bound by default. If you forget to bind this.handleClick and pass it to onClick, this will be undefined when the function is actually called.

> This is not React-specific behavior; it is a part of how functions work in JavaScript. Generally, if you refer to a method without () after it, such as onClick={this.handleClick}, you should bind that method.

**Comment by obiwarn** [comment]
`@action.bound` fixed it.

Thank you so much!
