### ISSUE TITLE
mobx computed value not updating at the first time but asking for a reload and then it's getting updated

### ISSUE THREAD

**Issue by shruthijanardhan123** [mobxjs/mobx-react#598]
On click of sign in after entering the username and password in the login page, it's not redirecting to the required page instead it's asking to reload. after reloading it's redirecting to the required page. when I debug, I can see that props of the user store (this.props.userStore.isAuthenticated) doesn't get updated for the first time. once reloaded I get the value of it.

**Expected Behaviour**: On click of sign-in, it must redirect to the required page.
**Observed Behaviour**: After clicking on submit and reloading, it's redirecting to the required page.

**userStore.ts**

`import { action, computed, observable } from "mobx";

interface IAdcUser {
  name: string | undefined
  token: string;
  role: string;
}

export default class UserStore {
  @observable
  public userObj: IAdcUser;
  @observable
  public pageLoading = false;
  @observable
  public errors: string | undefined = undefined;
  @observable
  public loginForm = {
    username: "",
    password: ""
  };

  constructor() {
    if (localStorage.userObj && localStorage.userObj.length) {
      this.userObj = JSON.parse(localStorage.userObj);
    }
  }

  @computed
  get isAuthenticated() {
    if (this.userObj && this.userObj.token) {
      return true;
    }
    return false;
  }
  @action
  public async login(username: string, password: string) {
    this.pageLoading = true;
    this.errors = undefined;

    this.loginForm = {
      username,
      password
    };

    const url = process.env.REACT_APP_BACKEND_URL + "/login/";
    const options = {
      body: JSON.stringify(this.loginForm),
      headers: {
        "Content-Type": "application/json"
      },
      method: "POST"
    };

    try {
      const loginResponse = await fetch(url, options);
      const json = await loginResponse.json();
      localStorage.setItem("userObj", JSON.stringify(json));
      console.log(this.userObj.token);
      this.userObj = json;
    } catch (error) {
      this.errors = "Login failed";
    } finally {
      this.pageLoading = false;
    }
  }

  @action
  public logout() {
    this.userObj = {} as IAdcUser;
    delete localStorage.userObj;
  }
}`

**Component.tsx**

`import * as React from "react";
import { translate } from "react-i18next";
import { inject, observer } from "mobx-react";
import {
  Button,
  Card,
  CardContent,
  createStyles,
  FormControl,
  Grid,
  Input,
  InputLabel,
  Typography,
  withStyles
} from "@material-ui/core";
import { Theme } from "@material-ui/core/styles/createMuiTheme";
import { Redirect } from "react-router";

const styles = (theme: Theme) =>
  createStyles({
    form: {
      marginTop: theme.spacing.unit * 2,
      width: "100%"
    },
    grow: {
      flexGrow: 1
    },
    pane: {
      marginTop: theme.spacing.unit * 10
    },
    root: {
      flexGrow: 1
    },
    submit: {
      marginTop: theme.spacing.unit * 3
    }
  });

@inject("userStore") // To use the store - USER STORE
@observer // To make sure that each component individually re-renders when relevant data changes
class Login extends React.Component<any, any> {
  private email: string = "";
  private password: string = "";

  public handleSubmit = (event: React.MouseEvent<HTMLButtonElement>) => {
    event.preventDefault();
    this.props.userStore.login(this.email, this.password);
  };

  public handleEmail = ({
    currentTarget: { value }
  }: React.ChangeEvent<HTMLInputElement>) => {
    this.email = value;
  };

  public handlePassword = ({
    currentTarget: { value }
  }: React.ChangeEvent<HTMLInputElement>) => {
    this.password = value;
  };

  public render() {
    const { classes, t } = this.props;

    if (this.props.userStore.isAuthenticated) {
      return <Redirect from="/" to="/file-download" exact={true} />;
    }

    return (
      <div className={classes.root}>
        <Grid
          container={true}
          spacing={16}
          justify="center"
          className={classes.pane}
        >
          <Grid item={true} xs={3}>
            <Card>
              <CardContent>
                <Typography>{t("login-note")}</Typography>
                <form className={classes.form}>
                  <FormControl margin="normal" required={true} fullWidth={true}>
                    <InputLabel htmlFor="email">
                      {t("email-address")}
                    </InputLabel>
                    <Input
                      id="email"
                      name="email"
                      autoComplete="email"
                      autoFocus={true}
                      onChange={this.handleEmail}
                    />
                  </FormControl>
                  <FormControl margin="normal" required={true} fullWidth={true}>
                    <InputLabel htmlFor="password">{t("password")}</InputLabel>
                    <Input
                      name="password"
                      type="password"
                      id="password"
                      autoComplete="current-password"
                      onChange={this.handlePassword}
                    />
                  </FormControl>
                  <Button
                    fullWidth={true}
                    variant="contained"
                    color="primary"
                    type="submit"
                    className={classes.submit}
                    onClick={this.handleSubmit}
                  >
                    {t("sign-in")}
                  </Button>
                </form>
              </CardContent>
            </Card>
          </Grid>
        </Grid>
      </div>
    );
  }
}

export default translate()(withStyles(styles)(Login));`

Struggling from a week.
**Any help asap is appreciated!!! Thanks in advance :)**

**Comment by mweststrate** [comment]
@shruthijanardhan123 please format your issue properly. Also I am missing the question here. What is the observed and expected behavior?

**Comment by shruthijanardhan123** [comment]
On click of sign in after entering the username and password in the login page, it's not redirecting to the required page instead it's asking to reload. after reloading it's redirecting to the required page

**Comment by mweststrate** [comment]
No reproduction still.... closing
