### ISSUE TITLE
When I install mobx, I encountered crash in release with IOS, in debug there is no problem.Without mobx everythink was working.(React Native)

### ISSUE THREAD

**Issue by buraksak35** [mobxjs/mobx-react#600]
![ekran resmi 2018-11-07 09 42 13](https://user-images.githubusercontent.com/39245976/48155499-29fe1500-e2dc-11e8-82a3-1b42e1952a92.png)

This is my release IOS log.

**Comment by mattruby** [comment]
We're going to need a whole lot more than that to help. I doubt mobx is your problem.

**Comment by buraksak35** [comment]
> I doubt mobx is your problem.

Hmm. I tried with new clear project with react-native init and I tried react-native release this is working good. But I install Mobx to this new clear project. After the just install mobx, I encountered crash in release mode not debug debug is good.

**Comment by buraksak35** [comment]
<img width="1035" alt="ekran resmi 2018-11-08 18 46 12" src="https://user-images.githubusercontent.com/39245976/48222476-b88a9900-e3a5-11e8-994c-1420aeec803c.png">
<img width="1072" alt="ekran resmi 2018-11-08 18 46 27" src="https://user-images.githubusercontent.com/39245976/48222478-b88a9900-e3a5-11e8-80e1-c0e1eb76ba9a.png">
<img width="1040" alt="ekran resmi 2018-11-08 18 46 21" src="https://user-images.githubusercontent.com/39245976/48222482-b9232f80-e3a5-11e8-95a4-b171570d9668.png">
<img width="876" alt="ekran resmi 2018-11-08 18 46 18" src="https://user-images.githubusercontent.com/39245976/48222483-b9bbc600-e3a5-11e8-930f-f3571ca9830d.png">

**Comment by mattruby** [comment]
Can you post your package.json?

**Comment by buraksak35** [comment]
> Can you post your package.json?

{
  "name": "starterkit",
  "version": "1.0.0",
  "private": true,
  "scripts": {
    "start": "node node_modules/react-native/local-cli/cli.js start",
    "test": "jest",
    "ios": "react-native run-ios",
    "android": "react-native run-android"
  },
  "dependencies": {
    "@babel/core": "7.0.0-beta.47",
    "mobx": "3.3.1",
    "mobx-react": "4.3.4",
    "prop-types": "^15.6.2",
    "react": "16.4.1",
    "react-native": "0.56.0",
    "react-native-router-flux": "^4.0.0-beta.31"
  },
  "devDependencies": {
    "@babel/core": "7.0.0-beta.47",
    "@babel/plugin-proposal-decorators": "7.0.0-beta.47",
    "@babel/plugin-transform-runtime": "7.0.0-beta.47",
    "@babel/runtime": "7.0.0-beta.47",
    "babel-eslint": "^8.2.6",
    "babel-jest": "23.4.0",
    "babel-preset-react-native": "5.0.2",
    "eslint": "^4.19.1",
    "eslint-config-airbnb": "^17.0.0",
    "eslint-config-prettier": "^2.9.0",
    "eslint-plugin-babel": "^5.1.0",
    "eslint-plugin-import": "^2.13.0",
    "eslint-plugin-jsx-a11y": "^6.1.1",
    "eslint-plugin-prettier": "^2.6.2",
    "eslint-plugin-react": "^7.10.0",
    "eslint-plugin-react-native": "^3.2.1",
    "jest": "23.4.1",
    "prettier": "^1.13.7",
    "prettier-eslint": "^8.8.2",
    "react-test-renderer": "16.4.1"
  },
  "jest": {
    "preset": "react-native"
  },
  "peerDependencies": {
    "babel-core": "6.x || ^7.0.0-0"
  },
  "resolutions": {
    "mobx": "3.3.1",
    "mobx-react": "4.3.4"
  }
}

**Comment by buraksak35** [comment]
I solved with downgrade to 0.55.4

**Comment by mweststrate** [comment]
@buraksak35 supplemental note: note that you are mixing babel 6 and 7 dependencies, and since babel 7 is out of beta, so 7-beta is not supported anymore

**Comment by httol** [comment]
> @buraksak35 supplemental note: note that you are mixing babel 6 and 7 dependencies, and since babel 7 is out of beta, so 7-beta is not supported anymore

what version babel should  use?
