### ISSUE TITLE
Can i inject limited store?

### ISSUE THREAD

**Issue by colordove** [mobxjs/mobx-react#601]
I wanna do like this
![image](https://user-images.githubusercontent.com/11832969/48241215-e1944380-e410-11e8-8476-bc0c4de9d615.png)

but stores type is string[]
![image](https://user-images.githubusercontent.com/11832969/48241303-45b70780-e411-11e8-826b-70be4c27899d.png)

is anyway makes it like
![image](https://user-images.githubusercontent.com/11832969/48241381-9cbcdc80-e411-11e8-9d5c-6c26e16850a7.png)

**Comment by mweststrate** [comment]
You can't define the type of the store at that position, rather you should be using:

```typescript
interface PostListProps {
    // whatever was in there
    hello: StoreEnum
}
```

See also: #256
