### ISSUE TITLE
React Native doesn't react to observable array

### ISSUE THREAD

**Issue by Komalov** [mobxjs/mobx-react#607]
I am currently using `5.3.1` version of mobx-react

The problem is I cannot use pagination on SectionList

```
@observer
export default class History extends React.Component {
  makeSections = () => {
    const { myStore } = this.props
    const sectionsObject = myStore.history.slice().reduce((acc, item) => {

      ...do a bunch of stuff

      return {
        ...acc,
        [day]: [ getPropsFrom(item) ],
      }
    }, {})
    return Object.keys(sectionsObject).map(key => ({
      title: key,
      data: sectionsObject[key],
    }))
  }
  render() {
    return (
      <SectionList sections={this.makeSections()} />
    )
  }
}
```
I simplify calculations I do in makeSections, but I hope you got the idea

This time, at myStore I have

```
class MyStore {
  @observable history = []

  @action.bound
  async updateHistory() {
    const response = await apiCall()
    this.history.push(response) // I got data here, 15 items per page, classic
  }
}
```

So, it just doesn't work. But when I was on previous version it worked fine. Changes I did

![mobx broken](https://user-images.githubusercontent.com/26224268/48711682-4c215c80-ec25-11e8-85a0-e1a698988de0.png)

I am not sure this is the right place, and maybe I should point this at mobx repo directly. But it seems something goes wrong in mobx-react/native observer

I have watched changelog but didn't find any breaking changes at this point.

Would be glad for any help or explanation

**Comment by Komalov** [comment]
Maybe it is relevant to
> N.B. the syntax to inject stores has changed since mobx-react 4, always use inject(stores)(component) or @inject(stores) class Component.... Passing store names directly to observer is deprecated

but it was fine with 4.4.2, so I thought I use it right

**Comment by mweststrate** [comment]
@Komalov the problem is here:

`render = () => <SectionList sections={this.makeSections()} />`

You redefine render on the instance, which overrides the one on the prototype that will be picked by mobx. For render, and for all other React lifecycle methods, you should never use fields and arrow functions (it doesn't have any benefit, only negative performance impact anyway for those methods). Instead use:

```
render () {
  return <SectionList sections={this.makeSections()} />
}
```

**Comment by Komalov** [comment]
@mweststrate 
Sorry, I know that and I actually using 
```
render() {
   return (
     ...
  )
}
```
construction. It was my mistake when I was simplifying my real code to share. I'll fix code example, but sadly problem still exist

**Comment by mweststrate** [comment]
Are other reactions to observables working, or are maybe decorators not working at all?

**Comment by Komalov** [comment]
No, they are fine.

In my app this problem occurs twice, because I have 2 similar screens with the similar `makeSections logic`. Only difference between them in collections mapping.

btw I was using RN55 and babel6 when I found this bug. Not I am on RN57.5 and babel7 so it takes a time to check decorators do work

**Comment by Komalov** [comment]
Sorry, it's actually my silly fault

Yep, I use some `render = () => { }`, cant remember how it happened 😞 I have to be more concentrated

@mweststrate Thanks a lot for help!
