### ISSUE TITLE
5.4.0 CDN version cannot be used

### ISSUE THREAD

**Issue by flyinghail** [mobxjs/mobx-react#608]
```
ReferenceError: require is not defined
```
The reason for the error is this code:
```
require("react-is")
```

**Comment by mweststrate** [comment]
Which CDN url are you using?

Op di 20 nov. 2018 om 08:59 schreef Feng Hao <notifications@github.com>:

**Comment by flyinghail** [comment]
@mweststrate https://unpkg.com/mobx-react@5.4.0/index.min.js

**Comment by flyinghail** [comment]
@mweststrate there is a new error
···
Error: render property of ForwardRef was not a function
···

**Comment by mweststrate** [comment]
Ah that is an actual error! Could you open a separate issue on that,
isolated with the component that throws it? It means that a ForwardRef is
not built up the way mobx-react expects it

Op di 20 nov. 2018 om 09:34 schreef Feng Hao <notifications@github.com>:

**Comment by flyinghail** [comment]
@marksilvis I see the code.
ReactIs.ForwardRef is coverted to undefined in CDN version.

**Comment by flyinghail** [comment]
related: #609
