### ISSUE TITLE
Error “ForwardRef was not a function“ in 5.4.1 CDN version 

### ISSUE THREAD

**Issue by flyinghail** [mobxjs/mobx-react#609]
```
Error: render property of ForwardRef was not a function
```

ReactIs.ForwardRef is coverted to undefined in 5.4.1 CDN version.

**Comment by mweststrate** [comment]
Argh. Where is my good old JVM. Will investigate :)

**Comment by wqj97** [comment]
same problem here

**Comment by titoBouzout** [comment]
Good mornings :)

**Comment by mweststrate** [comment]
Morning!

/me slightly distracted writing lamentation on building, bundling and modules in JS. "But the tests passed!"

**Comment by AdirAmsalem** [comment]
happens when consumed as an npm package as well:
![image](https://user-images.githubusercontent.com/2660550/48764629-dbc41b00-ecb8-11e8-9e1f-ca5f4028663c.png)

**Comment by johanazhu** [comment]
same problem here

**Comment by mweststrate** [comment]
ok, `mobx-react@5.4.2` should fix this, if somebody has a public CDN based project for quick verification that'll be great :)

**Comment by AdirAmsalem** [comment]
@mweststrate works (npm use-case). thanks for the quick fix!

**Comment by dmitru** [comment]
@mweststrate works for me too! So exciting - a bug that's fixed just a minute after I came across it 😄

**Comment by AdirAmsalem** [comment]
@mweststrate works (npm use-case). thanks for the quick fix!

**Comment by flyinghail** [comment]
@mweststrate thanks, it works to me :)
