### ISSUE TITLE
Redundant reevaluation of computed properties used by react components.

### ISSUE THREAD

**Issue by gusev-p** [mobxjs/mobx-react#61]
Hello!

mobx-react do not track dependencies between components contained in each other
so evaluations of computed props they use are not ordered by mobx stale/ready algorithm.
This means that mobx-react's forceUpdate of parent component can eventually
call render method of child component while it's used `@computed`'s are stale.

More precisely, suppose we have two components A and B where A uses B in it's render metod.
There is also Store with two `@computed` properties x and y both depending on `@observable` z.
Component A uses x, component B uses y. Now when z changes the following can happen:
z changes -> x evaluated -> forceUpdate A -> render B -> use y which is stale.

Computed properties x and y are not completely pure in my code, they
can make ajax requests, see [this](https://github.com/mobxjs/mobx/issues/238) for the reasons.
The problem is that component B queries y multiple times, so many equal ajax
requests can be made. I admit that this violates mobx requirement for `@computed` props
to be absolutely pure functions, but maybe there is some workaround ? :)
All my other code is very neat without autorun's. And as another argument: many reevaluations of pure functions can also be an overhead.

(great work for mobx, @mweststrate, thank you for sharing it!)

**Comment by gusev-p** [comment]
Wrote this simple primitive

```
function isPromise<T>(x:IPromise<T> | T):x is IPromise<T> {
    const p = <IPromise<T>>x;
    return p.then !== undefined;
}

export class ObservablePromise<T> {
    private _valueAtom = new Atom();
    private _isPendingAtom = new Atom();
    private _value: T;
    private _isPending: boolean;
    private _getter: () => (IPromise<T> | T);
    private _pendingValue: T;
    private _autorunDisposer: any;

    constructor(getter: () => (IPromise<T>|T), pendingValue: T) {
        this._getter = getter;
        this._pendingValue = pendingValue;
        this._value = pendingValue;
    }

    public get value(): T {
        if (!this._autorunDisposer) {
            this._autorunDisposer = autorun(() => {
                const value = this._getter();
                if (isPromise(value)) {
                    this._setIsPending(true);
                    value.then(v => transaction(() => {
                        this._setIsPending(false);
                        this._setValue(v);
                    }));
                }
                else {
                    this._setValue(value);
                }
            });
        }
        this._valueAtom.reportObserved();
        return this._value;
    }

    public get isPending(): boolean {
        this._isPendingAtom.reportObserved();
        return this._isPending;
    }

    private _setValue(v: T) {
        this._value = v;
        this._valueAtom.reportChanged();
    }

    private _setIsPending(value: boolean) {
        this._isPending = value;
        this._isPendingAtom.reportChanged();
    }
}
```

Using it instead of `@computed` props solves the problem. Is it ok conceptually?

**Comment by mweststrate** [comment]
For the example in your first comment: Note that A and B usually render independently when MobX. So even when A renders before B, B renders only one as the `shouldComponentUpdate` usually prevents the render of B "because it is a child of A". The only exception to that is when assigning new props to B. But now that I think of it that case can maybe be optimized away as well :)

I think your `ObservablePromise`  is a very neat abstraction! I can imagine that being able to return promises from the `getter` works very nice with `async/await`. Thanks for sharing!

**Comment by capaj** [comment]
@gusev-p so how would this be used?

**Comment by gusev-p** [comment]
@capaj something like this:

```
class PersonsRepository {
    public loadPeson(id: number): IPromise<Person> {
        //...make server request for person
    }
}

class PersonsStore {
    private _repository: PersonsRepository;

    constructor(PersonsRepository repository)  {
        this._repository = repository
    }

    @observable
    public currentId: number;
    
    //_person.value can be used by regular computed props
    @computed
    public get personName(): string { return this._peson.value.name + " " + this._person.value.surname; }

    //can be used to display progress indicator
    @computed
    publci get personIsLoading(): boolean { return this._person.isPending; }

    //new server request will be made when currentId changes
    private _person = new ObservablePromise(() => this._repository.loadPerson(this.currentId), Person.emptyPerson);
}

```

**Comment by gusev-p** [comment]
@mweststrate for some reason in my case forceUpdate on A always calls render on B ignoring shouldComponentUpdate on it although https://facebook.github.io/react/docs/component-api.html#forceupdate clearly states the opposite: _forceUpdate will trigger the normal lifecycle methods for child components, including the shouldComponentUpdate() method of each child._

**Comment by mweststrate** [comment]
@gusev-p apologies for the late response. Can you share your components A and B? What might happen is that keys are not setup, or that you pass new closures as callback to the child each time the parent is rendered. This might cause unexpected renderings on the child. The child then re-renders because the props have changed unintentionally.

**Comment by mweststrate** [comment]
Closed for inactivity, feel free to reopen when needed
