### ISSUE TITLE
The future of mobx-react

### ISSUE THREAD

**Issue by Obiwarn** [mobxjs/mobx-react#617]
Hooks are awesome. 
The react 16.7. "alpha" is beeing used in production by some nutterists. 
Time to prepare!

It started in #588 but I am a bit unsure now:

@mweststrate et.al. What are your plans for mobx-react?
Is mobx.react-lite the way to go? Is it supported by the creators of MobX? 
Since hooks are really mature so far: How "alpha" is mobx-react-lite? 
Can I try using mobx-react-lite in new a larger project?

**Comment by ItamarShDev** [comment]
In my opinion, the two aren't related now.
First, its still alpha.
Second, are we sure everyone will use hook from now on?

**Comment by mweststrate** [comment]
@Obiwarn 

1. mobx-react isn't going away anywhere in the near future, there is no reason to
2. that is for the consumers to decide. If you kill all non-hook based components in your code base; then it makes sense to only use lite
3. If you dare to use hooks in prod, I think you can use lite in prod
4. I guess

@RayLuxembourg that is a statements the React team itself isn't even making.
