### ISSUE TITLE
react native of expo using mobx can't re-render when change observable variable

### ISSUE THREAD

**Issue by puhahalx** [mobxjs/mobx-react#627]
When I change the observed variable, the observable value  in the method with /@action  changes but doesn't re-render.
![image](https://user-images.githubusercontent.com/28496967/50289412-bc7d0100-04a3-11e9-8653-5af763d58d97.png)
![image](https://user-images.githubusercontent.com/28496967/50289429-c999f000-04a3-11e9-9310-65e9f5f1b2ad.png)
![image](https://user-images.githubusercontent.com/28496967/50289454-d7e80c00-04a3-11e9-9d93-d5709b622cf9.png)
![image](https://user-images.githubusercontent.com/28496967/50289531-17aef380-04a4-11e9-9d07-d4d3a035d965.png)
My package.json file configuration
![image](https://user-images.githubusercontent.com/28496967/50289580-3e6d2a00-04a4-11e9-87d3-048f5395aba1.png)
Please help me check whether it is due to the mobx-react version or the incompatibility expo.

**Comment by mweststrate** [comment]
Please provide a reproducible reproduction when filing a bug report.

**Comment by puhahalx** [comment]
oh I found my fault.I Set the staticrendering to true which caused the error
