### ISSUE TITLE
"Dynamic observable objects cannot be frozen" on non-observable object style

### ISSUE THREAD

**Issue by Liooo** [mobxjs/mobx-react#628]
I met the error in the title, and after debugging I finally identified the line causing the error which is:

```
  <div style={{minHeight: '10px', maxHeight: '10px'}}></div>
```

this JSX, and when I remove the style attribute above, exactly the same code works without the error. I saw the [the description about this error in CHANGELOG](https://github.com/mobxjs/mobx/blob/master/CHANGELOG.md#known-issues), but seems like this doesn't apply to me as it's just a plain object. 

Giving bit more of the context, here's the gist of the code

```

function renderContent() {
  // here's the style tag that's likely to be causing the issue
  return (
    <div style={{minHeight: '10px', maxHeight: '10px'}}>
    </div>
  )
}

const modal = observable({content: null})

class Modal extends Component{
  ...
  render() {
    return <Modal>{modal.content}</Modal>
  }
}

function showModal(content) {
  modal.content = content


showModal(renderContent())
```

Minimum and rough but the gist is something like above, trying to render the JSX returned from a function, which is stored in an observable object. This Modal part of code is working in the other part of the app, so I'm guessing there's something wrong with the content it's trying to render.

Can anybody figure out what's going on here?

**Comment by Liooo** [comment]
@mweststrate 
Thanks so much, was able to reproduce exactly the same thing in codesandbox.

But now `observable.shallow` is raising `[mobx] Incorrect decorator invocation. @observable decorator doesn't expect any arguments`, which also happened in my local environment. Here's the [codesandbox](https://codesandbox.io/s/4rz19ppvy7), am I misunderstanding something here?

**Comment by mweststrate** [comment]
Sorry, shallow is the decorator indeed, you can use `observable({ contents:
null }, { contents: observable.ref })` instead


Op do 27 dec. 2018 om 12:08 schreef Ryo Yamada <notifications@github.com>:

**Comment by Liooo** [comment]
@mweststrate 	
That did it, sorry should have read the document there. Thanks for the quick response and the great library I really appreciate!
