### ISSUE TITLE
how to create a transitive observable class

### ISSUE THREAD

**Issue by mengjade** [mobxjs/mobx-react#629]
I want to create a transitive class to compute and summarize data from the store based on key values (A, B & C). The steps 1 and 3 are clear to me. I didn't know what to do with step 2. 
Thanks!

<hr/>
Step 1: create a store

    class store {
        mapping = {
            A: 1,
            B: 3,
            C: 10
        };
    }

    decorate(store, {
        mapping: observable
    });

<hr/>
Step 2: 

mapDetail should :

(1) take an input, mapKey. For example, mapKey = A

         constructor(mapKey) {
             this.mapKey = mapKey;
         }

(2) access the store and get the corresponding value of mapKey. In this case, 1.

     this.props.store.mapping[this.mapKey]

(3) compute some values. For example, map2 and map6.

        get map2() {
            return this.props.store.mapping[this.mapKey] * 2;
        }
        get map6() {
            return this.props.store.mapping[this.mapKey] * 6;
        }

<hr/>
Step 3: 

A react component passes mapKeys to create new mapDetails and returns the data. When the mapping object in the store changes, this component should automatically update the values.

    class mapFinal extends React.Component {
        aDetail = new mapDetail("A")
        bDetail = new mapDetail("b")
        render() {
            return (<div> {this.aDetail.map6} {this.bDetail.map2}</div>);
        }
    }

**Comment by adrianhelvik** [comment]
```
import { observer } from 'mobx-react'

...

export default observer(mapFinal)
```

You should go through some tutorials or read the documentation. This is also not the best place to ask this, as it's not an issue with the library. 🙂 Maybe find a good forum.

`observer` is the React flavor of `autorun`. Components will not update unless wrapped with it.
