### ISSUE TITLE
Warning: findDOMNode is deprecated in StrictMode. React 16.6 deprecated findDomNode-function

### ISSUE THREAD

**Issue by dikujepsen** [mobxjs/mobx-react#630]
Hi,

I was recently trying to upgrade from React 16.5 to React 16.6 in which they have deprecated the findDomNode function in the react-dom npm package. We are using the <React.StrictMode> to check for programming mistakes, and now it also checks a gives a warning for usage of the findDomNode. To my surprise, when I open up the page I'm developing, I got up to 50 warnings of the same error of the form:
"Warning: findDOMNode is deprecated in StrictMode. findDOMNode was passed an instance of Panel which is inside StrictMode. Instead, add a ref directly to the element you want to reference."

We are not using findDOMNode anywhere in our code. I boiled it down to the following example which produces the warning...

```typescript
import { observer } from "mobx-react";
import * as React from "react";

interface IPanelProps {
    header?: React.ReactNode;
    panelStyle?: React.CSSProperties;
    panelBodyStyle?: React.CSSProperties;
    panelHeaderStyle?: React.CSSProperties;
}

@observer
class Panel extends React.Component<IPanelProps, any> {
    @override
    render() {
        const { header, panelStyle, panelBodyStyle, panelHeaderStyle } = this.props;
        return (
            <div className="panel panel-default" style={panelStyle}>
                {header && (
                    <div className="panel-heading" style={panelHeaderStyle}>
                        {header}
                    </div>
                )}
                <div className="panel-body" style={panelBodyStyle}>
                    {this.props.children}
                </div>
            </div>
        );
    }
}

export { Panel, IPanelProps };
```

when I comment out the observer import, the warning goes away. So I looked in the observer implementation [https://github.com/mobxjs/mobx-react/blob/73120d88cc86d2a22d36c42d385959aa396b9a8d/src/observer.js](https://github.com/mobxjs/mobx-react/blob/73120d88cc86d2a22d36c42d385959aa396b9a8d/src/observer.js)

and I found that it uses the findDOMNode function. 

How much work is there in rewriting the observer implementation to not use the findDOMNode function? 

We are currently waiting with our React 16.6 upgrade, because we still want to use the strict mode, but getting 30-50 warning of this sort makes it unusable.

**Comment by mweststrate** [comment]
Mobx-react 5 won't support strict mode, but v6 will, see #640
