### ISSUE TITLE
Support for react ErrorBoundary 

### ISSUE THREAD

**Issue by helt** [mobxjs/mobx-react#634]
React 16 added a new Component-level method `componentDidCatch`.

Is this lifecycle method supported in mobx? I.e. does componentDidCatch trigger if a mobx statement fails?

**Comment by mweststrate** [comment]
yes

Op wo 23 jan. 2019 om 10:13 schreef helt <notifications@github.com>:

**Comment by Maaartinus** [comment]
(I hope my question is placed here correctly.)

@mweststrate I tried with my own `ErrorBoundary` and failed and the [original one](https://codepen.io/gaearon/pen/wqvxGa?editors=0010) doesn't work either. It can confirm that `componentDidCatch` gets called, but once `errorInfo` gets set, there's no need to re-render anything. Neither the constructor nor `componentWillDidWhatever` get called anymore as the state is perfectly stable. What am I missing?

**Comment by mweststrate** [comment]
@Maaartinus best use code sandbox for a reproduction

**Comment by mweststrate** [comment]
Might be valid issue, but closing until someone provides a reproduction.

**Comment by Maaartinus** [comment]
@mweststrate Here you are: https://codesandbox.io/s/yn368ro5z?fontsize=14
