### ISSUE TITLE
disposeOnUnmount as decorator with arrays throw an error when unmounts

### ISSUE THREAD

**Issue by Amareis** [mobxjs/mobx-react#637]
`"mobx-react": "^5.4.3",`

![image](https://user-images.githubusercontent.com/4806617/51908379-865c6680-23eb-11e9-9b28-70d38b61f755.png)
Then, when component unmounts:
>Uncaught Error: [mobx-react] disposeOnUnmount only works on functions such as disposers returned by reactions, autorun, etc.

`disposeOnUnmount(this, [...])` works perfectly.

**Comment by mweststrate** [comment]
@Amareis this variation of the api is not supported indeed, instead I suggest to break it into two fields.

**Comment by Amareis** [comment]
Yep, I already did so, but it's strange inconsistency of API.

**Comment by mweststrate** [comment]
Ha yeah I think it is a pattern so far nobody thought of yet. But it makes
sense, feel free to PR :)

Op do 7 feb. 2019 om 10:57 schreef Иван Плесских <notifications@github.com>:

**Comment by Amareis** [comment]
PR done, #631
