### ISSUE TITLE
component update behaviour

### ISSUE THREAD

**Issue by PLSFIX** [mobxjs/mobx-react#639]
Hello. I'm using a third-party package for creating an ui and faced a strange issue with component not being updated properly.
Sandboxes:

1. https://codesandbox.io/s/zr4nyky2r3
2. https://codesandbox.io/s/1o099qywv3

The only difference between them is `JSON.stringify()` call, which triggers _mobx-magic_
Docs say to not touch sCU/PureComponent as well.
Are there any possible workarounds?

**Comment by PLSFIX** [comment]
Little update after some digging: found out that wrapping the `Tree` component in `observer()` helps.
Basically, it's following the docs statement:

> Use @observer on all components that render @observables.

But the next question then is it really that frustrating with the 3rd party? I'm not really sure this is a correct workaround because it looks a little bit ductape-ish. You can face the need to wrap something down the tree at any moment.

**Comment by mweststrate** [comment]
@PLSFIX the clue is that if a third party lib doesn't understand observables, you shouldn't give it observables. Since your `Tree` lib doesn't know the concept of observable data, you should give it plain data, and `toJS` can be used to convert it, by means of `contents={toJS(appState.tree)}`. By doing that in the `observer` based `View` component, `View` takes the responsibility of tracking the changes in the entire tree, and converting it to plain data by means of `toJS` and pass it to the tree. 

Once you do that, you can drop the `stringify`, which, like `toJS` traverses the whole tree, making `View` consume everything in the tree, which is why that work around worked.

**Comment by urugator** [comment]
https://github.com/mobxjs/mobx-react/issues/484#issuecomment-391685354

**Comment by RussianDragon** [comment]
Hi.
We cannot use conversation... Because tree in callback return changed element and if convert struct we will lost contecst. We try using _Autorun_ and _Reaction_ but this function not have deep reaction. Maby you will add function with deep reaction for like solution situation?

**Comment by urugator** [comment]
@RussianDragon not sure if I understand correctly, but note you can use `toJS(tree)` only to subscribe, but pass the original tree to the 3rd party lib (as suggested in the comment above).

**Comment by RussianDragon** [comment]
> @RussianDragon.
Yes. We use this solution, but... Это костыль! 
First: this function need using in render function, and meaning of this function is not clear when reading (it is problem, if project havin many people).
Second: Second: This function easy deleting on refactoring or developing and miss this fact on code review.
More better solution have special function with forceUpdate() in constructor or componentDidMount

**Comment by urugator** [comment]
I would suggest to create dedicated "workaround" component with the same API as the original component:
```javascript
// sensible commentary
observer(function OserveringTree({ tree }) {
  mobx.toJS(tree); // sensible commentary 
  return El(OriginalTree, { tree }); 
})
```
That should make it clear enough I think.

To create "deep reaction" you can use the same technique:
```javascript
class Comp extends React.Component {
  constructor() {
    this.workaroundReaction = reaction(() => mobx.toJS(this.props.tree), () => this.forceUpdate());
  }
}  
```
However I would avoid this as it's even more convoluted and won't work exactly the same way.
