### ISSUE TITLE
Usage with react-dnd

### ISSUE THREAD

**Issue by jamiewinder** [mobxjs/mobx-react#64]
I don't know if this is an 'issue' or just something to be aware of, but I've noticed that when `@observer` is used with the react-dnd`@dragSource` decorator (and potentially others) it is important that these are applied in the correct order:

```javascript
@dragSource(...)
@observer
class MyComponent {
}
```
If these are the other way around, then some of the optimizations that `@observer` gives us don't appear to be applied (in particular, the `shouldComponentUpdate` method doesn't appear to be used).

I haven't look into this much further than confirming that the order matters in my particular situation, and the above appears to be the 'right' way, but I can look into it more if it comes as a surprise.

**Comment by mweststrate** [comment]
@jamiewinder correct, `@observer` should be applied first (that is, the inner decorator, after all it is just fancyness for `dragSource(...)(observer(MyComponent))`. I think that is mentioned in the docs as well.

**Comment by jamiewinder** [comment]
Just an update on this - I'm pretty sure using observer([stores]) with react-dnd causes further issues - specifically the injected stores aren't available to the react-dnd functions.

```typescript

const dragSourceSpec = {
    beginDrag(props) {
        const appState = props.appState; // appState is undefined
        // ...
    }
};

const dragSourceCollect = (...);

@dragSource('item', dragSourceSpec, dragSourceCollect)
@observer(['appState'])class MyItem extends Component {
     // ...
}
```
Swapping the decorators around fixes this, but causes the original issue. 

Hope the example is enough? Let me know if you need more details.

**Comment by mweststrate** [comment]
Closing this issue in favor of #77
