### ISSUE TITLE
ComponentWillReact stops firing

### ISSUE THREAD

**Issue by stevenfuzz** [mobxjs/mobx-react#643]
Just updated to react 16.8. Trace always shows component update due to reactive props. The first time it fires, but on future prop updates ComponentWillReact only fires for state changes, not prop updates. Am I missing something?

**Comment by stevenfuzz** [comment]
Sorry using mobx 5@latest

**Comment by stevenfuzz** [comment]
Let me clarify. After initial fire, ComponentWillReact only gets fire by domain state changes, not prop updates.

**Comment by mweststrate** [comment]
Could you demonstrate the issue in code sandbox?

Op za 9 feb. 2019 20:12 schreef stevenfuzz <notifications@github.com>:

**Comment by stevenfuzz** [comment]
Yes, I'll see what I can do. So it should fire with all prop updates, right? 

I haven't tested it in isolation. I use mobx in a framework I'm writing. So, it took a while to figure out why so many things were broken.

I'll try to duplicate in a simple component first.

**Comment by stevenfuzz** [comment]
So I created a simple component, but couldn't duplicate the issue. That being said, I am still seeing it happen. Basically (in one of several examples) several changes to the ui domain occur concurrently (set menu open state, set theme). Trace shows the reactions are observed (reactive props). ComponentWillReact fires and has the state of the first change, but doesn't fire again. 

I can trace the changes that are not being fired with ComponentWillReact in ComponentDidUpdate (by keeping a variable hasReacted), and can see that mobx has called forceRender.

ComponentWillReact should always be called right? Is it possible I have a method set as an action when it shouldn't be?

I guess I could regress react to an older version, try to figure out where things stopped working. What can I do to help? Would the trace of the prop change that didn't fire ComponentWillReact help?

**Comment by stevenfuzz** [comment]
Ok. Figured it out. In upgrading, the peer dependencies for mobx got messed up between the app and framework. I didn't realize this until I reverted back mobx and got a warning. I wish I saw this in the latest version...
