### ISSUE TITLE
Import observer causes Range Error exception

### ISSUE THREAD

**Issue by tomswales** [mobxjs/mobx-react#647]
Import of mobx-react observer is causing an uncaught range error exception. 

**Component renders correctly (I didn't wrap observer function around the test component so as to isolate the issue):**

`import React from 'react';
// import { observer } from "mobx-react";

export default class Routes extends React.Component {
    render() {
        return <div>Test</div>
    }
}`

**App crashes:**

`import React from 'react';
import { observer } from "mobx-react";

export default class Routes extends React.Component {
    render() {
        return <div>Test</div>
    }
}`

**Error message in console:**
Uncaught RangeError: Maximum call stack size exceeded

**Dependencies:**
"dependencies": {
    "@babel/runtime": "^7.1.5",
    "chance": "^1.0.18",
    "chart.js": "^2.7.3",
    "express": "^4.16.4",
    "meteor-node-stubs": "^0.4.1",
    "mobx": "^5.9.0",
    "mobx-react": "^5.4.3",
    "react": "^16.8.2",
    "react-dom": "^16.8.2",
    "react-router": "^4.3.1",
    "react-router-dom": "^4.3.1"
  },

Any idea what might be going wrong? I have used mobx-react successfully for a long time. This is the first time I have had any issue.

**Comment by mweststrate** [comment]
Are you using React Native? Could you provide a small test repo?

**Comment by adrianhelvik** [comment]
Also, Could you wrap your code in triple backticks for proper markdown rendering?

**Comment by mweststrate** [comment]
Closing for lack of reproduction / info
