### ISSUE TITLE
@observer is broken when a Consumer is used

### ISSUE THREAD

**Issue by tonypee** [mobxjs/mobx-react#649]
I am trying to find how to make the ant.d component library compatible with mobx. I have found that since they use React.createContext to Provide/Consume config, their components cannot use an observer. (i thought calling observer(List) for example might make it work) 

how can we get around this? Here is a small example:
https://codesandbox.io/s/pp1xv8nlvj

**Comment by adrianhelvik** [comment]
Wrap the children of the render function in an Observer.

```
<Consumer>
  {state =>
    <Observer>
      {() =>
        <div>{state.foo}</div>
      }
    </Observer>
  }
</Consumer>
```

**Comment by tonypee** [comment]
hmm, yah, that means that the library needs to explicitly support mobx then. this is unfortunate, as antd team wont make that change (someone already asked for a mobx specific change, and it was not received as it was data specific). Any other thoughts?

**Comment by adrianhelvik** [comment]
A better solution is to generate context data in a computed field. This way you can return a new object once state changes.

**Comment by tonypee** [comment]
Do you mean @computed somthing() { return {xxx:123} } ?  - im not sure how that will affect the rendering of the component however?

I dont really want to fork antd, as that would be a kettle of fish, and plus, it would be good to have a pattern for libraries to follow to be able to be friendly with mobx

**Comment by adrianhelvik** [comment]
Okay, generally you don't want to expose mobx values to external libraries directly. You can get the regular JS values by using mobx.toJS(store).

Example solution with toJS: https://codesandbox.io/s/jlx73zy565

In your example there is another issue. You use store.items.map inside the non-observer consumer function.

```
 1  const val = {
 2    somthing: 123
 3  };
 4  const Context = React.createContext(val);
 5  
 6  function App() {
 7    return (
 8      <Context.Provider value={val}>
                                 ^ This should be called toJS on
 9        <Context.Consumer>
10          {state => (
11            <div className="App">
12              <h1>Using Consumer</h1>
13              <h2>this will fail to update</h2>
14              <ul>
15                {store.items.map(item => (
                         ^ This will not happen in an external library.
                           If store.items are used here, but not "seen" by
                           a third party library, simply wrap the contents
                           of the consumer function in an Observer
16                  <li>item: {item}</li>
17                ))}
18              </ul>
19            </div>
20          )}
21        </Context.Consumer>{" "}
22      </Context.Provider>
23    )
24  }
25  
26  const App2 = observer(App);
27  
28  setInterval(() => {
29    store.items.push(store.items.length + 1);
30  }, 1000);
```

**Comment by urugator** [comment]
https://github.com/mobxjs/mobx-react/issues/484#issuecomment-391685354

**Comment by mweststrate** [comment]
Closing as answers have been provided
