### ISSUE TITLE
Components with renderProps must be observers

### ISSUE THREAD

**Issue by AmrAbdulrahman** [mobxjs/mobx-react#651]
Hey,

First, **[a codesandbox explaining the issue.](https://codesandbox.io/s/ll4k6px1m9)**

So, I'm having a component `<ParentComponent>` that uses `<List>` and the List Component just loops through the props.list and invokes props.renderItem. quite straight forward design.
I'm having a dynamic map of observables using `observable.map({});`

**Problem?**
Interactivity is broken.

**Work arounds**
*First work around*
I have to make my `<List>` component `observer` although, it does **not** render any observables.
[Line:5 List.js](https://codesandbox.io/s/ll4k6px1m9)

*Second work around*
Make an arbitrary referencing to the dynamic map observables within the render method of the Parent Component
[Line:26 ParentComponent.js](https://codesandbox.io/s/ll4k6px1m9)

**What I expect?**
As long as the `<ParentComponent />` is `observer`, it should take care of all observables/references within its **own** render() method.

The following code should be interactive based on `this.isLoading` state.
```
<Item
   item={item}
   loading={this.isLoading.get(item.id)}
   onAction={(...args) => this.onItemAction(...args)}
/>
```
specifically this line: `loading={this.isLoading.get(item.id)}` but it's not.
[Line:38 ParentComponent.js](https://codesandbox.io/s/ll4k6px1m9)

**Comment by mweststrate** [comment]
Please read https://mobx.js.org/best/react.html, and specifically the
section "MobX only tracks data accessed for observer components if they are
directly accessed by render". The answer to your question should be in
there. Let us know if anything is unclear after that.

**Comment by AmrAbdulrahman** [comment]
@mweststrate thank you so much! now it's on me 😃

**Comment by AmrAbdulrahman** [comment]
👍 
```
return (
  <List
    list={Store.list}
    renderItem={item => (
      <Observer>
        {() => (
          <Item
            item={item}
            loading={this.isLoading.get(item.id)}
            onAction={(...args) => this.onItemAction(...args)}
          />
        )}
      </Observer>
    )}
  />
);
```
