### ISSUE TITLE
observer does not trigger re-render

### ISSUE THREAD

**Issue by vonovak** [mobxjs/mobx-react#652]
This is a peculiar bug that is visible with react native in some situations. In short, re-render it not triggered by observer component when array changes.

This is imo a fairly problematic bug, as now I'm not sure if my app works in all scenarios. In mobx 4, I was using `peek()` in these places, after moving to mobx 5 the assumption was I will not need to do anything. For now the workaround is to slice the array.

Note that using `trace()` will also make the component re-render.

using latest mobx and mobx-react

minimal repro: https://github.com/vonovak/mobx-bug

to run the repro, just clone, `yarn` and `yarn start` should work, you can run this on your phone

gist:
```js
class ObjectWithArray {
  @observable arr = [0, 1, 2];
  @action pushToArray = () => {
    this.arr.push(this.arr.length);
  };
}

@observer
export default class App extends React.Component {
  obj = new ObjectWithArray();
  render() {
    console.warn('render!');
    const data = this.obj.arr; //add slice() to make sure component is re-rendered
    return (
      <View style={styles.container}>
        <Text onPress={this.obj.pushToArray}>add item to array</Text>
        <Text>content of array:</Text>
        {/* 
        uncomment this and it will work!
        <Text>{data}</Text> 
        */}
        <SectionList
          sections={[{ data, title: 'dummy' }]}
          renderItem={this._renderItem}
          keyExtractor={this.keyExtractor}
        />
      </View>
    );
  }
  keyExtractor = item => {
    return String(item);
  };
  _renderItem = ({ item }) => {
    return <Text>{item}</Text>;
  };
}
```

**Comment by urugator** [comment]
> after moving to mobx 5 the assumption was I will not need to do anything

Mobx will never be able to make `observer` from 3rd party component (`SectionList`)
If `observer` (`App`) doesn't depend on array content, it doesn't have a reason to re-render when the array content changes.
https://mobx.js.org/best/react.html

**Comment by vonovak** [comment]
huh, what a rookie mistake!
