### ISSUE TITLE
How can I realize HMR with mobx-react?

### ISSUE THREAD

**Issue by kwzm** [mobxjs/mobx-react#653]
I use react-hot-loader but find when I modify some jsx codes the mobx states are lost.

**Comment by jeremy-coleman** [comment]
look around my repos, about a billion examples in my dev repo, plus a few others

**Comment by mweststrate** [comment]
There are quite some HMR related questions already in this repo, and all of them provide more info than this question. Closing, and please provide a minimal reproduction when asking questions in the future.
