### ISSUE TITLE
Add react-native project examples using more up-to-date versions of RN

### ISSUE THREAD

**Issue by schumannd** [mobxjs/mobx-react#655]
AFAICT the react native version used in the example is 0.21 which is ancient.

[This Article](https://medium.com/react-native-training/react-native-with-mobx-getting-started-ba7e18d8ff44) has been a great resource when starting in the past, but recent changes have made it unhelpful. Can anyone share their mobx configurations (especially .babelrc etc.) with a newer RN version?

**Comment by mweststrate** [comment]
Anything wrong with the config as described in the docs https://mobx.js.org/best/decorators.html under the "babel 7" section?

**Comment by jinshin1013** [comment]
I've got a boilerplate setup for using react native, react-native-navigation and mobx and just recently upgraded all the dependencies, [here](https://github.com/jinshin1013/rnn-boilerplate). But the config explained above are sufficient.

**Comment by mweststrate** [comment]
closed for inactivity (and we don't control external blog posts, better report there if things are outdated)
