### ISSUE TITLE
Hooks in a mobx 5 codebase

### ISSUE THREAD

**Issue by pmonty** [mobxjs/mobx-react#659]
So I have a codebase that is class based and decorated using `observer` from `mobx-react`.

I have an issue where I have a new basic functional component as a test using `useState()`. It is used in one of the class components and now I get a `Hooks can only be called inside the body of a function component.` error. 

It seems to be erroring out all the way down the tree. Have any exisiting users had this issue and found a fix? 

I also just tried a basic 
```
const Test = () => {
   const [myStr, setMyStr] = useState('a)
   return (<p>{myStr}</p>
}
```
in the entry point of my app and it failed with the same error. Though when I do it on sandboxes it seems to work fine. Just updated all my package.jsons as well so using the most recent versions of all mobx related libraries and react.

Was happy to wait for mobx-react 6 until deadline got pushed forward, so hoping someone who has experienced this see's it.

Cheers!

**Comment by mweststrate** [comment]
Make sure to include a reproduction when filing an issue

**Comment by mweststrate** [comment]
`mobx-react@6.0.0-rc.1` is now available! So feel free to test it

**Comment by gunar** [comment]
Yey! Works for me @mweststrate :tada:

**Comment by gunar** [comment]
Something else broke tho :sob: Can't figure out broke exactly.
![image](https://user-images.githubusercontent.com/7684574/54842879-df40d080-4cb1-11e9-841f-52ce82956742.png)

**Comment by mweststrate** [comment]
You need rc.4, not 2

Op vr 22 mrt. 2019 18:51 schreef Gunar Gessner <notifications@github.com>:

**Comment by pmonty** [comment]
Well here is one kind of example where the parent is a decorated observer class https://codesandbox.io/s/jpjnlp5xkw

It works fine I have tried simple examples like this in my mobx code base. I also thought it might be because some yarn workspaces had different versions of mobx-react so updated them all but no difference.

**Comment by mweststrate** [comment]
@pmonty that is a different case: your example has `<Main>` component which is an `observer`, and `<App>` component which uses hooks, that works without problems indeed (observer affects only its target component, not it's children). This question is about using hooks inside an observer (class) component, which is not possible prior to v6

**Comment by pmonty** [comment]
In my setup I have tried to cases. 
1. I have a `@observer` decorated class (parent) that renders a child component that uses a simple useState hook as a test. 
2. I have an `@observer` decorated class (parent) that renders a child component that is an observer() with some simple hooks.

Both cases I get the `Hooks must be used in a function` related error. But in that example sandbox if you add observer it still seems to work for some reason.

**Comment by pmonty** [comment]
Ok so had some time to try again. 

Relevant packages:
```
        "react": "^16.8.5",
        "react-dom": "^16.8.5",
        "mobx": "^5.9.0",
        "mobx-react": "^6.0.0-rc.4",
```

Those are the package versions I am using in all the workspaces that my gatsby site consumes. Yet I get the following error when I try run it. Despite having absolutely no hooks in my codebase yet. Just updated mobx-react to see if it runs still

`Invalid hook call. Hooks can only be called inside of the body of a function component. This could happen for one of the following reasons:
1. You might have mismatching versions of React and the renderer (such as React DOM)
2. You might be breaking the Rules of Hooks
3. You might have more than one copy of React in the same app`

The path i was going to take was:
1. update mobx-react and confirm it works
2. add our first hook :) 
3. profit...

But can't get past 1 unfortunately. If I revert back to `@latest` the project works again.

**Comment by pmonty** [comment]
Ok so this was definitely an issue with our monorepo and multiple react versions apparently...

https://reactjs.org/warnings/invalid-hook-call-warning.html#duplicate-react

Will formulate a proper response but the main issue was yarn and the noHoist object in our monorepos package.json. Will close and update this answer when fully fixed.

**Comment by jim-king-2000** [comment]
Hi @pmonty , I met the same issue when I had upgraded react-mobx to v6.0.3.

> Invariant Violation: Invalid hook call. Hooks can only be called inside of the body of a function component. This could happen for one of the following reasons:
> 1. You might have mismatching versions of React and the renderer (such as React DOM)
> 2. You might be breaking the Rules of Hooks
> 3. You might have more than one copy of React in the same app

So, is there any solution or workaround?

**Comment by mweststrate** [comment]
This issue was closed 2 months ago on a different version. Please open new issue

**Comment by jim-king-2000** [comment]
I have resolved it. It fails since the library depends on mobx-react v6 while the main project does not. It succeeds when I move mobx-react v6 dependent from the library to the main project.

```
// library.json
dependencies: {
  mobx-react: 6.0.3
}

// myProj.json
dependencies: {
  library: x.x.x
}
```
> Invariant Violation: Invalid hook call...

```
// library.json
dependencies: {
  
}

// myProj.json
dependencies: {
  mobx-react: 6.0.3,
  library: x.x.x
}
```
> Success

**Comment by mweststrate** [comment]
Your libraries should use peerDependencies for mobx, mobx-react, react,
react-dom, not dependencies.

**Comment by jim-king-2000** [comment]
Got it. Thank you!
