### ISSUE TITLE
Inject can't observer removed data

### ISSUE THREAD

**Issue by kwzm** [mobxjs/mobx-react#660]
Online demo: [https://codepen.io/kwzm/pen/MxPMGK?editors=0010](https://codepen.io/kwzm/pen/MxPMGK?editors=0010)

I found just used `inject` could not observer data been removed, the component could not re-render.
But if you add `observer` everything is ok.
 Ps: I used a func in `inject`, so it will auto add `observer`.
![捕获](https://user-images.githubusercontent.com/16114101/54744014-c75d4400-4c00-11e9-900c-18499b43bce4.PNG)

**Comment by mweststrate** [comment]
`inject` does not automatically apply `observer`, so the correct definition is, `const App = inject((store) => ({data: store.data}))(observer(List))`, which fixes the issue. 

The `observer` you are seeing in the source is the `observer` of the wrapping HOC component, that runs the inject function (which might also be reactive), but it is not the child component itself, which needs to be an observer as well if is consuming observables.

**Comment by kwzm** [comment]
@mweststrate Ok, I see. Thank you.
