### ISSUE TITLE
"Too much recursion" as soon as i import mobx-react

### ISSUE THREAD

**Issue by vjau** [mobxjs/mobx-react#662]
When writing 
```
import {observer} from "mobx-react";
```
i get a "too much recursion" error in the browser.
Please note that this is just this single line, i don't even use it. 
I'm using Meteor as a build tool. All other tools and libraries are working fine. 
What could be the source of this issue ?

**Comment by vjau** [comment]
Repro 
https://github.com/vjau/toomuchrecursionmeteor

**Comment by vjau** [comment]
Probably related to #647

**Comment by mweststrate** [comment]
Volunteer that has experience with the meteor build stack to investigate further is welcome :) Would be interested to see if a different range of mobx-react version would make a difference

**Comment by vjau** [comment]
This doesn't seems to happen anymore with Meteor 1.8.1

**Comment by 3210jr** [comment]
Thanks @vjau . I can confirm upgrading to Meteor 1.8.1 from 1.8.0 fixes the issue
