### ISSUE TITLE
mobx-react failing in IE11 with mobx 4.X

### ISSUE THREAD

**Issue by jorshali** [mobxjs/mobx-react#663]
We still have users in our base that are using IE11.  Due to this, our project is on the 4.X branch of mobx (version 4.9.4 as of this writing).  We recently attempted to upgrade mobx-react to version 5.4.3.  This appears to work without issue for Chrome and Safari, but IE11 shows a blank page with no errors logged in the developer console.

Version 5.2.8 works as expected with mobx 4.9.4 in IE11.  With no errors being output, I know this isn't much to go on, but please let me know if there is more information I can provide.

**Comment by mweststrate** [comment]
Could you provide a small reproduction?

**Comment by mweststrate** [comment]
closing for the lack of reproduction

**Comment by jorshali** [comment]
Sorry for the delay.  As soon as I get a chance to create a reproduction I will open a new issue and link with the code sample.  Thanks.
