### ISSUE TITLE
Mouse Events causing unnecessary re-renders

### ISSUE THREAD

**Issue by ryanking1809** [mobxjs/mobx-react#665]
I've created the following component. Basically when you click on the yellow bg of `<App>` it updates a mobx store to be `selected` and it alters the css colours. Within `<App>` I have a `<Hello>` component with an `onClick` event, when `<App>` updates, `<Hello>` re-renders unnecessarily. However when I remove the click event `<Hello>` only renders once as expected. Any idea what's going on here?
https://codesandbox.io/s/zzq718xn5x

```jsx
const App = observer(() => {
  return (
    <div
      className="App"
      style={{
        color: MobXStore.selected ? "red" : "blue",
        background: "yellow",
        padding: "10em"
      }}
      onClick={MobXStore.toggleSelection}
    >
      <Hello greeting={"Hello"} onClick={e => null} />
    </div>
  );
});

let numRenders = 0;

const Hello = observer(({ greeting, ...props }) => {
  numRenders += 1;
  console.log("hello", numRenders);
  return <h1 {...props}>{greeting}</h1>;
});
```

**Comment by urugator** [comment]
The `onClick` callback is created every time the `App` re-renders, breaking the pure check on `Hello` (because `prevProps.onClick !== props.onClick`).

**Comment by ryanking1809** [comment]
Ah perfect! I'll have to keep an eye on that one, thanks!
