### ISSUE TITLE
Mixing `@disposeOnUnmount` and `disposeOnUnmount(this, ...)` is broken

### ISSUE THREAD

**Issue by JabX** [mobxjs/mobx-react#666]
Hello,

`disposeOnUnmount` registers the disposers or the property keys (pointing to the disposers) in an array that is stored on the class. If you use `disposeOnUnmount` as a decorator, that array will be stored in the class prototype, but if you use it inside the class it will be stored as an instance property. `runDisposersOnUnmount` doesn't care where the property is located because `this[storeKey]` can refer to either.

As long as I have a `@disposeOnUnmount` decorator, the array will necessarily be stored on the prototype, but any `disposeOnUnmount` that is declared inside the class will also be registered on the prototype, despite being firmly from the instance side of things.

Usually, this doesn't cause a lot of problems, except for the case where you use two (or more) instances of the same class, with one unmounting before the other : the first unmount will also dispose every reaction created inside the instance of the second class.

I know that `disposeOnUnmount` doesn't distinguish between being called as a decorator and being called directly, but I feel that storing the property key disposers and the function disposers in two separate arrays could be an easy fix that doesn't break the API. I don't think people are using the `disposeOnUnmount(this, "myDisposer")` way, since the docs don't mention it and it's weirder and not as convenient as `disposeOnUnmount(this, autorun(() => …))`. Using the argument type as a way to separate decorator and non-decorator usage looks like an okay heuristic we could use, and in any case doing this won't break anything, so that would be a straight improvement.

**Comment by mweststrate** [comment]
Thanks for reporting :). PRs that address this issue one way or  another are welcome

**Comment by bsmith-cycorp** [comment]
For the time being, could we add a warning to the docs not to intermix `@disposeOnUnmount` and `disposeOnUnmount()`? Would've saved me some debugging time today.

**Comment by FredyC** [comment]
@bsmith-cycorp PR is surely most welcome :)

**Comment by mweststrate** [comment]
Released as 6.1.1
