### ISSUE TITLE
Pausing observer

### ISSUE THREAD

**Issue by d4rky-pl** [mobxjs/mobx-react#667]
It would be nice to be able to pause the `observer` in some cases. An example would be React Navigation and it's [withNavigationFocus](https://reactnavigation.org/docs/en/with-navigation-focus.html) HOC. 

Currently when using MobX with React Navigation, all the screens are constantly updated in the background which can have performance penalties for more complex screens.

Apologies if this was already asked for, I looked through the issues but I couldn't find it

**Comment by urugator** [comment]
Not sure if applicable, but you can disable subscriptions with `untracked`:
```javascript
const Cmp = observer(({ store }) => {
   const render = () => el('div', {}, store.x)

   if (store.isVisible) {
      return render()
   } else {
      return untracked(render)
   }
})
```
