### ISSUE TITLE
Mobx mutate previous props

### ISSUE THREAD

**Issue by Spaider15** [mobxjs/mobx-react#668]
https://wz7k5jo5.codesandbox.io/
![image](https://user-images.githubusercontent.com/12617760/56423238-d85aad00-62b3-11e9-9a20-adcc7c48fe31.png)

**Comment by mweststrate** [comment]
That is the point of mutability; references are stable, values are mutable. It is not the previous props that is being mutated here, it is the previous TodoStore. Which is what is supposed to happen :)
