### ISSUE TITLE
Do I need observer?

### ISSUE THREAD

**Issue by zisiszikos** [mobxjs/mobx-react#669]
From the documentation is clear that I should wrap react components with `observer` if I want to observe some property of the component. It also says that when using `inject` I don't really need to wrap component with `observer` too. But what if I use `inject` to pass a prop to the component but I also pass an observable prop at the component by its parent? Should I use the `observer` for the second prop, or `inject` tracks changes at both props?

From this [example](https://codesandbox.io/s/4qn1578o09) it seems that both props are tracked because of the use of `inject`.

So do I really need `observer` when using `inject` in my app?

**Comment by mweststrate** [comment]
Inject takes care of injecting (like `useContext`), but it doesn't take care of observability, those two things are completely unrelated. If your component is rendering observables, you will need `observer`.

**Comment by zisiszikos** [comment]
Thanks for the answer.

I made some test and found that `inject` updates the view without the `observer` when it is passed primitive types, but not with Objects and Arrays. I guess because some shallow equality check returns `true` for Objects and Arrays with changed content.
