### ISSUE TITLE
Advice on mixing mobx with React state

### ISSUE THREAD

**Issue by ptallett** [mobxjs/mobx-react#670]
I'm looking for advice on how to best organise state in a mobx application. I'm new to React (1 year) but have used mobx from the start - I've never called setState in any of my code. I looked at Redux, but it seemed very complex, and as I work for Microsoft and come from a XAML/MVVM background, mobx seemed a better fit for me.

It seems I can go against some of the rules of React code with mobx - one way state flow, readonly props, stateless components etc. I'd like to know which best practices to follow and which to ignore.

I'm trying to build a graphical editor which allows editing a JSON structure. Each item in the data is rendered as a React component (a div), and has an x,y position. My layout code uses the rendered height of each component to compute the position of the next. This seems tricky as the position of a component is only known after the others have rendered so I can get the height which seems to go against the React philosophy that components should be independent.

I've got it all working with an app-wide observable data structure - I have a point class that has x,y properties and pass the relevant point to a component via props so it knows where to render. I also update the app-wide structure with the height of the component in the componentDidRender method.

I was worried about infinite loops, but mobx seems to sort it all out and the render methods get minimal calls.

However, this approach doesn't seem very scaleable. Since I'm storing UI state app-wide (which is a no-no in XAML), if I wanted multiple instances of my layout engine, things would break as there's only one set of state.

What's the correct way to organise the state and when do I use props to pass it? I'm wondering if a ViewModel type approach would be best, but can't see how to achieve it.

Thanks.
Paul

**Comment by Maaartinus** [comment]
I'm a real noob here, but I have a strong opinion on this: Forget about state as mobx with props is everything you need. Using `this.state` gives you another storage possibility, which you don't need. It broadens the question where to store what and it behaves differently (worse); I see two huge disadvantages nothing to gain.

> Since I'm storing UI state app-wide [...], if I wanted multiple instances of my layout engine

You can continue storing it app-wide when you use a map keyed by some instance identifier. You're thinking about using `setState` on some component, so you can store your state in an observable field of the very component, can't you?

I guess, I'm right: https://blog.cloudboost.io/3-reasons-why-i-stopped-using-react-setstate-ab73fc67a42e

**Comment by mweststrate** [comment]
> if I wanted multiple instances of my layout engine, things would break as there's only one set of state.

Just create new instances of your layout engine state in root's of the tree where they apply to. There is no need for MobX to have your state as global / singleton. It can then passed down via props / Provider / context. Doesn't really matter.
