### ISSUE TITLE
[QUESTION] Do I need observer when only using actions in some component functions?

### ISSUE THREAD

**Issue by artechventure** [mobxjs/mobx-react#672]
Do I Need @observer when I only need to use actions in provider Store, and not using observables in render?

Pretend I have a Store, which is injected to rootComponent by Provider,
and Component A is only using a action in Store, 
Component B uses observable values in render.

Do I have to use @inject @observer to access action in Component A?
If I don't have to, what are better ways to do it?

**Comment by mweststrate** [comment]
No, `observer` is only needed to be able to reactively _render_.

**Comment by artechventure** [comment]
> No, `observer` is only needed to be able to reactively _render_.

Thank you for answering, then if I want to use only actions and values in store but not observable values in render,
can I only @inject without @observer?
Or just use it from directly importing from store? (like import RootStore from './store', RootStore.increaseCount() )

**Comment by mweststrate** [comment]
Both work

Op wo 1 mei 2019 11:51 schreef Chang Young Oh <notifications@github.com>:
