### ISSUE TITLE
disposeOnUnmount usability problem

### ISSUE THREAD

**Issue by bsmith-cycorp** [mobxjs/mobx-react#676]
It seems problematic that `@disposeOnUnmount`'s effect will be disposed on _unmount_, but (in a property initializer) gets initialized on _construction_, not _mount_. Wouldn't this mean that if a component gets mounted, unmounted, and then mounted again, the autorun/reaction will only be active during its first lifespan? Would this be possible to address automatically or is the solution just to call it as a function in `componentDidMount()` instead of in a property initializer?

**Comment by FredyC** [comment]
If you are ever planning to transition to React Hooks, have a look here...

https://mobx-react.js.org/recipes-effects

**Comment by Maaartinus** [comment]
@bsmith-cycorp This is something, I didn't even think about (I'm a newbie here). I'm afraid, having to initialize the variable in `componentDidMount()` makes this feature mostly useless; when you do this, then you can add a disposer call to `componentWillUnmount()` as well. It could get more usable with
```
@lifecycle.autorun doSomething = () => whatever()
```
adding `autorun(this.doSomething)` and its disposer to where they belong.

**Comment by urugator** [comment]
> if a component gets mounted, unmounted, and then mounted again

I don't think that's possible. Do you have an example when it happens?

**Comment by bsmith-cycorp** [comment]
You know, I'd been operating under the assumption that it was for a very long time, but I'm now struggling to come up with proof.

**Comment by Maaartinus** [comment]
FWIW: https://reactjs.org/docs/react-component.html#componentwillunmount

*Once a component instance is unmounted, it will never be mounted again.*
