### ISSUE TITLE
bug: ES6 syntax "static variable async vs static variable = async"

### ISSUE THREAD

**Issue by meabed** [mobxjs/mobx-react#678]
Thanks for the update and maintaining the project.

In the last v6.0.0
Applying @inject, static properties are not copied correctly if its defined in this syntax
```

@inject('store')
@observer
class Btn extends Component {
  // ❌ not working
  static async getInitialProps () {
    console.log("static");
  };
  render() {}
}
```
When you change it to variable based it works
```

@inject('store')
@observer
class Btn extends Component {
  // ✅this works
  static getInitialProps = async () => {
    console.log("static");
  };
  render() {}
}
```
My guess is the issue is in ```copyStaticProperties``` 

Could you guys have a look at this as it breaks any components now.
I am using it in nextjs as reference here.

Thank you and keep up the awesome work 👍

**Comment by urugator** [comment]
https://github.com/mobxjs/mobx-react/blob/master/src/utils/utils.js#L69
`Object.keys(base)` has to be replaced by `Object.getOwnPropertyNames(base)` to include non-enumerables.
The check `base.hasOwnProperty(key)` is redundant, both `.keys/.getOwnPropertyNames` returns *own* props.

**Comment by meabed** [comment]
Yes, absolutely need to change, thanks for the suggestion 👍 
![image](https://user-images.githubusercontent.com/45731/58596889-cc84e200-8286-11e9-9379-f41ca133c7cd.png)

**Comment by mweststrate** [comment]
PR welcome!

**Comment by meabed** [comment]
@mweststrate PR ready :) Thanks!
