### ISSUE TITLE
[Bug] Module "mobx-react/native" does not exist in the Haste module map

### ISSUE THREAD

**Issue by kesha-antonov** [mobxjs/mobx-react#680]
Hey!

After upgrade from ```5.4.3``` to ```6.0.0``` in RN project.

**Comment by mweststrate** [comment]
Reproduction?

**Comment by robertmylne** [comment]
Same problem

**Comment by FredyC** [comment]
Well, I think it's obvious, microbundle is not creating any `native.js` file. Been thinking about the same (slightly different build tool) in https://github.com/mobxjs/mobx-react-lite/issues/168

**Comment by mweststrate** [comment]
The package.json refers to a different file `"react-native": "dist/mobx-react.rn.module.js",`. 

`/native` was the entry point that was used in mobx-react@5. So this might be a cache issue. 

More +1's will be pointless until somebody sets up a reproduction or PRs a fix :)

**Comment by karltaylor** [comment]
Rolled back to 5.4.3 and works fine

**Comment by bang88** [comment]
> The package.json refers to a different file `"react-native": "dist/mobx-react.rn.module.js",`.
> 
> `/native` was the entry point that was used in mobx-react@5. So this might be a cache issue.
> 
> More +1's will be pointless until somebody sets up a reproduction or PRs a fix :)

How to tell react-native to use this field. Thank you

**Comment by stevelizcano** [comment]
I ran into this problem while upgrading to Expo 33. If you upgrade to mobx-react 6, you'll get this issue.

Happy to dive into creating a PR to fix, but not quite sure where to look?

**Comment by stevelizcano** [comment]
Upon further exploration, initialization of a new ExpoKit (SDK 33) project, adding mobx-react 6 and importing it into your project will give this bug. I believe this should also occur with full Expo-managed projects.

**Comment by mweststrate** [comment]
The most important question is how the the build tool finds the react
native specific entry point of a module. If something has changed in that
regard, we can change it here.

Op do 6 jun. 2019 07:08 schreef Stephen Lizcano <notifications@github.com>:

**Comment by FredyC** [comment]
@mweststrate It depends on bundler which is used. By default RN uses Metro bundler which uses "browser" field by default, but [it's configurable](https://github.com/facebook/metro/blob/3bf0a9354633f16555cbf4cb8dcc0e8f13c1a323/docs/Configuration.md#resolvermainfields). Then there is alternative Haul based on Webpack which also [needs to be configured].

The strange fact is why is it looking for `mobx-react/native`. It must be some undocumented way for doing it.

**Comment by younes200** [comment]
same here, just upgrade from `5.4.3` to `6.0.0` I had reference to `import { Provider } from 'mobx-react/native'` should be now `import { Provider } from 'mobx-react'` ?

**Comment by FredyC** [comment]
@younes200 Can you please try locally if you save a copy of this file to `node_modules/mobx-react/native.js`?

https://unpkg.com/mobx-react@6.0.3/dist/mobx-react.rn.module.js

**Comment by mweststrate** [comment]
Please try and let us know. That might explain where the error is coming
from.

Op ma 10 jun. 2019 19:35 schreef Younes <notifications@github.com>:

**Comment by FredyC** [comment]
@kesha-antonov @robertmylne @karltaylor Any change you actually have import from `mobx-react/native` somewhere in your code?

**Comment by younes200** [comment]
I removed all `mobx-react/native` references but app crashs on start with a the `
Expected a constructor` exception.

 I think is related to the new provider/contexte. This is a dummy example for reproduction :

```
class MyStore {}
const myStore = new MyStore()

@inject('myStore')
@observer
class App ()=>
  render() {
    return (
      <View/>
    )
  }
}

const Main = () => (
    <Provider myStore={myStore}>
        <App />
    </Provider>
)
```
Did I miss something ?
Thank you

**Comment by FredyC** [comment]
@younes200 Please use search next time ... #690

**Comment by younes200** [comment]
@FredyC Thanks and sorry about that ;)

**Comment by mweststrate** [comment]
Seems issue is solved. Make sure to import from `"mobx-react"`, not `"mobx-react/native"`

**Comment by FredyC** [comment]
@mweststrate I have a feeling that with default configuration the `react-native` field is not even used. That would mean it's running with React batching instead of RN one. I wonder if there is really such a difference. Perhaps we could drop RN specific build completely.

**Comment by mweststrate** [comment]
If you can test it doesn't make a difference, that is fine, but I think it
is gonna die pretty hard on the missing react-dom import :)

**Comment by kesha-antonov** [comment]
@mweststrate thanks!
