### ISSUE TITLE
use reaction with hooks is not working!

### ISSUE THREAD

**Issue by jackple** [mobxjs/mobx-react#683]
```ts
// in component
function handleMessagesChanged() {
    console.log('handleMessagesChanged of component')
}
React.useEffect(() => reaction(() => message.length, handleMessagesChanged), [])

// in store
@observable messages: IMessage[] = []

constructor() {
   super()
   reaction(() => this.messages.length, this.handleMessagesChanged)
}

handleMessagesChanged = () => {
    console.log('handleMessagesChanged of store')
}
```

when `messages.push(xxx)`, there is only `handleMessagesChanged os store`, `handleMessagesChanged of component` is never logged!

**Comment by mweststrate** [comment]
Reproduction is required to file an issue.

**Comment by jackple** [comment]
@mweststrate https://github.com/YDJ-FE/ts-react-webpack/blob/test/src/containers/views/SocketDebugger/Browse/Message.tsx

Check this!

**Comment by mweststrate** [comment]
Awesome!

Op vr 31 mei 2019 12:14 schreef jackple <notifications@github.com>:

**Comment by jackple** [comment]
After I removed all usages of `inject` and some other things(I had changed so many files), it works. But I don't know why yet!
Now I have pushed to `master`, and I kept branch `test`, I will make some tests between them.
https://github.com/YDJ-FE/ts-react-webpack
