### ISSUE TITLE
[Bug] useLocalStore does not work when store is defined in separate function

### ISSUE THREAD

**Issue by mmalicki** [mobxjs/mobx-react#684]
Hi,

I followed these docs: https://mobx-react.netlify.com/recipes-context
Store created with useLocalStore and then passed in via react context ignores updates by called methods defined in store.
It does work, when store is created in the same component where it is used though. Also, I could make this work by directly assigning new value on store "counter", without inc() method.

So it looks like, somehow methods defined in store do not update it in that one particular case.

Reproduced here: https://codesandbox.io/s/inspiring-fermi-ssmmt
(I might be missing something, since it is relatively new to me, but I followed docs examples quite closely...)

**Versions:**
```
 "react": "16.8.4"
 "react-dom": "16.8.4",
 "mobx": "^5.9.4",
 "mobx-react": "6.0.2"
```

**Comment by mmalicki** [comment]
After digging a bit more, I think I found the cause. 

If store is defined using "useLocalStore" but not as inline function, then its methods can't access store variables using store object captured in closure. Probably it can be accessed that way only when store object is already wrapped in useLocalStore? So this doesn't work:
`
export function createStore() {
  const store = {
    counter: 0,
    inc(): {
        store.counter++;
    }
  }
  return store
}
...
const store = useLocalStore(createStore)
`
It has to be accessed using "this", so this works:
`
export function createStore() {
  const store = {
    counter: 0,
    inc(): {
        this.counter++;
    }
  }
  return store
}
...
const store = useLocalStore(createStore)
`

As for now, docs say otherwise, so I'm not really sure whether it's a feature or a bug...

**Comment by urugator** [comment]
> Probably it can be accessed that way only when store object is already wrapped in useLocalStore?

Yes, because `store` returned from `useLocalStore` is an observable copy of a `store` returned from `createStore`. The `inc()` therefore increments original non-observable `store` objects, which isn't the one observed by the component.
cc @FredyC

**Comment by FredyC** [comment]
Ah, interesting, so I guess it will be a bad pattern to declare store like that. Alternatively `this` has to be used if an external definition of store is desired, but there are [some Typescript issues](https://github.com/mobxjs/mobx/issues/1954). I think ultimately I would go the way of custom hooks that only declare store. I will update documentation later.

**Comment by mweststrate** [comment]
Closing over here, as the behavior is as expected and this should be documented differently
