### ISSUE TITLE
External store declaration is wrong

### ISSUE THREAD

**Issue by FredyC** [mobxjs/mobx-react#685]
Ah, interesting, so I guess it will be a bad pattern to declare store like that. Alternatively `this` has to be used if an external definition of store is desired, but there are [some Typescript issues](https://github.com/mobxjs/mobx/issues/1954). I think ultimately I would go the way of custom hooks that only declare store. I will update documentation later.

_Originally posted by @FredyC in https://github.com/mobxjs/mobx-react/issues/684#issuecomment-498117462_

**Comment by mweststrate** [comment]
yeah, as suggested before, `this` is the idiomatic way to do it, and afaik it has actually less TS issues as well.

**Comment by mweststrate** [comment]
closing this issue as all documentation in this repo already used `this`

**Comment by FredyC** [comment]
Ah, I made it in wrong repo, I wanted to copy that comment to docz repo 🙈 

Btw it is going to hurt over time. This repo recommends `this` everywhere and docz site has closures as a recommendation. People will be confused. Can you please have a look at https://github.com/mobxjs/mobx/issues/1954 soon? There is a reproduction of `this` not working properly.
