### ISSUE TITLE
Question / Idea: Transient updates for animation in MobX-React

### ISSUE THREAD

**Issue by ryanking1809** [mobxjs/mobx-react#686]
Is there any way for mobx-react to not re-render when an observed store updates? It's very useful for handling animation state, where asking react to re-render is to slow. Currently to get this working a split the component in two, one with `observer` for animation, and another with `observer` for re-rendering. It works but it's a little messy for my liking, and I'm constantly causing unexpected re-renders.

Is it possible to do this in the one component? Where you say re-render on these store props, but don't re-render on these ones.

Paul Henschel just created something for this in `Zustand` https://twitter.com/0xca0a/status/1135465164504031233 it would be great if it were possible in MobX-React.

**Comment by urugator** [comment]
https://github.com/mobxjs/mobx-react/issues/667#issuecomment-483747386

**Comment by ryanking1809** [comment]
Oh perfect, thanks!
