### ISSUE TITLE
Recommendation of using Context API for accessing stores

### ISSUE THREAD

**Issue by Kiarash-Z** [mobxjs/mobx-react#687]
Hello,

Found this suggestion on the readme:

`React.createContext can be used to pass stores around.`

But using Context for passing stores has a downside. Take a look at this [sandbox](https://codesandbox.io/s/sad-fast-yw86g?fontsize=14) please. It's a simple timer.

I have 2 child components called `Child1` and `Child2`. `Child1` calls `startTimer` method and `Child2` shows timer's number. The problem is calling `startTimer` in `Child1`; I placed this method call in `useEffect` hook like this:
```
  useEffect(() => {
    appStore.startTimer();
  }, []);  // not passing appStore as a dependancy
```
However, it shows me a warning ⚠️ (because of referencing a context value): 
```
React Hook useEffect has a missing dependency: 'appStore'. Either include it or remove the dependency array. (react-hooks/exhaustive-deps)
```
I can include it as a dependancy but why should I? it wouldn't get reassigned and It gets called just once when component mounts. so this hook wouldn't run twice.  I only need a reference to`appStore`.

Any solution? If I import `appStore` manually in `Child1` then the warning is gone. If importing stores manually is better then why is recommended to use Context API instead?

**Comment by urugator** [comment]
Context isn't an alternative for `import`, but for passing dependencies via props.

> Any solution?

Either satisfy the eslint rule (recommended) or disable it.

More about  static (import) vs dynamic (context/props) deps:
https://github.com/mobxjs/mobx-react/issues/410#issuecomment-388058128
https://github.com/mobxjs/mobx-react/issues/553#issuecomment-422606514

**Comment by Kiarash-Z** [comment]
> Context isn't an alternative to `import`, but to passing dependencies via props.
> 
> >

Can you provide an example using `useEffect` hook where Context is useful for passing stores please? Because It's recommended in the docs, I want to know what's the proper way to use it.

**Comment by mweststrate** [comment]
You are using it the proper way, and passing it as dependency is a valid warning, as the linter doesn't know that you are not going to change that store reference. So, as @urugator suggested, just add it as dep (because you are not going to change it, you can just as well add it, no harm in that). Or disable the rule (because you are not going to change it, you can just as well disable it, no harm in that).

**Comment by Kiarash-Z** [comment]
@mweststrate Thanks for the reply. I'm just wondering: What's the point of using context API then?🤔
- when using context for passing stores I need to import the context instance and also include it as a dep in `useEffect`.
- when not using context and using import instead, I import store directly and I don't have to include it in `useEffect` hook as a dep which will result in a cleaner `useEffect` hook.

**Comment by mweststrate** [comment]
Without context your store will be global state. All benefits and
disadvantages that come with that hold, it shouldn't be too hard to find
several issues discussing the downsides of having your store as global
state. (e.g. tests become side effectful)

**Comment by Kiarash-Z** [comment]
@mweststrate  Thank you got it 👍
