### ISSUE TITLE
@inject  cause Expected a constructor.

### ISSUE THREAD

**Issue by princeMing** [mobxjs/mobx-react#690]
i use reactNative

![image](https://user-images.githubusercontent.com/19681693/58928404-f2c5e880-8784-11e9-92d2-cc8192ca9b22.png)
Is ok

![image](https://user-images.githubusercontent.com/19681693/58928433-05402200-8785-11e9-9c8c-4b6a46aa60c7.png)

cause

![image](https://user-images.githubusercontent.com/19681693/58928466-26087780-8785-11e9-998e-b6631116f553.png)

Any good ideas？

**Comment by princeMing** [comment]
My configuration

![image](https://user-images.githubusercontent.com/19681693/58928578-a4fdb000-8785-11e9-9625-a56ff6a22fa3.png)
![image](https://user-images.githubusercontent.com/19681693/58928582-a7600a00-8785-11e9-8318-f3ccce0076d0.png)

**Comment by princeMing** [comment]
Listening service
![image](https://user-images.githubusercontent.com/19681693/58928859-cf03a200-8786-11e9-9943-ffef9d03f9ad.png)

**Comment by whdckszxxx** [comment]
Same problem with fresh install of react-native, mobx and mobx-react.
Did you find a workaround?

**Comment by whdckszxxx** [comment]
maybe related to this issue ? 
https://github.com/facebook/react-native/issues/24452

**Comment by ispirLee25** [comment]
i getting same error :(

**Comment by FredyC** [comment]
Yea, I would say it is definitely related to facebook/react-native#24452 and as such should be resolved there.

In case you don't want to wait, feel free to keep using mobx-react V5. As long as you write class components only, V6 doesn't give you much of the benefit.

**Comment by stevelizcano** [comment]
Hey everyone, here is a fix you can add yourself that will work with RN >= 0.59 or Expo SDK 33.

Here is how for RN >= 57

1. Create rn-cli.config.js in your base folder.

```js
module.exports = {
    transformer: {
        babelTransformerPath: require.resolve('./scripts/customReactNativeTransformer')
    }
};
```

1. Create a file in your base folder called  ./scripts/customReactNativeTransformer.js

Add the following: 

```js
const {
    transform,
    getCacheKey,
} = require('metro-react-native-babel-transformer/src/index);

function customTransform(config) {
    config.options.hot = false;
    return transform(config);
}

module.exports = {
    transform: customTransform,
    getCacheKey,
};
```

1. Now you can use MobX@6!

**Comment by fengh16** [comment]
I tried the solution provided by @stevelizcano , but it didn't work for me.

I did the following:

- Created file `rn-cli.config.js`, created folder `script` and created file `customReactNativeTransformer.js` in this folder;

- I tried to install npm dependencies again, pod install and start (using commands `rm -rf node_modules/`, `npm i`, `pod install` and `npm start -- --reset-cache`), start iOS project using Xcode;

But the problem still exists, showing `Expected a constructor`.

Some configurations:

- `package.json`:

  - ``` json
    {
      // some settings such as name, version are not shown here
      "dependencies": {
        "@babel/plugin-proposal-decorators": "^7.4.4",
        "babel-preset-react-app": "^9.0.0",
        "mobx": "^5.10.1",
        "mobx-react": "^6.1.1",
        "prop-types": "^15.7.2",
        "react": "16.8.3",
        "react-native": "0.59.9",
        // some other dependencies that I think not related to this issue
      },
      "devDependencies": {
        "jest": "^24.8.0",
        "react-test-renderer": "16.8.3"
      },
      "jest": {
        "preset": "react-native"
      },
      "babel": {
        "plugins": [
          [
            "@babel/plugin-proposal-decorators",
            {
              "legacy": true
            }
          ]
        ],
        "presets": [
          "react-app"
        ]
      }
    }
    ```

- `babel.config.js`

  - ``` js
    module.exports = {
      presets: ['module:metro-react-native-babel-preset']
    };
    ```

- `jsconfig.json`

  - ``` json
    {
        "compilerOptions": {
            "experimentalDecorators": true
        }
    }
    ```

Are there any important settings that haven't done here? Thank you!

**Comment by FredyC** [comment]
Folks, this isn't really a bug caused by MobX (unless proved otherwise) and such you should be discussing it in react-native community. I appreciate posting pointers for passers-by, but let's not dwell into "it doesn't work for me here". Thanks :)

**Comment by qazse1234567** [comment]
my solution:
`
class Test extends Component {
    ···
}
export default inject("appStore")(observer(Test));
`

**Comment by qazse1234567** [comment]
my solution:
```
class Test extends Component {
    ···
}

export default inject("appStore")(observer(Test));
```

**Comment by ChauVV** [comment]
Same error.
How to fix?

**Comment by ardyfeb** [comment]
> Hey everyone, here is a fix you can add yourself that will work with RN >= 0.59 or Expo SDK 33.
> 
> 1. Create rn-cli.config.js in your base folder.
> 
> ```js
> module.exports = {
>     transformer: {
>         babelTransformerPath: require.resolve('./scripts/customReactNativeTransformer')
>     }
> };
> ```
> 
> 1. Create a file in your base folder called  ./scripts/customReactNativeTransformer.js
> 
> Add the following:
> 
> ```js
> const {
>     transform,
>     getCacheKey,
> } = require('metro-react-native-babel-transformer/src/index);
> 
> function customTransform(config) {
>     config.options.hot = false;
>     return transform(config);
> }
> 
> module.exports = {
>     transform: customTransform,
>     getCacheKey,
> };
> ```
> 
> 1. Now you can use MobX@6!

hot reload will not available with this config
