### ISSUE TITLE
Idiomatic way to use mobx PropTypes

### ISSUE THREAD

**Issue by st-sloth** [mobxjs/mobx-react#691]
Since `PropTypes` here only contains mobx specific types, an application needs to use both `PropTypes` from `prop-types` and `PropTypes` from `mobx-react` (mainly for `arrayOrObservableArrayOf`, it seems).

[Search on GitHub](https://github.com/search?q=arrayOrObservableArrayOf&type=Code) shows mostly the approach
```
import PropTypes from "prop-types"
import { PropTypes as MobxPropTypes } from "mobx-react" // or `as ObservablePropTypes`

Component.propTypes = {
  items: MobxPropTypes.arrayOrObservableArrayOf(
    PropTypes.shape({ ... }),
  ),
}
```

and rarely, including [tests here](https://github.com/mobxjs/mobx-react/blob/master/test/propTypes.test.js) use
```
import ReactPropTypes from "prop-types"
import { PropTypes } from "mobx-react"

Component.propTypes = {
  items: PropTypes.arrayOrObservableArrayOf(
    ReactPropTypes.shape({ ... }),
  ),
}
```

README here too hints at the second way
> Use `import { PropTypes } from "mobx-react"` to import them, then use for example `PropTypes.observableArray`

but does not say how to use it with `prop-types` which causes confusion and spending extra time researching on how one should use them together.

What do you consider the preferable way for combining `PropTypes` from the two libraries?

**Comment by FredyC** [comment]
I am not sure what are you asking. Each set of prop types is different and as such needs to be imported separately. What naming scheme you use it's up to you. If you want to keep it consistent, you can make yourself something like this and use it throughout your code base.

```js
import ReactPropTypes from "prop-types"
import { PropTypes as MobXPropTypes } from "mobx-react"

export { ReactPropTypes, MobXPropTypes }
```

There is also some idea to actually move prop types out of mobx-react into a separate package. In theory, we could provide such exports in there.

**Comment by st-sloth** [comment]
Yes, this is exactly the problem. There are so many ways to do this thing, and it is up to the developer to choose from them. And since there is little functional difference, it seems to be purely matter of preference. But a way idiomatic in the community is usually preferable (as with all standardization), so other people reading the code would be at home with this code.

For someone new to MobX, this choice is a bit overwhelming, especially with nothing about this topic in the docs (using `PropTypes` from both libraries at the same time). So one has to either go with their inner feeling, or research how other people are doing this.

It is curious how authors, maintainers and community in general see both `PropTypes` should be used. So that it could be added to the docs.

**Comment by FredyC** [comment]
To be honest, this particular concern of yours is an absolute drop in the sea :) How you import and name something is effectively irrelevant to the code. If you work on a team, you can establish your "idiomatic way" and it's totally fine.

It's one of the reasons why Prettier became so popular. People don't wont to spend time thinking about how the code looks, but how the code works and if it does what they need. Naming variables is pretty much in this category too.

Feel free to create a repo that takes prop-types from this package and exports them together with React ones. We can then transfer it under MobX wings and make it official. See more at #661 

---

Personally, I would recommend you to switch to TypeScript (or FlowType if you must) and forget about PropTypes altogether. It's so annoying to wait for the error to show up in the runtime when instead, you can have IDE (VSCode) to tell you that this value is wrong without actually running the code.

**Comment by urugator** [comment]
If you're using Mobx5, I think you can more or less stick with normal `prop-types`. Everything should work as expected. 
The benefit of forcing observability is arguable:
```javascript
// fine
<Something array={anObservableArray}></Something>
// throws, because array isn't observable, even though everything would work correctly 
<Something array={anObservableArray.filter(Boolean)}></Something>
```
And if checking for observability is neccesary for whatever reason, the implementation of `MyPropType.observable(arbitraryPropType)` should be pretty trivial.

**Comment by st-sloth** [comment]
@FredyC, @urugator thank you for your answers!
I hope it's okay if I leave this open for a while, in case someone has something to add.

**Comment by mweststrate** [comment]
Closing as question has been answered
