### ISSUE TITLE
Confusing Documentation \ Changelog 

### ISSUE THREAD

**Issue by samcooke98** [mobxjs/mobx-react#700]
Sorry to open an issue \ question for this.

In the Readme.md, it says: 
"Note that `observer` automatically applies `React.memo` to any component you pass to it."
I see that this was added in https://github.com/mobxjs/mobx-react/commit/516a21ebd4656a29e2a98decd8307c7ad0b64d19 (Post v6)

However, in the changelog, it says: 
"Using PureComponent is now recommended."
https://github.com/mobxjs/mobx-react/blob/master/CHANGELOG.md

So should we be using the following code? ie: Going through our current observed components, and making them Pure? 
```
@observer
class SomeClass extends PureComponent 
```

**Comment by FredyC** [comment]
You are right, it is confusing :) The `React.memo` is relevant for a functional components only. For class components, you should indeed use `PureComponent` (which is equivalent).

PR welcome if you can write it in a more understandable form.
