### ISSUE TITLE
Wrong typings of 'inject' used as function in typeScript

### ISSUE THREAD

**Issue by Lazarencjusz** [mobxjs/mobx-react#706]
This is not about @decorator. I want to export React.PureComponent using `inject`:
 `export const ModalInputContainer = inject('localStoregeStore')(ModalInput);`

`localStoregeStore` is my one storage:

```jsx
export class LocalStoregeStore {
  @observable someValue: string = 'value';
}

export interface IAppStore {
  localStoregeStore: LocalStoregeStore;
}

export const appStore: IAppStore = {
  localStoregeStore: new LocalStoregeStore(),
};

  ReactDom.render(
    <Provider {...appStore}>
      <App />
    </Provider>,
    document.getElementById('body'),
  );

```

So, exporting the component like I show at top I got TS error:
```
Property 'localStoregeStore' is missing in type '{ prop: string; }' but required in type 'Readonly<IProps>'.ts(2741)
```
and component definition:
```jsx
export interface IProps {
  localStoregeStore: LocalStoregeStore;
  prop: string;
}

export class ModalInput extends React.PureComponent<IProps> {}
```

I have looked to inject types definitions, and it seems, that extracting Store properties from own properties works wrong. TS still require property that is injected. Using `inject` by passing function as argument (instead store name as string) cause same error.

**Comment by FredyC** [comment]
Please see https://github.com/mobxjs/mobx-react/issues/256 and numerous others. It's practically impossible to get typing of inject right.

I would recommend slowly migrate away from inject pattern: https://mobx-react.netlify.com/recipes-inject

**Comment by Lazarencjusz** [comment]
@FredyC 
ok, I have tried https://mobx-react.js.org/recipes-context and I get error, 
```
Invalid hook call. Hooks can only be called inside of the body of a function component
```

Do you have any example working repository?

**Comment by FredyC** [comment]
You need mobx-react@6 or mobx-react-lite.

**Comment by Lazarencjusz** [comment]
@FredyC well, I have latest `"mobx-react": "^6.0.3"` and get this error

**Comment by FredyC** [comment]
Can you show more information then? Possibly some code? My crystal ball is broken this week 😆

**Comment by Lazarencjusz** [comment]
So my `index.tsx`:
```tsx
export function start() {
  ReactDom.render(
    <StoreProvider>
      <MatchMaker />
    </StoreProvider>,
    document.getElementById('body'),
  );
}
start();
```
`StoreProvider`:
```tsx
const storeContext = React.createContext<TStore | null>(null);
export const StoreProvider = ({ children }) => {
  const store = useLocalStore(createStore);
  return <storeContext.Provider value={store}>{children}</storeContext.Provider>;
};

export const useStore = () => {
  const store = React.useContext(storeContext);
  if (!store) {
    // this is especially useful in TypeScript so you don't need to be checking for null all the time
    throw new Error('You have forgot to use StoreProvider, shame on you.');
  }
  return store;
};
```
Simple component used as starting point in `index.tsx`:
```tsx
export const MatchMaker = observer(() => {
  const store = useStore();
  return <p>AAA</p>;
});
```

**Comment by FredyC** [comment]
Well, I don't see any issue with that, definitely not related to the error you've reported. Can you please use CodeSandbox to demonstrate the issue?

**Comment by Lazarencjusz** [comment]
@FredyC sorry for this mess. Can't explain what happen, but most probably my webpack build cashed some files and didn't react for any changes after showing the rebuild.

Thanks for help, I will continue testing of `mobx-react` :)
