### ISSUE TITLE
Provider doesn't seem to work in an isomorphic setting 

### ISSUE THREAD

**Issue by prashaantt** [mobxjs/mobx-react#71]
I use a static method (the typical `fetchData()`) in my components to load all the required data before rendering on the server. Using the `Provider` API no longer gives me access to that static method.

**Comment by prashaantt** [comment]
To be more specific, the static method isn't available any longer if I use the `observer(["store"])` construct. Using `Provider` by itself isn't the real reason.

**Comment by mattruby** [comment]
I think I can see what you're up against here.  The observer with store is calling createStoreInjector which calls React.createClass with the correct context settings.  You component is wrapped up in the render call of the wrapper.  Hmmmm...  Give me a few to look into what could be done to attach your statics to the wrapping component.  Can you think of anything other than statics that would need to be applied to the wrapper?

**Comment by mattruby** [comment]
@prashaantt Give my PR a look.  See if that fixes the issue with statics.

**Comment by prashaantt** [comment]
Thanks, this works perfectly!

I can't think of anything else for the moment that Provider should surface, but will surely report back if I do.

**Comment by mweststrate** [comment]
@prashaantt didn't merge the proposed PR. I think it is a bit fuzzy and unidiomatic. It is better to either separate the inner and higher order component. Also the original component is now available on the higher order component as `.wrappedComponent`. If anything is unclear, feel free to re-open this issue.

**Comment by prashaantt** [comment]
@mweststrate The good thing is, I'm not sure if you intended it but I now have access to my `fetchData` inside the `wrappedComponent` all right!

**Comment by mattruby** [comment]
@prashaantt pretty sure that was @mweststrate 's intent.  His wrappedComponent is the better way to go.
