### ISSUE TITLE
Uncaught TypeError: Cannot read property 'Observer' of undefined

### ISSUE THREAD

**Issue by MikeWarren2014** [mobxjs/mobx-react#710]
For some reason, when I brought in mobx-react, right after React,ReactDOM `<script>` tags, it fails with the following error:
```
Uncaught TypeError: Cannot read property 'Observer' of undefined
```
I try Google search for this and it returns nothing.

I am bringing the dependencies in via the following URIs:

MobX : `//unpkg.com/mobx@5.9.4/lib/mobx.umd.min.js`
ReactJS : `//unpkg.com/react/umd/react.development.js`
ReactDOM: `//unpkg.com/react-dom/umd/react-dom.development.js`
MobX-React: `//unpkg.com/mobx-react`

**Comment by FredyC** [comment]
Wow, I am surprised that somebody actually uses UMD :) You are missing "mobx-react-lite" dependency. 

Friendly advice: When using UMD always look on top of the file for all the `require` calls and make sure you got all of them.

**Comment by MikeWarren2014** [comment]
That fixed the issue! btw, when did this become a thing!?
