### ISSUE TITLE
disposeOnUnmount are failing with react-hot-loader

### ISSUE THREAD

**Issue by Amareis** [mobxjs/mobx-react#725]
Latest mobx-react version. I think it's related to react-hot-loader, but not sure.

![image](https://user-images.githubusercontent.com/4806617/61125345-06224d00-a4c3-11e9-9526-156bb3d4074a.png)
![image](https://user-images.githubusercontent.com/4806617/61125388-1d613a80-a4c3-11e9-8db8-8b834ba81102.png)

**Comment by Amareis** [comment]
(there is no such error at decorator version)

**Comment by FredyC** [comment]
Please provide a reproduction, otherwise, we are as clueless as you are :)

**Comment by Amareis** [comment]
Reproduction: https://github.com/Amareis/testmr

**Comment by FredyC** [comment]
Thank you, we will look into it.

On the sideline, seeing you have React 16.8 there, would you consider trying out hooks? Especially the case like this gets amazingly simple. The `useEffect` will take care of disposing for you without any extra utilities. Read more at https://mobx-react.js.org/recipes-effects

```js
export default const App {
  const path = window.location.pathname
  React.useEffect(() => when(
    () => app.state !== AppState.START,
    () => startRouting(path))
  }, [path])

  return null
}
```

**Comment by Amareis** [comment]
Yep, we start using hooks recently, but didn't switch whole codebase to it yet. Original component has some reactions as class fields, and this isn't single broken component, so it's not as simple to just rework all the things :)

**Comment by JabX** [comment]
Pretty sure this is indeed a react-hot-loader problem since you have 2 `componentDidMount` references in your stack trace. That limitation on direct subclasses for `disposeOnUnmount` is going to be lifted with #707 (by tying it with `observer` instead of `React.Component`), so when that PR is merged your problem should be fixed.

As far as my projects are concerned I've been waiting for that to upgrade to mobx-react@6. In the mean time I use mobx-react-lite directly for hooks support and it works fine.

**Comment by akonyer** [comment]
Any word on this yet? It's frustrating to not be able to update to mobx-react v6 just because of react-hot-loader

**Comment by FredyC** [comment]
@akonyer As you can see, there is a pending PR #707 which seems got kinda stuck, not sure why, but please refrain from asking "when" in there. Apparently, people got busy. You can try to take a stab at it on your own if you desperately need it.

**Comment by akonyer** [comment]
I apologize. Did not mean to rush anyone, and of course people get busy. Thank you for your reply and an update on the status of this PR. I will stick to v5 for now, or consider dropping react-hot-loader.

**Comment by chrisinajar** [comment]
The decorator seems to work correctly as compared to using the method inside of componentDidMount... if you change:
```jsx
componentDidMount() {
  disposeOnUnmount(this, disposerStatement());
}
```
to
```jsx
@disposeOnUnmount disposer = disposerStatement();
```
then it works

**Comment by Amareis** [comment]
Still failing, but switching from react-hot-loader to react fast refresh solves the issue.

**Comment by Amareis** [comment]
Solution is using react-fast-refresh
