### ISSUE TITLE
Do mobx-react support react-native?

### ISSUE THREAD

**Issue by pssgo** [mobxjs/mobx-react#732]
RT

i tried to use mobx and mobx-react in react-native,
but

i got error 

![image](https://user-images.githubusercontent.com/16378134/62037063-a4354780-b225-11e9-8cc8-461fb294fe69.png)

**Comment by pssgo** [comment]
I solved this problem by turning mobx-react back to 5.4.3

**Comment by FredyC** [comment]
See #690
