### ISSUE TITLE
Attempted import error: 'useObserver' is not exported from 'mobx-react'

### ISSUE THREAD

**Issue by SidKwok** [mobxjs/mobx-react#734]
mobx-react@6.1.1

**Comment by FredyC** [comment]
That's total oversight, thanks for letting us know. I've fixed it directly in master, so it will be there with the next release.

**Comment by FredyC** [comment]
6.1.2 published with the fix

**Comment by nrkroeker** [comment]
While the function itself is now exported, it isn't included in the types definition. For us Typescript users would you mind adding the same one line fix to index.d.ts? 😝 @FredyC

**Comment by FredyC** [comment]
Ah, still can't seem to remember that this project is still written in JS and TS has to be maintained separately. I need to change that soon, it's fairly annoying.

Published fix in 6.1.3
