### ISSUE TITLE
Explain the difference between mobx-react's observer and mobx-react-lite's observer

### ISSUE THREAD

**Issue by blacksteed232** [mobxjs/mobx-react#736]
Hi, I'm currently using `mobx-react@6.1.1`. I noticed that when I try to import `observer`, I could import it from either `mobx-react` or `mobx-react-lite`. I also notice that only the one from `mobx-react-lite` is the one I want to use as I'm using function component that needs `forwardRef` and only the latter has typescript support for `forwardRef`. 

So my question is what is the difference between these? Is this the case that `mobx-react v6` is really just the wrapper around `mobx-react-lite` so whenever we want to use function component, we have to import stuffs from `mobx-react-lite`? If so, if I have an app which is 100% function component, should I just install `mobx-react-lite` instead?

---

Also, do you have a recommendation on which pattern should I pick `observer` or `useObserver` for function components? I have read the documentation, and my impression is, we can always just use `observer` to wrap around the whole function component and `useObserver` is only when you want to avoid polluting the component tree, but you have to be extra careful not to miss any observable, am I right?

---
UPDATE: I'm aware of #640 but then the thread gets too long and I don't think it gives me a definite answer. Hopefully, we could have one here and update the doc for both `mobx-react` and `mobx-react-lite` accordingly

**Comment by FredyC** [comment]
Have you seen https://mobx-react.js.org/libraries?

**Comment by blacksteed232** [comment]
@FredyC 
Gotcha! So for now fresh project should use `mobx-react-lite` and even if that might get deprecated, it will be super easy to migrate.

**Comment by FredyC** [comment]
Yes, the lite will be slightly faster as it doesn't need to check for class components.
