### ISSUE TITLE
Can't resolve 'react-dom'

### ISSUE THREAD

**Issue by JamesRamm** [mobxjs/mobx-react#741]
Hi

I am having the same issue as in #42 in that I get the following error:

```
ERROR in <path>/node_modules/mobx-react/index.module.js
    Module not found: Error: Can't resolve 'react-dom' in '<path>\node_modules\mobx-react'
```

However my project *is* using react-dom. 
My offending local module which is using mobx-react is being _npm link_'d into my project (which, for what its worth is a mendix 'pluggable widget'). 

The paths in the error message refer to the linked module, although there is 'react-dom' present in the node_modules of both the linked module and my project. 

It seems it can be related to npm link but it is not clear how, especially since the build process of my project is a little bit cryptic; its not actually under my control and the auto-generated package.json file does not list React nor ReactDOM although both are present in node_modules after a build.

**Comment by FredyC** [comment]
If I recall correctly, any linked module needs to have its own set of modules. It cannot reuse ones from the linked project.

If that's not the case then I don't think we can do anything without proper reproduction.

**Comment by JamesRamm** [comment]
Yes both the linked module (in which I ran 'npm link') and the mendix widget project (in which I ran 'npm link mymodule') have their dependencies installed in node_modules and in both cases react-dom is present (and the versions are equal if that makes a difference). 

I will try to get an reproduction but since I dont particularly know how mendix is handling the bundling it could be tricky...

**Comment by JamesRamm** [comment]
OK. A minimal reproduction attached. 
[issue_repro.zip](https://github.com/mobxjs/mobx-react/files/3455974/issue_repro.zip)
Steps:
1. Run `npm install` in the `./jsmodule` and `./mxwidget/widget` folders
2. In `./jsmodule` run `npm link`
3. In `./mxwidget/widget` run `npm link jsmodule`
2. Run `npm run build` in `./mxwidget/widget`

Output:

```
    ERROR in D:/source/mendix/issue_repro/jsmodule/node_modules/mobx-react/dist/mobx-react.module.js
    Module not found: Error: Can't resolve 'react-dom' in 'D:\source\mendix\issue_repro\jsmodule\node_modules\mobx-react\dist'
     @ D:/source/mendix/issue_repro/jsmodule/node_modules/mobx-react/dist/mobx-react.module.js 1:0-52 1:9899-9900 1:9923-9924
     @ D:/source/mendix/issue_repro/jsmodule/index.js
     @ D:/source/mendix/issue_repro/mxwidget/widget/src/Widget.jsx
```

**Comment by FredyC** [comment]
Well, I am thinking since you are Mendix which is something nobody probably heard about here, you might get a better response in their support channels. It's most likely it's some issue related to their bundling approach. I don't have a capacity to dive into that for now, sorry.

**Comment by JamesRamm** [comment]
After some investigation, adding the following to the webpack file used by the mendix build process seems to fix (or maybe ignore?) the issue:
```
resolve: {
      alias: {
         'react-dom': path.resolve(path.join(__dirname, './node_modules/@hot-loader/react-dom')),
      }
   }
```

In any case it does seem to be caused by the mendix stuff rather than anything in mobx-react itself, so closing.

As far as I am aware mobx was either created at Mendix or the author works at mendix so it could be useful if @mweststrate is able to confirm that this is an issue specific to mendix widgets?

**Comment by mweststrate** [comment]
I no longer work at Mendix, and I've not been using the widget
infrastructure for the last ~3 years, so my knowledge here is really
outdated. That being said, importing react-dom from another dependency,
@hot-loader, looks quite awkward? (Or maybe this is how hot-loader is
supposed to be used, I have no experience with the package, but to be sure
best visit their docs)
