### ISSUE TITLE
[Please help] IE 11 not working inject store

### ISSUE THREAD

**Issue by mrnav90** [mobxjs/mobx-react#753]
I used lib version:
I trying to build and run my application on IE 11 with some tricks but not working.
1. Import @babel/polyfill
2. import proxy-polyfill
3. import es6-symbol/implement
![ie](https://user-images.githubusercontent.com/9253581/62508767-fdf3ce00-b832-11e9-8b85-c38ab5e80bcb.png)
I used lib version like below:
Mobx: 5.13.0
Mobx-React: 5.4.3

I'm trying to downgrade mobx 4 for support IE11. It's worked but mobx 4 don't re-render when I change properties observable.
Ex:
@observable tracks = {};
const media = this.tracks[userId].find(t => t.type === 'video')
try to modifier
media.muted = !media.muted;
It's not re-render component, but when I used mobx 5 it's worked.

So now I don't know do somethings for support IE 11 or fix issue re-render in mobx 4.
Somebody please help me.
Thanks you so much.

**Comment by FredyC** [comment]
You have to use MobX 4 for IE 11 support - Proxies which are in MobX 5 cannot be polyfilled by any means.

**Comment by mrnav90** [comment]
@FredyC But when I used Mobx 4 for IE11, I've happen issue re-render.
Can you help me?
I've explain my issue in first post.

**Comment by FredyC** [comment]
Please, provide a reproduction with eg. CodeSandbox.
