### ISSUE TITLE
Typo in Migration guide documentation

### ISSUE THREAD

**Issue by Kazimirkas** [mobxjs/mobx-react#755]
[Here](https://mobx-react.js.org/recipes-migration)
you have a wrong import string.
As I understood
`import { useObserver } from 'mobx-react'`
should be replaced to 
`import { useObserver } from 'mobx-react-lite'`
Because it is not available in mobx-react v6.1.1.

I made a [PR](https://github.com/mobxjs/mobx-react-docz/pull/28) with this fix

**Comment by vkrol** [comment]
It was fixed in https://github.com/mobxjs/mobx-react/commit/885aa9cf75706b8d4e303450accfd5eefda62d8d. Maybe it's better to wait for the release of 6.1.2.

**Comment by Kazimirkas** [comment]
> It was fixed in [885aa9c](https://github.com/mobxjs/mobx-react/commit/885aa9cf75706b8d4e303450accfd5eefda62d8d). Maybe it's better to wait for the release of 6.1.2.

Im a newbie in MobX and it is kind of confusing to me, because it is not obvious. Could it be fixed now and be fixed again with 6.1.2 release?

**Comment by FredyC** [comment]
Sadly, it's not possible to add that reexport to previous versions. It was just an oversight.

**Comment by Kazimirkas** [comment]
> Sadly, it's not possible to add that reexport to previous versions. It was just an oversight.

Im talking only about a text fix in documentation. I've made a [PR](https://github.com/mobxjs/mobx-react-docz/pull/28)
