### ISSUE TITLE
decorator @inject not works with typescript and 'reflect-metadata'

### ISSUE THREAD

**Issue by tvolodimir-note** [mobxjs/mobx-react#756]
using **inject** as decorator with **typescript** and **reflect-metadata** lib raise error
```js
import * as React from 'react';
import * as ReactDOM from 'react-dom';
import { Provider } from 'mobx-react';
import { inject } from 'mobx-react';

// comment next line to start working
import 'reflect-metadata';

class MyStore {

}

@inject('myStore')
class App extends React.Component<{ myStore?: MyStore }> {
  render() {
    console.log(this.props.myStore);
    return <p>Hello</p>;
  }
}

ReactDOM.render(
  (<Provider myStore={new MyStore()}>
    <App />
  </Provider>), document.getElementById('root'));
```
```
TypeError
    at DecorateConstructor (Reflect.js:544)
```
libs:
```
mobx: 5.13.0
mobx-react: 6.1.2
react: 16.9.0
react-dom: 16.9.0
reflect-metadata: 0.1.13
```

demo with issue: https://stackblitz.com/edit/react-mobx-ts-issue

**Comment by FredyC** [comment]
Duplicate to https://github.com/mobxjs/mobx-react/issues/706 (and many others). Please use the search next time.

**Comment by tvolodimir-note** [comment]
Any decorators of constructor function should return constructor function. And your library doesn't support this standards

**Comment by FredyC** [comment]
Well, if you have an idea of how to fix that, feel free to send in PR. Apparently, you are the first being concerned by this, so it's kinda up to you to fix that ;)

**Comment by dubinam** [comment]
@FredyC  Hi, the same problem, tried to google some solution but nothing at all.

**Comment by FredyC** [comment]
Considering that we are considering `inject` as obsolete, I wouldn't expect a fix too soon unless the one you wants to do that. Obviously, you want to use something that's not even officially in language spec, so you have to pay the price for the bleeding edge.

**Comment by tvolodimir** [comment]
I found workaround, using another injection library - **inversify**

```js
import * as React from 'react';
import * as ReactDOM from 'react-dom';
import { Provider, resolve } from 'inversify-react';
import { Container, injectable } from 'inversify';

import 'reflect-metadata';

@injectable()
class MyStore {

}

class App extends React.Component {
  @resolve(MyStore)
  private readonly myStore: MyStore;

  render() {
    console.log(this.myStore);
    return <p>Hello</p>;
  }
}

const container = new Container();
container.bind(MyStore).toConstantValue(new MyStore());

ReactDOM.render(
  (<Provider container={container}>
    <App />
  </Provider>), document.getElementById('root'));
```

So I anyway I recommend everyone to start using any well known **DI library** instead of **@inject**

**Comment by FredyC** [comment]
Not sure why you would want to avoid React Context, but your fight. Closing then.

**Comment by tvolodimir** [comment]
@FredyC can you advise what to do with class-based components?

**Comment by FredyC** [comment]
Use the Context ... https://reactjs.org/docs/context.html#classcontexttype

**Comment by zetoke** [comment]
>reflect-metadata which purpose is still eluding me.

@FredyC It has a lot of possibilities but speaking about Typescript it's very useful for the cases when you need to get and use somehow a typescript type inside a decorator.
Typescript emits and sets metadata information during complication time.
https://www.typescriptlang.org/docs/handbook/decorators.html#metadata

It especially useful for the things like DI systems, ORM, and so on.

**Comment by vkrol** [comment]
@tvolodimir-note 
> Any decorators of constructor function should return constructor function. And your library doesn't support this standards

There is some issue with `react-redux` https://github.com/rbuckton/reflect-metadata/issues/108#issuecomment-484621621.
