### ISSUE TITLE
mobx加form表单，当mobx中绑定到form表单的数据改变时，不会触发mapPropsToFields方法

### ISSUE THREAD

**Issue by mqyun** [mobxjs/mobx-react#761]
### Reproduction link
[https://github.com/mqyun/antd-mobx](https://github.com/mqyun/antd-mobx)

### Steps to reproduce
npm install 后， npm start运行进入 /login 页面，输入表单信息，点击重置按钮mobx中数据清空了，但是不会触发antd form的mapPropsToFields方法，页面上仍显示input内容
### What is expected?
数据清空后和mobx中的数据保持一致，form表单信息清空
### What is actually happening?
form表单显示未清空，实际mobx中的数据已清空

Environment | Info
-- | --
antd | 3.21.4
React | 16.8.6
System | macOS Mojave 10.14.4
Browser | 76.0.3809.100

**Comment by FredyC** [comment]
Sorry, I don't speak your language. Use google translate if you must, but I can't help you like this.
