### ISSUE TITLE
Upgrading from v5.4.3 to v6 introduces Error: MobX injector: Store '*' is not available

### ISSUE THREAD

**Issue by stovmascript** [mobxjs/mobx-react#763]
We're using Next.js and mobx-state-tree and are setup according to the Next.js [with-mobx-state-tree](https://github.com/zeit/next.js/tree/canary/examples/with-mobx-state-tree) example.

I've searched around for this error and usually it comes to people incorrectly naming the store `Provider` prop doing something like `<Provider appStore={this.store}>` and then `inject('store')`. We have "appStore" everywhere and it works with mobx-react 5.

The things specific with our app are that we have quite a lot of nested models, though usually not more than one level, like this:

```js
import Dashboard from './Dashboard'
// ...

const AppStore = types
  .model('AppStore', {
    dashboard: types.optional(Dashboard, {}),
    reports: types.optional(Reports, {}),
    user: types.optional(User, {}),
// ...
```

And apart from `inject('appStore')(observer(Component))`, we're also wrapping a lot of our components other HOCs like Lingui's `withI18n` and our custom HOCs, so a component may look like this:

```js
import { withI18n } from "@lingui/react"
import withConfirmDialog from './withConfirmDialog'

// ... const Component ...

export default withConfirmDialog(withI18n()(inject('appStore')(observer(Component))))
```

I've also tried setting up error boundaries in Next.js' [`_app`](https://nextjs.org/docs#custom-app) and [`_error`](https://nextjs.org/docs#custom-error-handling) components, which wrap all pages, but this error never goes through them and crashes the app.

Does any of this sound like it could be related to changes made in mobx-react 6?

---

Packages:

```
    "mobx": "^4.8.0",
    "mobx-react": "^6.1.3",
    "mobx-state-tree": "^3.13.0",
    "next": "^9.0.1",
    "react": "^16.8.6",
    "react-dom": "^16.8.6",
```

**Comment by FredyC** [comment]
Please provide reproduction and proper versions of relevant packages, mobx, react, etc...

**Comment by stovmascript** [comment]
Ok, so it's not a mobx-react issue. Finally figured it out after tons of digging. We're using and old version of Material-UI (v0), which we are working to upgrade to the latest version (v4, lol), which uses hooks a lot - hence the upgrade of mobx-react. It seems that Material-UI v0 renders popovers (icon menus, etc.) somewhere outside the React root element, which means outside the MobX store provider, which triggers this error. If you don't inject the store in the component that's being rendered inside the popover, it works fine. Material-UI v4 doesn't have this problem and also works fine with mobx-react v6.
