### ISSUE TITLE
Jest test require react-dom

### ISSUE THREAD

**Issue by jinshin1013** [mobxjs/mobx-react#764]
### Problem
We recently set up a jest test with [@testing-library/react-native](https://github.com/testing-library/native-testing-library) for our react-native project. 

When running `jest ./src`, I get the following error:
```
Cannot find module 'react-dom' from 'mobx-react.js'

    at Resolver.resolveModule (node_modules/jest-resolve/build/index.js:230:17)
    at Object.<anonymous> (node_modules/mobx-react/dist/mobx-react.js:1:36)
```

Jest doesn't seem to be using `dist/mobx-react.rn.module.js`. I don't think it's `mobx-react` problem but I was wondering if anyone had encountered this problem and how to resolve it.

#### Installed packages:

```json
"dependencies": {
  "react": "16.8.6",
  "react-native": "0.60.5",
  "mobx": "5.13.0",
  "mobx-react": "6.1.3",
},

"devDependencies": {
  "@testing-library/react-native": "4.0.7",
  "jest": "24.8.0",
  "ts-jest": "24.0.2",
}
```

#### jest.config.js
```js
const { defaults: tsjPreset } = require('ts-jest/presets')
const jestPreset = require('@testing-library/react-native/jest-preset')

module.exports = Object.assign(jestPreset, {
  ...tsjPreset,
  preset: '@testing-library/react-native',
  transform: {
    ...tsjPreset.transform,
    '\\.(ts|tsx)$': '<rootDir>/node_modules/ts-jest/preprocessor.js',
    '\\.js$': '<rootDir>/node_modules/react-native/jest/preprocessor.js',
  },
  globals: {
    'ts-jest': {
      babelConfig: true,
      diagnostics: false,
    },
  },
  testPathIgnorePatterns: ['\\.snap$', '<rootDir>/node_modules/'],
  setupFiles: [
    ...jestPreset.setupFiles,
    '<rootDir>/node_modules/react-native-gesture-handler/jestSetup.js',
    '<rootDir>/node_modules/appcenter/test/AppCenterMock.js',
    '<rootDir>/node_modules/appcenter-analytics/test/AppCenterAnalyticsMock.js',
    '<rootDir>/node_modules/appcenter-crashes/test/AppCenterCrashesMock.js',
    '<rootDir>/node_modules/appcenter-push/test/AppCenterPushMock.js',
  ],
  setupFilesAfterEnv: [
    '@testing-library/react-native/cleanup-after-each',
    '<rootDir>/setupUnitTest.ts',
  ],
  cacheDirectory: '.jest/cache',
})

```

**Comment by FredyC** [comment]
I think you will need to configure a [custom resolver](https://jestjs.io/docs/en/configuration#resolver-string) there that maps to a correct file. BUT there might be a problem is that `mobx-react.rn.module.js` is in ESM format, but Jest requires CJS. Not sure if that gets picked up by transforms.

**Comment by jinshin1013** [comment]
Yeah jest is refusing to use `mobx-react.rn.moduile.js` unfortunately. We are working around by just installing `react-dom` to `devDependencies`. It works for now.

**Comment by FredyC** [comment]
And what about that custom resolver? I believe it should work. Basically, you need to remap the `mobx-react.js` to `mobx-react.rn.module.js`.

FYI That RN build is no special, it's just copy `mobx-react.module.js` and text replace of `react-dom` to `react-native`.

**Comment by cory-gottschalk** [comment]
Hey @FredyC,

I also ran into this issue after upgrading to mobx-react v6 and found that adding the following to jest.config.js can be used as a workaround:

```javascript
{
    moduleNameMapper: {
        '^mobx$': '<rootDir>/node_modules/mobx/lib/mobx.module',
        '^mobx-react-lite$': '<rootDir>/node_modules/mobx-react-lite/dist/native',
        '^mobx-react$': '<rootDir>/node_modules/mobx-react/dist/mobx-react.rn.module',
    }
}
```

@jinshin1013 Can you try adding the above to your jest.config.js and see if it works for you?

**Comment by FredyC** [comment]
@cory-gottschalk Good call. I don't think it's _workaround_ more like a current solution. As long as Jest does not recognize `react-native` entry file that's defined there, we cannot really do anything about it.

See here for reasons why we even need RN specific build: https://github.com/facebook/react/issues/15080

**Comment by FredyC** [comment]
@cory-gottschalk Currently, I toying with a [different approach](https://github.com/mobxjs/mobx-react-lite/pull/214) in `mobx-react-lite` and chances are we would add it here as well. That would at least remove the need to configure Jest in a specific way.
