### ISSUE TITLE
Strict mode changing observed observable values outside actions is not allowed message._store.validated

### ISSUE THREAD

**Issue by jkeruzec** [mobxjs/mobx-react#765]
I think I have an issue with mobx-react. It's a particular case :
It was something that worked before with old mobx version .. 

version used : 
```js
"react": "^16.9.0",
"mobx": "^5.13.0",
"mobx-react": "^6.1.3",
"mobx-react-devtools": "^6.1.1",

```
I'm trying to set a message in a mobx action with enforceAction always.

```js
this.dialog.current.setMessage(<div>
                    <Typography key={1} gutterBottom component='span'>
                    Your session is about to expire.
                  </Typography>
                    <Typography key={2} gutterBottom component='span'>
                    You will be automatically signed out in : {expirationDate - currentTimeInS}s
                  </Typography>
                        <Typography key={3} gutterBottom component='div'>
                        Do you want to stay logged in ?
                      </Typography>
                </div>);
```
when my component is rendered with the message. It enters : 
![image](https://user-images.githubusercontent.com/3499632/63593704-cae06700-c5b4-11e9-8d33-17f450fef982.png)

 validateChildKeys(arguments[i], type);
with arguments[2] my message as : 
![image](https://user-images.githubusercontent.com/3499632/63593750-ec415300-c5b4-11e9-85b9-7c4f876c31de.png)
```

 // This element was passed in a valid location.
        if (node._store) {
          node._store.validated = true;
        }
```
node is my mobx "message" ..

It tries to set "validated" value out of an action directly from react.development.js ... 

Can you help ?

**Comment by FredyC** [comment]
Would you be able to create a simple reproduction with eg. CodeSandbox? Seems like some pieces are missing here so we need to see a whole picture.

**Comment by mweststrate** [comment]
From the stack trace, it seems that you are trying to update some state inside your render, which is forbidden by both React itself and by MobX :). Render should be pure. To update state, do it from one of the life cycle hooks of React, for example useEffect / componentDidUpdate

**Comment by FredyC** [comment]
Looks like we have misconfigured auto close bot, this tag shouldn't keep it open. I will fix that.

@jkeruzec Sorry, but without reproduction, we are unable to proceed further.
