### ISSUE TITLE
Incomplete migration guide to hooks

### ISSUE THREAD

**Issue by liranreg** [mobxjs/mobx-react#771]
Hello,

Currently in the docs there is explenation how to migrate from Class Component with @inject to Functional Component with useStores hook.

However, since the docs specify that the best practice is not to use React.Context to publish, and not the old react-mobx's Provider, I think what is really missing is a migration guide from react-mobx's Provider to React.Context.

A lot of apps, have a lot of Class Cimponents with "Inject", and its not resonable to expect them to migrate them all at once. howver, we do want them to start using the React.Context for new components.

What I am looking for, is a documentation of a way to have both in parallel.. so people can start using React.Context from now on, and gradually get rid of the old Provider (and @inject) usage.

Thank you

**Comment by liranreg** [comment]
My (failed) attempt:

```javascript
ReactDOM.render(
  <StoreProvider>
    <MobxProviderForInject>
          <App />
    </MobxProviderForInject>
  </StoreProvider>
  , document.getElementById('root')
)

function MobxProviderForInject ({ children }) {
  const stores = useStore()

  return <Observer>{() =>
    <Provider {...stores}>
      {children}
    </Provider>
  }</Observer>
}
```

where useStore and StoreProvider are taken from [the recipt](https://mobx-react.js.org/recipes-context).

I tried to use the React.Context to fulfill the Provider

**Comment by FredyC** [comment]
When you are referring to a migration guide, do mean this one? https://mobx-react.js.org/recipes-migration#hooks-to-the-rescue

Does it answer your question? Especially the second portion of that linked section with `MobXProviderContext`.

**Comment by liranreg** [comment]
thanks @FredyC. I saw this, but it does not answer my question.
the MobXProviderContext is a solution allowing you to keep using the **OLD** way of creating global stores with both inject and hooks.

I'm looking for a way to use global stores in the **NEW** way of useLocalStore hook, but still consume it with both inject and hooks.

**Comment by FredyC** [comment]
`MobXProviderContext` is a new way :) Why do you consider it old? The `mobx-react@6` uses only new way.

**Comment by liranreg** [comment]
Its new indeed, but I want to start using the recommended way, which according to the docs is useLocalStore + React.Context.. right now I can't

**Comment by FredyC** [comment]
I am really lost what's the problem. The `inject` is using the same `MobXProviderContext` that you can use with your hooks. As such you can migrate step by step.

**Comment by liranreg** [comment]
from the Components side who consume the store you are right.
but from the global stores side, it forces me to keep using the old way.. while I would like to migrate them to **useLocalStore** + **React.Context**.

If my code would have work, it would be possible..

**Comment by FredyC** [comment]
The point is that once you migrate all your `inject` to hooks, you can simply replace context with your own and nothing will break. Using `MobXProviderContext` is necessary if you don't want to migrate all at once. There is no other way.

**Comment by liranreg** [comment]
my suggestion would not be a better, other way?

Some projects would not migrate everything to hooks for a very long time. maybe never.

for all those projects, it forces them to never migrate to useLocalStore and React.Context instead of the old way of Provider + observable store..

**Comment by FredyC** [comment]
Wait, what? How is actually `useLocalStore` related to context? It's for _local stores_.

Either way, you can surely have two providers if that's a more interesting approach for you. Both will work equally.

**Comment by liranreg** [comment]
look at https://mobx-react.js.org/recipes-context under **Setup  context**, line #8. you can see that useLocalStore is used for creating the _global_ store. I agree that the term "local" is very confusing in this regard ..

I tried having two providers.. but my code (in the first reply of this post) didn't work. do you understand why?
anyway, I believe its a better approach so I would also add that to the migration guide, for the reasons I explained..

**Comment by FredyC** [comment]
That is one of the many approaches how you can set up a store. In fact, when you need stores that depend on each other you might rather grab mobx-state-tree or https://github.com/mobxjs/mobx-react-lite/issues/206#issuecomment-526052519.

But if you do have `inject` and don't want to migrate, you can always make your own `inject` ([as suggested](https://mobx-react.js.org/recipes-migration#make-your-own-inject)) and that way you don't need to rely on `MobXProviderContext` at all.

If you have a suggestion to improve docs, please send in a PR. From my point of view, it seems clear enough, so it's up to other people who can see it differently to show a better way.
