### ISSUE TITLE
Gotchas with React hooks and reactions

### ISSUE THREAD

**Issue by FredyC** [mobxjs/mobx-react#772]
Lately, I got somewhat burned by MobX powered side-effects. I hope you won't be intimidated by the length of this.

## The past
At the beginning of `mobx-react-lite` we had [a utility hook](https://github.com/mobxjs/mobx-react-lite#usedisposabled-extends-tdisposabledisposergenerator---d-inputs-readonlyarrayany---d) `useDisposable` which was supposed to be used to set up reactive side effects. Then came the realization that it doesn't offer anything on top of the `React.useEffect` so we decided to deprecate it.

```js
React.useEffect(() => {
  return reaction(() => store.count, () => {
    // side-effect
  })
}, [])
```

The only difference is that you need to specify empty deps. In case you would forget/omit that, the effect would execute on each render, clear previous reaction, and set up a new one. Not a big deal in most cases, but would bite especially when `fireImmediately` option would be used.

## Custom hooks to rescue

Most people (including me) probably went and made custom hooks to avoid these mistakes. Or perhaps they did not and that's ok too.

```js
export function useReaction(expression, effect, options) {
  React.useEffect(() => {
    return reaction(expression, effect, options)
  }, [])
}
```

Nothing spectacular and works the same as `useDisposable` except it removes another indentation level being specific to `reaction`. That's a win for abstraction.

```js
useReaction(() => store.count, () => {
    // side-effect
})
```

## The Enemy - closure

Consider the following, somewhat contrived, example.

```js
function Demo() {
  const store = useLocalStore(() => ({
    count: 1
  }))
  const [multiplier, setMultiplier] = React.useState(1)
  useReaction(
    () => store.count,
    count => {
      console.log(count * multiplier) // <-- Will this work?
    }
  )
  return useObserver(() => (
    <div className="App">
      Count: {store.count * multiplier}
      &nbsp; Multiplier: {multiplier}
      <br />
      <button onClick={() => setMultiplier(m => m + 1)}>Multiply!</button>
    </div>
  ))
}
```

See that in action: https://codesandbox.io/s/bold-dew-gubut

Values are rendered correctly, BUT at the moment you open the console to see the output of our little `reaction`, you realize it's wrong. Why? Because of the JavaScript closure 😱. The reaction is created with an initial effect function which has access to an initial value of `multiplier`. When the multiplier updates, the reaction is not recreated and still referring to initial value.

## ESLint is helpful

The infamous `react-hooks/exhaustive-deps` ESlint rule has surely saved many headaches (and caused some) in figuring out deps issues in hooks. In the case of our simple custom hook, the recommendation pops out to do the following...

```js
export function useReaction(expression, effect, options) {
  React.useEffect(() => {
    return reaction(expression, effect, options)
  }, [expression, effect, options]) // <-- Note the change
}
```

And the ESLint is right in this case too - partially. The output in console is correctly multiplied, although doubled due to `fireImmediately` and reaction recreating. [See an updated demo](https://codesandbox.io/s/blissful-driscoll-733mp).

It could be optimized like the following, but that's not very pretty. Kinda kills down MobX ease of use.

```js
const expression = React.useCallback(() => store.count, [store])
const effect = React.useCallback((count) => /* side effect */, [other, deps])
const options = React.useMemo(() => ({ fireImmediately: true }), [])
useReaction(expression, effect, options)
```

## The solution

The expression and options usually don't need to be up-to-date so we can keep them in refs and use their initial values only.

```js
export function useReaction(expression, effect, options) {
  const expressionRef = React.useRef(expression)
  const optionsRef = React.useRef(options)
  React.useEffect(() => {
    return mobx.reaction(
      expressionRef.current,
      effect,
      optionsRef.current,
    )
  }, [effect])
}
```

The effect itself can be optimized with `React.useCallback` to avoid recreating reaction when not recreated when it doesn't really need to. Generally avoiding staleness should be a priority.

However, with `fireImmediately` this gets even more complicated. I've ended up with a separate hook for that specific case. [See in the action](https://codesandbox.io/s/frosty-lake-2ki5m). I did not bother with other reaction options as those are rarely used (at least for me).

```js
export function useReactionNow(expression, effect) {
  const expressionRef = React.useRef(expression)
  const firedOnce = React.useRef(false)
  React.useEffect(() => {
    return reaction(
      expressionRef.current,
      (...args) => {
        effect(...args)
        if (!firedOnce.current) {
          firedOnce.current = true
        }
      },
      { fireImmediately: !firedOnce.current }
    )
  }, [effect])
}
```

Thoughts? I think we should definitely publish it somewhere as utilities. People shouldn't be forced to rediscover these issues the hard way.

**Comment by Maaartinus** [comment]
While I'm just starting with hooks, I've encountered quite a few problems already, so I definitely agree that something should be done. Just a few naive ideas:

- In the first codebox, allowing to pass `[multiplier]` as the deps through `useReaction` would solve it. Maybe the deps should be even mandatory so they don't get forgotten easily. It's quite possible that this idea isn't helpful in general as my experience is very limited. Anyway, "react-hooks/exhaustive-deps" isn't happy with it.
- Recreating the effect sounds wrong, however, the react guys seem to be happy with this and I can't see any alternative.
- Nitpick: The "if (!firedOnce.current)" test is superfluous.

**Comment by urugator** [comment]
Personally I suggest to avoid reactions completely.
They're similar to events in a sense that you can create ad hoc depdendencies/data flows. 
That itself leads to a code which is really hard to predict/follow/debug ... reaction causing another reaction possibly causing another reaction ... you can't tell, because anything can subscribe to anything anywhere. However they can't be even used like synchronous events as they're not "immediate" (explained in link below).
They may seem to provide a way to decouple code, but they just hide coupling, which is even worse.
They also don't work as a replacement for `componentDidUpdate/useEffect` as they're completely detached from react's lifecycle (eg. accessing DOM from reaction is not safe, unlike `cDU/useEffect`). 
(We wrap them inside `useEffect` so they can be properly disposed, but they don't run as part of `useEffect`!) 
Here is a bit more reasoning: https://github.com/mobxjs/mobx/issues/1006#issuecomment-426027838
I am convinced they're overused, misused, don't lead to a good design, have very little actual value and therefore I won't support any kind of API that encourages their use (especially inside components).
At the same time I won't battle against it - reactions are probably being used by a lot of people without(?) problems (I think it's more of a bliss ignorance though).

The problem itself should be probably solved like this:
```javascript
const [multiplier, setMultiplier] = React.useState(1);
const source = useAsObservableSource({ multiplier });
React.useEffect(() => {
    return reaction(
       () => store.count * source.multiplier, // you could also return [store.count, source.multiplier] and use shallow comparator
       result => {
          console.log(result);
       };
    )
}, [store, source])
```
But as I have already stated elsewhere, you can avoid all these kind of troubles by not mixing react state/props with mobx.

**Comment by FredyC** [comment]
@urugator Your "solution" is would work for sure, but that wasn't a point of this issue. It was contrived on purpose. The per-case solution is always easier, but thinking more abstract and trying to figure some _universal and safe_ approach is what I am trying to do so it can be taught properly.

It all nice in theory, but there are definitely a couple of cases where the imperative approach is necessary. For once when interacting with 3rd party imperative code. There isn't many of these, but they do exist.

And a real use case which I cannot imagine doing declaratively. Data about a user are cached, but when different user signs in, those need to be refreshed. It's not a rendering logic.

```ts
  const { data, loading, refetch } = useQLogoutWidget(
    { id: auth.userId! },
    { skip: !auth.isAuthenticated, fetchPolicy: 'cache-first' },
  )

  useReaction(() => auth.userId, userId => {
    if (userId !== null) {
      refetch({ id: userId })
    }
  })
```

---

I've ended up with following implementation that seems to work quite nicely. The `useReaction` would suffice in most cases and doesn't care about staleness. The `useLiveReaction` can recreate a reaction if a different effect is passed. I've also decided to revive the deprecated `useDisposable` (with some modifications) as I realized it can do more than simple `useEffect`, mainly the early disposal which comes in handy sometimes.

```ts
export function useReaction<T>(
  staticExpression: (r: mobx.IReactionPublic) => T,
  staticEffect: (arg: T, r: mobx.IReactionPublic) => void,
  options?: mobx.IReactionOptions,
) {
  const expressionRef = React.useRef(staticExpression)
  const effectRef = React.useRef(staticEffect)
  const optionsRef = React.useRef(options)
  return useLiveReaction(
    expressionRef.current,
    effectRef.current,
    optionsRef.current,
  )
}

export function useLiveReaction<T>(
  expression: (r: mobx.IReactionPublic) => T,
  effect: (arg: T, r: mobx.IReactionPublic) => void,
  options?: mobx.IReactionOptions,
) {
  const expressionRef = React.useRef(expression)
  return useDisposable(
    React.useCallback(
      () => mobx.reaction(expressionRef.current, effect, options),
      [effect, options],
    ),
  )
}

```

**Comment by urugator** [comment]
> universal and safe approach is what I am trying to do so it can be taught properly.

Effect in reaction should depend solely on it's arguments. You can leak variable to effect closure anywhere, it doesn't have to be inside react component/hook and it doesn't matter whether it's observable or not, it's always a potential error.
To prevent that you need an eslint rule, which checks that the effect body doesn't access anything outside it's scope (similary to `exhaustive-deps`). 

> 3rd party imperative code

If `reaction` is inavoidable it would mean that the 3rd party lib isn't usable without observables, which seem unlikely.
Afaict, the lib you're using depends on `react`, so you may need to use `useEffect`, but not a reaction.

> And a real use case which 

Again the reaction's are completely detached from react's lifecycle.
When you set `auth.userId`, your reaction can be invoked before a component update, meaning that the reaction's effect won't use a most up to date `refetch` function using the current `auth.userId`.
Even if you do it like I proposed:
```javascript
const source = useAsObservableSource({ refetch });
React.useEffect(() => {
    return reaction(
       () => [auth.userId, refetch],
       [userId, refetch] => {
          console.log(result);
       },
       {
        equals: shallowComparator,
       }
    )
}, [store, source])
```
While the effect will be eventually called with correct values, it may be called at least once on inconsistent values. These kind of issues may become a lot more apparent with async rendering.
Do yourself a favor and don't use `reaction` :D

**Comment by FredyC** [comment]
I think I would rather have a reaction recreated (it's not that expensive) than dealing with such verbose code :) In this case I even know that `refetch` won't change because it has a stable reference.

> If `reaction` is inavoidable it would mean that the 3rd party lib isn't usable without observables, which seem unlikely.

I don't see how is that related. If the library only does some imperative action and doesn't render anything, then the reaction is kinda obvious choice if state causing that is observable.

To be clear, I am not saying it's something we are using a lot. In our project with 900 source files, the reaction is present in 5 of them. It's really just to solve a couple of edge cases, so I wouldn't be worried about it as a source of confusion.

For the main topic of the issue, you are basically saying that we shouldn't be publishing any hooks helping with setting up these reactions? Do you consider [the recipe in docs](https://mobx-react.js.org/recipes-effects) sufficient or misleading?

**Comment by urugator** [comment]
> obvious choice if the state is observable.

But isn't the whole issue about reaction depending on non-observable state (multiplier/refetch)?
Isn't `useEffect(/**/,[userId,refetch,multiplier])` a more obvious solution in such case?

> Do you consider the recipe in docs sufficient or misleading?

I think it offers solutions which provide little benefits, but involve a lot of risks.
There are some things I consider downright misleading (or dishonest) like the `store` missing in deps list.

**Comment by FredyC** [comment]
You are right, I was kinda trying to abstract the problem, but in case there is a risk of staleness, having direct `useEffect` might be better indeed.

Although, I would argue that in the case of `fireImmediately` it's not that easy because it would be firing again on the reaction being recreated. The best solution I was able to come up with is the following and I would say that's already non-trivial piece of code that would be annoying to copy around.

https://bit.dev/mobx/react/use-reaction-now/~code

There are some other hooks exported in case someone else finds it useful. Not sure if I am going to polish it further at this point (docs, examples).

**Comment by urugator** [comment]
> it would be firing again on the reaction being recreated

It may overfire anyway, because it will loose the cached value used for determining whether `effect` needs to fire.

**Comment by lake2** [comment]
Does this useReaction hooks published?

**Comment by FredyC** [comment]
In Bit platform only so far, not sure if I am going to proceed with NPM, depends on the demand.

https://bit.dev/mobx/react

**Comment by FredyC** [comment]
Alright, there is apparently no demand and I started to see the problem from a urugator's perspective and it's true these hooks are used rarely.
