### ISSUE TITLE
relax dependency on mobx-react-lite

### ISSUE THREAD

**Issue by mixtur** [mobxjs/mobx-react#775]
currently we have two copies of mobx-react-lite in our app becuase of this dependency graph:

app->mobx-react (~6.1.3)->mobx-react-lite (1.4.0) //EXACT version
app->some-package->mobx-react-lite (~1.4.1)

Therefore we have in our build both mobx-react-lite@1.4.0 and mobx-react-lite@1.4.1

**Comment by pedro-mass** [comment]
Has this been resolved by https://github.com/mobxjs/mobx-react/commit/039b7db2b394e0ec566316cc21a583322793dcf2 ?

It still not a relaxed dependency, so it'll resurface when the underlying package updates their inner-dependency. Maybe there's still work to see if the dependency can be switched to a `~`?

**Comment by FredyC** [comment]
Well, to be honest, I don't expect mobx-react-lite to have more 1.x version anytime soon. More likely 2.0 will come out soon-ish (https://github.com/mobxjs/mobx-react-lite/pull/212) so we can relax dependency after that.

**Comment by mixtur** [comment]
There could still be patches. No library is perfect.

**Comment by FredyC** [comment]
Yea well, given that 2.0 does not deliver any big breaking changes, I don't think we will support 1.x after 2.x is published.

**Comment by FredyC** [comment]
The lite 2.0 has been published some time ago and mobx-react 6.2.0 depends on it. Closing this.
