### ISSUE TITLE
inject causing component to be remounted

### ISSUE THREAD

**Issue by florian-bd** [mobxjs/mobx-react#777]
I updated to mobx-react v6 and inject is behaving weird.

See this repo: 
https://codesandbox.io/embed/mystifying-pike-rdkec

Every time the parent is rendered the component is unmounted and mounted again.
Works fine with mobx-react 5 or without the inject

**Comment by FredyC** [comment]
I have no idea how Table from antd work. Can you please isolate issue without it so we are sure it's a MobX problem?

**Comment by florian-bd** [comment]
True, it seems like there is something going on with Table

**Comment by florian-bd** [comment]
In the scenario with the bug it's a new instance of HeaderCell every time

**Comment by florian-bd** [comment]
Found the bug! It's in rc-table they can't handle what is returned by React.forwardRef
