### ISSUE TITLE
Test cases for @computed and @action with enzyme ?

### ISSUE THREAD

**Issue by ksunilssah** [mobxjs/mobx-react#782]
I am wondering how to test @computed with enzyme. I am fairly new to this looking for pointer.

**Comment by FredyC** [comment]
I don't think you should test `@computed` at all as any kind of state is an implementation detail. But that's generally "problem" with Enzyme which allows it. I would really recommend NOT to. If you cannot change to [RTL](https://testing-library.com/docs/react-testing-library/intro) then I guess I have no other advice.

**Comment by FredyC** [comment]
If you have further questions, please open a new issue with more details
