### ISSUE TITLE
observer causes app to break when using 0.61's fast refresh

### ISSUE THREAD

**Issue by ertankara** [mobxjs/mobx-react#784]
How to reproduce

Wrap your react native function component with `observer` and refresh twice, the first refresh doesn't break it but following refresh does.

`Erorr is -> Invariant Violation: Rendered fewer hooks than expected. This may be caused by an accidental early return statement.`

If I remove the observer it'll refresh without a problem, so I think this issue deserves to be here rather than on React-Native project.

**Comment by FredyC** [comment]
Duplicate to https://github.com/mobxjs/mobx-react-lite/issues/226

**Comment by gaearon** [comment]
Just noting that the problem was the way they interact, and that a fix is possible. https://github.com/mobxjs/mobx-react-lite/issues/226#issuecomment-541752567

**Comment by FredyC** [comment]
Please update to mobx-react@6.1.4 for the fix.
