### ISSUE TITLE
Documentation regarding performance and best approaches

### ISSUE THREAD

**Issue by VasylenkoAlexey** [mobxjs/mobx-react#791]
Can we have more information regarding such cases performance-wise:

1) Provider vs React.Context
2) Provider/Context vs passing props
3) _Using PureComponent is recommended_ (mobx-react v6 changelog) - to what extent, should we go with class components over functional for this?

Or please guide me to correct documentation page cause right now I can't find deep enough info about this topicks.

**Comment by FredyC** [comment]
Have you read through https://mobx-react.js.org? Feel free to submit a PR to https://github.com/mobxjs/mobx-react-docz with improvements on what's missing there for you.

**Comment by FredyC** [comment]
> Using PureComponent is recommended (mobx-react v6 changelog) - to what extent, should we go with class components over functional for this?

I've updated the changelog to clear this slightly.

> Using PureComponent is now recommended for class-based components or React.memo for functional ones.

**Comment by mweststrate** [comment]
1. Indifferent
2. Wrong question to ask. Pick the best fitting abstraction for the problem instead. But pretty sure if props are needed by direct child than props is faster, if props are only needed in far descendants, context is faster. But if props are passed through intermediate objects without re-rendering them (the case if you passing observable objects through observer comps) it doesn't matter again. 
3. Use `observer` and it is taken care of :)

**Comment by VasylenkoAlexey** [comment]
Thank you for the all the response, this made things more clear.

**Comment by vkrol** [comment]
> Using PureComponent is now recommended for class-based components or React.memo for functional ones.

> Use observer and it is taken care of :)

In my opinion these two sentences contradict each other.

**Comment by FredyC** [comment]
@vkrol Feel free to submit PR with a cleaner explanation :)

Generally, I would avoid recommending to stick `observer` everywhere. I suppose the major meaning of that changelog message was that PureComponent wasn't supported in V5 because it was a monkey-patching sCU method.
