### ISSUE TITLE
<ForwardRef /> in Jest Snapshots instead of <inject-component /> after upgrading to 6.x.x from 5.x.x

### ISSUE THREAD

**Issue by mikeborozdin** [mobxjs/mobx-react#792]
We've upgraded to version `6.1.4` from `5.4.4`. That's to be able to use React hooks in observer components.

But we can see that it resulted in breaking some snapshots tests. For example, if we have the following component:

```ts
import Bar from './bar';

//code for MyComponent
//rendering
<Foo bar={<Bar />} />
```

Previously, the snapshot would contain:

```ts
<Foo bar{<inject-Bar />} />
```

But with `mobx-react@6.x.x` it will be:

```ts
<Foo bar={<ForwardRef />} />
```

**Comment by FredyC** [comment]
Please provide reproduction. Looking at the code it seems more like an issue of your testing environment.

https://github.com/mobxjs/mobx-react/blob/78c6b4964c7703de7a673913d759e9a2aab669f3/src/inject.js#L29
