### ISSUE TITLE
Provider or inject store doesn't work

### ISSUE THREAD

**Issue by Kacper-Baros** [mobxjs/mobx-react#793]
I am new to mobx react and followed some instructions in starred repos.

Here are mobx and mobx-react versions.
mobx : 4.14.1
mobx-react: 5.4.4

ViewArticlesContainer.jsx

```
import React from 'react';
import { Provider } from 'mobx-react';
import ArticleStore from '../store/articleStore';
import Articles from '../components/Articles';

export default (props, _railsContext) => {
  const store = {
    articleStore: new ArticleStore()
  }
  store.articleStore.setArticles(props.articles);

  return (
    <Provider articleStore={store.articleStore}>
      <Articles >
    </Provider>
  );
}
```

articleStore.js
```
import { observable, action } from 'mobx';

export default class ArticleStore {

  @observable articles = [];

  constructor(articles = []) {
    this.articles = articles;
  }

  @action setArticles = (articles) => {
    this.articles = [];
    let i = 0;
    while(articles[i] != undefined) {
      this.articles.push(articles[i]);
      i++;
    }
  }
}
```

Articles.jsx
```
import React, { Component } from 'react';
import { inject, observer } from 'mobx-react';
import Article from '../components/Article';

@inject('articleStore')
@observer class Articles extends Component {

  render() {
    const { articleStore } = this.props; // Here articleStore undefined error occurs
    ...
  }
}
export default Articles;
```
Can you check what's wrong here?
const { articleStore } = this.props; // articleStore undefined

Thanks

**Comment by FredyC** [comment]
Please, setup a reproduction with eg. CodeSandbox ... and also please look up how to format code in here, this is really hard to read.

**Comment by Kacper-Baros** [comment]
Thanks, @FredyC !
I formatted code and reopened this issue.
Hope to hear back from you.

**Comment by FredyC** [comment]
Try to flip around the observer and inject. I never know the correct order (one of the reasons why I don't use classes & [inject anymore](https://mobx-react.js.org/recipes-inject)).

**Comment by Kacper-Baros** [comment]
I fliped and still not work.
You said you don't use inject anymore. Then how do you use store in component?
Do you use only functional component?
If yes, can you provide me sample repo?

**Comment by FredyC** [comment]
Follow that link I sent above...

**Comment by Kacper-Baros** [comment]
@FredyC 
I tried to follow the link. So I updated mobx and mobx-react versions to 5 and 6.
Then I am getting this issue.
![2](https://user-images.githubusercontent.com/37815442/67953106-e07d9880-fbc4-11e9-8ec1-31b288a02e5d.png)

I searched this issue before and the answer was to downgrade mobx-react version to 5.
If I downgrade mobx-react version to 5, it works fine. But I can't follow the link. Because in this tutorial, it says it requires mobx-react version 6.

**Comment by FredyC** [comment]
Please provide CodeSandbox reproduction, hard to tell what's wrong here.

**Comment by Kacper-Baros** [comment]
Can you check this? https://codesandbox.io/s/nervous-kilby-uppst

**Comment by Kacper-Baros** [comment]
It tries to get data using api at store constructor. It successfully get in local. But it doesn't update articles component.

**Comment by FredyC** [comment]
That's not a problem of the code, the API request is getting blocked. Try it with mocked data first without actually reaching some network.

**Comment by Kacper-Baros** [comment]
Can you check this again?
It says invalid hook call. I need to set articles in index.ts.
Because I am developing react on rails. Rails pass articles data as params.
So I need it in index.ts.
Or set articles using api is possible. But if I get articles using api and set it to store, then the component show nothing. I saw that setArticles is called.

**Comment by FredyC** [comment]
You cannot call hooks outside of React components :) Sorry, I cannot help you make your app. You are the developer here ;) Come back when you can have a reproduction of issue that's MobX related.

**Comment by Kacper-Baros** [comment]
I fixed hook call issue.
In sandbox it works but in my local it doesn't work.
It calls setArticles successfully but component shows nothing.

Hope to get help from you.

**Comment by FredyC** [comment]
Sorry, without reproduction I cannot really help. Obviously, you are doing something else in your local code causing the issue.

**Comment by Kacper-Baros** [comment]
I don't see any issue on my local. Store change successfully but it doesn't rerender functional component.
Is it related to .babelrc file?

Here's my .babelrc file.
```
{
  "presets": [
    "@babel/preset-env"
  ],
  "plugins": [
    ["@babel/plugin-proposal-decorators", { decoratorsBeforeExport: true }],
    ["@babel/plugin-proposal-class-properties", { "loose": true }]
  ]
}
```

**Comment by Kacper-Baros** [comment]
@FredyC I invited you to my private repo.
Hope you to check the react part.
You can see react part in App/JavaScript/Story

**Comment by FredyC** [comment]
Sorry, I cannot really dig into your app code, too busy for that. Simply try a small subset of the code that works and keep adding until it breaks. There are joys of being a developer, you have to stand up to the challenge.
