### ISSUE TITLE
include useStore in mobx-react

### ISSUE THREAD

**Issue by leantide** [mobxjs/mobx-react#795]
Feature Request

Given I have a store of many mobX stores that have interdependencies, it was much easier to migrate to hooks creating my own useStore hook wrapping your MobXProviderContext. Thank you.

Given a significant folder hierarchy in my project, I unfortunately found myself having to `import {useStore} from '../../../../folder/useStore';` with lots of ../.. in all my component files which were everywhere.

I observe in the docs that the preference is to not have useStore as a part of mobx-react.  If it was part of mobx-react, then that would clean up the imports. Would you reconsider putting useStore as part of mobx-react?

Of course, in the absence of it being a part of mobx-react, I made my own npm package.

**Comment by FredyC** [comment]
To be honest, that sounds like a silly reason to just shorten import path :) There are other ways to deal with that (eg. webpack aliases) if it hurts you so much. In my opinion with VSCode the imports are hardly any concern anymore, they are just nuisance that needs to be there, but I don't care about those. If you move the file, VSCode will properly refactor all concerned paths.

**Comment by mweststrate** [comment]
Btw, if you published a library for this, feel free to share the name here, so that other running into this can profit as well :)

**Comment by leantide** [comment]
https://www.npmjs.com/package/mobx-use-store

Will have to agree to disagree on what should be part of an API. Not my code so you win. Just no so interested in typing .../.../... about 500 times.

My experience thus far with VSCode extensions or even the built in TS/JS features that automate paths and such are egg-frying features, running all my cores at 100% when used with large projects. So I must disable them.

Had assumed Webpack alias would require me to eject my create-react-app. But I will look into this further. Thanks.

**Comment by leantide** [comment]
Re. dropping MobXProviderContext in future versions. Maybe I'm missing something but given the interdependence of my stores, requiring the `this.store = store;` in my store constructors, and `this.substore = new SubStore(this);` in the root store constructor, I didn't see any way to migrate my MobX hooks without MobXProviderContext. 

Happy to be enlightened.

**Comment by FredyC** [comment]
`MobXProviderContext` is nothing more than just `React.createContext`. Then there is [a little glue code](https://github.com/mobxjs/mobx-react/blob/master/src/Provider.js) in the exported `Provider` which basically grabs stores from the props and puts them into a single object. Nothing special about it. In total, it just **8 lines of code**.

However, it's also fairly limiting. You can do so much more with Context directly. Global state is kinda overrated and sort of the bad habit created by Redux. On the contrary, having multiple Contexts for specific parts of the app makes the code less coupled together. If done well, you can truly reuse a bundle of components that use its own Context.

**Comment by leantide** [comment]
Thank you. So I can create a context for each of my stores, but can I access the context of a store from within another store?

Also, am unable to use Webpack alias without ejecting cra. But can do it with customize-cra hackery package. So will use alias.

**Comment by FredyC** [comment]
> can I access the context of a store from within another store?

What does that even mean? :) Obviously, if you have stores that depend on each other then you need to somehow interconnect that dependency, eg. by storing reference of one store onto an instance of another one. Context has nothing to do with that.

Have a look at `react-app-rewired` and similar which allows you to tweak config without ejecting. For example this extension: https://github.com/arackaf/customize-cra/blob/master/api.md#addwebpackaliasalias

**Comment by FredyC** [comment]
> So I can create a context for each of my stores

You can, but I would be thinking more in terms of separating features of the app. It's not necessary to have a single store for that. Point is that you have a freedom to do whatever you like instead of being constrained by a single Provider from the package.
