### ISSUE TITLE
Cannot read property 'prototype' of undefined when import useObserver

### ISSUE THREAD

**Issue by Ridermansb** [mobxjs/mobx-react#796]
When I import `useObserver` I'm getting this error:

![image](https://user-images.githubusercontent.com/725337/68530175-ce96a680-02e4-11ea-93e4-d9d8f2ae9d2b.png)

I tried both way ...

`import { useObserver } from "mobx-react-lite";`

or 

`import { useObserver } from "mobx-react";`

Full example here: 
https://codesandbox.io/s/example-preact-mobx-state-tree-with-hooks-yk7o2

**Comment by FredyC** [comment]
Um, based on error stack it's preact-compat library related issue, so please ask there.

I know there was some rumor, that mobx-preact is no longer needed and mobx-react should used instead, but I don't believe it's true ... https://github.com/mobxjs/mobx-preact/issues/18
