### ISSUE TITLE
Component-class with @observer doesn't dispose reaction if render() is hot-swapped

### ISSUE THREAD

**Issue by Venryx** [mobxjs/mobx-react#797]
[mobx-react version: 6.1.4]

For a React component-class with the `@observer` decorator, instances of the class do not dispose their MobX reactions, if their `render()` method is overridden.

For example:
```
class MyButton extends Component {
	render() {
		return <button>MyButton</button>;
	}
	render_withLogging() {
		console.log("Start");
		return <button>MyButton</button>;
		console.log("End");
	}
	componentDidMount() {
		if (window.enableLogging) {
			this.render = this.render_withLogging;
		}
	}
}
```

Since the component above hot-swaps the render function, the `this.render[mobxAdminProperty]` attachment becomes inaccessible to the following code in mobx-react's patched version of `componentWillUnmount()`: https://github.com/mobxjs/mobx-react/blob/a4099e86f07b3c0778da92663a82746c077c1756/src/observerClass.js#L36-L40

Become the reaction (stored under the `mobxAdminProperty` key) is inaccessible, the call to `[reaction].dispose()` is short-circuited, meaning it never gets cleaned up.

For reference, here is where that special property is first attached: (it only runs the first time the component is rendered, so its hot-swapping of the render function is not guaranteed to be final) https://github.com/mobxjs/mobx-react/blob/a4099e86f07b3c0778da92663a82746c077c1756/src/observerClass.js#L88-L89

### Real-world library conflicts

The reason I discovered the issue is because I've been using this library to enable hooks in react class-components: https://github.com/salvoravida/react-class-hooks

It conflicts because, as alluded to above, the library hot-swaps the render function of component instances just like mobx-react does, except it does it even later than mobx-react. (when a hook is first used, rather than when the render function merely begins)

### Potential solutions

1) Attach the reaction (ie. value under `mobxAdminProperty`) to the class instance rather than the render function.
2) Patch the `this.render` to be a getter+setter rather than a property, and code the setter such that, if the value gets replaced, the special `mobxAdminProperty` property (ie. the reaction) gets transferred from the old render-function to the new one.

I favor the first solution since it doesn't add another level of indirection.

Thoughts?

**Comment by FredyC** [comment]
Huh, hot-swapping render? Sounds like a nasty hack :) Never understood this weird desire to have hooks in classes. It's messed up an idea imo to have two ways of handling side effects and state.

In my personal opinion, I don't think this should be supported in the library. If you are feeling for it, make a PR with proper tests and let's see what happens next.

**Comment by Venryx** [comment]
I was afraid of mentioning the `react-universal-hooks` library because of this sort of response. XD

This issue was opened because of the potential memory leaks (and slowdown from persistent, unneeded reactions) caused by "late hot-swapping" from any source -- not just `react-universal-hooks` specifically.

Want an example of library other than `react-universal-hooks` that uses the "nasty hack" of hot-swapping render? You're looking at it -- this library. :P 

The conflict only happens because both libraries are using hot-swapping, and mobx-react uses _fragile_ hot-swapping -- that is, it assumes it's the only one hot-swapping the function. (That is, it attaches data to its override and assumes it will remain hoisted at `this.render`)

That's an unwarranted assumption imo, and its conflict with `react-universal-hooks` is just an example of it.

**Comment by FredyC** [comment]
Yea, as I said, feel free to make a PR with a solution and if it turns out not invasive too much without breaking too many things, we might consider merging it.

**Comment by Venryx** [comment]
Okay, sounds good.

I suspect it is as simple as changing the two lines that attach/retrieve from `this.render[mobxAdminProperty]` to instead attach/retrieve from `this[mobxAdminProperty]`, but we'll see.

**Comment by mweststrate** [comment]
Just do the swapping / if check inside the render? Or copy all own members
of the original function onto your new render function?

**Comment by Venryx** [comment]
> Just do the swapping / if check inside the render?

I'm not sure what you mean.

> Or copy all own members of the original function onto your new render function?

If the only source of `this.render` swapping were the project developer, this could work. However, some libraries rely on modifying/wrapping `this.render`. For example, `mobx-react`, `react-universal-hooks`, and some custom (in npm-module) decorators I use.

**Comment by Venryx** [comment]
For reference, I've created this test to make clear what's going wrong: (the test is currently failing)
```
test("#797 - replacing this.render should not break disposing of reaction", () => {
    @observer
    class Component extends React.Component {
        render() {
            return <div/>
        }
        swapRenderFunc() {
            this.render = () => {
                return <span/>
            }
        }
    }

    const compRef = React.createRef()
    const { unmount } = render(<Component ref={compRef} />)

    const reaction = compRef.current[$mobx]
    expect(reaction.isDisposed).toEqual(false)

    compRef.current.swapRenderFunc()
    unmount()
    expect(reaction.isDisposed).toEqual(true)
})
```

**Comment by mweststrate** [comment]
> Or copy all own members of the original function onto your new render function?

That would probably look like:

```
	componentDidMount() {
		if (window.enableLogging) {
                         const source = this.render
			this.render = this.render_withLogging;
                         for (let key in source) this.render[key] = this.source[key]
		}
	}
```

(might need a different way of enumeration depending on the enumerability of the original function)

By the way, I doubt that doing the above actually will enable logging reliable, as mobx-react IIRC captures the original `render` in it's reaction closure, so a swapped render will probably totally be ignored when a re-render is caused by an observable change. 

(That all being said, I personally don't get why one would want hooks in a component class (I mean, wouldn't just refactoring the then not be a lot more intuitive). But I even less get that why do that for an `observer` component, as you can leverage all mobx primitives for managing side effects already)

**Comment by Venryx** [comment]
I agree that the usefulness of hooks in component classes goes down a lot when integrating MobX. My project used to use Redux, so I wasn't able to use external state as liberally (since connect functions have a higher overhead than MobX dependency trees), leading to me using local class variables for some complex behavior.

One place where hooks are still useful in component classes is for the "useCallback" hook -- enabling you to only have a callback updated when a variable it uses is changed. This improves performance by having letting the children components use React.PureComponent to not re-render if no props have changed.

But anyway, that's just the library that made me detect this issue; even if `react-universal-hooks` did not exist, I'd still think it's worth fixing this issue for other libraries that might try to use swapping of this.render.

**Comment by mweststrate** [comment]
Just as a head up: We probably won't accept a PR unless it is a really trivial change on our side, for the simple reason that the above library isn't significant enough yet to warrant the significant additional complexity on maintenance of this one while there are clear work arounds (such as splitting the component in 2, using `<Observer>` instead, etc. 

Btw, not patching render methods is a documented limitation of mobx-react (the simple case of `render = () => { }` is already forbidden in `observer` components).

**Comment by Venryx** [comment]
> That would probably look like: [...]

Yeah, I think that would work fine for a project developer's own swapping of this.render, but it's not really a solution for cases where third-party libraries perform the swapping.

> (That all being said, I personally don't get why one would want hooks in a component class (I mean, wouldn't just refactoring the then not be a lot more intuitive). But I even less get that why do that for an observer component, as you can leverage all mobx primitives for managing side effects already)

I agree that the usefulness of hooks in component classes goes down a lot when integrating MobX. My project used to use Redux, so I wasn't able to use external state as liberally (since connect functions have a higher overhead than MobX dependency trees), leading to me using local class variables for some complex behavior.

One place where hooks are still useful in component classes is for the "useCallback" hook -- enabling you to only have a callback updated when a variable it uses is changed. This improves performance by having letting the children components use React.PureComponent to not re-render if no props have changed.

But anyway, that's just the library that made me detect this issue; even if `react-universal-hooks` did not exist, I'd still think it's worth fixing this issue for other libraries that might try to use swapping of this.render.

> We probably won't accept a PR unless it is a really trivial change on our side

Well, I created this PR for it just now: https://github.com/mobxjs/mobx-react/pull/798

The modification used to make the fix seems pretty straight-forward/trivial to me; it's just attaching the reaction to the class instance instead of the render function.

**Comment by mweststrate** [comment]
Note to self: check compatibility with devtool packages, to probably pick
the meta data from render instead, making this a breaking change.

**Comment by mweststrate** [comment]
Did you check if the logging now actually works? As said I suspect the
swapping is a no-op when it comes to reactively triggered renders

**Comment by Venryx** [comment]
Good point. Just tested, and component renders triggered by MobX do _not_ call into a newly-swapped-in this.render function.

For example this fails:
```
test("#797 - replacing this.render should not break disposing of reaction", () => {
    let newRenderFuncCalled = false
    @observer
    class Component extends React.Component {
        @observable
        thing = 1

        render() {
            return <div />
        }
        swapRenderFunc() {
            this.render = () => {
                newRenderFuncCalled = true
                return <span>{this.thing}</span>
            }
        }
    }

    const compRef = React.createRef()
    const { unmount } = render(<Component ref={compRef} />)

    const reaction = compRef.current[mobxAdminKeyForRender]
    expect(reaction.isDisposed).toEqual(false)

    compRef.current.swapRenderFunc()
    //compRef.current.forceUpdate()         // new render-func runs if triggered by this
    compRef.current.thing = 5               // but not if by this
    expect(newRenderFuncCalled).toEqual(true)

    unmount()
    expect(reaction.isDisposed).toEqual(true)
})
```

I suppose that a proper fix would therefore require a more substantial reworking of mobx-react's render-func wrapping. (while my PR fixes the particular bug in MobX, it doesn't solve the wider problem of MobX not having a reference to the new `this.render` in order to have it actually called)

I don't have time/motivation for that "proper fix" right now, so I'll close the pull-request since it's incomplete.

Will leave this issue open for now though, since I think `mobx-react` should at least log a warning if something tries to modify the render function after mobx accesses and wraps it, as it can lead to silent memory leaks as mentioned earlier.

It seems the fix would be as simple as adding this to the `componentWillUnmount` function:
```
if (this.render[$mobx] == null) {
    console.warn(`The render function for an @observer component (${this.constructor.name}) was modified after MobX attached. This is not supported, since the new function can't be triggered by MobX.`);
}
```

**Comment by FredyC** [comment]
Feel free to make a PR with a warning, otherwise, I don't think we are too keen supporting something like that. Perhaps it will help other people to realize that trying to mix hooks and classes is a bad idea :)

**Comment by mweststrate** [comment]
The warning sounds good. I think we have a similar check already in place
to check for `render = () => { }` at mounting time. But that obviously
misses this case :) (btw, note that cWU can be swapped out at exact the
same way as render and then you'd end up with the very same problem (both
in mobx-react and your lib). Which is kinda the problem hooks fundamentally
solve)

**Comment by Venryx** [comment]
Okay, a warning would be good enough for me. (assuming the "proper fix" would require a substantial mobx-react rework)

I mainly just didn't want others to hit the "hidden bug" of lots of MobX reactions unknowingly leaking / persisting past component lifecycle.

**Comment by Venryx** [comment]
Created a pull-request (#799) that adds a warning for the issue (replacing `this.render` after MobX has attached).

If one needs to do so anyway, here is a complete example of how you can, while preventing the leaking/persistence of the MobX reaction for the component:
```
@observer
class Test1 extends Component<{}, {}> {
	render() {
		return <div/>;
	}
	componentDidMount() {
		setTimeout(()=>this.swapRenderFunction(), 1000); // simulate delay
	}
	swapRenderFunction() {
		const oldRender = this.render;
		this.render = function () {
			// <<< add wrapper code here
			return oldRender.apply(this, arguments);
		};

		// copy over mobx administration object
		for (const symbol of Object.getOwnPropertySymbols(oldRender)) {
			this.render[symbol ] = oldRender[symbol ];
		}
	}
}
```

**Comment by Venryx** [comment]
A better way than the above (because of issue 2 mainly), is actually just to make sure the wrapper you want to place around `this.render`, is applied **prior to** the first time `this.render` is called (since that is when MobX attaches its own wrapper).

Actually, that won't work currently because the class-decorator stores a reference to the class prototype's `render` function even prior to the first call to render. This workaround would be enabled if mobx-react changed this:
```
const baseRender = target.render
target.render = function() {
    return makeComponentReactive.call(this, baseRender)
}
```

To this:
```
target.render = function() {
    return makeComponentReactive.call(this, this.render)
}
```

Is the fix above straight-forward enough to be accepted as a PR? It would enable compatibility with other libraries (or custom code) that modify `this.render` (prior to first render), without causing any architectural changes in mobx-react.

**Comment by Venryx** [comment]
Since I don't see a clear path forward to making mobx-react compatible with hot-swapping of `this.render`, I will close this issue.

If someone thinks of a good solution (that isn't confusing like the last option listed above), feel free to bring it up.

As of now, I'll find some other way to integrate the libraries that use `this.render` hot-swapping (perhaps by making pull-requests for them that use alternate ways of implementing their behavior).
