### ISSUE TITLE
Upgrading to v6 breaks store injection

### ISSUE THREAD

**Issue by morgrimm** [mobxjs/mobx-react#804]
`mobx`: v4.15.0
`mobx-react`: v6.1.4
`react`: v16.12.0
`react-dom`: v16.12.0

I'm moving a legacy project to v6 from v5, since we're starting to build new code using hooks with the intent of migrating legacy components eventually as well. It was my understanding that upgrading shouldn't break any existing store injection, but using this component at the top level:

```
import React from 'react';

import { inject } from 'mobx-react';

import { ThemeProvider as SCThemeProvider } from `styled-components`;

const buildTheme = stores => ({
    mainColor: stores.rootStore.mainColor
});

const ThemeProvider = inject(buildTheme)(props => <ThemeProvider {...props} />);

export default ThemeProvider;

```

I get an invalid hook call error, like so:

```
The above error occurred in the <Observer> component:
    in Observer (created by inject-with-buildTheme(Function))
    in inject-with-buildTheme(Function)
    in MobXProvider (created by StoreProvider)
    in StoreProvider
    in ContextProviders

...

Error: Invalid hook call. Hooks can only be called inside of the body of a function component. This could happen for one of the following reasons:
1. You might have mismatching versions of React and the renderer (such as React DOM)
2. You might be breaking the Rules of Hooks
3. You might have more than one copy of React in the same app
See https://fb.me/react-invalid-hook-call for tips about how to debug and fix this problem. 2 react.development.js:1590

```

This worked perfectly in v5, and there are currently no hooks anywhere in the project. Am I migrating incorrectly?

**Comment by FredyC** [comment]
Would you be able to set up a minimal reproduction? It sounds more like an issue in your setup than in the library.

**Comment by morgrimm** [comment]
You're right - with the exact versions I'm using, and identical code, I can't reproduce it in a code sandbox. I'll close the issue and focus on debugging my setup.
