### ISSUE TITLE
MobX and Hooks

### ISSUE THREAD

**Issue by leantide** [mobxjs/mobx-react#807]
Discuss

My React app has a global MobX root store composed of many sub-stores, collectively containing all the observables, computed's and actions for the app. This architecture has been very resilient, especially since every store has quick access to every other store via its this.store collection of sub-stores.

I've converted my React app to hooks. My root MobX store is now accessed in my functional components via useStore/useContext instead of Provider/Inject. All good.

But I am finding that as I use more and more libraries that have converted to hook APIs, it is not so easy for my @computed and @action methods to access this information as hooks can not be used in classes and my MobX stores are class based.

For @actions, I find myself calling the hook in the functional component and passing the hook results to the @action with additional props. Works I guess. But not sure what to do with @computed that needs the hook info.

Is there a better MobX store architecture I should be using that is more aligned with hooks? Must my MobX stores be class based? If I migrate to useLocalStore within the components, I think I will lose all the power and convenience of a global central root store. Besides this, most of my stores are single instance and don't need to have an instance per component rendered.

Any suggestions?

**Comment by leantide** [comment]
My present mitigation for @computed properties that involve hook data is to pull them out of my MobX stores and put the equivalent logic inside each functional component where I have access to the MobX stores and to the hook data. Meaning I lose the code re-use and MobX just-in-time-only-if-needed execution of my @computed's.

**Comment by leantide** [comment]
For code reuse, I am able to create custom hooks for logic that involves MobX store data and hook data. So what I am presently seeing is @computed data being pulled out of my MobX class-based stores and replaced by custom hooks. And like a virus, @computed's that depend on @computed's that depend on hook data are also coming out as custom hooks. The hooks are eating my stores.

**Comment by FredyC** [comment]
> But I am finding that as I use more and more libraries that have converted to hook APIs, it is not so easy for my @computed and @action methods to access this information

I don't follow. How was this different with class components? How did that "access" look like?

> But not sure what to do with @computed that needs the hook info.

Generally, any computed that relies on non-observable data is tricky because MobX won't see a change to such data. You are not supposed to "call" computed with new data. Instead, you should construct observable and store it as property on store class which can be accessed by computed. 

> If I migrate to useLocalStore within the components, I think I will lose all the power and convenience of a global central root store

Why would you think that? The name of that hook might be misleading, but you can as well have such a store inside the context and access it from anywhere. It's just a different way of how a store is constructed.

**Comment by leantide** [comment]
Let me try to be more specific with an example. Previously I had access in one of my MobX stores to browser history and location pathname. I have a sidebar that can only be visible on certain pathnames. Previous working code:

```
@computed get showSidebar( ) {
   return this.store.subStore1.pathname === '/accepablePath' &&  this.store.subStore2.useWantsToShowSidebar;
}
```
Now I have access to the current browser location pathname via a usePath hook. 

My present solution is to convert showSidebar from a MobX @computed to a new hook:

```
export const useSidebar = () => {
   const { subStore2 } = useStore( );
   const { pathname } = usePath( );
   const { useWantsToShowSidebar } = subStore2;
   return pathname === '/acceptablePath' && useWantsToShowSidebar;
}
```
Furthermore, any other @computed's that depended on the previous @computed showSidebar now also need to be removed from MobX as they now depend on the new hook.

Likewise, any of my @action handlers that depend on pathname no longer have access to it via the store. 

So more specifically my question is, is there an approach that enables me to keep @computed code inside of MobX with dependencies on data sourced from hooks? Can useLocalStore help? Or, by design, code that has dependencies on hook data must remain outside of MobX?

Thank you for your time.

**Comment by leantide** [comment]
Boiling it down to basics, my current understanding is that data sourced from library hooks are not observable data and therefore any derived data must remain outside of MobX. And furthermore MobX action handlers must have these non-observable dependencies injected via props.

**Comment by FredyC** [comment]
Sorry, but still confused. How were you handling it with class components before? I mean you were apparently synchronizing current browser path to be available on `this.store.subStore1.path` right? I suppose you have utilized lifecycle methods? Well, why is it a problem to do the same with hooks?

```js
const StoreProvider = () => {
  const { pathname } = usePath( );
  React.useEffect(() => {
    store.subStore1.path = pathname // or use actions if you like
  }, [pathname])
}
```

I am not seeing the need to move all store logic to hooks really.

**Comment by leantide** [comment]
Thank you, From your example I now see that the issue is not class vs hook but really observable vs non-observable. They just happened to be coupled in my transition to hooks, where the previous arrangement had a subscription service that the hook doesn't provide, and that your code example would replicate.
