### ISSUE TITLE
6.1.3 -> 6.1.4 fails all tests with "Invalid hook call"

### ISSUE THREAD

**Issue by charliematters** [mobxjs/mobx-react#809]
Sorry for the lack of info, but the affected system isn't one I can copy and paste from.

I've upgraded @testing-library/react, @testing-library/dom, @testing-library/jest-dom to their latest version and the tests run fine.

When upgrading from mobx-react@6.1.3 to 6.1.4 every component test fails saying that the render() function is making an invalid hook call.

These tests are all testing components wrapped by observer()

**Comment by FredyC** [comment]
Sorry, but without minimal reproduction, we can't really help you. We don't need your whole system, just try to reproduce the issue at hand.

**Comment by charliematters** [comment]
2 hours later and I've found the problem. Some other dependency was pulling in mobx-react-lite@1.4.1 which was the cause of the error. Sorry!
