### ISSUE TITLE
forwardRef set via observer is not generating documentation when using react-docgen

### ISSUE THREAD

**Issue by thecodejack** [mobxjs/mobx-react#810]
I am trying to use `observer` with forwardRef like below

```js
function MyReactComponent(props, ref) {
    useImperativeHandle(ref, () => ({
       handleClick:()=>{}
   })
   return <div>Test</div>
}

MyReactComponent.displayName = 'Test';

MyReactComponent.propTypes = {
    title: PropTypes.string
}

export default observer(MyReactComponent, { forwardRef: true })
```

For same when I try generating documentation via react-docgen, I am unable to get propTypes, displayName etc.

**Comment by FredyC** [comment]
I am not familiar with react-docgen. I wonder, is it working for you if you use `React.forwardRef` directly without the observer?

**Comment by FredyC** [comment]
Looks like there were some issues with that: https://github.com/reactjs/react-docgen/pull/392
Can you try upgrading to the latest version to see if that fixes it for you?

**Comment by thecodejack** [comment]
sure...let me try that...

**Comment by thecodejack** [comment]
seems like it's working with react-docgen@5.0 when i tried here

http://reactcommunity.org/react-docgen/
