### ISSUE TITLE
Convert mobx-react to TS

### ISSUE THREAD

**Issue by ynejati** [mobxjs/mobx-react#813]
@FredyC mentioned wanting to do this in #801. Following the suggestion in the [PR template found in the mobx repo](https://github.com/mobxjs/mobx/blob/master/PULL_REQUEST_TEMPLATE.md), I'm opening an issue here first so that (my) time spent on this would not be considered "wasted".

**Comment by mweststrate** [comment]
It is not entirely clear from the title, but if you are suggesting to convert mobx-react itself to TS, feel free to go ahead :)

**Comment by ynejati** [comment]
Awesome. I've made the title more clear to prevent any confusion.  Thanks!

**Comment by ynejati** [comment]
Merged. Closing issue.
