### ISSUE TITLE
How can I avoid re-render in react-native-webview ?

### ISSUE THREAD

**Issue by Macrow** [mobxjs/mobx-react#815]
I have a webview(react-native-webview) in this block, it all wrapped by useObserver method, when some props changed, the whole webview will reload, how can I avoid this ?

Thanks!

```typescript
return useObserver(() => (
      <View>
        <View>
          {someFunction()}
        </View>
        <View>
          <WebView ..../>
          </View>
        </View>
      </View>
    ));
```

**Comment by mweststrate** [comment]
Did you try using `observer` instead?

Op wo 8 jan. 2020 07:51 schreef Macrow <notifications@github.com>:

**Comment by FredyC** [comment]
Wait ... on props change the component will re-render, that has nothing to do with MobX.

**Comment by Macrow** [comment]
My mistake, it has nothing to do with MobX indeed. 

I use React.useMemo to fix my bugs.

Thanks.
