### ISSUE TITLE
Is it okay to use `autorun` in hook/component?

### ISSUE THREAD

**Issue by lcswillems** [mobxjs/mobx-react#816]
I am wondering if it is okay to use `autorun` in a hook or component?

E.g. (this dumb example):

```
const store = observable({
    x: 0
});

const MyComponent = observer(() => {
    autorun(() => {
        if (store.x > 10) {
           alert('too much');
        }
    });

    return <div onClick={() => store.x += 1} />
});
```

My concern is about `autorun` end of life. Is it stopped when component unmounts?

**Comment by FredyC** [comment]
Please see https://mobx-react.js.org/recipes-effects

**Comment by lcswillems** [comment]
Thank you! I missed that!
