### ISSUE TITLE
Combine Stateless Components and Class Components

### ISSUE THREAD

**Issue by lapidus** [mobxjs/mobx-react#817]
I have a working setup for Stateless components:

```
// State
export const useMyAppStore = () => {
  return useContext(StoreContext)
}

// In the Component
const App = observer(() => {
  const store = useMyAppStore()
})

```

But I have one "Map Class component" that **requires inner state**. How can I inject the same Store into a class component and make it observe the state? I tried the below but it doesn't quite work:

```

import { useMyAppStore } from "./state"

@inject(useMyAppStore)
@observer

class Map extends Component {
  constructor(props) {
    super()
        console.log(props)
    }
}

```

Thanks!

**Comment by FredyC** [comment]
> But I have one "Map Class component" that **requires inner state**.

What does that even mean? Do you know about `useState`? :) 

With your own Context, you cannot use `inject`, but you can use [contextType](https://reactjs.org/docs/context.html#classcontexttype) as easy escape hatch.

**Comment by lapidus** [comment]
Thank you. I am closing for now as it was perhaps not the best explanation. And I have a functional workaround :)
