### ISSUE TITLE
Do not change component displayName

### ISSUE THREAD

**Issue by hecerinc** [mobxjs/mobx-react#819]
![image](https://user-images.githubusercontent.com/7988472/72560050-0ed15280-385b-11ea-9259-33d0ae2a6d78.png)

When using `inject` or for that matter containers this code https://github.com/mobxjs/mobx-react/blob/ab90ae65991c95da73406accd1048e225e63f02e/src/inject.js#L37 changes the component names, which makes it impossible to debug in React DevTools because you don't know which component is which.

**Comment by FredyC** [comment]
Then don't use `inject`, nobody is forcing you ;) 

See https://mobx-react.js.org/recipes-inject

**Comment by FredyC** [comment]
Nobody else seems to be bothered by this so closing.
