### ISSUE TITLE
Observer render not called when the mobx-state-tree is updated.

### ISSUE THREAD

**Issue by simonssspirit** [mobxjs/mobx-react#825]
Observer render not called when the mobx-state-tree is updated.

I have made an example and uploaded it in this repo for reference:

https://github.com/simonssspirit/mobx-state-tree-test-example

I have a hierarchical tree and each item is wrapped in observable as well as the main tree.

Updates are happening when updating only the top level of the tree, even if all of the child nodes are wrapped as well. 

Any suggestions on why this is happening will be very helpful.

**Comment by FredyC** [comment]
Line 94, use `toJS` from `mobx` instead of `slice.` Since you are interacting with non-observable lib, you have to shove the whole thing in its direction, top-level only is not enough.

**Comment by simonssspirit** [comment]
@FredyC Thank you for the fast response.

I did try with toJS initially, but the result was the same.

`you has to shove the whole thing in its direction, top-level only is not enough.`

This code is making each node an observable, is this not enough to apply the observables on each level?

```  const myItemRender = (props) => {
    return (<Observer key={props.itemHierarchicalIndex}>
      {() => {
        return <span>{props.item.name}</span>
      }}
    </Observer>
    )
  }
```

**Comment by FredyC** [comment]
I am not sure what you have tried but changing that one line does seem to fix it. Clicking on any of the buttons renders both trees correctly. I am misunderstanding a problem here?

https://codesandbox.io/s/magical-shockley-vpqp8

I am not sure why it wouldn't work like you are suggesting, someone else might have a better answer. It's always tricky expecting reactivity from a library that's not designed that way. One small thing can elude you on the path and screws everything.

**Comment by simonssspirit** [comment]
@FredyC thank you, I guess something was not updated properly on my end.

Everything is working perfectly now.
