### ISSUE TITLE
Observable reactive state being read outside a reactive context

### ISSUE THREAD

**Issue by sammy007** [mobxjs/mobx-react#828]
I have simple component which is `observer` and have `observable` properties.

```jsx
class SomeForm extends React.Component {
  someField = 'someValue';
  handleChange(e) {
    this[e.target.name] = e.target.value;
  }

render() {
  return (
  ...
  <Form.Control type="text" name="someField" value={this.someField} onChange={this.handleChange}/>
  ...
  )}
}
decorate(SomeForm, {
  someField: observable,
  handleChange: action.bound,
})
export default withRouter(observer(SomeForm));
```

Just trying to use mobx instead of setState in a hope it will make things consistent and simple. Getting tons of `Observable reactive state being read outside a reactive context` if `observableRequiresReaction: true` is set. I am guessing I got these errors because I am using  `Form.Control` which is indeed not an observer because it's `react-bootstrap` component. I have added:

```jsx
<Observer render={() => <Form.Control ... value={this.someField}/>} />
```

to get rid of warnings. I am asking whether it's so called "idiomatic way" or I am missing something?

**Comment by mweststrate** [comment]
The `<Observer>` wrapper should not be needed. 

Are there any `mobx.configure` calls in your code base?

**Comment by sammy007** [comment]
I set as follows in `App.js`:

```jsx
configure({
    enforceActions: 'observed',
    computedRequiresReaction: true,
    observableRequiresReaction: true,
    reactionRequiresObservable: true,
});
```

**Comment by mweststrate** [comment]
ok, so far it seems your setup is correct and this issue is indeed looks like a duplicate of #806. For now I recommend to disable `observableRequiresReact`, as it won't work together with react class components until that one is resolved.

**Comment by sammy007** [comment]
Could you shed some light on `actions` also? If these directives are not mandatory, and it works without defining function as action, what a point of doing so?

**Comment by mweststrate** [comment]
see the actions documentation. Actions optimize batching and clarify the intend of the method.

**Comment by Bnaya** [comment]
@sammy007 that should've be solved on the latest release,
Please check and update/close the issue

**Comment by sammy007** [comment]
Solved.

**Comment by sammy007** [comment]
@mweststrate, @Bnaya 

With `enforceActions: 'always'`:

```javascript
class MyStore {
    field = false;

    constructor() {
        if (...) {
            this.field = true;
        }
    }
}
```

```
Uncaught Error: [mobx] Since strict-mode is enabled, changing observed observable values outside actions is not allowed. Please wrap the code in an `action` if this change is intended. Tried to modify: MyStore@3.field
```

Not sure I really should mark `constructor` as `action` though.

**Comment by FredyC** [comment]
@sammy007 I think you are sort of contradicting yourself. If you want to enforce actions, then you should really use actions always. You cannot expect it would work selectively :)

```js
class MyStore {
    field = false;

    constructor() {
        if (...) {
            this.initField()
        }
    }
    
    @action
    initField() {
      this.field = true
    }
}
```

**Comment by mweststrate** [comment]
Typically, the thing that create MyStore should be an action, as it is in
response to some event

**Comment by sammy007** [comment]
It's really non logical to expect that. It's a constructor, `mobx` must treat is as `action` without any directive. The creation is the same `js` source file.

```javascript
export default React.createContext(new MyStore());
```

**Comment by Bnaya** [comment]
1. that's out of the scope of that issue, you may open FRC issue
2. mobx,or any other js code has no way to know if he is called inside a "constructor" or just a "function" somewhere in his callstack

**Comment by mweststrate** [comment]
Do consider app state initialization logic just another action / event. 

Anyway, this behavior is known, working as intended and documented so closing this issue. 

If it annoys you use the strict "observed" setting instead, which is also the recommended one for this reason. https://mobx.js.org/refguide/api.html#enforceactions
