### ISSUE TITLE
IE11 Issue around Symbols

### ISSUE THREAD

**Issue by paulmowat** [mobxjs/mobx-react#834]
Hi.

Think I've found a issue in IE11 while updating my projects dependencies.

Looks like 

mobx4 + mobx-react6.1.5 => success
mobx4 + mobx-react6.1.7 => fail

From what I can tell it looks like a issue to do with symbols.

On debugging it seems to be coming from src/utils/utils.ts in the following code

function createSymbol(name) {
  if (typeof Symbol === "function") {
    return Symbol(name);
  }

  const symbol = `__$mobx-react ${name} (${symbolId})`;
  symbolId++;
  return symbol;
}

Getting a invalid character error at "const symbol = `__$mobx-react ${name} (${symbolId})`;"

![image](https://user-images.githubusercontent.com/2870617/74150479-e17d8780-4c01-11ea-9c47-3c6a951e4aa0.png)

Thanks

Paul

**Comment by FredyC** [comment]
Thanks for the report. We have changed the way how the module is built and haven't considered ES5 for bundling. I will fix that soon.

**Comment by FredyC** [comment]
Closing this in favor of more comprehensive #835, subscribe there to watch for resolution, please.
