### ISSUE TITLE
Props not marked as `isObservable`

### ISSUE THREAD

**Issue by marcfallows** [mobxjs/mobx-react#837]
In an `observer`, `isObservable` on `props` returns `false`. However, reactions to that observable happen as expected so it would appear `props` are indeed observable.

Here's a code sandbox to highlight what I am seeing:
https://codesandbox.io/s/simple-mobx-todolist-eunfn

In that sandbox I would expect "Props observable? Yes"

**Comment by FredyC** [comment]
Can you please a link documentation that speaks about such expectations? We are certainly not making props observable and never were. There is no point in that, the component will re-render whenever props change.

**Comment by mweststrate** [comment]
No, we do 😊, to make sure they can be used in computeds and reactions

Op vr 14 feb. 2020 06:51 schreef Daniel K. <notifications@github.com>:

**Comment by FredyC** [comment]
Huh, really? So that's another the speciality of class components? What a weirdness gave that in functional components it doesn't work like that.

So the problem here is that `isObservable` does not work or how do you explain it?

**Comment by FredyC** [comment]
@marcfallows I am curious, what are you actually trying to achieve? Are you really driving app logic by using `isObservable` or was it because something else did not work for you?

**Comment by mweststrate** [comment]
Technically they are not made using observables but only use the lower
level concept of atoms, which is why they'll yield false.

Op vr 14 feb. 2020 07:53 schreef Daniel K. <notifications@github.com>:

**Comment by JohnMFlowers** [comment]
Must you proxy props for classes that are not observers?

**Comment by FredyC** [comment]
@JohnMFlowers How is that related to the topic? Please, if you have some other concerns, open a separate issue with full details

**Comment by FredyC** [comment]
Do we want to fix something in here? Does it make sense to expand `isObservable` to somehow recognize structure built by atoms somehow? Is that even observable in that case?

**Comment by mweststrate** [comment]
I don't think this needs solving, not all observable things necessary have to pass the `isObservable` check, as there are many more things that are 'behind the scenes' observable, like some utils in mobx-utils.
