### ISSUE TITLE
Can't pass store for two components

### ISSUE THREAD

**Issue by ifokeev** [mobxjs/mobx-react#84]
I have this DOM structure. I have a Provider with a store ```mobx-store```
![Error](https://cldup.com/Ncj_5R839a.png)

I can't access the store in two components in the same time. 
Now I can't access the store in Sidebar. I got: ```Uncaught Error: MobX observer: Store 'store' is not available! Make sure it is provided by some Provider```

I have no idea how to fix it. I though it was because of TicketsPage component, but it happens with components on the same line.

**Comment by ifokeev** [comment]
I found that it's because of: 
```
Sidebar.contextTypes = {
  router: React.PropTypes.object,
};
```

I think we should update docs to caution users.

**Comment by jtraub** [comment]
It is related to #70.

I have put a warning into local mobx-react copy to catch such cases in the existing codebase.

**Comment by jtraub** [comment]
@ifokeev as a side note I would recommend you to use [`withRouter` HOC](https://github.com/reactjs/react-router/blob/master/docs/API.md#withroutercomponent) instead of manual receiving router from context.

[Recent post](https://facebook.github.io/react/blog/2016/07/13/mixins-considered-harmful.html#context) by Dan Abramov partially addresses this

**Comment by ifokeev** [comment]
@jtraub thank you for your advice. I will use ```withRouter``` instead of ```contextTypes```.
Issue is resolved.

**Comment by mweststrate** [comment]
@jtraub could you share how you did setup the warning?

**Comment by jtraub** [comment]
@mweststrate Sure. I use this code - https://github.com/jtraub/mobx-react/commit/bd83fccb8e4c496f96ab6e3a6a38432376b91a56

It produces 
![image](https://cloud.githubusercontent.com/assets/153191/16893123/bfbabdfa-4b71-11e6-9cc6-e057017988de.png)

for code
```
@observer(['store']) class MyComponent extends Component {

  render() {
    return <div>abc {store}</div>;
  }

}

MyComponent.contextTypes = {
  router: React.PropTypes.object,
};

MyComponent.propTypes = {
  store: PropTypes.object.isRequired,
};
```

If you want I can simply add a few tests and send it to you.

**Comment by mweststrate** [comment]
@jtraub that is really nice! PR would be appreciated :)
