### ISSUE TITLE
React Native + Jest: Cannot find module 'react-dom' from 'mobxreact.cjs.development.js'

### ISSUE THREAD

**Issue by jayshah123** [mobxjs/mobx-react#844]
Having a fairly barebones react-native + mobx setup here (https://github.com/jayshah123/mobx-jest-test-error)
Running `npm test` asks for`react-dom` dependency.

## Intended outcome

Jest test should run as expected

## Actual outcome

Test fails saying: `Cannot find module 'react-dom' from 'mobxreact.cjs.development.js'`

Full error: 
```
bash-3.2$ npm test

> JestMobxChecker@0.0.1 test /Users/jay.shah/Documents/sampleapps/JestMobxChecker
> jest

 FAIL  __tests__/App-test.js
  ● Test suite failed to run

    Cannot find module 'react-dom' from 'mobxreact.cjs.development.js'

    However, Jest was able to find:
        './ColorComponent.js'

    You might want to include a file extension in your import, or update your 'moduleFileExtensions', which is currently ['js', 'json', 'jsx', 'ts', 'tsx', 'node'].

    See https://jestjs.io/docs/en/configuration#modulefileextensions-array-string

    However, Jest was able to find:
        '../App.js'

    You might want to include a file extension in your import, or update your 'moduleFileExtensions', which is currently ['js', 'json', 'jsx', 'ts', 'tsx', 'node'].

    See https://jestjs.io/docs/en/configuration#modulefileextensions-array-string

      at Resolver.resolveModule (node_modules/jest-resolve/build/index.js:276:11)
      at Object.<anonymous> (node_modules/mobx-react/dist/mobxreact.cjs.development.js:10:16)

Test Suites: 1 failed, 1 total
Tests:       0 total
Snapshots:   0 total
Time:        1.401s
Ran all test suites.
npm ERR! Test failed.  See above for more details.
```
## How to reproduce the issue

https://github.com/jayshah123/mobx-jest-test-error
1. clone the repo
2. npm install
3. npm test

## Versions
```
    "mobx": "^5.15.4",
    "mobx-react": "^6.1.8",
    "react": "16.9.0",
    "react-native": "0.61.5"
```

**Comment by FredyC** [comment]
This will be generally solved by https://github.com/mobxjs/mobx-react/pull/787 once I get to finishing it up :)

For now, you basically have to force `mobx-react` in Jest config to resolve to RN bundle instead of regular CJS one.

**Comment by vonovak** [comment]
@jayshah123 this PR makes the test run https://github.com/jayshah123/mobx-jest-test-error/pull/1

**Comment by FredyC** [comment]
Alright, upgrade to mobx-react 6.2.0 and see [instructions in the readme](https://github.com/mobxjs/mobx-react#observer-batching).
