### ISSUE TITLE
'_allowStateReadsEnd' is not exported from 'mobx'

### ISSUE THREAD

**Issue by Charles-Hang** [mobxjs/mobx-react#847]
## Actual outcome
./node_modules/_mobx-react@6.1.8@mobx-react/dist/mobxreact.esm.js
Attempted import error: '_allowStateReadsEnd' is not exported from 'mobx'.

## Versions
6.1.8

**Comment by jontyt** [comment]
I just ran into this issue half an hour ago. 
What version of mobx are you using?
mobx-react 6.1.8 has a mobx peer dependency of `"^5.15.4 || ^4.15.4"`
https://github.com/mobxjs/mobx-react/blob/master/package.json#L44

This would make sense that that's the cause of your error as `_allowStateReadsEnd` has only been an exposed method as of mobx as of 4.15.1/5.15.1  (see: https://github.com/mobxjs/mobx/pull/2233/files)

**Comment by FredyC** [comment]
Yea this is one rare case where ignoring peer dependency warning isn't a good idea :)

**Comment by Charles-Hang** [comment]
> I just ran into this issue half an hour ago so this should help.
> 
> What version of mobx are you using?
> mobx-react 6.1.8 has a mobx peer dependency of `"^5.15.4 || ^4.15.4"`
> https://github.com/mobxjs/mobx-react/blob/master/package.json#L44
> 
> if your mobx version is lower than that then that would make sense why you're getting that error as `_allowStateReadsEnd` has only been an exposed method of mobx as of 4.15.1/5.15.1 (see: https://github.com/mobxjs/mobx/pull/2233/files)

I got it, thanks a lot !
