### ISSUE TITLE
Hooks: mixing react state and mobx state

### ISSUE THREAD

**Issue by AndrewMorsillo** [mobxjs/mobx-react#853]
The docs have left me with a bit of confusion regarding using mobx with hooks, especially useEffect. Would the following pattern work? If not, why?

```
const MyComponent = observer(() => {
    const [foo, setFoo] = useState("bar")
    const store = useStore() //get MST store from context
    

    useEffect(() => {
         console.log(`Hello ${foo} and ${store.myProp}`)
    }, [store.myProp, foo])

    return ....
})
```

From what I can tell this should work just fine since `store.myProp` is referenced in the deps of useEffect ensuring that the observer will re-render the component (and hence recreate the effect) if it changes. 

I think it won't be quite as efficient as using a mobx reaction because the whole component has to re-render for the effect to fire if `store.myProp` changes rather than just the reaction function running. That seems a small price to pay in most cases given the quirks of using observables and react state together pointed out here https://github.com/mobxjs/mobx-react/issues/772

**Comment by FredyC** [comment]
Yea, as long as you have `observer`, the deps of `useEffect` are picked up. However, you are sort of losing on MobX utility here. If you would use `autorun` inside the `useEffect`, then you don't need to worry about deps at all. It depends on the complexity of the scenario. Usually, you want to keep your side effects narrowly focused meaning there won't much deps.

Performance-wise it doesn't matter that much if a component is re-rendered because of `observer` or because the `autorun`.

Do you have some actual issue or just fishing around? :)

**Comment by AndrewMorsillo** [comment]
I'm adding some animations to my react-native app. I have most state in MST but sometimes it makes sense to have some transient local component state. I could put that local state in the store but that's a hassle and overkill for something that's only used local to one or two components. 

I'm enjoying using hooks to make my animations reusable and cleanly separated from my components, but the pitfalls of useEffect + mobx + react state mentioned in #772 have opened up some cases where I'm not confident about the best way to do some things.

So the general pattern is:
1. Function component wrapped in observer displays some data from MST
2. I want to do some animation based on changes to the data in the MST store *and* local state

For example
```
export const useSlideToAnimation = (x: number, y: number, speed: number = 500) => {
        //a nicely encapsulated reusable animation, thanks hooks!
    const xPos = useRef(new Animated.Value(x))
    const yPos = useRef(new Animated.Value(y))
    const [isRunning, setIsRunning] = useState(false)
    const isFirstRun = useRef(true)

    useEffect(() => {
        if (isFirstRun.current) {
            //Skip first run, x and y are always equal and we don't want to return isRunning==true when we're not animating
            isFirstRun.current = false
            return
        }
        setIsRunning(true)
        Animated.parallel([
            Animated.timing(xPos.current, {
                toValue: x,
                duration: speed,
                easing: Easing.linear,
                useNativeDriver: true,
            }),
            Animated.timing(yPos.current, {
                toValue: y,
                duration: speed,
                easing: Easing.linear,
                useNativeDriver: true,
            }),
        ]).start(() => setIsRunning(false))
    }, [x, y])

    return [xPos.current, yPos.current, isRunning] as const
}

const ExampleAnimatedComponent = observer(() => {
    const store = useStore()
    const { x, y } = store.coordinates
    const [slideX, slideY, isRunning] = useSlideToAnimation(x, y)

    //This should work fine
    useEffect(() => {
        if (store.foo && isRunning) {
            //do some other animation based on store state AND react state
        }
    }, [store.foo, isRunning])

    //This version is more verbose and might? have unintended behavior
    useEffect(
        () =>
            reaction(
                () => store.foo,
                (foo) => {
                    if (foo && isRunning) {
                        //do some other animation based on store state AND react state
                    }
                },
                { fireImmediately: true }
            ),
        [isRunning]
    )
    return <Animated.View style={{ transform: [{ translateX: slideX, translateY: slideY }] }}>....</Animated.View>
})

```

It seems that when dealing with side effects in function components with mobx it's cleaner and safer to just wrap the component in `observer()` then use react's `useEffect` as if the values aren't observable. 

Combining `useEffect` with `autorun` or `reaction` seems to introduce the potential for unintended behavior while offering little benefit that I can see in these situations.  Am I missing something?

**Comment by FredyC** [comment]
Honestly, MobX isn't the best tool for animations, it's not optimized for such load and changes to observable several times per second. I am not saying it's slow, but you might be better off with something else. If you like a mutable state, have a look at Immer (there is also useImmer hook).

**Comment by AndrewMorsillo** [comment]
Oh I'm not trying to animate the values with mobx! That sounds like a bad idea haha. 

I'm using react-native's built in Animated library. In the example above mobx only stores the target x/y coordinates. The actual values that get animated are instances of `Animated.Value` and the animation is done in native code (thanks to `useNativeDriver: true`. When the coordinates in the store change the `useEffect` in the hook kicks off an animation of the `Animated.Value`s to the new coordinates. I use that hook verbatim in my app and it works great.

My concern here is just about triggering side effects (which happen to be animations) based on react local state and MST state while avoiding any bugs due to the behavior of useEffect and mobx reactions.

I looked into `useLocalStore` but I found the documentation unclear. Do modifications to a local store need to be actions (function) on that store or can anything modify the store? I also can't think of an easy way to use `useLocalStore` with typescript if I need to pass the store to some child components.

**Comment by FredyC** [comment]
> Do modifications to a local store need to be actions (function) on that store or can anything modify the store?

That depends purely if you have strict mode enabled or not, it has nothing to do with that hook which is just thin wrapper around `observable` call.

As for Typescript, if you would extract to a custom hook, then you can easily export `ReturnType<typeof useMyStore>`

**Comment by FredyC** [comment]
Closing for now, but feel free to ask further about the topic.
