### ISSUE TITLE
It seems that a re-rendering of a React component is triggered while in static (server-side) mode. Please make sure components are rendered only once server-side. 

### ISSUE THREAD

**Issue by Dashue** [mobxjs/mobx-react#855]
Could anyone elaborate on what's causing this, I find very little documentation on the issue and what patterns may product this message?

**Comment by FredyC** [comment]
Have you seen this? https://mobx-react.js.org/recipes-ssr

**Comment by Dashue** [comment]
Thanks for input @FredyC 
I hadn't seen that link before, however I am doing that before my class in _app.tsx. Using nextjs.

All my pages support serverside rendering by default through nextjs.

Should I be enabling it per page basis?

**Comment by mattruby** [comment]
In next.js I think you could add the ssr logic to _app.jsx.

**Comment by mattruby** [comment]
Looks like this might help: https://github.com/zeit/next.js/blob/5592e64c366a1b10bf96953bf2712fcf0333fa83/examples/with-mobx/store.js

While it's not in _app.tsx I think it gets the point across.

**Comment by Dashue** [comment]
@mattruby Worked like a charm, thanks!

**Comment by FredyC** [comment]
I would appreciate if either of you can contribute a small PR to https://github.com/mobxjs/mobx-react-docz with information about NextJS.
