### ISSUE TITLE
Log why function component re-rendered

### ISSUE THREAD

**Issue by AndrewMorsillo** [mobxjs/mobx-react#856]
Perhaps I'm missing something obvious here, but I can't seem to find a way to log the reason why a function component wrapped in `observer` is re-rendering. I tried `trace()` but it just prints "[mobx.trace] 'observer' tracing enabled" and no further information.

What's the best way to log why a function component is rendering?

**Comment by mweststrate** [comment]
put the trace at the end of your func. Note that it might also rerender
unrelated to mobx, for that you can use the React profiler

**Comment by AndrewMorsillo** [comment]
Ah, I made an unrelated mistake causing confusion. `trace()` works fine. Thanks!
