### ISSUE TITLE
[Typescript] How to define type parent store in childrent store without eslint Dependency cycle detected or any type.

### ISSUE THREAD

**Issue by dongnh124** [mobxjs/mobx-react#872]
Such as mobxjs/mobx#1935 or Mobx [documentation](https://mobx.js.org/best/store.html)

**Comment by FredyC** [comment]
And what is the question?

**Comment by dongnh124** [comment]
> And what is the question?

I try combining multiple stores with typescript. And my question is How to define type of RootStore in UserStore and TodoStore. UserStore and TodoStore in difference file with RootStore.

**Comment by FredyC** [comment]
Please supply code examples of what have you tried and did not work for you for some reason. If you are looking for a "best way", I can tell you there is no such thing in development. Go with the one that feels best for you.
