### ISSUE TITLE
js framework benchmark - Huge performance drop after upgrading mobx and mobx-react to latest version

### ISSUE THREAD

**Issue by darkowic** [mobxjs/mobx-react#877]
After upgrading react, mobx and mobx-react to latest version in https://github.com/krausest/js-framework-benchmark/tree/master/frameworks/keyed/react-mobX I found huge performance drop in the benchmark. The example is really simple but I don't know what is the problem.

![image](https://user-images.githubusercontent.com/11510581/84930805-25156000-b0d2-11ea-96d0-b7c87cc567a3.png)

## How to reproduce the issue

Upgrade react, mobx and mobx-react to the latest version and run the benchmark.

## Versions
```
  "dependencies": {
    "mobx": "5.15.4",
    "mobx-react": "6.2.2",
    "react": "16.13.1",
    "react-dom": "16.13.1"
  }
```

**Comment by mweststrate** [comment]
Shit, yes forget about this. 

@FredyC I think we still need to revert the batching-opt-in change? We really can't do that in a minor update, it hurts serious applications really bad and probably no test will detect it.

**Comment by FredyC** [comment]
@darkowic So you haven't noticed that "friendly" warning what you need to do?

**Comment by darkowic** [comment]
Yeah, I didn't notice any warning

**Comment by FredyC** [comment]
And can you please confirm that after [following these instructions](https://github.com/mobxjs/mobx-react#observer-batching) the performance is back on track?

**Comment by darkowic** [comment]
I just checked it. Adding `require('mobx-react/batchingForReactDom');` didn't solve it.
`[Violation] 'click' handler took 34428ms` - creating 10k rows...

You have to take a look at this benchmark I guess.

**Comment by mweststrate** [comment]
Just tried to narrow this done, it seems that the react update itself causes the difference. As soon as I upgrade to react 6.13.1, the perf drops from 3 to 40 secs, with the same mobx / mobx-react version. Does this ring a bell to anyone?

**Comment by mweststrate** [comment]
Yeah, it's super sad! Glad someone else found that out before, would never have figured that out myself.
