### ISSUE TITLE
forwardRef set via observer is not working version "mobx-react-lite": "^2.0.6",

### ISSUE THREAD

**Issue by mvudugula** [mobxjs/mobx-react#878]
import React, {
	useState,
	useEffect,
	FC,
	createRef,
	memo,
	useRef,
	useImperativeHandle
} from 'react';
import Styles from './accommodation-list.scss';

import { observer } from 'mobx-react-lite';
import AddonList from '../shared/addon-list/addon-list';

const AccommodationList = ( {ref} :{ref:React.Ref<any>} ) => {
	const refs = useRef(null);
	useImperativeHandle(ref, () => ({
		submitForm: () => {
			refs.current.submitForm();
		}
	}));

	return (
		<>
			<div className="accommodations-container">
				{store.booking.accommodations &&
					store.booking.accommodations.map((accommodation, index) => (
						<div className="accommodation-content" key={index}>
							<div className="title">{accommodation.name}</div>
							<div className="accommodation-body">
<AddonList
										ref={refs}
										addons={accommodation.addons.linked}
									
									
									/>
							</div>
							
						</div>

					))}
			</div>

			<style jsx>{Styles}</style>
		</>
	);

};

export default observer(AccommodationList, { forwardRef: true });

**Comment by FredyC** [comment]
Please provide reproduction with eg. CodeSandbox.
