### ISSUE TITLE
github Releases is error

### ISSUE THREAD

**Issue by stfenjobs** [mobxjs/mobx-react#881]
like this  https://github.com/mobxjs/mobx-state-tree/issues/1538

**Comment by stfenjobs** [comment]
too old

![image](https://user-images.githubusercontent.com/6580897/85918830-ac17c480-b898-11ea-84b4-cc5e9c4858d2.png)

**Comment by mweststrate** [comment]
We don't release through github. Check NPM

**Comment by mweststrate** [comment]
We don't release through github. Check NPM

**Comment by FredyC** [comment]
"Fixed" here as well

![image](https://user-images.githubusercontent.com/1096340/85919861-48c56c80-b86f-11ea-9146-855e5642708d.png)
