### ISSUE TITLE
add more PropTypes

### ISSUE THREAD

**Issue by MikeDevice** [mobxjs/mobx-react#882]
Let's imagine the store `TodosStore`:

```js
class TodosStore {
  @observable todos = [];

  @computed get total() {
    return todos.length;
  }
}
```

and the component `Todos`:

```js
import React from 'react';
import ReactPropTypes from 'prop-types';
import {PropTypes} from 'mobx-react';

class Todos extends React.Component {
  static propTypes = {
    todosStore: PropTypes.shape({
      todos: PropTypes.observableArray.isRequired, // or ReactPropTypes.array.isRequired
      total: ReactPropTypes.number.isRequired
    }).isRequired
  }

  render() {
    // ...
  }
}
```

What's wrong with this example? `todosStore.total` is a `computed` number, so the line

```js
total: ReactPropTypes.number.isRequired
```

triggers a full recompute, as described here https://github.com/mobxjs/mobx-react/issues/56. So I think it would be useful to have the additional `PropTypes` methods for simple types like `number`, `string`, etc.

**Comment by mweststrate** [comment]
I think it'd be better to have the proptypes in a separate package. It
seems they are barely used (and I think TS does a better job at type
checking in general)

**Comment by MikeDevice** [comment]
But what to do without TypeScript?

**Comment by FredyC** [comment]
@MikeDevice You are most welcome to extract current prop types into a separate package and expanding it. It is indeed used rarely.

**Comment by MikeDevice** [comment]
Thank you for your answers. I close the issue now.
