### ISSUE TITLE
upgrade mobx-react version from 6.2.2 to 6.2.3，There is an error

### ISSUE THREAD

**Issue by zengqingzhuang** [mobxjs/mobx-react#887]
![image](https://user-images.githubusercontent.com/12510482/88510834-658fc400-d016-11ea-9f90-0ead998ddb33.png)

**Comment by FredyC** [comment]
Please create a small reproduction.

**Comment by joelharkes** [comment]
Yes have the same issue:

![image](https://user-images.githubusercontent.com/2960938/88539685-fd3ee380-d011-11ea-916e-ee6cb6408730.png)


We provide same component twice, because we use it for different stores, now it starts throwing errors. its quite annoying i had to downgrade to keep it working.

**Comment by joelharkes** [comment]
It would be nice to at least be able to disable this error/warning.

**Comment by mweststrate** [comment]
"We provide same component twice, because we use it for different stores"

Why do you need to wrap a component twice in observer twice because you use
it for two different stores? Please provide some example code why the
warning wouldn't be correct in your case.

**Comment by bigdrum** [comment]
The warning is fine. The real problem is getDisplayName (https://github.com/mobxjs/mobx-react/blob/376bff72d84ae8d342c55d1fb25ff81a223624d2/src/observerClass.ts#L26) is passed with a undefined value; and it is not properly handled.

**Comment by FredyC** [comment]
We will publish a fix soon, it was merely an oversight.

**Comment by mweststrate** [comment]
Just release 6.2.4. Thanks for reporting!
