### ISSUE TITLE
Notice about react-router

### ISSUE THREAD

**Issue by ifokeev** [mobxjs/mobx-react#89]
I found that ```Link``` of ```react-router``` doesn't pass activeClassName property after changing the history (e.g. I have product categories and clicked on next category).
It works only with with ```shouldComponentUpdate: true```. I think it's because of mobx-react uses pure render and there were no update of properties or state. 
You can try the script with/without @observer and @inject.

```javascript
import React, {
  Component
} from 'react';

import {
  observer,
  inject
} from 'mobx-react';

import Category from '../atoms/Category';

@inject((allStores) => ({
  items: allStores.store('categories')
})) @observer
class CategoriesList extends Component {
  shouldComponentUpdate() {
    return true;
  }

  render() {
    const {
      items
    } = this.props;
    
    // let items = [{
    //   id: 1,
    //   permalink: '1111',
    //   pretty_name: '1111'
    // }, {
    //   id: 2,
    //   permalink: '2222',
    //   pretty_name: '2222'
    // }];

    const categoriesRender = items.map((elem) => {
      return (
        <Category key={elem.id} data={elem} />
      );
    });
    
    return (
      <div className="categories">
        {categoriesRender}
      </div>
    );
  }
};

export default CategoriesList;
```

```javascript
import React, {
  Component
} from 'react';

import {
  Link
} from 'react-router';

class Category extends Component {
  render() {
    const {
      data
    } = this.props;
    
    return (
        <div className="categories__item">
          <Link to={`/all/${data.permalink.toLowerCase()}`}  activeClassName="active"> {data.pretty_name}</Link>
        </div>
    );
  }
};

export default Category;
```

**Comment by jtraub** [comment]
Try to upgrade to react-router 3.0 alpha. I think they have found a workaround for https://github.com/facebook/react/issues/2517

**Comment by mweststrate** [comment]
@jtraub did you try `withRouter`? see also https://github.com/reactjs/react-router/issues/3439

**Comment by ifokeev** [comment]
I tried react-router 3.0.alpha2 and it fixes this problem but makes some other. So I'll leave it as is and change it later.
But it was very helpful. I found that it's not only my problem and fix is in the changelog:
https://github.com/reactjs/react-router/blob/a30defc3875e1abbb3978b5728db4b7d049a52f3/CHANGES.md
