### ISSUE TITLE
build 6.2.4 is broken (missing files)

### ISSUE THREAD

**Issue by blendsdk** [mobxjs/mobx-react#890]
Hi,

I just updated to v6.2.4 and my react project broke due:
`Cannot find module: './mobxreact.cjs.production.min.js'. Make sure this package is installed.`

Looking at:
https://unpkg.com/browse/mobx-react@6.2.4/dist/ we mis the built files.

For comparing take a look at:

https://unpkg.com/browse/mobx-react@6.2.3/dist/

**Comment by mweststrate** [comment]
Apologies, did run the wrong release command. Should be fixed in 6.2.5. Apologies and thanks for reporting!
