### ISSUE TITLE
[mobx-react 6.2.4] Unable to resolve path to module 'mobx-react'

### ISSUE THREAD

**Issue by ZilvinasKucinskas** [mobxjs/mobx-react#891]
Just seen this one after `dependabot` update. 

## Intended outcome

```
import { observer } from 'mobx-react';
```

Should work.

## Actual outcome

Unable to resolve path to module 'mobx-react' 🤷‍♂️ 

## How to reproduce the issue

https://codesandbox.io/s/intelligent-wilson-3c5yg

## Versions

Listed in https://codesandbox.io/s/intelligent-wilson-3c5yg

**Comment by blendsdk** [comment]
same as: https://github.com/mobxjs/mobx-react/issues/890

**Comment by mweststrate** [comment]
woops, made a booboo. publishing is hard. Should be fixed in 6.2.5. Thanks for reporting!
