### ISSUE TITLE
Does mobx-react produces reactions in Unmounted Components?

### ISSUE THREAD

**Issue by jmaguirrei** [mobxjs/mobx-react#94]
Hello

I noticed reactions in components that are not rendered in the screen.
I putted a `console.log `in `render()` function and get those logs.
Even though this components are observers of data that has mutated, they are not rendered, so (I think) they should not react...

Is it possible to prevent this?

**Comment by andykog** [comment]
@jmaguirrei, if `render()` is being called, then your components are being rendered somewhere

**Comment by andykog** [comment]
You can try placing `console.log(this._reactInternalInstance._nativeParent._currentElement)` in those `render()`. It might help you to find out who is rendering your component (or might not).

**Comment by jmaguirrei** [comment]
@andykog Thanks, I found in one case those components were hidden because they are animated from 0 to 1 scale...

But, I have another case that calls render() and I think they should not.

For example, I have this (simplified) component tree:

Main (observes and passes A & B)
- Header (receives and observes 'A')
- List (receives and observes 'B')

'A' changes, Main is re-rendered, Header is re-rendered, but List is also re-rendered (I mean render is called but no DOM is changed).

I can control List not to re-render with some 'ad-hoc' ShouldComponentUpdate, but I like to rely on mobx-react to do that.

How could achieve that?

**Comment by andykog** [comment]
@jmaguirrei, thats the nature of MobX, forceUpdate() is _always_ being called if observable data, that was used on previous renders is changed. With forceUpdate shouldComponentUpdate is being skipped, so you can't control it. 

If Main is being re-rendered, then it uses observable A somehow instead of just passing it to Header. For example:
```jsx
var store = observable({ A: 0, B: 0 });

// This way Main is subscribed to both A and B updates
// as it looks for theirs values during render:
class Main extends Component {
  render() {
    return (
      <div>
        <Header a={store.A} />
        <List b={store.B} />
      </div>
    );
  }
}

// And this way Header and List will be updated separately and Main won't:
class Main extends Component {
  render() {
    return (
      <div>
        <Header a={store} />
        <List b={store} />
      </div>
    );
  }
}
```

By the way, mobx-react is already implementing https://facebook.github.io/react/docs/pure-render-mixin.html in observer components for you.

**Comment by jmaguirrei** [comment]
@andykog I understand now, the pattern then is

> If a Father Component passes data to its children, but not directly use this data, then they should pass the whole store, otherwise it will be like he is actually consuming this data and will re-render in some cases redundantly...

But, what is the point to pass a store to a child component?

If the child component can directly import the store, then this pattern look cleaner to me:

```javascript

// Main.jsx
import { Header } from ...;
import { List } from ...;

class Main extends Component {
  render() {
    return (
      <div>
        <Header />
        <List />
      </div>
    );
  }
}

// Header.jsx
import { Store } from ...;

class Header extends Component {
  render() {
    const { A } = Store;
    return (
      <div>
        `I am the Header ${A}`
      </div>
    );
  }
}

// List.jsx
import { Store } from ...;

class List extends Component {
  render() {
    const { B } = Store;
    return (
      <div>
        { _.map(B, item => <div>{item}</div>}
      </div>
    );
  }
}

```

Is that correct in the way also skips unnecessary re-renders?

**Comment by andykog** [comment]
@jmaguirrei, of course. I've passed the «store» just for explanation. Your code looks good.

**Comment by andykog** [comment]
> If a Father Component passes data to its children, but not directly use this data, then they should pass the whole store, otherwise it will be like he is actually consuming this data and will re-render in some cases redundantly
Not quite. You are free to pass some part of your store that is not meant to be replaced very often. For example, if you use
```
render() {
  return <List items={store.data.users} />
}
```
then this component will be re-rendered only if link to users array itself will change: `store.data.users = ['new array']`, or if the whole data will change: `store.data = newData`, but not when the link stays the same: `store.data.users.push(newUser)`.

**Comment by jmaguirrei** [comment]
Thanks very much, I think now I understand the pattern!

For my "mental model" my best option should be:

1) Pass the whole store and the name of the observable field to child component if it is reusable and therefore can render different things, example:

```javascript

// In some files
<MyList store={Messages} field='myMessages' />
<MyList store={Core} field='Users' />
...

// MyList.jsx
class MyList extends Component {
    render() {
        const
            { store } = this.props,
            data = store[field];
        return (
            // something with data
        );
    }
}
```

2) Just import the store he needs statically:

```javascript
// List.jsx
import { Store } from ...;

class List extends Component {
  render() {
    const { B } = Store;
    return (
      <div>
        { _.map(B, item => <div>{item}</div>}
      </div>
    );
  }
}
```

This I way I know that option A) "dynamic" its preferred when the component could be used for multipurpose and option B) "static" is preferred when "the data and the component belongs to each other..."

Always use option B in case both can be used, because its easy to understand (everything is in the closure)

Cheers!

**Comment by jmaguirrei** [comment]
Closing this, no evidence that unmounted components are rendered, thans for the whole explanation

**Comment by andykog** [comment]
> 'A' changes, Main is re-rendered, Header is re-rendered, but List is also re-rendered (I mean render is called but no DOM is changed).
Removed misleading comments about forceUpdate. We have discovered, that this is happening because `List` doesn't have pure rendering implemented. That can be achieved either with decorating `List` with `@observable` (that implements pureRenderMixin), or just using something like https://www.npmjs.com/package/pure-render-decorator for `LIst`
