### ISSUE TITLE
3.5.2 renderReporter error

### ISSUE THREAD

**Issue by timothyallan** [mobxjs/mobx-react#96]
Just updated to 3.5.2 and am getting a showstopper error on load:
```Uncaught TypeError: Cannot read property 'renderReporter' of undefined```

Downgrading to 3.5.1 gets rid of it.

I'm only using ```observer``` in my code and nothing else...

**Comment by mweststrate** [comment]
Confirmed, same issue here

**Comment by andykog** [comment]
Sorry, my bad, released fixed version as 3.5.3

**Comment by timothyallan** [comment]
Yep, 3.5.3 seems to have fixed it. Wish all my problems could be fixed in 15 minutes 👍

**Comment by mweststrate** [comment]
awesome!
