### ISSUE TITLE
Observer decorator in TSX throws type error when updating project from 3.3.0 to 3.5.x

### ISSUE THREAD

**Issue by Haubach** [mobxjs/mobx-react#97]
I'm working in a code base which has a react class decorated with the observer decorator. In Mobx-react 3.3.0 this worked perfectly, but after installing 3.5.x it throws a type error on compilation with typescript 1.8.10.

> Unable to resolve signature of class decorator when called as an expression.
  Type 'ComponentClass<void>' is not assignable to type 'void'.

[Here's](https://github.com/Haubach/Mobx-react-bug) a minimal example which recreates the issue.

`@observer
class Foo extends React.Component<void,void> {
	render() {
		return (<div></div>);
	}
}`

**Comment by mweststrate** [comment]
Quick check, what about `React.Component<{}, {}>` (that's what I always use)?

**Comment by Haubach** [comment]
Yes, that does work.

**Comment by andykog** [comment]
Strange. Component state should allow `void` https://github.com/DefinitelyTyped/DefinitelyTyped/blob/master/react/react.d.ts#L16
@Haubach, are you using that type definition for React? Works fine for me.

**Comment by Haubach** [comment]
Yes, that is the react type definition I'm using in [the example repo](https://github.com/Haubach/Mobx-react-bug).

I've just verified the behavior on my colleagues machine.

**Comment by mweststrate** [comment]
It is unclear to me why `void` isn't allowed by the type system, could be investigated further but is `{}` instead of `void` an acceptable work around? (Personally I would argue that it is more correct as well, props aren't absent, but just empty)

**Comment by Haubach** [comment]
The decision to use void over empty object was taken some time ago where we encountered an issue in another code base, but I don't remember the specific reasoning. For now, this regression is not a serious issue and hopefully it will continue to be a non-issue if you don't intend to continue to support the 3.3.0 behavior.
